### ISSUE TITLE
[NM] Patch 12/09 late Total PCR tests (specimens) and Negative PCR tests (people) update

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#1000]
State: NM

Dates affected: 12/09

Describe the issue: On December 9, 2020, New Mexico updated their Total PCR tests (specimens) after the time of our daily update. As a result we were unable to update their Total PCR tests (specimens) and Negative PCR tests (people), which is calculated as Total PCR tests (specimens) minus Positive PCR tests (people), on December 9, 2020.

**Comment by muamichali** [comment]
We do not have any data available to make this change.
