### ISSUE TITLE
[ND] Clear out the confirmed & probable deaths time series (leaving the total deaths number)

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#1001]
**State or US**:  North Dakota

**Describe the problem**
1. The definitions on North Dakota's website do not explicitly classify deaths as confirmed or probable. We were previously capturing positive deaths as confirmed, but since it is now clear that they include antigen and PCR positives, and since ND does not call these confirmed deaths, we do not think we should label them as confirmed deaths. 
2. We are going to also clear the previously captured probable deaths time series, since the category that North Dakota calls 
**Deaths of Individuals Presumed Positive** doesn't necessarily match probable cases. 

**Link to data source**
https://www.health.nd.gov/diseases-conditions/coronavirus/north-dakota-coronavirus-cases

**Comment by glasswoman** [comment]
[ND Probable deaths deleted 12-10-20.xlsx](https://github.com/COVID19Tracking/issues/files/5674586/ND.Probable.deaths.deleted.12-10-20.xlsx)
[ND Confirmed deaths deleted 12-10-20.xlsx](https://github.com/COVID19Tracking/issues/files/5674587/ND.Confirmed.deaths.deleted.12-10-20.xlsx)
[ND Deaths 12-10-2020.xlsx](https://github.com/COVID19Tracking/issues/files/5674588/ND.Deaths.12-10-2020.xlsx)
