### ISSUE TITLE
DE: 31 March data does not match screenshots

### ISSUE THREAD

**Issue by tomdottom** [COVID19Tracking/issues#101]
Daily `positive` listed as 406 whilst screenshots shows 264.
When I first noticed this last night (around 23:00) dashboard in question was actually showing 316.

![image](https://user-images.githubusercontent.com/5106166/78151885-15597a00-7407-11ea-8f17-b15e93aee657.png)

316 aligns with latest reported figures

![image](https://user-images.githubusercontent.com/5106166/78152222-826d0f80-7407-11ea-988d-da9474411ddf.png)

**Comment by una-smith** [comment]
There is already an issue open for DE.

**Comment by tomdottom** [comment]
@una-smith #90 relates to the negative count and testing.

This issues refers to positive count and the conflicting information between screenshots, historical data for 31 March, and latest reported data.

**Comment by tomdottom** [comment]
:thinking: just looking at a public arcgis datasource and see
```
{'NAME': 'New Castle', 'Presumptive_Positive': 197}
{'NAME': 'Kent', 'Presumptive_Positive': 34}
{'NAME': 'Pea Patch', 'Presumptive_Positive': None}
{'NAME': 'Sussex', 'Presumptive_Positive': 88}
{'NAME': 'Reedy Island', 'Presumptive_Positive': None}
{'NAME': 'Statewide', 'Presumptive_Positive': 87}
```

Sum including `Statewide` is 406.
Sum excluding `Statewide` is 319 (which matches current reported count).

Was a similar (same?) data source used and `Statewide` not excluded?

**Comment by tomdottom** [comment]
Data on site now reflects expected value
