### ISSUE TITLE
[NH] Capture antigen positive as probable cases and add confirmed cases by summing antigen + PCR positive and PCR positive columns from daily reports

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#1012]
**State or US**: NH

**Describe the problem**
NH revises down its antigen count upon positive PCR test, making it a probable case count rather than an antigenpositive count. Plus, we can get a PCR confirmed count by summing the PCR + antigen positive and PCR only positive counts in the state reports.

**Link to data source**
State reports. We will probably be able to confirmed from subtracting total cases - antigen cases. And we can get the probable timeseries from our antigen column.
https://www.nh.gov/covid19/documents/case-summary.pdf

**Comment by the-daniel-lin** [comment]
[On 10/3/20](https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/NH/NH-secondary-20201003-002151.png), NH began releasing a PCR positive + Antigen positive breakdown on their COVID-19 Summary Dashboard.

Our time series only goes back until 11/20/20.

We have screenshots of the dashboard form 10/3/20 - 11/11/20.
On 11/12/20, NH's COVID-19 Summary Dashboard began to have issues, and we were unable to resume screenshots of the page (now PDF) until 12/11/20. This means that there is a one week period from 11/12/20 - 11/19/20 where we do not have numbers.

**Comment by karaschechtman** [comment]
Whoops, double filed for this at #1027 and #1028
