### ISSUE TITLE
[VA] Add antibody and antigen tests to tracking

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#1013]
**State or US**: VA

**Describe the problem**
VA added antibody testing encounters data and antigen test encounters that we're not capturing on 11/23.
(We didn't capture the antigen because we were unsure about lumping with antibody)
We can get historical data for it.
https://www.vdh.virginia.gov/content/uploads/sites/182/2020/11/VDH-Antibody-Test-Reporting-Insights.pdf

**Link to data source**
https://www.vdh.virginia.gov/coronavirus/coronavirus/covid-19-in-virginia-testing/
https://data.virginia.gov/resource/3u5k-c2gr.json

**Comment by jaclyde** [comment]
Done in Issue [1062](https://github.com/COVID19Tracking/issues/issues/1062)
