### ISSUE TITLE
[TX] Backfill PCR and Antigen totals and positives

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#1014]
**State or US**: Texas

**Describe the problem**
Backfill the time series of Positive Tests (PCR), Total Tests (PCR), Positive Tests (Antigen), Total Tests (Antigen) 

**Link to data source**
[SpecimenTest.csv](https://services5.arcgis.com/ACaLB9ifngzawspq/arcgis/rest/services/TX_DSHS_COVID19_TestData_Service/FeatureServer/6/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=Date%2COldPositive%2CNewPositive%2COldTest%2CNewTest&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=Date+DESC&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=)

**Comment by space-buzzer** [comment]
Backfilling antigen tests and positive antigen test results.
[Multi-edit tool-PRODUCTION - TX-reb-20201214.csv.txt](https://github.com/COVID19Tracking/issues/files/5691941/Multi-edit.tool-PRODUCTION.-.TX-reb-20201214.csv.txt)
[Multi-edit tool-PRODUCTION - TX-reb-20201214_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5691942/Multi-edit.tool-PRODUCTION.-.TX-reb-20201214_post.csv.txt)

**Comment by space-buzzer** [comment]
PCR testing: Total tests and positive test results backfill
[Multi-edit tool-PRODUCTION - TX-reb-20201214_pcr.csv.txt](https://github.com/COVID19Tracking/issues/files/5692024/Multi-edit.tool-PRODUCTION.-.TX-reb-20201214_pcr.csv.txt)
[Multi-edit tool-PRODUCTION - TX-reb-20201214_pcr_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5692025/Multi-edit.tool-PRODUCTION.-.TX-reb-20201214_pcr_post.csv.txt)

**Comment by space-buzzer** [comment]
Negative updates
[Multi-edit tool-PRODUCTION - TX-reb-20201214_neg.csv.txt](https://github.com/COVID19Tracking/issues/files/5692527/Multi-edit.tool-PRODUCTION.-.TX-reb-20201214_neg.csv.txt)
[Multi-edit tool-PRODUCTION - TX-reb-20201214_neg_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5692528/Multi-edit.tool-PRODUCTION.-.TX-reb-20201214_neg_post.csv.txt)
