### ISSUE TITLE
[WA] Backfill confirmed and probable cases from timeseries provided by Washington

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#1017]
**State or US**: Washington

**Describe the problem**
ON 12/17/2020, Washington started providing a breakdown of confirmed and probable cases on its dashboard. The "Case counts" tab on the dashboard provides a historical time series of cases by specimen collection date. In order to present a more accurate view of when the probable cases were classified, we are going to backfill our historic time series, to reflect the cases on the dates the specimen was collected. 
We are also going to update the Cases (Confirmed and Proabable) values in our database to reflect the probable cases, and we are going to refresh the full time series of Positive Cases (PCR) so that it matches the probable and lumped timeseries.

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.
![image](https://user-images.githubusercontent.com/1749380/102650791-6ea23e80-4139-11eb-94c3-d0822ffc1ba2.png)

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - WA-reb-20201218.csv.txt](https://github.com/COVID19Tracking/issues/files/5718193/Multi-edit.tool-PRODUCTION.-.WA-reb-20201218.csv.txt)
[Multi-edit tool-PRODUCTION - WA-reb-20201218_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5718194/Multi-edit.tool-PRODUCTION.-.WA-reb-20201218_post.csv.txt)

**Comment by space-buzzer** [comment]
Good bot
