### ISSUE TITLE
Fix for WA total test encounters (PCR) data problem on 12/18

### ISSUE THREAD

**Issue by theomichel** [COVID19Tracking/issues#1021]
**State or US**: WA

**Describe the problem**
On 12/18, Washington's Total Tests number dropped from the 12/17 number of 3432892 to a much lower 2765404, before rising again on 12/19. CTP collected the lower number on 12/18, which was clearly a temporarily blip in their data.

The planned fix is to carry the 12/17 number forward to 12/18 in order to avoid a major spike in the curve.

**Link to data source**
https://www.doh.wa.gov/Emergencies/COVID19/DataDashboard

**Comment by theomichel** [comment]
Fixed!

Rows edited: 1
WA 2020-12-18
    totalTestEncountersViral: 3432892 (was 2765404)

**Comment by hmhoffman** [comment]
The same decision was made for WA's Negative PCR tests (specimens). 
Rows edited: 1
WA 2020-12-18
    negative: 3226298 (was 2556060)
