### ISSUE TITLE
[OH] Backfill PCR and Antigen timeseries from data provided by Ohio

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#1033]
**State or US**: Ohio

**Describe the problem**
As of 12/29/2020, Ohio is providing a download of antigen and pcr tests, including positive tests

**Link to data source**
https://data.ohio.gov/wps/portal/gov/data/view/covid-nineteen-key-metrics-on-testing

**Comment by karaschechtman** [comment]
[OH before.xlsx](https://github.com/COVID19Tracking/issues/files/5777721/OH.before.xlsx)
[OH after.xlsx](https://github.com/COVID19Tracking/issues/files/5777730/OH.after.xlsx)
![Columns C-D](https://user-images.githubusercontent.com/15933271/103811195-8d09a480-502a-11eb-9b46-582e444c1972.png)

**Comment by karaschechtman** [comment]
[Changes (1).txt](https://github.com/COVID19Tracking/issues/files/5777752/Changes.1.txt)
