### ISSUE TITLE
[NH] Patch 01/01/21 late update

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#1036]
**State**: New Hampshire

**Date**: 1/1/2021

**Describe the problem**
Adding data that updated after our publish time

**Comment by jaclyde** [comment]
It looks like NH did not update their dashboards on 1/1/21 however the totals for PCR tests, Antigen tests, Cases, and Deaths are available in the CSVs available from the state at https://www.covid19.nh.gov/dashboard
