### ISSUE TITLE
[ND]Backfill antigen and PCR tests

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#1043]
**State or US**: North Dakota

**Describe the problem**
On December 30, 2020, North Dakota began reporting antigen in addition to PCR testing. From December 31, 2020 to January 3, 2021, we captured those numbers combined in our Total Tests (PCR) and Total Test Encounters (PCR) fields. On January 4, 2021, we began reporting these figures separately and revised our historical data to reflect the separate antigen and PCR numbers North Dakota provides.

**Link to data source**

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - ND-reb-20210105.csv.txt](https://github.com/COVID19Tracking/issues/files/5767662/Multi-edit.tool-PRODUCTION.-.ND-reb-20210105.csv.txt)
[Multi-edit tool-PRODUCTION - ND-reb-20210105_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5767663/Multi-edit.tool-PRODUCTION.-.ND-reb-20210105_post.csv.txt)
