### ISSUE TITLE
States Daily SQLite DB

### ISSUE THREAD

**Issue by danap** [COVID19Tracking/issues#105]
Before I open a project thought would reach out.

I have corrected the current states daily, 2020-03-27, csv to
input into a SQLite database. There were inconsistences. The
project would have this database and SQL files. Perhaps instead
include files here?

[states-daily-20200327.tar.gz](https://github.com/COVID19Tracking/covid-tracking-data/files/4396429/states-daily-20200327.tar.gz)

danap

**Comment by quangnguyen1995** [comment]
Late update: Thank you very much for linking your project! We hope that you'll be able to make good use of our data. We apologize for all possible inconsistencies that might arise in the collection of this data.
