### ISSUE TITLE
[NJ] Patch 01/08 Probable Cases, and Cases (confirmed + probable)

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#1057]
**State:** NJ

**Dates affected:** 01/08 

**Describe the issue:** On January 8, 2021 New Jersey’s **Probable cases** increased from 53,967 to 72,123 without explanation. This affected their Cases (confirmed + probable), which is calculated as Positive PCR tests (people) plus Probable cases in the absence of an explicit total case number. On January 9, 2021, their Probable cases decreased from 72,123 to 56,147. Because of this, we believe that the figure reported on  January 8, 2021 was a mistake, and are editing the number in out timeseries. In the absence of a historical timeseries for Probable cases, we are updating Probable cases for January 8, 2021 to be 53967, the same figure reported on January 7, 2021.

**Comment by hmhoffman** [comment]
Rows edited: 1
NJ 2021-01-08
    positive: 570575 (was 588731)
    probableCases: 53967 (was 72123)

**Comment by space-buzzer** [comment]
Updated the values again, using the data from "Case and Mortality Summaries" tab, and then inside the "PCR and Antigen Positives" (with value captured on 2021-01-08)

[Multi-edit tool-PRODUCTION - NJ-HMH-20210109_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5791965/Multi-edit.tool-PRODUCTION.-.NJ-HMH-20210109_post.csv.txt)
[Multi-edit tool-PRODUCTION - NJ-pre-20210109.csv.txt](https://github.com/COVID19Tracking/issues/files/5791966/Multi-edit.tool-PRODUCTION.-.NJ-pre-20210109.csv.txt)
