### ISSUE TITLE
Inconsistencies in the database

### ISSUE THREAD

**Issue by fabioanza** [COVID19Tracking/issues#108]
Hi, 

I am looking at the database for the number of cases in the US and either there are some internal inconsistencies or I do not understand what 'total' means.

My understanding was that total was positive+negative+pending. This is true for all dates but the following ones: 10,11,12 and 17 of March. Importing the dataset into a pandas dataframe called covid19_usa_daily and running 

`covid19_usa_daily['total']==(covid19_usa_daily['positive']+covid19_usa_daily['negative']+covid19_usa_daily['pending'])`

you see that this is not always true. Also, if you compute the difference between left-hand and right-hand sides you see that the left one is always smaller, which should not be correct.

**Comment by Nosferican** [comment]
- There were also cases of the UTC dates not being correct based on the ET timestamps early on.
- There were a few cases of the `grade` field not matching the `score`.
- See also #149 for other types of inconsistencies.
They seem to get better but if someone spots new ones and has specific cases do report them.

**Comment by muamichali** [comment]
I am closing this issue without further action at this time. Currently the totals still do not take pending into consideration. Very few states are reporting pending at this time.
