### ISSUE TITLE
[PA] backfill total tests historical data from new state data source

### ISSUE THREAD

**Issue by theomichel** [COVID19Tracking/issues#1085]
**Target Date:** This week
**Overview:** backfill up to most recent date and let daily DE continue.

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - PA-reb-20210202.csv.txt](https://github.com/COVID19Tracking/issues/files/5907876/Multi-edit.tool-PRODUCTION.-.PA-reb-20210202.csv.txt)
[Multi-edit tool-PRODUCTION - PA-reb-20210202_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5907877/Multi-edit.tool-PRODUCTION.-.PA-reb-20210202_post.csv.txt)
