### ISSUE TITLE
[GA] Capture "antigen positive cases" as probable cases

### ISSUE THREAD

**Issue by jaclyde** [COVID19Tracking/issues#1087]
State: Georgia

Issue: Moving Georgia's anitgen positive cases (which were added [here](https://github.com/COVID19Tracking/issues/issues/926)) to probable cases.

**Comment by karaschechtman** [comment]
Expected change:
![Columns F-G](https://user-images.githubusercontent.com/15933271/106814043-cd673d00-663f-11eb-8340-f571cee29982.png)

**Comment by karaschechtman** [comment]
[Changes (3).txt](https://github.com/COVID19Tracking/issues/files/5921804/Changes.3.txt)
