### ISSUE TITLE
[MS] Clear Positive Antibody Tests timeseries

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#1095]
**State:** MS

**Dates affected:** 05/21/20 - 02/10/21

**Describe the issue:** From May 21, 2020 through May 26, 2020, we briefly captured Mississippi's Positive antibody tests (specimens) through state press conferences. After May 26, 2020, Mississippi no longer reported new data for this metric and we carried it over. On February 11, 2021, we cleared Mississippi's Positive antibody tests (specimens) timeseries to ensure that our data is as accurate and consistent as possible.

**Comment by hmhoffman** [comment]
Rows edited: 265
MS 2021-02-09
    positiveTestsAntibody: None (was 95)
MS 2021-02-08
    positiveTestsAntibody: None (was 95)
MS 2021-02-07
    positiveTestsAntibody: None (was 95)
MS 2021-02-06
    positiveTestsAntibody: None (was 95)
MS 2021-02-05
    positiveTestsAntibody: None (was 95)
MS 2021-02-04
    positiveTestsAntibody: None (was 95)
MS 2021-02-03
    positiveTestsAntibody: None (was 95)
MS 2021-02-02
    positiveTestsAntibody: None (was 95)
MS 2021-02-01
    positiveTestsAntibody: None (was 95)
MS 2021-01-31
    positiveTestsAntibody: None (was 95)
MS 2021-01-30
    positiveTestsAntibody: None (was 95)
MS 2021-01-29
    positiveTestsAntibody: None (was 95)
MS 2021-01-28
    positiveTestsAntibody: None (was 95)
MS 2021-01-27
    positiveTestsAntibody: None (was 95)
MS 2021-01-26
    positiveTestsAntibody: None (was 95)
MS 2021-01-25
    positiveTestsAntibody: None (was 95)
MS 2021-01-24
    positiveTestsAntibody: None (was 95)
MS 2021-01-23
    positiveTestsAntibody: None (was 95)
MS 2021-01-22
    positiveTestsAntibody: None (was 95)
MS 2021-01-21
    positiveTestsAntibody: None (was 95)
MS 2021-01-20
    positiveTestsAntibody: None (was 95)
MS 2021-01-19
    positiveTestsAntibody: None (was 95)
MS 2021-01-18
    positiveTestsAntibody: None (was 95)
MS 2021-01-17
    positiveTestsAntibody: None (was 95)
MS 2021-01-16
    positiveTestsAntibody: None (was 95)
MS 2021-01-15
    positiveTestsAntibody: None (was 95)
MS 2021-01-14
    positiveTestsAntibody: None (was 95)
MS 2021-01-13
    positiveTestsAntibody: None (was 95)
MS 2021-01-12
    positiveTestsAntibody: None (was 95)
MS 2021-01-11
    positiveTestsAntibody: None (was 95)
MS 2021-01-10
    positiveTestsAntibody: None (was 95)
MS 2021-01-09
    positiveTestsAntibody: None (was 95)
MS 2021-01-08
    positiveTestsAntibody: None (was 95)
MS 2021-01-07
    positiveTestsAntibody: None (was 95)
MS 2021-01-06
    positiveTestsAntibody: None (was 95)
MS 2021-01-05
    positiveTestsAntibody: None (was 95)
MS 2021-01-04
    positiveTestsAntibody: None (was 95)
MS 2021-01-03
    positiveTestsAntibody: None (was 95)
MS 2021-01-02
    positiveTestsAntibody: None (was 95)
MS 2021-01-01
    positiveTestsAntibody: None (was 95)
MS 2020-12-31
    positiveTestsAntibody: None (was 95)
MS 2020-12-30
    positiveTestsAntibody: None (was 95)
MS 2020-12-29
    positiveTestsAntibody: None (was 95)
MS 2020-12-28
    positiveTestsAntibody: None (was 95)
MS 2020-12-27
    positiveTestsAntibody: None (was 95)
MS 2020-12-26
    positiveTestsAntibody: None (was 95)
MS 2020-12-25
    positiveTestsAntibody: None (was 95)
MS 2020-12-24
    positiveTestsAntibody: None (was 95)
MS 2020-12-23
    positiveTestsAntibody: None (was 95)
MS 2020-12-22
    positiveTestsAntibody: None (was 95)
MS 2020-12-21
    positiveTestsAntibody: None (was 95)
MS 2020-12-20
    positiveTestsAntibody: None (was 95)
MS 2020-12-19
    positiveTestsAntibody: None (was 95)
MS 2020-12-18
    positiveTestsAntibody: None (was 95)
MS 2020-12-17
    positiveTestsAntibody: None (was 95)
MS 2020-12-16
    positiveTestsAntibody: None (was 95)
MS 2020-12-15
    positiveTestsAntibody: None (was 95)
MS 2020-12-14
    positiveTestsAntibody: None (was 95)
MS 2020-12-13
    positiveTestsAntibody: None (was 95)
MS 2020-12-12
    positiveTestsAntibody: None (was 95)
MS 2020-12-11
    positiveTestsAntibody: None (was 95)
MS 2020-12-10
    positiveTestsAntibody: None (was 95)
MS 2020-12-09
    positiveTestsAntibody: None (was 95)
MS 2020-12-08
    positiveTestsAntibody: None (was 95)
MS 2020-12-07
    positiveTestsAntibody: None (was 95)
MS 2020-12-06
    positiveTestsAntibody: None (was 95)
MS 2020-12-05
    positiveTestsAntibody: None (was 95)
MS 2020-12-04
    positiveTestsAntibody: None (was 95)
MS 2020-12-03
    positiveTestsAntibody: None (was 95)
MS 2020-12-02
    positiveTestsAntibody: None (was 95)
MS 2020-12-01
    positiveTestsAntibody: None (was 95)
MS 2020-11-30
    positiveTestsAntibody: None (was 95)
MS 2020-11-29
    positiveTestsAntibody: None (was 95)
MS 2020-11-28
    positiveTestsAntibody: None (was 95)
MS 2020-11-27
    positiveTestsAntibody: None (was 95)
MS 2020-11-26
    positiveTestsAntibody: None (was 95)
MS 2020-11-25
    positiveTestsAntibody: None (was 95)
MS 2020-11-24
    positiveTestsAntibody: None (was 95)
MS 2020-11-23
    positiveTestsAntibody: None (was 95)
MS 2020-11-22
    positiveTestsAntibody: None (was 95)
MS 2020-11-21
    positiveTestsAntibody: None (was 95)
MS 2020-11-20
    positiveTestsAntibody: None (was 95)
MS 2020-11-19
    positiveTestsAntibody: None (was 95)
MS 2020-11-18
    positiveTestsAntibody: None (was 95)
MS 2020-11-17
    positiveTestsAntibody: None (was 95)
MS 2020-11-16
    positiveTestsAntibody: None (was 95)
MS 2020-11-15
    positiveTestsAntibody: None (was 95)
MS 2020-11-14
    positiveTestsAntibody: None (was 95)
MS 2020-11-13
    positiveTestsAntibody: None (was 95)
MS 2020-11-12
    positiveTestsAntibody: None (was 95)
MS 2020-11-11
    positiveTestsAntibody: None (was 95)
MS 2020-11-10
    positiveTestsAntibody: None (was 95)
MS 2020-11-09
    positiveTestsAntibody: None (was 95)
MS 2020-11-08
    positiveTestsAntibody: None (was 95)
MS 2020-11-07
    positiveTestsAntibody: None (was 95)
MS 2020-11-06
    positiveTestsAntibody: None (was 95)
MS 2020-11-05
    positiveTestsAntibody: None (was 95)
MS 2020-11-04
    positiveTestsAntibody: None (was 95)
MS 2020-11-03
    positiveTestsAntibody: None (was 95)
MS 2020-11-02
    positiveTestsAntibody: None (was 95)
MS 2020-11-01
    positiveTestsAntibody: None (was 95)
MS 2020-10-31
    positiveTestsAntibody: None (was 95)
MS 2020-10-30
    positiveTestsAntibody: None (was 95)
MS 2020-10-29
    positiveTestsAntibody: None (was 95)
MS 2020-10-28
    positiveTestsAntibody: None (was 95)
MS 2020-10-27
    positiveTestsAntibody: None (was 95)
MS 2020-10-26
    positiveTestsAntibody: None (was 95)
MS 2020-10-25
    positiveTestsAntibody: None (was 95)
MS 2020-10-24
    positiveTestsAntibody: None (was 95)
MS 2020-10-23
    positiveTestsAntibody: None (was 95)
MS 2020-10-22
    positiveTestsAntibody: None (was 95)
MS 2020-10-21
    positiveTestsAntibody: None (was 95)
MS 2020-10-20
    positiveTestsAntibody: None (was 95)
MS 2020-10-19
    positiveTestsAntibody: None (was 95)
MS 2020-10-18
    positiveTestsAntibody: None (was 95)
MS 2020-10-17
    positiveTestsAntibody: None (was 95)
MS 2020-10-16
    positiveTestsAntibody: None (was 95)
MS 2020-10-15
    positiveTestsAntibody: None (was 95)
MS 2020-10-14
    positiveTestsAntibody: None (was 95)
MS 2020-10-13
    positiveTestsAntibody: None (was 95)
MS 2020-10-12
    positiveTestsAntibody: None (was 95)
MS 2020-10-11
    positiveTestsAntibody: None (was 95)
MS 2020-10-10
    positiveTestsAntibody: None (was 95)
MS 2020-10-09
    positiveTestsAntibody: None (was 95)
MS 2020-10-08
    positiveTestsAntibody: None (was 95)
MS 2020-10-07
    positiveTestsAntibody: None (was 95)
MS 2020-10-06
    positiveTestsAntibody: None (was 95)
MS 2020-10-05
    positiveTestsAntibody: None (was 95)
MS 2020-10-04
    positiveTestsAntibody: None (was 95)
MS 2020-10-03
    positiveTestsAntibody: None (was 95)
MS 2020-10-02
    positiveTestsAntibody: None (was 95)
MS 2020-10-01
    positiveTestsAntibody: None (was 95)
MS 2020-09-30
    positiveTestsAntibody: None (was 95)
MS 2020-09-29
    positiveTestsAntibody: None (was 95)
MS 2020-09-28
    positiveTestsAntibody: None (was 95)
MS 2020-09-27
    positiveTestsAntibody: None (was 95)
MS 2020-09-26
    positiveTestsAntibody: None (was 95)
MS 2020-09-25
    positiveTestsAntibody: None (was 95)
MS 2020-09-24
    positiveTestsAntibody: None (was 95)
MS 2020-09-23
    positiveTestsAntibody: None (was 95)
MS 2020-09-22
    positiveTestsAntibody: None (was 95)
MS 2020-09-21
    positiveTestsAntibody: None (was 95)
MS 2020-09-20
    positiveTestsAntibody: None (was 95)
MS 2020-09-19
    positiveTestsAntibody: None (was 95)
MS 2020-09-18
    positiveTestsAntibody: None (was 95)
MS 2020-09-17
    positiveTestsAntibody: None (was 95)
MS 2020-09-16
    positiveTestsAntibody: None (was 95)
MS 2020-09-15
    positiveTestsAntibody: None (was 95)
MS 2020-09-14
    positiveTestsAntibody: None (was 95)
MS 2020-09-13
    positiveTestsAntibody: None (was 95)
MS 2020-09-12
    positiveTestsAntibody: None (was 95)
MS 2020-09-11
    positiveTestsAntibody: None (was 95)
MS 2020-09-10
    positiveTestsAntibody: None (was 95)
MS 2020-09-09
    positiveTestsAntibody: None (was 95)
MS 2020-09-08
    positiveTestsAntibody: None (was 95)
MS 2020-09-07
    positiveTestsAntibody: None (was 95)
MS 2020-09-06
    positiveTestsAntibody: None (was 95)
MS 2020-09-05
    positiveTestsAntibody: None (was 95)
MS 2020-09-04
    positiveTestsAntibody: None (was 95)
MS 2020-09-03
    positiveTestsAntibody: None (was 95)
MS 2020-09-02
    positiveTestsAntibody: None (was 95)
MS 2020-09-01
    positiveTestsAntibody: None (was 95)
MS 2020-08-31
    positiveTestsAntibody: None (was 95)
MS 2020-08-30
    positiveTestsAntibody: None (was 95)
MS 2020-08-29
    positiveTestsAntibody: None (was 95)
MS 2020-08-28
    positiveTestsAntibody: None (was 95)
MS 2020-08-27
    positiveTestsAntibody: None (was 95)
MS 2020-08-26
    positiveTestsAntibody: None (was 95)
MS 2020-08-25
    positiveTestsAntibody: None (was 95)
MS 2020-08-24
    positiveTestsAntibody: None (was 95)
MS 2020-08-23
    positiveTestsAntibody: None (was 95)
MS 2020-08-22
    positiveTestsAntibody: None (was 95)
MS 2020-08-21
    positiveTestsAntibody: None (was 95)
MS 2020-08-20
    positiveTestsAntibody: None (was 95)
MS 2020-08-19
    positiveTestsAntibody: None (was 95)
MS 2020-08-18
    positiveTestsAntibody: None (was 95)
MS 2020-08-17
    positiveTestsAntibody: None (was 95)
MS 2020-08-16
    positiveTestsAntibody: None (was 95)
MS 2020-08-15
    positiveTestsAntibody: None (was 95)
MS 2020-08-14
    positiveTestsAntibody: None (was 95)
MS 2020-08-13
    positiveTestsAntibody: None (was 95)
MS 2020-08-12
    positiveTestsAntibody: None (was 95)
MS 2020-08-11
    positiveTestsAntibody: None (was 95)
MS 2020-08-10
    positiveTestsAntibody: None (was 95)
MS 2020-08-09
    positiveTestsAntibody: None (was 95)
MS 2020-08-08
    positiveTestsAntibody: None (was 95)
MS 2020-08-07
    positiveTestsAntibody: None (was 95)
MS 2020-08-06
    positiveTestsAntibody: None (was 95)
MS 2020-08-05
    positiveTestsAntibody: None (was 95)
MS 2020-08-04
    positiveTestsAntibody: None (was 95)
MS 2020-08-03
    positiveTestsAntibody: None (was 95)
MS 2020-08-02
    positiveTestsAntibody: None (was 95)
MS 2020-08-01
    positiveTestsAntibody: None (was 95)
MS 2020-07-31
    positiveTestsAntibody: None (was 95)
MS 2020-07-30
    positiveTestsAntibody: None (was 95)
MS 2020-07-29
    positiveTestsAntibody: None (was 95)
MS 2020-07-28
    positiveTestsAntibody: None (was 95)
MS 2020-07-27
    positiveTestsAntibody: None (was 95)
MS 2020-07-26
    positiveTestsAntibody: None (was 95)
MS 2020-07-25
    positiveTestsAntibody: None (was 95)
MS 2020-07-24
    positiveTestsAntibody: None (was 95)
MS 2020-07-23
    positiveTestsAntibody: None (was 95)
MS 2020-07-22
    positiveTestsAntibody: None (was 95)
MS 2020-07-21
    positiveTestsAntibody: None (was 95)
MS 2020-07-20
    positiveTestsAntibody: None (was 95)
MS 2020-07-19
    positiveTestsAntibody: None (was 95)
MS 2020-07-18
    positiveTestsAntibody: None (was 95)
MS 2020-07-17
    positiveTestsAntibody: None (was 95)
MS 2020-07-16
    positiveTestsAntibody: None (was 95)
MS 2020-07-15
    positiveTestsAntibody: None (was 95)
MS 2020-07-14
    positiveTestsAntibody: None (was 95)
MS 2020-07-13
    positiveTestsAntibody: None (was 95)
MS 2020-07-12
    positiveTestsAntibody: None (was 95)
MS 2020-07-11
    positiveTestsAntibody: None (was 95)
MS 2020-07-10
    positiveTestsAntibody: None (was 95)
MS 2020-07-09
    positiveTestsAntibody: None (was 95)
MS 2020-07-08
    positiveTestsAntibody: None (was 95)
MS 2020-07-07
    positiveTestsAntibody: None (was 95)
MS 2020-07-06
    positiveTestsAntibody: None (was 95)
MS 2020-07-05
    positiveTestsAntibody: None (was 95)
MS 2020-07-04
    positiveTestsAntibody: None (was 95)
MS 2020-07-03
    positiveTestsAntibody: None (was 95)
MS 2020-07-02
    positiveTestsAntibody: None (was 95)
MS 2020-07-01
    positiveTestsAntibody: None (was 95)
MS 2020-06-30
    positiveTestsAntibody: None (was 95)
MS 2020-06-29
    positiveTestsAntibody: None (was 95)
MS 2020-06-28
    positiveTestsAntibody: None (was 95)
MS 2020-06-27
    positiveTestsAntibody: None (was 95)
MS 2020-06-26
    positiveTestsAntibody: None (was 95)
MS 2020-06-25
    positiveTestsAntibody: None (was 95)
MS 2020-06-24
    positiveTestsAntibody: None (was 95)
MS 2020-06-23
    positiveTestsAntibody: None (was 95)
MS 2020-06-22
    positiveTestsAntibody: None (was 95)
MS 2020-06-21
    positiveTestsAntibody: None (was 95)
MS 2020-06-20
    positiveTestsAntibody: None (was 95)
MS 2020-06-19
    positiveTestsAntibody: None (was 95)
MS 2020-06-18
    positiveTestsAntibody: None (was 95)
MS 2020-06-17
    positiveTestsAntibody: None (was 95)
MS 2020-06-16
    positiveTestsAntibody: None (was 95)
MS 2020-06-15
    positiveTestsAntibody: None (was 95)
MS 2020-06-14
    positiveTestsAntibody: None (was 95)
MS 2020-06-13
    positiveTestsAntibody: None (was 95)
MS 2020-06-12
    positiveTestsAntibody: None (was 95)
MS 2020-06-11
    positiveTestsAntibody: None (was 95)
MS 2020-06-10
    positiveTestsAntibody: None (was 95)
MS 2020-06-09
    positiveTestsAntibody: None (was 95)
MS 2020-06-08
    positiveTestsAntibody: None (was 95)
MS 2020-06-07
    positiveTestsAntibody: None (was 95)
MS 2020-06-06
    positiveTestsAntibody: None (was 95)
MS 2020-06-05
    positiveTestsAntibody: None (was 95)
MS 2020-06-04
    positiveTestsAntibody: None (was 95)
MS 2020-06-03
    positiveTestsAntibody: None (was 95)
MS 2020-06-02
    positiveTestsAntibody: None (was 95)
MS 2020-06-01
    positiveTestsAntibody: None (was 95)
MS 2020-05-31
    positiveTestsAntibody: None (was 95)
MS 2020-05-30
    positiveTestsAntibody: None (was 95)
MS 2020-05-29
    positiveTestsAntibody: None (was 95)
MS 2020-05-28
    positiveTestsAntibody: None (was 95)
MS 2020-05-27
    positiveTestsAntibody: None (was 95)
MS 2020-05-26
    positiveTestsAntibody: None (was 95)
MS 2020-05-25
    positiveTestsAntibody: None (was 80)
MS 2020-05-24
    positiveTestsAntibody: None (was 80)
MS 2020-05-23
    positiveTestsAntibody: None (was 80)
MS 2020-05-22
    positiveTestsAntibody: None (was 80)
MS 2020-05-21
    positiveTestsAntibody: None (was 80)

**Comment by jaclyde** [comment]
The carried over value for Mississippi's Positive antibody tests was not cleared from February 10, 2021 when the rest of the time series was cleared. Deleting the value.

Value updated: 
[Changes (33).txt](https://github.com/COVID19Tracking/issues/files/6455548/Changes.33.txt)
