### ISSUE TITLE
Cumulative hospitalizations in Arizona

### ISSUE THREAD

**Issue by KarenReill** [COVID19Tracking/issues#110]
Hospitalizations in Arizona are under-reported in the Covid Tracking Project.  At the time of this writing, it notes 140 cumulative hospitalizations for Arizona.  However, Maricopa County alone (the most populous county) has 158 as of 1 Apr 2020, 140 yesterday.  Perhaps the data published on CTP is using hospitalization data solely from Maricopa County?  There are 14 additional counties.

**Comment by muamichali** [comment]
Hi @KarenReill 

Sorry it took a little while to get to your query. In the past, we used hospitalization data from the counties that were reporting it. We are currently using https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/index.php#novel-coronavirus-hospital-reporting-data  for **current** hospitalizations state wide in AZ. 

Unfortunately right now this dashboard is not working but you can see the historical values in the API endpoint on our site https://covidtracking.com/api/v1/states/daily.json
