### ISSUE TITLE
Missing dates for Michigan new positive cases

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/issues#111]
From Brad Gowland, who's watching our data: "Let me know if there's a better way to propose any corrections in the future. I work with Michigan Radio, Southeastern Michigan's NPR station, we're using the API for some graphics on our site and we follow the Michigan numbers closely."

He just submitted the following comment as part of a pull request on our data backup repo, which I'm not going to merge there but putting his comments here in case we want to make these fixes to our historical data (and then the backup repo will pick that up):

"Aggregates were correct, but some missing days for Michigan data would add the total of two days of cases:

- 4 new positives on 3/12, 10 new positives on 3/13 instead of 14 new positives on 3/13
- 993 new positives on 3/28, 836 new positives on 3/29 instead of 1,829 new cases on 3/29"

**Comment by schmian** [comment]
👀

**Comment by muamichali** [comment]
I asked Brad some clarifying questions over at https://github.com/COVID19Tracking/covid-tracking-data/pull/20
