### ISSUE TITLE
[NC] backfill total tests, and adjust PCR testing based on PCR-only testing numbers from the state

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/issues#1119]
**Target Date:** Backfilling tests from March-17th to May-17th, 2020.
Updating the time series with the separated PCR (from antigen) tests starting on September 22th, 2020 -- this is when the state started reporting separate PCR and antigen testing.

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - NC-reb-20210302_post.csv.txt](https://github.com/COVID19Tracking/issues/files/6071630/Multi-edit.tool-PRODUCTION.-.NC-reb-20210302_post.csv.txt)
[Multi-edit tool-PRODUCTION - NC-reb-20210302.csv.txt](https://github.com/COVID19Tracking/issues/files/6071631/Multi-edit.tool-PRODUCTION.-.NC-reb-20210302.csv.txt)

**Comment by karaschechtman** [comment]
We carried a source note and accidentally used lumped at the topline by mistake -- fixing
[Changes (7).txt](https://github.com/COVID19Tracking/issues/files/6079266/Changes.7.txt)
