### ISSUE TITLE
The row of Colorado (CO) state data for 3/31 is a duplicate 3/30

### ISSUE THREAD

**Issue by philgoetz** [COVID19Tracking/issues#112]
These can't both be right unless CO reported no data for 3/31:

20200331 | CO | 2,627 | 12,737 |   | 414 | 51 | 15,364
-- | -- | -- | -- | -- | -- | -- | --
20200330 | CO | 2,627 | 12,737 |   | 414 | 51 | 15,364
-- | -- | -- | -- | -- | -- | -- | --

**Comment by saewoonam** [comment]
Same as issue #98.

**Comment by philgoetz** [comment]
> Same as issue #98.
I guess I should close this one, then.
