### ISSUE TITLE
[MI] Patching 03/10/20 - 03/16/20 due to copy paste error

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#1128]
**State or US**: [State name, or "US" if this is an issue with country-wide data]

**Describe the problem**
When we copy pasted for #487 we missed 03/10/20 to 03/16/20. 

**Link to data source**
https://docs.google.com/spreadsheets/d/1n0dOR8Dxjtg_usQdgbYe4LuDPURi_HK6WFL3wvawRn0/edit#gid=500776026

**Comment by karaschechtman** [comment]
[Changes (9).txt](https://github.com/COVID19Tracking/issues/files/6087378/Changes.9.txt)
