### ISSUE TITLE
[KY] Patch 01/25/21 Cur. hosp

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#1136]
**State:** KY

**Dates affected:** 01/25/21

**Describe the issue:** On January 25, 2021, we incorrectly captured Kentucky's Currently hospitalized as 1537 instead of 1539. This error was corrected on March 29, 2021.

**Comment by muamichali** [comment]
[
[Changes (3).txt](https://github.com/COVID19Tracking/issues/files/6222746/Changes.3.txt)
](url)
