### ISSUE TITLE
[ND] Remove total, positive, and negative antibody tests from 12/15/20 onward

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#1145]
**State:** ND

**Dates affected:** 12/15/20-03/07/21

**Describe the issue:** On December 15, 2020, North Dakota stopped updating Total antibody tests (specimens), Positive antibody tests (specimens), and Negative antibody tests (specimens), and later removed the metrics from their data dashboard entirely. To ensure that our dataset represents values that are as up to date for the day in our timeseries as possible, we are clearing their  Total antibody tests (specimens), Positive antibody tests (specimens), and Negative antibody tests (specimens) from December 15, 2020 to March 7, 2021.

**Comment by jaclyde** [comment]
Values removed: 
[Changes (18).txt](https://github.com/COVID19Tracking/issues/files/6347243/Changes.18.txt)
