### ISSUE TITLE
No of hospitalization

### ISSUE THREAD

**Issue by sramesh81** [COVID19Tracking/issues#116]
What does no of hopsitalization mean?
Does this tell how many people have been hospitalized so far? Any data that tells how many of them discharged so it gives and idea on how much hospital capacity is used up? 
Also if possible can that data be available for no of ICU beds used up?
Thanks

**Comment by careeningspace** [comment]
Number of Hospitalized is a cumulative number. We will be adding ICU data soon.

Regarding capacity, that is currently beyond our scope

**Comment by DataHunter500** [comment]
I can’t speak for the other states, but the number shown for the state of Connecticut hospitalizations is the current number of people hospitalized not cumulative. That can be confirmed at the Connecticut Public health website which has the exact numbers that are at Covid tracking.com

**Comment by roblav96** [comment]
@sramesh81 @careeningspace @DataHunter500 

## Hospital datasets

> COVID-19 relevant data on hospital location / capacity, nursing home location / capacity, county demographics
https://github.com/jsfenfen/covid_hospitals_demographics

> `populationData.tsv` - Models of COVID-19 outbreak trajectories and hospital demand
https://github.com/neherlab/covid19_scenarios/blob/master/data/populationData.tsv

> Hospitals State Health Facts - Kaiser Health Foundation
https://www.kff.org/state-category/providers-service-use/hospitals/

> Health Care Resources - Organization for Economic Cooperation and Development (OECD)
https://stats.oecd.org/index.aspx?DataSetCode=HEALTH_REAC#

> United States Resource Availability for COVID-19 - Society of Critical Care Medicine (SCCM)
https://www.sccm.org/Blog/March-2020/United-States-Resource-Availability-for-COVID-19

> COVID19 Parameters
https://docs.google.com/spreadsheets/d/1zZKKnZ47lqfmUGYDQuWNnzKnh-IDMy15LBaRmrBcjqE/edit#gid=1585003222

**Comment by jdmaresco** [comment]
As of today, we have started splitting out current vs. cumulative hospitalized in our dataset. If you see old numbers that are listed as "cumulative" that should be listed as "current", it would be helpful if you could file a separate issue for each state, with screenshots and the relevant dates, and we will address. Thank you for the report!
