### ISSUE TITLE
DE cases 3/31-4/1

### ISSUE THREAD

**Issue by OregonCarrot** [COVID19Tracking/issues#117]
The # of cases for Delaware dropped from 406 on 3/31 to 368 on 4/1.

Given that it reports positive tests, and not active cases, I don't know how this is possible.

**Comment by tomdottom** [comment]
Relates to #101

**Comment by tomdottom** [comment]
I believe this has already been addressed

![image](https://user-images.githubusercontent.com/5106166/78360034-267bc580-7584-11ea-9c42-536faef8cf6e.png)

**Comment by OregonCarrot** [comment]
Thank you
