### ISSUE TITLE
Washington State data is incorrect

### ISSUE THREAD

**Issue by jessejanderson** [COVID19Tracking/issues#118]
Not sure if this is the right repo, but the data for WA is currently incorrect. Their system is currently having [technical difficulties](https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/DelayDataPosting.pdf) and covidtracking.com currently has duplicate data listed for March 30th and 31st.

**Comment by careeningspace** [comment]
Hello,

I apologize for the delay, but I was able to clean up some of the numbers for Washington. Their negative/total tested number as reported is hard to reconcile, but I have updated the positives. One of the challenges with Washington is that they appear to be updating historical numbers over time, so it will take regular maintenance to keep in sync.

**Before**
![Screen Shot 2020-04-09 at 1 18 54 PM](https://user-images.githubusercontent.com/43073915/79060602-12efef00-7c55-11ea-8c9e-af20838dc457.png)

*Screencap from state site** These numbers are still in flux and may change.
![Screen Shot 2020-04-12 at 12 47 36 AM](https://user-images.githubusercontent.com/43073915/79060905-5bf57280-7c58-11ea-8a50-013ca5c9383b.png)
![Screen Shot 2020-04-12 at 12 51 19 AM](https://user-images.githubusercontent.com/43073915/79060907-60219000-7c58-11ea-8f7f-20edb6fb2911.png)

**After**
![Screen Shot 2020-04-12 at 12 54 52 AM](https://user-images.githubusercontent.com/43073915/79060909-644dad80-7c58-11ea-8560-9cb46abd2b07.png)
