### ISSUE TITLE
Arithmetic error in California numbers

### ISSUE THREAD

**Issue by dbrekke** [COVID19Tracking/issues#119]
Total test results currently listed for California is incorrect. It's listed as 90,138, but that number is the sum of positive+negative+pending tests (instead of just positive+negative). Here's a screenshot: 
<img width="616" alt="Screen Shot 2020-04-01 at 10 24 30 PM" src="https://user-images.githubusercontent.com/15219955/78213564-f17a5080-7467-11ea-8695-26b9cb841424.png">

**Comment by kevee** [comment]
Thanks for this! We [have a fix](https://github.com/COVID19Tracking/website/pull/358) to be implemented soon.

**Comment by kevee** [comment]
Fix deployed. Thanks again!

https://covidtracking.com/data/state/california
