### ISSUE TITLE
Florida moved to a new dashboard

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/issues#12]
The currently listed URL `http://www.floridahealth.gov/diseases-and-conditions/COVID-19/` now redirects to a domain (`floridahealthcovid19.gov`) which no longer lists the same data that was previously available on the daily report still published there.

I recommend the [new dashboard](https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429) the report now links to: `https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429`. 

![image](https://user-images.githubusercontent.com/65950/76922117-3453fa00-68a6-11ea-8467-8e7898604b2b.png)

Although it visually obfuscates a ton of data it does include the previously listed data: 
- number of people tested
- negative tests
- positive tests
- pending results
- currently monitored individuals

It uses the familiar [ARCGIS map from JHU](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6).

I'm trying to get familiar with the Ruby crawler to submit a Pull Request right now but perhaps @huuep can update the crawler faster than I can.

**Comment by olivierlacan** [comment]
FYI I emailed and [tweeted at][1] the Florida Department of Health (ESF14@em.myflorida.com) to ask them to follow the [Best Practices document][2]. I'm hoping they improve their releases over the next few days.

[1]: https://twitter.com/olivierlacan/status/1240118090492452864
[2]: https://docs.google.com/document/d/1OyN6_1UeDePwPwKi6UKZB8GwNC7-kSf1-BO2af8kqVA/edit

**Comment by olivierlacan** [comment]
With some browsing around, I managed to find and reach out to the maintainer of the new Florida COVID-19 dashboard thanks to its About page: https://fdoh.maps.arcgis.com/home/item.html?id=8d0de33f260d444c852a615dc7837c86

The page itself is helpful to interpret some of the data. I think it's more likely she'll respond to me than the FDOH Twitter account or email so here's hoping we'll get some improvements in data released tomorrow.

**Comment by hammer** [comment]
Thanks @olivierlacan! We were also excited to see this dashboard show up: https://twitter.com/COVID19Tracking/status/1239780238013292545. We use this site for data collection internally, but the external link is intended to take users to the COVID-19 landing page for each state, so I think we'll keep it as is.
