### ISSUE TITLE
suggestion to remove all fatality data

### ISSUE THREAD

**Issue by jonah** [COVID19Tracking/issues#120]
I know this will probably go ignored, but the emerging science is suggesting coronavirus is an asymptomatic spread low fatality virus.  Infection rates are estimated to be around 60% in Washington State.  Since rick factors align exactly with natural cause of death risk factors you would strongly suggest this was just a false correlation problem.  You publicly available data is fantastic for so many things, but the death numbers lead to bad reporting and panic.

**Comment by careeningspace** [comment]
Hello,

I thank you for your suggestion. We are strictly reporting the data provided by the state. We avoid redefining this data. Should the states choose to reclassify the data, we will report that.

That is a fantastic question for your state and local governments!
