### ISSUE TITLE
increase default width of Google sheet?

### ISSUE THREAD

**Issue by smrgit** [COVID19Tracking/issues#122]
depending on which url I use to access the Google sheet, the columns are too narrow (and un-adjustable) to be able to see the entire numeric values -- also cannot read the headings, eg:

![image](https://user-images.githubusercontent.com/3067449/78286664-d1817600-74d5-11ea-9d4b-3873d7bf51db.png)

**Comment by jdmaresco** [comment]
@smrgit thanks for the report. I've adjusted the columns. It may take a bit for the cache to clear and for these changes to reflect.

**Comment by smrgit** [comment]
looks great, thank you!
