### ISSUE TITLE
Hawaii Negative Data Source?

### ISSUE THREAD

**Issue by natexx** [COVID19Tracking/issues#123]
The Hawaii [data source](https://health.hawaii.gov/coronavirusdisease2019/) is not reporting "negative" totals, but the covidtracking [website](https://covidtracking.com/data/state/hawaii) is.

Where is Covidtracking acquiring the negative numbers that they are reporting?

**Comment by muamichali** [comment]
@natexx https://health.hawaii.gov/news/corona-virus/hawaii-covid-19-daily-news-digest-april-1-2020/ 

<img width="1001" alt="Screen Shot 2020-04-03 at 11 00 25 AM" src="https://user-images.githubusercontent.com/1749380/78375137-5df56c80-759a-11ea-91eb-86a9f4a51a26.png">
