### ISSUE TITLE
Michigan negative counts -- COVID19Tracking is behind latest state report

### ISSUE THREAD

**Issue by catawbasam** [COVID19Tracking/issues#124]
If they are on weekly updates, we should note that.  Otherwise they may not be tracking the tests.
Worrisome for one of the top hot-spots.

**Comment by catawbasam** [comment]
Updated numbers are posted to https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html

## Cumulative Number of Specimens Tested for COVID-19 - Last Updated 4/2/2020 14:45
Lab Type | Negative Tests | Positive Tests | Total Specimens Tested
-- | -- | -- | --
Commercial | 2312 | 592 | 2909
Hospital | 16930 | 5906 | 22450
Public   Health | 4303 | 1507 | 5818
Grand Total | 23545 | 8005 | 31177

### Notes

Notes:
This is a new reporting system and additional laboratories will be included over time.  Counts of specimens tested positive will not equal number of people with COVID-19. People may have more than one test or may have had their test from an out of state lab. 
Total samples tested includes test that were negative, positive, and inconclusive.
Commercial labs only includes data from LabCorp.
Public health labs include the Michigan Department of Health and Human Services Bureau of Laboratories.
Counts represent the total specimens tested, not total patients tested. A patient can have more than one specimen tested, therefore the number of specimens tested may be more than the number of patients tested.

**Comment by careeningspace** [comment]
Those counts are for specimens. I did update with even more accurate data. See issue #173
