### ISSUE TITLE
PA cumulative hospitalized overcounting 

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#126]
From @webmasterkai 
> The hospitalizedCummulative data for PA goes down from 20200329 to 20200330, then does not exceed the 20200329 value again until today.

The higher, earlier numbers are not correct. We should adjust based on screen captures

![image](https://user-images.githubusercontent.com/1327983/78314360-c3f4dc00-7527-11ea-86db-5dfa3b58665a.png)

**Comment by muamichali** [comment]
I updated States Daily based on the screenshots.
