### ISSUE TITLE
ICU total data entry mistake?

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/issues#128]
> Important FYI. I think there was a data entry mistake
> 
> Says 4,264 in ICU currently (but 541 in ICU cumulative)
> Can you check this.👆🏼
> 
> Also it would be helpful to know how may states have provided hospitalization and ICU stats. Don’t seem to be that many on api page.

Screenshots here:
https://twitter.com/We3forDemocracy/status/1245894298903523329

**Comment by careeningspace** [comment]
We have updated the Cumulative vs Current issues that we have caught. Please see issue #132 

Thanks!
