### ISSUE TITLE
Hospitalization/Ventilator/ICU Data incomplete thus misleading

### ISSUE THREAD

**Issue by faronium** [COVID19Tracking/issues#129]
Can you please update your website to note that the non-testing related numbers are mostly unavailable from states and thus national totals can be wildly inaccurate? For example, your US total ventilator number is currently 67 and lists zero people in NY despite yesterday's death number of more than 300.  That's simply impossible. Other hot spots like Louisiana, Michigan, New Jersey, and Florida don't list any ICU or ventilator data and thus your US totals are way low. This is fueling the conspiracy folks who are claiming that this is all a hoax or that the modeled case forecasts are completely wrong and overblown. Please, either don't report the data or somehow clearly quality the US totals so that people know what is trustworthy.

**Comment by Jmuccigr** [comment]
> For example, your US total ventilator number is currently 67 and lists zero people in NY despite yesterday's death number of more than 300.

Actually the database gives NY's number as ```NA``` which is not 0, so it's correct. I agree that some more lengthier notes are needed in a prominent place.

PS I'd also suggest just giving a numerical score rather than a letter grade. Maybe even just provide each state a quick table with checkmarks for each of the 4 categories.

**Comment by faronium** [comment]
> Actually the database gives NY's number as NA which is not 0, so it's correct.

Ah, that makes sense. I was looking at the spreadsheet on google docs that shows a blank, so missed that it is NA in the real data. 

The problem with this arises here:
https://covidtracking.com/data
Where cumulative hospitalized seems to be the sum of incomplete data and thus is misleadingly low.  In R-speak, maybe the sums for nearly incomplete data should be sum(x,na.rm=F) or some such. Folks who don't know better will sum up the ventilator data and get a small number and may run with it.

**Comment by careeningspace** [comment]
Please check out #132 to find where we updated all of the outcome data to better match how states are reporting. We have also stopped reporting the outcome data as a national aggregate because of the @faronium raises
