### ISSUE TITLE
Update Hawaii to include totals, not just positives

### ISSUE THREAD

**Issue by anticrisis** [COVID19Tracking/issues#13]
State of Hawaii has more complete information, including negative results, which are not currently included in the tracker, here: https://health.hawaii.gov/news/covid-19-updates/

The data is in tables in each of the daily updates linked to from that page.

For example, [today's update](https://health.hawaii.gov/news/corona-virus/covid-19-daily-update-march-17-2020/) has cumulative 14 positive, and 93 negative.

**Comment by hammer** [comment]
@anticrisis we noted this new site yesterday in our Slack but failed to incorporate it into our data entry process today. I'm very sorry about that, we'll be sure to get it moving forward.

**Comment by hammer** [comment]
We're now tracking this data, thanks again @anticrisis for highlighting it!
