### ISSUE TITLE
MS: Governor reporting much higher test numbers

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#130]
The governor of Mississippi was on Twitter today bragging on their testing stats. He says:

> Mississippi has done 16,662 total tests. We have 1,177 cases. Our population is a little less than three million.

That positive count agrees with the database, but his test count is three times higher. 

Looking at it, I'm also not sure where the project's test numbers are coming from. The webpage for the MS health dept reports only _their_ tests and has a positive rate of 10% or so. (I don't see any info on private tests on their pages.) It also says they've done 5,257 tests. Together therefore they account for about half of cases, but nearly 90% of tests in the project. That seems off.

If their pos rate persists in private testing, it would suggest roughly 5,000 private tests have been done, for a total test count of around 10k. That's a lot lower than the governor's claim of 16k, but maybe private companies are testing a different population. His claim seems closer than the project's 5,900 count.

In any case, something's inconsistent here.

Source: https://twitter.com/tatereeves/status/1245843019745673217

**Comment by muamichali** [comment]
@Jmuccigr Thank you for this information. 

The governor is indeed reporting 16,662 tests, however tests do not equal **number of individuals tested.** which is what we are tracking.

For testing data (positives and negatives) in MS, our project is using the numbers provided by the state on https://msdh.ms.gov/msdhsite/_static/14,0,420.html. You are absolutely correct that they are only reporting tests from MPHL. 

Please urge MS to provide the number of individuals tested, and positive from private sources so we can expand our reporting data.

**Comment by Jmuccigr** [comment]
Thanks for the reply. Yes, I get the distinction, but you'll see that further on in the thread the governor compares that number to the "residents tested" in South Korea, so he is implying that that figure is people tested, not simply tests. Unless he's just trying to be deceptive.

Would a 3:1 ratio of tests to persons tested not be a bit high?

To the second point, since the website gives only the public tests, where is the rest of the count coming from? Again, the public positive rate would suggest a lot more private tests than are listed.
