### ISSUE TITLE
Add reporting grade to reports

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#131]
Since the [recommendation](https://covidtracking.com/about-data#data-quality-grade) is not to report positive rates only for "states that have an A grade," please include the grade in the daily reports so that we can easily exclude non-A states. I'd be happy with four fields for each of the categories, TBH.

**Comment by Nosferican** [comment]
See https://github.com/COVID19Tracking/issues/issues/157#issuecomment-621448230

**Comment by muamichali** [comment]
As @Nosferican said, we have added the state grades to the states Daily API. The column name is dataQualityGrade
