### ISSUE TITLE
Revisit previous logic about migrating current numbers to cumulative

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#132]
When we first added outcomes data, we decided to copy over current values to cumulative in the absence of a cumulative number from the state. We're moving away from this for new data and should probably reverse the backfill previously done here:

https://github.com/COVID19Tracking/issues/issues/70

**Comment by jdmaresco** [comment]
Based on @careeningspace comment on #70, marking this as closed

**Comment by jdmaresco** [comment]
Just noticed the timing on that comment. Reopening until confirmed this has been addressed

**Comment by jdmaresco** [comment]
Just noticed the timing on that comment. Reopening until confirmed this has been addressed

**Comment by careeningspace** [comment]
- [ ] **Arizona**  The data collected on hospitalization was from one-two counties only. If you want this data, it can be found at the county sites: [from Maricopa County](https://www.maricopa.gov/5460/Coronavirus-Disease-2019) and [Pima County](https://webcms.pima.gov/cms/One.aspx?portalId=169&pageId=527452):

**Before:**
![Screen Shot 2020-04-08 at 8 08 04 AM](https://user-images.githubusercontent.com/43073915/78782535-2eff4200-7970-11ea-9a88-9a0fce477bca.png)

**After:**
![Screen Shot 2020-04-08 at 8 12 30 AM](https://user-images.githubusercontent.com/43073915/78782990-eb590800-7970-11ea-8a16-0bd7474cfe18.png)

- [ ] **Arkansas** Additional cumulative hospitalization and ventilator data were obtained from the daily press conferences. 
[Apr-5 Press Conference](https://youtu.be/rGLeGLkW5jY?t=433)
[Apr-2 Press Conference](https://youtu.be/B5MeQsDO7Io?t=584)
[Apr-7 Press Conference](https://youtu.be/Y0P0HXEp98A?t=654)

**Before**
![Screen Shot 2020-04-08 at 8 23 37 AM](https://user-images.githubusercontent.com/43073915/78796357-2dd81000-7984-11ea-81c0-09b3939ce4a8.png)

**After**
![image](https://user-images.githubusercontent.com/43073915/78796371-36304b00-7984-11ea-97e3-1ee7bed3a91a.png)

**Comment by careeningspace** [comment]
- [ ] **Louisiana** Moving hospitalization/ventilator data from the cumulative column to the current column. Also a slight update to 4/6 data from [4/7 press release](http://ldh.la.gov/index.cfm/newsroom/detail/5531)

**Before**
![Screen Shot 2020-04-08 at 10 50 20 AM](https://user-images.githubusercontent.com/43073915/78801854-2b2ce900-798b-11ea-8064-e6c3d555ae97.png)

**After**
![Screen Shot 2020-04-08 at 11 19 08 AM](https://user-images.githubusercontent.com/43073915/78801884-33852400-798b-11ea-8d32-78bd01f2a8f6.png)

**Comment by careeningspace** [comment]
- [ ] **California** Removing cumulative data to match reporting

**Before**
![Screen Shot 2020-04-08 at 11 35 33 AM](https://user-images.githubusercontent.com/43073915/78803719-54e70f80-798d-11ea-8dbc-ee4c2b8a4a98.png)

**After**
![Screen Shot 2020-04-08 at 11 38 01 AM](https://user-images.githubusercontent.com/43073915/78803792-6d572a00-798d-11ea-962f-a1f977a31fac.png)

**Comment by careeningspace** [comment]
- [ ] **Conneticut** Migrating cumulative data to current data to reflect reporting

**Before**
![Screen Shot 2020-04-08 at 11 39 48 AM](https://user-images.githubusercontent.com/43073915/78804124-c45cff00-798d-11ea-85ea-30f828eacbee.png)

**After**
![Screen Shot 2020-04-08 at 11 41 12 AM](https://user-images.githubusercontent.com/43073915/78804218-dfc80a00-798d-11ea-91cf-99389ceb5f8d.png)

**Comment by careeningspace** [comment]
- [ ] **District of Columbia** Removing errant ventilator data ([capacity data](https://coronavirus.dc.gov/page/hospital-status-data) that is not directly attributed to COVID-19 cases)

**Before**
![Screen Shot 2020-04-08 at 12 10 24 PM](https://user-images.githubusercontent.com/43073915/78807589-4c450800-7992-11ea-9f9b-ed2bee647378.png)

**After**
![Screen Shot 2020-04-08 at 12 10 35 PM](https://user-images.githubusercontent.com/43073915/78807670-641c8c00-7992-11ea-9ee6-650988ac00da.png)

**Comment by careeningspace** [comment]
- [ ] **Delaware** Migrating cumulative hospitalization data to reflect reporting.

**Before**
![Screen Shot 2020-04-08 at 12 23 44 PM](https://user-images.githubusercontent.com/43073915/78809128-713a7a80-7994-11ea-9a75-a89ce45335dd.png)

**After**
![Screen Shot 2020-04-08 at 12 26 52 PM](https://user-images.githubusercontent.com/43073915/78809161-7a2b4c00-7994-11ea-97f6-267e5d400c53.png)

**Comment by careeningspace** [comment]
**Florida** Errant data entered for current data for hospitalization.

**Before**
![Screen Shot 2020-04-08 at 1 25 08 PM](https://user-images.githubusercontent.com/43073915/78814382-8a472980-799c-11ea-904c-858febf7cb5d.png)

**After**
![Screen Shot 2020-04-08 at 1 26 38 PM](https://user-images.githubusercontent.com/43073915/78814430-9d59f980-799c-11ea-8c70-6d854879ce4e.png)

**Comment by careeningspace** [comment]
- [ ] **Hawaii** Removing the death that was falsely attributed to COVID-19 from 3/24

**Before**
![Screen Shot 2020-04-08 at 1 32 21 PM](https://user-images.githubusercontent.com/43073915/78815038-a4cdd280-799d-11ea-8f9c-24492b946df2.png)

**After**
![Screen Shot 2020-04-08 at 1 34 04 PM](https://user-images.githubusercontent.com/43073915/78815063-adbea400-799d-11ea-91e2-ca64b6c0aed8.png)

**Comment by careeningspace** [comment]
- [ ] **Guam** Migrating cumulative data to current data per reporting.

**Before**
![Screen Shot 2020-04-08 at 1 37 30 PM](https://user-images.githubusercontent.com/43073915/78815415-3f2e1600-799e-11ea-8cda-ecb65a3716e5.png)

**After**
![Screen Shot 2020-04-09 at 12 28 58 AM](https://user-images.githubusercontent.com/43073915/78858021-299a0a00-79f9-11ea-94ec-c56f505cf222.png)

**Comment by careeningspace** [comment]
- [ ] **North Carolina** Eliminating cumulative data to match what the state reports.

**Before**
![Screen Shot 2020-04-09 at 1 10 12 AM](https://user-images.githubusercontent.com/43073915/78860097-4f2a1200-79ff-11ea-8b71-143476c5b8de.png)

**After**
![Screen Shot 2020-04-09 at 1 10 20 AM](https://user-images.githubusercontent.com/43073915/78860112-57824d00-79ff-11ea-88c8-096dcfde9d33.png)

**Comment by careeningspace** [comment]
- [ ] **North Dakota** Began reporting current hospitalized on 4/5

**Before**
![Screen Shot 2020-04-09 at 1 22 09 AM](https://user-images.githubusercontent.com/43073915/78860752-f52a4c00-7a00-11ea-8201-bfcb64f84cb2.png)

**After**
![Screen Shot 2020-04-09 at 1 24 06 AM](https://user-images.githubusercontent.com/43073915/78860768-fd828700-7a00-11ea-93f4-57b7088fa3f4.png)

**Comment by careeningspace** [comment]
- [ ] **New Hampshire** Removing current hospitalization data to match state's reporting

**Before**
![Screen Shot 2020-04-09 at 1 29 13 AM](https://user-images.githubusercontent.com/43073915/78861020-b47f0280-7a01-11ea-82b2-1b21b5c29098.png)

**After**
![Screen Shot 2020-04-09 at 1 29 33 AM](https://user-images.githubusercontent.com/43073915/78861028-bcd73d80-7a01-11ea-9aed-3b6b21d27e86.png)

**Comment by careeningspace** [comment]
- [ ] **New Mexico** Removing cumulative data to match the state's reporting.

**Before**
![Screen Shot 2020-04-09 at 1 32 50 AM](https://user-images.githubusercontent.com/43073915/78861261-63bbd980-7a02-11ea-8a28-d6c952513517.png)

**After**
![Screen Shot 2020-04-09 at 1 33 01 AM](https://user-images.githubusercontent.com/43073915/78861272-71715f00-7a02-11ea-9928-35361ad12476.png)

**Comment by careeningspace** [comment]
- [ ] **New York** removing cumulative ICU data to match the State's reporting

**Before**
![Screen Shot 2020-04-09 at 1 38 57 AM](https://user-images.githubusercontent.com/43073915/78861593-24da5380-7a03-11ea-930e-98a0b4dec1dd.png)

**After**
![Screen Shot 2020-04-09 at 1 39 06 AM](https://user-images.githubusercontent.com/43073915/78861613-315eac00-7a03-11ea-92c4-51f99d83c1f8.png)

**Comment by careeningspace** [comment]
- [ ] **Ohio** removing current hospitalization data to match the state's reporting

**Before**
![Screen Shot 2020-04-09 at 7 57 02 AM](https://user-images.githubusercontent.com/43073915/78892930-41dd4980-7a38-11ea-96aa-5200f09ab76c.png)

**After**
![Screen Shot 2020-04-09 at 7 57 10 AM](https://user-images.githubusercontent.com/43073915/78892938-486bc100-7a38-11ea-89a2-e28cc16be8c4.png)

**Comment by careeningspace** [comment]
- [ ] **Oklahoma** cleaned up and added current hospitalization data from the reports provided by the [Executive Order reporting](https://coronavirus.health.ok.gov/executive-order-reports)

**Before**
![Screen Shot 2020-04-09 at 8 18 01 AM](https://user-images.githubusercontent.com/43073915/78900652-29276080-7a45-11ea-8637-256d9b495b6f.png)

**After**
![Screen Shot 2020-04-09 at 9 30 43 AM](https://user-images.githubusercontent.com/43073915/78900680-30e70500-7a45-11ea-86e1-421e2098155d.png)

**Comment by careeningspace** [comment]
-[ ] **Oregon** Updated data for current and cumulative using the [Daily Updates](https://www.oregon.gov/oha/erd/pages/covid-19-news.aspx)

**Before**
![Screen Shot 2020-04-09 at 10 18 59 AM](https://user-images.githubusercontent.com/43073915/78909908-28e19200-7a52-11ea-9f42-743a32ecbf7b.png)

**After**
![Screen Shot 2020-04-09 at 11 05 38 AM](https://user-images.githubusercontent.com/43073915/78909933-339c2700-7a52-11ea-8343-3465a22b6a29.png)

**Comment by careeningspace** [comment]
- [ ] **Rhode Island** Updating data to match the State's reporting and incorporate historical data provided in [State's Data Set](https://docs.google.com/spreadsheets/d/1n-zMS9Al94CPj_Tc3K7Adin-tN9x1RSjjx2UzJ4SV7Q/edit#gid=1290804212)

**Before**
![Screen Shot 2020-04-09 at 11 35 12 AM](https://user-images.githubusercontent.com/43073915/78914655-b88a3f00-7a58-11ea-9377-d9327ee229fc.png)

**After**
![Screen Shot 2020-04-09 at 11 51 57 AM](https://user-images.githubusercontent.com/43073915/78914678-c049e380-7a58-11ea-8250-99ef5fc3fec5.png)

**Comment by careeningspace** [comment]
- [ ] **Texas** migrating cumulative hospitalization data to current to match the State's reporting.

**Before**
![Screen Shot 2020-04-09 at 12 20 21 PM](https://user-images.githubusercontent.com/43073915/78917683-3d775780-7a5d-11ea-85fc-cc3147408124.png)

**After**
![Screen Shot 2020-04-09 at 12 20 59 PM](https://user-images.githubusercontent.com/43073915/78917717-4536fc00-7a5d-11ea-9643-973adfb4a7ba.png)

**Comment by careeningspace** [comment]
- [ ] WA and WV have some cumulative hospitalization data in the middle of the data set that will need investigation. Bookmarking it as the rest of the states are up-to-date
