### ISSUE TITLE
Texas Hospitalization Data Source?

### ISSUE THREAD

**Issue by scdavis50** [COVID19Tracking/issues#136]
What is the source on your Texas hospital data?   I don't see it at the Texas DSHS link, and it hasn't been updated for a few days.

This an amazing and super helpful resource.  Thanks!

**Comment by aquineas** [comment]
The "states" tab in the google sheet tracker lists the data sources. 

https://docs.google.com/spreadsheets/d/18oVRrHj3c183mHmq3m89_163yuYltLNlOmPerQ18E8w/htmlview#

For TX it appears to be https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83

The data between the spreadsheet and that site match (as of today, 4/3).
