### ISSUE TITLE
NY daily number timestamp discrepencies

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/issues#137]
> I wanted to let you know that the NY State data on COVID Tracking Project is shown for the wrong day.
>  
> For example, the data that is listed as “April 2” is actually March 31 data. The governor disclosed the data on April 2, but throughout his slides he makes it clear that the data is from the end of the day April 1.
>  
> The source is the NY Governor’s webcast press conferences each day at around noon. They put some of it on their own YouTube page.
> 
> Unfortunately their website that posts the numbers is showing them from the previous day without saying so.
> 
> All the numbers you have are correct I think, they are just listed for one day off. So the numbers you have for 4/3 are actually for 4/2.
> 
> Here is the NY Governor’s YouTube page: https://m.youtube.com/user/nygovcuomo
> Thanks, Kevin

**Comment by careeningspace** [comment]
You are correct - all pf NY data is for the end of the day prior to our report. We are considering adding a timestamp to our data to help clarify this issue.  

Another way to look at this is: we cannot report on all of data from 4/2 until 4/3
