### ISSUE TITLE
Inconsistencies in "States daily 4 pm ET"

### ISSUE THREAD

**Issue by klumbard** [COVID19Tracking/issues#14]
These are instances in which the cumulative count of pos/neg on a given day are less than the previous day:

Negative:
NM on 03-08
CO on 03-10
MS on 03-13
UT on 03-13
CO on 03-15
ID on 03-15
NJ on 03-16
NY on 03-16
AZ on 03-17

Positive:
NV on 03-10
DC on 03-11

**Comment by hammer** [comment]
The NY error is likely because someone tried to keep the "total tests" number constant while using the positives number from the website. They should have carried forward the negative count from the previous day.

> 20200316	NY	950	4,322		7	5,272
> 20200315	NY	729	4,543		3	5,272

**Comment by hammer** [comment]
The CO error is likely because they switched from reporting samples to people.

> 20200309	CO	9	266			275
> 20200310	CO	12	142	1		155

**Comment by hammer** [comment]
The NJ error is an odd one. Did we try to carry forward the 120 from the previous day and just miss the leading 1?

20200317 | NJ | 267 | 163 | 55 | 3 | 485
20200316 | NJ | 178 | 20 | 20 | 2 | 218
20200315 | NJ | 98 | 120 | 34 | 2 | 252

**Comment by hammer** [comment]
I can't explain the CO 3/15 error...

> 20200315 | CO | 131 | 627 |   | 1 | 758
> 20200314 | CO | 101 | 712 |   | 1 | 814

**Comment by careeningspace** [comment]
NJ Is now cleaned up. I assumed that the negatives hold steady on the 14th as the data seems to be following a similar pattern before and after.
![image](https://user-images.githubusercontent.com/43073915/77167976-6d01f800-6a8d-11ea-8ffa-080d979fb9c4.png)

NJ Updated:
![image](https://user-images.githubusercontent.com/43073915/77168342-0c26ef80-6a8e-11ea-8ef1-65c62ab3ab4e.png)

NY Checks:
![image](https://user-images.githubusercontent.com/43073915/77168672-940cf980-6a8e-11ea-9966-56a3894f14d5.png)

NY Updated:
![image](https://user-images.githubusercontent.com/43073915/77168719-af780480-6a8e-11ea-8357-631d3a62c916.png)

CO error on 2/14 appears to be the total being entered into the negative column and it adds the deaths (maybe a formula?):
![image](https://user-images.githubusercontent.com/43073915/77168910-01208f00-6a8f-11ea-82bd-8cf6345a5232.png)

CO incorrect total and migrated 3/5 through 3/9 negatives from "tests" to cases by dividing by 2 and rounding up:
![image](https://user-images.githubusercontent.com/43073915/77170101-f0711880-6a90-11ea-877c-dd3e40ece33a.png)

AZ looks like a data entry error on negatives:
![image](https://user-images.githubusercontent.com/43073915/77170421-670e1600-6a91-11ea-9288-4e5d557ab6da.png)
AZ corrected:
![image](https://user-images.githubusercontent.com/43073915/77170647-b81e0a00-6a91-11ea-9362-75eaf5986b8b.png)

MS is not clear what happened - maybe someone tried to keep the total fixed, and adjusted the negatives on accident:
![image](https://user-images.githubusercontent.com/43073915/77171060-47c3b880-6a92-11ea-9ba1-493816130cf5.png)

MS Fixed, carrying negatives forward:
![image](https://user-images.githubusercontent.com/43073915/77170915-1e0a9180-6a92-11ea-8ac5-5f65f688a268.png)

NM Does not have any checks data until after the publish time. Reverting the negatives to match day prior:
![image](https://user-images.githubusercontent.com/43073915/77172136-e0a70380-6a93-11ea-99bd-e12b586784c5.png)

UT looks like either something changed on the website, or it was just a bad entry as the negatives stay fixed for quite a while:
![image](https://user-images.githubusercontent.com/43073915/77172447-54491080-6a94-11ea-93ab-69e9972736ed.png)

Reverting UT negatives on to 131 to smooth it out:
![image](https://user-images.githubusercontent.com/43073915/77172510-76db2980-6a94-11ea-8f27-6df8097b8640.png)

ID is a little strange, note quite sure what to do here:
![image](https://user-images.githubusercontent.com/43073915/77171763-4f379180-6a93-11ea-8010-c8b6b0230688.png)

**Comment by realfuture** [comment]
> The NJ error is an odd one. It looks like we tried to carry forward the 120 from the previous day and just missed the leading 1.
> 
> Here are the checkers/double checkers: PR, AM (3/17); SD, AM (3/16); PR, SJ (3/15).
> 
> > 20200317 | NJ | 267 | 163 | 55 | 3 | 485
> > 20200316 | NJ | 178 | 20 | 20 | 2 | 218
> > 20200315 | NJ | 98 | 120 | 34 | 2 | 252

What actually happened here is that New Jersey changed the way they were reporting negatives. And so their negative total dropped. It sucked. That's also when they said they were only reporting negatives from the state lab!

**Comment by realfuture** [comment]
The only one that flummoxes me is ID. I think we'd almost certainly have to go back to the AWS logs. Their data looked clean coming in, but maybe they were fiddling with the margins.

**Comment by careeningspace** [comment]
Based on our [screenshot](https://covid-data-archive.s3.us-east-2.amazonaws.com/state_screenshots/ID/ID-20200315-021631.png) and anecdotal evidence, I am going to make a judgment call that ID reported some numbers out of sync and our math caused the fluctuation. *Once a negative, always a negative.

Before:
![Screen Shot 2020-03-27 at 1 10 46 PM](https://user-images.githubusercontent.com/43073915/77781788-8f1aed80-702c-11ea-8179-05618fd68001.png)

After:
![Screen Shot 2020-03-27 at 1 11 08 PM](https://user-images.githubusercontent.com/43073915/77781820-993cec00-702c-11ea-8ea6-eaaece6c57cc.png)
