### ISSUE TITLE
CA recent numbers are strange

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#141]
Something seems odd with the recent CA numbers:

1. They got 47,000 pending tests back today and they were effectively all negative. In fact their positive increase was lower than yesterday.
1. Even ignoring the returned pending cases, they added 30k new test results when the most they've been able to do before is 7k (once, over a month ago).
2. For the third straight day, their totalTestResults were an even multiple of 100.
3. For the past two days, their totalTestResultsIncrease was likewise a multiple of 100.
4. Their pending cases have also been -00, but I had figured that was just routine rounding.

I feel a little conspiracy-addled even writing this, but #1 seems so incredible to me that the others seem worth mentioning as well. This isn't a direct issue for the project, but perhaps someone has a way to ask them about this.

**Comment by careeningspace** [comment]
Hello,

We too have struggled with the numbers coming out of California.  Check out this [great article by ALEXIS C. MADRIGALROBINSON MEYER](https://www.theatlantic.com/health/archive/2020/03/next-covid-19-testing-crisis/609193/)that digs into some of the issues.

**Comment by Jmuccigr** [comment]
Thanks, but how does CA rate a grade of B? They clearly have not been reporting negatives with any reliability. Is it clear where the other 30k test results came from?

**Comment by realfuture** [comment]
In retrospect, California probably should not have had as high a grade as it did. 

We’re working on a system to attach grades to data on a daily basis, so you could go back and see that sort of thing. 

As it stands, we do not have that system in place. And for right now, I think California is now a B.

**Comment by Jmuccigr** [comment]
Thanks for the reply. My jury is still out. :-)

If you will be adding grades like that, I'd suggest practical categories, like "reliable for positive rate" and so on.
