### ISSUE TITLE
Michigan now have a new system which report much more information

### ISSUE THREAD

**Issue by atzhh** [COVID19Tracking/issues#144]
https://www.michigan.gov/coronavirus/ and then click see cumulative data. 

Also, for Arizona, you should use the negative number reported in test section lower right corner instead of just put the total. Not a significant difference though.

**Comment by catawbasam** [comment]
Michigan negative counts are now almost 3X what is being reported on https://covidtracking.com/data#state-MI

https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html

Cumulative Number of Specimens Tested for COVID-19 - Last Updated 4/4/2020 15:00
Lab Type | Negative Tests | Positive Tests | Total Specimens Tested
-- | -- | -- | --
Commercial | 3392 | 1202 | 4601
Hospital | 22140 | 7589 | 29830
Public Health | 4498 | 1644 | 6150
Grand Total | 30030 | 10435 | 40581

**Comment by careeningspace** [comment]
Yes - The difference is that Michigan is reporting specimens, not people tested. We have been reaching out to the state in hopes of more accurate people data.

From the state website:
![Screen Shot 2020-04-05 at 9 33 26 AM](https://user-images.githubusercontent.com/43073915/78499761-86a76e80-7720-11ea-8834-6717c3277fbb.png)

**Comment by careeningspace** [comment]
@atzhh Regarding AZ - we calculate the total negatives because the chart you are referring to appears to be slightly out of sync with the totals and positives being reported at the top of the dashboard.
