### ISSUE TITLE
NY April 3 total tested and negatives look wrong 

### ISSUE THREAD

**Issue by jonmoore** [COVID19Tracking/issues#145]
The April 3 total tested in NY is currently listed as 271,002

The total from Cuomo’s April 3 press conference was 260,520. See  2:08 at https://youtu.be/sdSyYm77XWo

Negative tests are also off because of this. 

The other figures (positive cases, hospitalized and deaths) match Cuomo’s.

**Comment by careeningspace** [comment]
Good catch! negatives should be `=260520-102863=157657`

Data before:
![Screen Shot 2020-04-05 at 9 10 23 AM](https://user-images.githubusercontent.com/43073915/78499218-5b6f5000-771d-11ea-9545-9c8ee3e0f118.png)

Data after:
![Screen Shot 2020-04-05 at 9 11 36 AM](https://user-images.githubusercontent.com/43073915/78499251-8ce81b80-771d-11ea-8095-49ec6df225cd.png)
