### ISSUE TITLE
Michigan is reporting 30,030 Negative Tests as of 10 am on 4/4

### ISSUE THREAD

**Issue by MichiganObserver** [COVID19Tracking/issues#147]
Why have you not updated your data?  Still reflecting only 11,829 Negative Tests for Michigan?

**Comment by paolinic03** [comment]
For my own sanity, why do we care about the number negative tests? I mean I get it that it is to show how many total tests we have done, but this number isn’t actionable unless we were able to show number of negative tests AFTER a positive diagnosis, hence recovery. Just failing to see the importance.

**Comment by Jmuccigr** [comment]
> For my own sanity, why do we care about the number negative tests? 

1. The positive rate (positives/total tests) is important in understanding and modeling the impact of the disease.
2. Having an idea of the total number of tests can show us where testing is lagging, and therefore where more resources might be directed.

PS This issue should be closed as MI's numbers were updated 4/5.
