### ISSUE TITLE
Data inconsistency [Jurisdiction reporting quality checks]

### ISSUE THREAD

**Issue by Nosferican** [COVID19Tracking/issues#149]
I found issues such as the following,
Examine these two comments
(1) https://github.com/COVID19Tracking/covid-tracking-data/commit/abef18fdd94afaeaabe40c988a04a75c3ee8a59e#r38300508
and
(2) https://github.com/COVID19Tracking/covid-tracking-data/commit/333993065f7f9391f36ce05bd4f728ce496d9dcc#r38300525.

Which one is correct? Should I assume the latter one is the correct one?
There are two versions for `IA` that were checked at the same time `3/31 14:42` but have different values
```
| state | positiveScore | negativeScore | negativeRegularScore | commercialScore | dateModified         | dateChecked          | SHA1                                     |
|-------|---------------|---------------|----------------------|-----------------|----------------------|----------------------|------------------------------------------|
| IA    | 1             | 1             | 1                    | 1               | 2020-03-31T04:00:00Z | 2020-03-31T18:42:00Z | abef18fdd94afaeaabe40c988a04a75c3ee8a59e |
| IA    | 1             | 1             | 0                    | 0               | 2020-03-31T04:00:00Z | 2020-03-31T18:42:00Z | 333993065f7f9391f36ce05bd4f728ce496d9dcc |
```
I am asking for being able to resolve those inconsistencies when they show up.
If possible, what was the cause for the incorrect data so I may incorporate or watch out for those issues?

**Comment by Nosferican** [comment]
Bump.

**Comment by Nosferican** [comment]
Bump.

**Comment by Nosferican** [comment]
Might be relevant as the grades are being recovered for the new API schema.

**Comment by muamichali** [comment]
Hi @Nosferican 
The stale bot has closed this issue, but if it something that you still need resolved, please open it and we will look at it.
