### ISSUE TITLE
All cases when states report fewer (cumulative) totals than the day before

### ISSUE THREAD

**Issue by philgoetz** [COVID19Tracking/issues#152]
MI reported fewer negative on 2020-03-20 than on 2020-03-19
MI reported fewer negative on 2020-03-21 than on 2020-03-20
MI reported fewer negative on 2020-03-22 than on 2020-03-21
MI reported fewer negative on 2020-03-23 than on 2020-03-22
MI reported fewer negative on 2020-03-24 than on 2020-03-23
MI reported fewer negative on 2020-03-25 than on 2020-03-24
MT reported fewer negative on 2020-03-30 than on 2020-03-29
MT reported fewer totalTestResults on 2020-03-30 than on 2020-03-29
NV reported fewer positive on 2020-03-10 than on 2020-03-09
NV reported fewer totalTestResults on 2020-03-10 than on 2020-03-09
SC reported fewer positive on 2020-03-24 than on 2020-03-23
UT reported fewer negative on 2020-04-02 than on 2020-04-01
UT reported fewer totalTestResults on 2020-04-02 than on 2020-04-01
WI reported fewer negative on 2020-03-30 than on 2020-03-29
WI reported fewer totalTestResults on 2020-03-30 than on 2020-03-29

These may be cases where rows were swapped.

These are all the cases up through today's report (4/3).

**Comment by julia326** [comment]
@joshuaellinger @Erin-Boehmer I'm guessing you're already including these checks in the QA work but forwarding just in case

**Comment by careeningspace** [comment]
- [ ] **Michigan** Data update was derived from improved data reporting by the state. Please see #173 for additional details

- [ ] **Montana**   Looks like the positives updated while the state did not update the total tested at the same rate. 

- **Before**
![Screen Shot 2020-04-10 at 11 47 32 PM](https://user-images.githubusercontent.com/43073915/79034808-eb325580-7b86-11ea-87d5-da328be757cf.png)

- **After**
![Screen Shot 2020-04-10 at 11 48 00 PM](https://user-images.githubusercontent.com/43073915/79034830-01d8ac80-7b87-11ea-82ff-c63e0a67f3fc.png)

- [ ] **Nevada**  Looks like the positives updated while the state did not update the total tested at the same rate.

- **Before**
![Screen Shot 2020-04-10 at 11 59 49 PM](https://user-images.githubusercontent.com/43073915/79035025-6cd6b300-7b88-11ea-9f35-590073ace52a.png)

- **After**
![Screen Shot 2020-04-11 at 12 06 24 AM](https://user-images.githubusercontent.com/43073915/79035030-7a8c3880-7b88-11ea-8399-cfe8f0c08ded.png)

- [ ] **South Carolina** Erroneous data entry on 3/23

**Before**
![Screen Shot 2020-04-11 at 12 20 35 AM](https://user-images.githubusercontent.com/43073915/79035233-77924780-7b8a-11ea-9b1f-bfd91c2e8e4f.png)

**After**
![Screen Shot 2020-04-11 at 12 20 46 AM](https://user-images.githubusercontent.com/43073915/79035237-7eb95580-7b8a-11ea-927a-825c11e88843.png)

- [ ] **Utah** Lag in reporting on total tests resulted in incorrect math on 4/1

**Before**
![Screen Shot 2020-04-11 at 12 25 18 AM](https://user-images.githubusercontent.com/43073915/79035304-2df62c80-7b8b-11ea-9b16-3f5a76020723.png)

**After**
![Screen Shot 2020-04-11 at 12 25 38 AM](https://user-images.githubusercontent.com/43073915/79035308-38182b00-7b8b-11ea-90fc-2311101d099f.png)

**Comment by careeningspace** [comment]
- [ ] **Wisconsin** Reported the same data you can find on our site. It looks like the numbers are reversed, but it would be difficult to write tomorrow's numbers today. I am going to leave WI for the time being.

**Screen capture from 3/29**
![Screen Shot 2020-04-11 at 12 29 55 AM](https://user-images.githubusercontent.com/43073915/79035400-313de800-7b8c-11ea-9edb-12ae980acc5a.png)

**Screen capture from 3/30**
![Screen Shot 2020-04-11 at 12 29 29 AM](https://user-images.githubusercontent.com/43073915/79035405-40bd3100-7b8c-11ea-89a3-e5613f708ef3.png)

@realfuture any ideas?
