### ISSUE TITLE
US is less than NY hospitalizedIncrease on 4/02

### ISSUE THREAD

**Issue by diranl** [COVID19Tracking/issues#153]
Cross referencing the data between the US daily and States daily endpoints:

- https://covidtracking.com/api/us/daily
- https://covidtracking.com/api/v1/states/daily.json

Repro:
- Retrieve 4/02 data on https://covidtracking.com/api/us/daily
- Retrieve 4/02 data for NY on https://covidtracking.com/api/v1/states/daily.json
- US data: `"hospitalizedIncrease": 1507,`
- NY data: `"hospitalizedIncrease": 2449,`

Expected: US to be greater than NY in hospitalizedIncrease as US encompasses NY
Actual: US < NY in hospitalizedIncrease

**Comment by careeningspace** [comment]
Hello,
We did go back and clean up some of our historical hospitalization data due to a modification of our process. Check out #132 for reference.

Here is what I see now:
- 4/2 US Daily: "hospitalizedIncrease":4141
-4/2 NY Dail: "hospitalizedIncrease":2449
