### ISSUE TITLE
CA, NY & RI inicuCumulative missing

### ISSUE THREAD

**Issue by xaminmo** [COVID19Tracking/issues#154]
On 04-02, the inicuCumulative value is missing for CA, NY and RI.  These should be the greater of the last value, or the currently in ICU, but it is probably a data import error.

This error affects the state and US, both for 04-02 and for "current".

**Comment by xaminmo** [comment]
Also, Indiana just showed up missing cumulative ICU.

**Comment by careeningspace** [comment]
Duplicate of #132 and you can find the resolution process on that issue
