### ISSUE TITLE
Separate issue repo is...odd?

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#156]
I just note that many issues here have been moved from the main project repo, which requires someone's time and also for those reporting the issue to learn about this repo (which clearly many do not before posting). It strikes me as a bit odd to have a separate repo just for issues. That's not the model. The point of having an issues section of a repo is so that issues with that repo can be reported there. This repo has no content; it's just an issue collector for another repo.

**Comment by joshuaellinger** [comment]
There are a whole class of issues that it is not clear which repo should own them.

I agree that it might make sense to move it up a level but doesn't seem worth the change.  If we get about 100 open issues, we should probably move out of issues into a different system.

**Comment by Jmuccigr** [comment]
> There are a whole class of issues that it is not clear which repo should own them.

Yes, well, that raises the larger question of why there are so many repos in the first place. :-) 

I think it's fairly common for a project to have one repo where multiple directories contain various aspects of the project. Splitting a single project up into multiple repos creates these kinds of problems.

**Comment by careeningspace** [comment]
Possibly the consequence of a number of separately maintained repos merging into one mega repo? We (volunteers) kind of fell into this project and it has kept growing.

**Comment by Jmuccigr** [comment]
> Possibly the consequence of a number of separately maintained repos merging into one mega repo? We (volunteers) kind of fell into this project and it has kept growing.

Yes, I get that and I am very glad this project is happening, so a big thank you to everyone!

However, creating a repo just for issues still seems weird to me and confusing.
