### ISSUE TITLE
Data request: Testing requirements

### ISSUE THREAD

**Issue by nnpok** [COVID19Tracking/issues#158]
It'd be super helpful to inform epidemiology analyses if the different testing protocol data were made available for each state, ie. if they're only testing symptomatic individual, if they're testing anyone, etc.

If states start releasing this info, it'd be great to get that tracked, thanks!

**Comment by muamichali** [comment]
That would be great, @nnpok!

**Comment by muamichali** [comment]
Thank you for the suggestion @nnpok 
We agree that it would be a great feature. Our editorial will consider and prioritize this request.
