### ISSUE TITLE
Cumulative hospital figures are lower than current.

### ISSUE THREAD

**Issue by DavidAWest** [COVID19Tracking/issues#159]
In the US_current.csv file, the inIcuCurrently, inIcuCumulative and  onVentilatorCurrently  onVentilatorCumulative appear to be reversed.  Currently (14:04 EDST 6 Apr 2020), the values are:

5497, 922 and  1812, 193

It seems to me that the cumulative figures should always be at least as large as the current figures.

**Comment by julia326** [comment]
@DavidAWest these numbers are indeed confusing, but actually correct to what we mean by them - please take a look at https://twitter.com/COVID19Tracking/status/1246917450924351489 for how they're different.

**Comment by careeningspace** [comment]
Duplicate of #132 and you can find the resolution process on that issue
