### ISSUE TITLE
Puerto Rico Data Error 

### ISSUE THREAD

**Issue by sanchobarriga** [COVID19Tracking/issues#161]
There seems to have been a mistake in data collection for Puerto Rico on April 4th. The Negative test count should be 2605, not 2065.

**Comment by muamichali** [comment]
@sanchobarriga You are correct. Sorry about that. We will update the historical data. 
https://covidtracking.com/screenshots/PR/PR-20200404-181302.png

**Comment by muamichali** [comment]
Updated. 
<img width="237" alt="PR Negatives Before" src="https://user-images.githubusercontent.com/1749380/78733627-f3368f00-7913-11ea-8ed8-34ddb9098f08.png">
<img width="243" alt="PR Negatives After" src="https://user-images.githubusercontent.com/1749380/78733631-fa5d9d00-7913-11ea-9f90-8abd5ac07e73.png">

**Comment by muamichali** [comment]
https://covidtracking.com/data/state/puerto-rico#historical updated

**Comment by sanchobarriga** [comment]
Thank you very much. Fantadtic work!
