### ISSUE TITLE
GA negative test results decreased

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/issues#164]
There seems to be an error in the Georgia history data between 6 Apr 2020 and the current (7 Apr) data.  The negative test results decreased by about 9,000.

**Comment by muamichali** [comment]
@webmasterkai It looks like the higher 4/6 number was a [data entry error.](https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1586225805363600) I am going to update the historical data.

**Comment by muamichali** [comment]
<img width="245" alt="GA Negatives Before" src="https://user-images.githubusercontent.com/1749380/78732335-68a06080-7910-11ea-883d-f8266d3c19be.png">

<img width="249" alt="GA Negatives After" src="https://user-images.githubusercontent.com/1749380/78732347-6dfdab00-7910-11ea-9691-fd4cb24d52bd.png">
