### ISSUE TITLE
California testing data error

### ISSUE THREAD

**Issue by rashecl** [COVID19Tracking/issues#166]
On April 4th, there were 78400 new test results in CA, and that number seems very high since other days there were <3000. 
Also, I created a GUI here: http://predict.rocks/state_of_the_union
Using this, I've found potential issues Montana and Wisconsin as well.

**Comment by una-smith** [comment]
CA simply reported its backlog of pending tests.  As discussed in other issues here, positives and negatives are reported in separate data streams and in some states the negatives are reported in batches weekly.  Backlogs affect negatives more than positives.

**Comment by careeningspace** [comment]
@una-smith is correct - California finally pushed a bunch of backlogged data on the 4th.
![Screen Shot 2020-04-09 at 12 51 35 PM](https://user-images.githubusercontent.com/43073915/78920100-e1aecd80-7a60-11ea-8bb4-50c1cc2af55c.png)
