### ISSUE TITLE
Need to resolve what to do about Guam Negatives, maybe fix historicals

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#167]
Guam typically includes in their overall Total, their Positives, and their Negatives some people (presumably Guam residents? sailors? not sure) who have been tested at the Naval base in San Diego. It's unclear to me whether we are supposed to include these people in the Guam counts or if we are assuming that they are included in the CA counts. I thought it was the latter, but if so, we haven't been subtracting those people from the Guam numbers.  

If we are not going to count the cases tested in San Diego for Guam, then the positive number for Guam should be a calculation -- their reported Total minus the number of cases tested in San Diego. On 4/7, that would be ```121-9``` (see https://www.facebook.com/GHSOCD/photos/a.494946803880729/3822682364440473/?type=3&theater for the "121" number -- see also press release no. 60 at https://ghs.guam.gov/jic-release-no-60-eight-test-positive-covid-19-breaking-news-found-governor-leon-guerrero%E2%80%99s-facebook), which would be 112, which would be one less than was reported on 4/6. We need to figure out whether to calculate Positives for Guam or to record their total, which includes the cases in San Diego.

**Comment by careeningspace** [comment]
Because Guam has been reporting the tests from San Diego in their total, I have been advising that we do so as well. Depending on where you look, the language can imply that these tests are Guam residents but tested in San Diego (is this because the people are in San Diego, or were the tests sent to San Diego?)

**Comment by amandafrench** [comment]
I think we have decided that we should include the San Diego numbers, correct? I am quite sure that *most* of the historicals do include it -- should someone (preferably not me) check *all* the historicals? I think we can close the issue unless someone is going to change the historicals.
