### ISSUE TITLE
PUBLISH TIME

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/issues#169]
## History

Alexis  Madrigal brought two pain points to my attention:
    1. He gets a lot of questions about why our data is out-of-sync with the state's dashboards.
    2. He feels publishing to history at 5PM (in retrospect) feels like a mistake.
    3. He likes the idea of a midnight update but worries that it would be too hard on data entry.

A group of us (Elliot/Zach/Julia/me) looked at how we could fix this.

Elliot is close to the data entry process.  He said that 5PM ET is a problem because the west coast often does not report on/at the deadline.  He thinks 8PM ET (5PM PT) is sufficient to insure that we get an update for each state every day in the history table (assuming they make one) . 

The next step in fixing this is for Alexis to find the right people to hash out the best publish date.  

## RECOMMENDATION

Our current recommendation is that we move the publish step to 8PM ET but do not change the process otherwise (keep it in the 2nd push) in the near future.  This would reduce operational pressure and make the numbers a lot more consistent.  There are other variations that I will add as comments for separate consideration.

We also recommend adding a field, called Source Date perhaps, to the published data that tells the consumers the 'as-of' date.  It would be on a per-state per-day basis.  It would clear up both the questions Alexis is getting and the questions about inconsistencies between Current and History.

My only concern about this change is if we have consumers who are news organizations with evening edition cutoffs.  I will list some alternatives in the comments.

## IMPLEMENTATION

1. [Now] Add a column called "Source Date (ET)" to the worksheet that tracks the timestamp of the data from the state and display that in the history table.  This is very close to the "Last Updated (ET)" conceptually but we may want the flexibility to put a different date into the history from the actual date that we last looked at it.

That would enable us to be clear on the website about when each record was from.  It would also enable us to leave the old date if the state fails to make an update in the day.

2. [Now] Back fill all the history records so that "Source Date (ET)" is the time of the 5PM push.  Initially, we should make it be the same time (5PM) but eventually we may update it based on the data in the CHECKS tab that records the actual time of update.

3. [Now] Tell everyone that consumes is a high profile consumer of our data to that we are planning to switch to an 8 PM ET publish time in the near future and listen for objections.

4. [Next Week] Move the history out of the spreadsheet into a relational database.  This is discussed as a separate issue but mentioned here because it is what will enable us to take the next steps without breaking the current process.  

5. [Following week]  Rebuild the history using an 8PM ET publish time using  the Checks tab, the screen shots, and backups of the worksheet.  Apply the other data fixes in the same process.   Publish it on a 'version 2' of the API.

6. [Go Live] Data Entry switches to an 8PM ET publish time.  The web site changes to use the new version of the API.  If you use the old version, the only change is that from this date forward you have data from 8PM.  If you use the new version, you get all the changes and fixes.

**Comment by joshuaellinger** [comment]
## VARIATION 1 - Publish by Time Zone

We divide the states into groups by time zones and update each at 5PM local.  This would be easy for our consumers to understand and not much different from the 'polls closed' behavior we are used to in politics.

It aligns with the data update schedule of the states.  It supports consumer that really just want a single state better than a later date.  It turns the one big publish into 4 smaller publishes and opens the door to enabling people to be double checkers without having to understand the idiosyncrasies of every state.  

This is the best approach if we're can't wait until 8PM ET.   We have not investigated if this would really work for data entry

## VARIATION #2: Continuous deployment

We change our model so that the current data in history is always 'mutable'.  Current never gets out of sync with history.  For humans consuming our data, this would feel natural.  We make the first row in the history table in a different color to make it feel different.

For our algorithmic consumers, we implement a web-hook that tells then when we change data.  This has the valuable side-effect that we can publish changes to history without having to reach out of each person using our data to drive other analysis.  This would make us a much more useful source of information for those systems.

**Comment by Jmuccigr** [comment]
FYI WY is now moving to a 3 pm (MDT, I assume) data release, so 5 pm EDT.

https://twitter.com/SethKlamann/status/1247915490170863617

**Comment by joshuaellinger** [comment]
Related to [issue 163](https://github.com/COVID19Tracking/issues/issues/163)

## VARIATION 3 - Move the Publish step out of the Google Spreadsheet.

We didn't talk about this option in detail but natural time for the consumers of the data is "as-of" midnight.  The problem with this is that we are organized around having the 2nd shift be the critical shift that gets the most vetting and the other two shift have newer staff.  

To scope this, we would need to move to a system where we do most of the work on the history during the 4PM shift and then 'pre-publish' it to a staging location.  Then we vet every change from 4PM to midnight to decide if it should roll into the history.

## POSSIBLE IMPLEMENTATION 

1. Separate the 'Publish' process from the 'push' step.  'Push' happens inside of the google spreadsheet and it updates both the current and history numbers in a database table that is only visible internally.  The data entry team no longer worries about publish.

2. The 4PM ET data is assumed to be well vetted.  After this push, the pre-publish table is populated with those numbers and locked.  Any changes between that will go into the public history have to be approved in a separate work.  We could also have a threshold so that small changes are allowed through automatically but big changes aren't.

3. When the 3rd shift signs off, the 'publish manager' (a new role) looks at a (new) web page that shows only shows everything changed between 5PM and 12PM and decides what to include on a per state basis.  It would be easy enough to use Twilio to send SMS messages so that the publish manager is an on-call type position rather than an active participant in the 3rd push.

4. The table would auto-publish if there is no issues at Midnight.  Depending on editorial policy, we could have code the notifies people if there are unresolved issues or we could flag a few states as preliminary and update them in the morning.
