### ISSUE TITLE
Clarification on /states/daily counts

### ISSUE THREAD

**Issue by plmrry** [COVID19Tracking/issues#17]
Are the values in `/api/states/daily` _cumulative_ or _new tests per day_?

I assumed they were cumulative, but noticed that the total value decreases over time for certain states (e.g. New York).

**Comment by careeningspace** [comment]
LA has been rectified:![Screen Shot 2020-04-01 at 11 33 14 AM](https://user-images.githubusercontent.com/43073915/78156300-9b2bf400-740c-11ea-9ea5-0ad83fd6e5a9.png)

**Comment by careeningspace** [comment]
NY is rectified:
![Screen Shot 2020-04-01 at 11 35 48 AM](https://user-images.githubusercontent.com/43073915/78156569-f827aa00-740c-11ea-8e43-6bafd0369665.png)
