### ISSUE TITLE
Move 'History' management into a Database

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/issues#170]
# MOTIVATION

There is nothing in this problem that requires using a relational database.  The problem is just a little to simple to make it necessary.  

If we had county data, we would need it.  If we wanted to publish variants, we would need it.  But we are just managing 10 data points across 56 states and over time so it isn't really required.

However, it would be worthwhile to move the primary historical record into a DB.  It would be easier to query, be less error prone, and offer us more flexibility in the future. 

The primary advantages today are that:
  1. we could simplify the spreadsheet by eliminating its need to manage history.
  2. we could simplify the API by eliminating its need to perform derived calculation.
  3. it would make a set of ad-hoc analysis easier. 

The cost of moving to a database seem minimal and something we can do incrementally.  The only downside is another component  in the stack.

# IMPLEMENTATION

Basically, we put the DB between the spreadsheet and the API endpoints.

>    Google Spreadsheet -> Database -> API -> Web Site

When the shift leader pushes data, it would run quality checks then insert the records into a database table.  The table would replace the CHECKS tab.  The google sheet would then query the database to populate a shortened version of the CHECKS tab.  There also several other tabs that would be populated from the DB.  This process would be run through a REST API.

# REST API

The working API spec is:

     POST /publish
           Copy from the spreadsheet into the DB.
     DELETE /publish
           Rollback the published result
     GET /publish
           Get meta-data of the last publish operation

      GET /tabs/checks
            Get data to populate the CHECKS tab
      GET /tabs/checks
            Get data to populate the CHECKS tab
      GET /tabs/states
            Get data to populate the States tab
      GET /tabs/states-current
            Get data to populate the States Current tab
      GET /tabs/states-daily
            Get data to populate the States Daily tab

**Comment by joshuaellinger** [comment]
Hey,  I don't have enough review around the implementation but this is in direction of what we discussed.

@careeningspace can you tell me if this could actually work and where you think it is a hard/dangerous change?

**Comment by careeningspace** [comment]
My sense is that our biggest risk is maintaining the data in the DB. We potentially create a bottleneck for this process. Currently, the number of people we allow to edit historical data is limited, so it may not really change anything.

**Comment by joshuaellinger** [comment]
Who can edit the history now?  I think getting the history out of the spreadsheet will feel like a bigger improvement than you realize.  Especially 3 months from now.

Let's add some requirements to minimize risk:

1. Those people can edit the values today and continue to do so both directly using SQL and from a Web UI.
2. Nobody touches those tables without those people approving.
3. The DB is setup to have automatic internal change tracking and we can roll it back.
4. It's hosted on at an endpoint that is agreed on by both data entry and website teams.
5. It's backed up with the google spreadsheet backups.

**Comment by Nosferican** [comment]
You can get the history of the data from the text file backups (see: [example](https://github.com/uva-bi-sdad/COVID_Tracking_Clean)). That code uses the GitHub API to get the backups even if the historical records were modified (those are all version controlled through snapshots). For the actual manipulation I did, I uploaded all the text backups to a Postgres database and wrote them back to text files.

**Comment by muamichali** [comment]
Since this is now in progress on https://github.com/COVID19Tracking/covid-publishing-api I am closing this issue.
