### ISSUE TITLE
Michigan has stopped reporting testing results ... now only reporting number of cases & deaths

### ISSUE THREAD

**Issue by MichiganObserver** [COVID19Tracking/issues#171]
Prior to stopping, the numbers showed Michigan as lagging behind in the quantity of testing being done ... other states with less cases have reported testing thousands more than Michigan.  For example compare Michigan to Illinois or to Florida or to many other states.

**Comment by Jmuccigr** [comment]
Well that's not good. MI already has one of the highest number of deaths per capita in the country. But their reporting of test results has been bad for a while. Lots of days with only positives reported.

**Comment by careeningspace** [comment]
Yes - unfortunately Michigan, along with a couple of other states have had troubles reporting total tested or negatives. Hopefully, they will figure it out and start reporting it again.

**Comment by catawbasam** [comment]
it is up on a new page
