### ISSUE TITLE
Confirmed vs. suspected deaths (Puerto Rico and New York City)

### ISSUE THREAD

**Issue by sacundim** [COVID19Tracking/issues#174]
There are reports that New York City will in the near future start reporting separate numbers for confirmed vs. suspected COVID-19 deaths, and Puerto Rico is already doing something similar as of April 9.

The data set collected in this repo might be well served to make a similar distinction as well, in order to, for example, avoid big jumps in day-to-day values that are really an artifact of that sort of reporting change.  For example, your website today reports that Puerto Rico went from 24 to 33 deaths, but in reality it went from 24 to 26 under the old standard (deaths of patients with positive test results), and a new category of suspected deaths was inaugurated with 7 cases from March (and a second batch of 7 has been added since this morning).

According to this April 8 story in Gothamist, New York city intends to start reporting counts both of confirmed and suspected COVID-19 deaths: 

- https://gothamist.com/news/death-count-expected-soar-nyc-says-it-will-begin-reporting-suspected-covid-deaths-addition-confirmed-ones 

> New York City officials will begin to count suspected COVID-19 deaths of people who die at home following a WNYC/Gothamist report revealing a staggering number of such deaths that were not included in the official tally.
>
> In a statement, Stephanie Buhle, a spokeswoman for New York City’s Health Department, said the city would no longer report only those cases that were confirmed by a laboratory test.
>
> “The Office of the Chief Medical Examiner (OCME) and the NYC Health Department are working together to include into their reports deaths that may be linked to COVID but not lab confirmed that occur at home,” she said. 
>
> She didn’t say when the city would begin reporting suspected deaths along with the overall count. But the new protocol is likely to add thousands to the toll.

The story says NYC officials have given no timeline for this change, but as I mentioned above, Puerto Rico today (April 9) started reporting deaths in two similar categories as well: 

1. Deaths for which there is a positive COVID-19 test result 
2. Deaths for which there isn't such a result but the doctor indicated COVID-19 in the death certificate 

As of right now (April 9, 10pm Puerto Rico time), the project's current best source for Puerto Rico is the Institute of Statistics dashboard:

- https://estadisticas.pr/en/covid-19

...which is breaking down the deaths like this:

- 33 total ("Muertes 33")
- 7 suspected ("Registro Demográfico = 7 (21.2%)")
- 26 confirmed ("Sistema de Vigilancia = 26 (78.8%)")

**Comment by muamichali** [comment]
Thanks for the information @sacundim. I will pass it on to the team.

**Comment by sacundim** [comment]
Update:

> # N.Y.C. Death Toll Soars Past 10,000 in Revised Virus Count
> ## The city has added more than 3,700 additional people who were presumed to have died of the coronavirus but had never tested positive.
> By J. David Goodman and William K. Rashbaum
> April 14, 2020 (Updated 6:40 p.m. ET)
>
> New York City, already a world epicenter of the coronavirus outbreak, sharply increased its death toll by more than 3,700 victims on Tuesday, after officials said they were now including people who had never tested positive for the virus but were presumed to have died of it.
>
> The new figures, released by the city’s Health Department, drove up the number of people killed in New York City to more than 10,000, and appeared to increase the overall United States death count by 17 percent to more than 26,000.

https://www.nytimes.com/2020/04/14/nyregion/new-york-coronavirus-deaths.html

**Comment by muamichali** [comment]
Hi @sacundim 

Thanks again for bringing this issue to our attention when you did. We are working on incorporating these data points from the states that provide them consistently
