### ISSUE TITLE
Fix historicals for American Samoa

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#178]
As reported in #47, we were using the wrong source entirely for American Samoa for about ten days, and the error has persisted in some places ever since. The incorrect URL for Western Samoa was removed on the website from the "Best current source" link ONLY, but the screenshots from that incorrect page remained, and the incorrect URL remained in the spreadsheet as the main AS page in States Matrix. I have fixed it in the States Matrix tab. However, our historicals for American Samoa are all over the place and need to be corrected. The data is very infrequent, and much of it is coming from news sources. I will make the appropriate notes about this in the sheet and add comments here as needed to clarify sources and to correct the historical data.

**Comment by amandafrench** [comment]
https://www.rnz.co.nz/international/pacific-news/412830/american-samoa-covid-19-test-negative

**Comment by amandafrench** [comment]
One newer source: https://www.samoanews.com/local-news/out-5-suspected-coronavirus-samples-3-test-negative-so-far

**Comment by careeningspace** [comment]
Eagle EYES!

**Before**
![Screen Shot 2020-04-12 at 12 15 47 AM](https://user-images.githubusercontent.com/43073915/79060447-079bc400-7c53-11ea-8323-cb62cc89b5c6.png)

**After**
![Screen Shot 2020-04-12 at 12 17 18 AM](https://user-images.githubusercontent.com/43073915/79060451-0ec2d200-7c53-11ea-8199-9e5b96dfd3a9.png)

**Comment by amandafrench** [comment]
Note of course for anyone viewing this and not on our private convos that those numbers come from https://www.samoanews.com/local-news/out-5-suspected-coronavirus-samples-3-test-negative-so-far
