### ISSUE TITLE
Pool resources with NYTimes?

### ISSUE THREAD

**Issue by jqnatividad** [COVID19Tracking/issues#18]
NYTimes seems to have more granular data behind this map
https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html?action=click&pgtype=Article&state=default&module=STYLN_coronahub&variant=show&region=header&context=menu#us

And they have paid staff compiling the data around the clock, starting emails/phone calls with “this is X with The NY Times”...

https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html

Have you tried reaching out to them?

Nowadays, maps are not good enough.

**Comment by hammer** [comment]
NYT using our data: https://www.nytimes.com/interactive/2020/03/17/us/coronavirus-testing-data.html.

Asked about making their map data open, they said no.
