### ISSUE TITLE
AL: ICU=177, ventilator=117, cume hospitalized=407 as of 4/10 4:08est

### ISSUE THREAD

**Issue by catawbasam** [COVID19Tracking/issues#180]
see https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7
'CASE CHARACTERISTICS' tab

**Comment by catawbasam** [comment]
![image](https://user-images.githubusercontent.com/1277811/79055407-c4256380-7c1a-11ea-8400-7cb6f2ec14fe.png)

**Comment by catawbasam** [comment]
accidently closed while commenting

**Comment by muamichali** [comment]
Thank you @catawbasam 

We added this information into the data and you should see it reflected on the
![Screenshot_2020-05-05 Coronavirus numbers by state (CovidTracking, DEV COPY)(6)](https://user-images.githubusercontent.com/1749380/81079107-1c1f5500-8ebd-11ea-9e5a-c84a523cc7b7.png)
![Screenshot_2020-05-05 Coronavirus numbers by state (CovidTracking, DEV COPY)(5)](https://user-images.githubusercontent.com/1749380/81079109-1c1f5500-8ebd-11ea-9199-653a66157ea0.png)

 API this afternoon.
