### ISSUE TITLE
CA confusion

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#181]
Where are the CA numbers coming from?

The last screenshot does not agree with the data in the API, and no place do I find any new numbers for April 11: the last screenshot shows April 9, and the "best current data source" (which the screenshots do **not** show) is April 10.

Meanwhile the database now shows 0 positive cases for CA today.

Can someone clarify for me?

(This perhaps overlaps with the question of when to provide a daily update.)

**Comment by sluggo1133** [comment]
Re: COVID 19 state data.  There is a probable data anomaly in California's "Positive" and "Deaths" numbers for 4/11/20.  These numbers are identical to those for 4/10/20 (19,472 and 541 respectively).  I'm new to this zoo so not sure exactly who, where or how to contact about this presumed error.

**Comment by Jmuccigr** [comment]
Again, the screenshots on April 12 show a date of April 10. And the numbers don't match those in the database. Where are those coming from?

**Comment by Jmuccigr** [comment]
There seems to be a discrepancy between the [text description](https://covidtracking.com/data/state/california) for CA on the state's data page and what's actually happening with the CA data. The former says:

> until 4/1, when we standardized on California's new data dashboards.

But the current best data source and the screen shots (and the data) are still from [the CDPH website](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Immunization/ncov2019.aspx).

The dashboard does seem to have more detailed data.

PS Notice that the dashboard is reporting a whole string of nice even numbers for testing totals, which are therefore obviously not accurate. See #141.

**Comment by sluggo1133** [comment]
I pulled the data from the California Health & Home Service Agency (CHHS) site and compared it to the data for California coming from the Github site and found two discrepancies.  Note CHHS is only reporting data from April 1 2020.  If it is now the current source of record it must have been added on or after April 1.  Also, the two pieces of data coming from CHHS appear to be “Total Count Confirmed” which ends up in the “Positive” column on GitHub and “Total Count Deaths” which is in the “Deaths” column in GitHub.  The data from CHHS and GitHub for Positive and Deaths match perfectly with two exceptions.

 

1.	CHHS dates are not aligned with GitHub:  CHHS data begins on 4/1/20.  Data for 4/1/20 in the CHHS dataset appears in GitHub in 4/2/20 a day later.  Is there a good reason from this?  If not this should be fixed.
2.	Incorrect Data in GitHub for 1/11/20: Data for “Positive” 4/11/20 (current dating scheme) should be 20,615 vice 21,794.  Data for “Deaths” for that day should be 609 vice 651.

 

This assumes, of course, that CHHS data is the preferred source for “Positive” and “Death” data for the GitHub DB.  I’m a newbie on GitHub so this is as much as I can do to rectify the data errors I see.

 

Here is the URL for the CHHS dataset:  <https://data.chhs.ca.gov/dataset/6882c390-b2d7-4b9a-aefa-2068cee63e47/resource/6cd8d424-dfaa-4bdd-9410-a3d656e1176e/download/covid19data.csv> https://data.chhs.ca.gov/dataset/6882c390-b2d7-4b9a-aefa-2068cee63e47/resource/6cd8d424-dfaa-4bdd-9410-a3d656e1176e/download/covid19data.csv

 

I hope this helps make the Github data more representative of the actual situation.

 

Cheers,

 

Stephen L Garry

525 Valle Vista Ave.

Oakland, CA 94610

[M] 510.407.1320

[H] 510.763.1455

**Comment by Jmuccigr** [comment]
The original issue is still occurring: What's the "best data source" for CA? The link and the screen shots on the data page are to the CA health dept page, but you say in the text that

>until 4/1, when we standardized on California's new data dashboards

So which is it?

Also 3 of the last 5 days have total tests as an even multiple of 100. Does anyone believe that? I think you're subtracting reported positives from reported tests to get negatives and the problem is that reported tests are **always** a multiple of 100, that is, they're approximations. That's pretty crappy reporting on the state's part.

**Comment by sluggo1133** [comment]
John,

 

The frequency of results that are multiples of 100 does strain the appearance of credibility.  I’ve be concentrating on the “Positive Infection” and “Death” numbers both of which are cumulative. To me the number that is most suspect is the “Pending” tests.  If the information in the attached article is correct then then testing, particularly in California, is not well organized or managed and therefore the numbers coming out of that process are likely to be suspect.  This would include “positives” and “negatives” but most especially “pending”.

 

If the testing process is opaque so are the criteria for placing a case in one or another of the categories.  For example, do people who died from COVID 19 but were never tested end up in the positive infection cume?  Do these criteria vary by county?  This is clearly our first rodeo but not our last.  I hope that there will be significant pressure to improve the timeliness and accuracy of the data and visibility to them as well.  It’s not just bookkeeping; actual “life and death” management decisions will be made based on these numbers.

 

slg

**Comment by Jmuccigr** [comment]
@sluggo1133 Yes, this great project has made it quite clear that testing and reporting in the US are a mess. CA is just one example. Hopefully one of the outcomes is the establishment of national standards.

WRT CA, pending is clearly heavily rounded. What I don't understand is how "tested" is rounded as well. To my mind, it's clear that CA's negative numbers are fairly unreliable.

**Comment by Jmuccigr** [comment]
Still happening. Screenshots and "best data" point to CDPH, not dashboards.
