### ISSUE TITLE
Illinois Data on 4/11/2020 is incorrect

### ISSUE THREAD

**Issue by oharatso** [COVID19Tracking/issues#182]
There is a typo with the Illinois numbers for 4/11.  You are showing a total of 19810 when the actual per IDPH is 19180.  This is also causing an inaccurate increase in positiveincrease total for 4/11.

**Comment by careeningspace** [comment]
Hello,

Thank you for the catch - I have fixed the data

**Before**
![Screen Shot 2020-04-11 at 10 49 51 PM](https://user-images.githubusercontent.com/43073915/79059350-e59c4480-7c46-11ea-8545-152d4fd4f226.png)

**After**
![Screen Shot 2020-04-11 at 10 51 10 PM](https://user-images.githubusercontent.com/43073915/79059352-f5b42400-7c46-11ea-8308-8a12d46ad853.png)

**Comment by oharatso** [comment]
Thanks!

Tim O’Hara
Chief Information Officer

O 847.544.4206  |  F 847.390.3290  |  wheels.com  | BUSINESS MOVES BETTER WITH WHEELS
