### ISSUE TITLE
CA data for 4/11 appears incorrect

### ISSUE THREAD

**Issue by aztocas** [COVID19Tracking/issues#183]
Same number of positives and deaths as previous day
Hospitalizations up 80% and ICU up 40% in one day

**Comment by Jmuccigr** [comment]
Cf. #181.

**Comment by realfuture** [comment]
Hey, we have an explanation for this for you, which I put together in this thread:
https://twitter.com/COVID19Tracking/status/1249366518950809602?s=20

**Comment by Jmuccigr** [comment]
Please reopen this. My observations have nothing to do with hospitalizations and half of what @aztocas menyions doesn’t wither. Please check #181.  (Personally I ignore hospital data.)
