### ISSUE TITLE
Ohio Cases

### ISSUE THREAD

**Issue by MuletownBrown** [COVID19Tracking/issues#184]
Ohio began reporting probable cases and probable deaths a couple of days ago, but chose to keep them separate from confirmed cases and confirmed deaths. The testing numbers you are reporting as confirmed cases include 63 probable cases which haven't been confirmed by testing. It also appears they are included in the total tests number. Since there were no tests done for those 63 they can't be considered confirmed. I suspect this could be an issue with other states as well if they are including probables based upon CDC guidance.

**Comment by careeningspace** [comment]
Hello,

Thank you for catching this. With the new data reporting that is happening, it is easy for our team to be unsure which number is best reported. You are correct and we are adopting a policy of only counting confirmed cases in our test number.

**Before**
![Screen Shot 2020-04-11 at 10 37 53 PM](https://user-images.githubusercontent.com/43073915/79059224-52164400-7c45-11ea-8ac5-97a9c35fd53c.png)

**After**
![Screen Shot 2020-04-11 at 10 40 40 PM](https://user-images.githubusercontent.com/43073915/79059262-c94bd800-7c45-11ea-8b1a-ac07b4daec10.png)
