### ISSUE TITLE
WA recent days not showing NA

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#189]
Washington hasn't done any reporting in two days, it looks like, but the data are showing zeroes instead of nulls for the relevant fields (e.g., all the -Increase fields).

PS the last screenshot on 4/12 seems to be an empty png.

**Comment by julia326** [comment]
@Jmuccigr thanks for raising the screenshot issue! I'll keep an eye on it but that should be fixed going forward. We're discussing how to handle the zeroes vs nulls question.

**Comment by smrgit** [comment]
I live near Seattle and have a particular interest in the WA data --  if you need an extra set of hands/eyes to update/curate the WA data, I'd be happy to help.
