### ISSUE TITLE
Adding Big Local News as a partner?

### ISSUE THREAD

**Issue by cephillips** [COVID19Tracking/issues#19]
Hi -- here to volunteer our help. Small team of four data journalists, plus a half-time engineer. Just launched our data-sharing for journalists platform, built around a robust API, ability to open data into tools, such as Datasette (SQL), or use api to open into Jupyter Notebooks, etc. We archive data with Stanford Libraries. Would like to help track and also create an open project that puts a new daily version into our platform so we can eventually archive and have a permanent record of this tracking. Let me know. cep3@stanford.edu Also, site is at [https://biglocalnews.org/](https://biglocalnews.stanford.edu)

**Comment by careeningspace** [comment]
We spend about 30-45 minutes after 4 pm ET verifying the data, so maybe at 5 pm ET would be a good time to pull our data?
