### ISSUE TITLE
Historicals for VA (4/11 & 4/12)

### ISSUE THREAD

**Issue by quangnguyen1995** [COVID19Tracking/issues#190]
Some issues with VA data for 4/12 and 4/11 so far as observed by the 4/13 morning data entry crew:

1. Guidelines for updating current hospitalizations have updated to include both pending and confirmed hospitalization cases (if the state reports it). However, the number from 4/12 seems to indicate that only hospitalization numbers from confirmed cases were reported. On 4/11, the number of hospitalizations was 1252, but, the next day it dropped to 751, which is closer to the number of current hospitalizations for cases only on the dashboard. Unfortunately this is only circumstantial evidence since no screenshots for the hospitalization dashboard were recorded. 

2. The number of current ICU and ventilation were also added together for 4/11 and 4/12. However, ICU numbers already include those on ventilation, which means those numbers should be separate. Specifically, the numbers should be: 
**4/11** Curr. ICU: 426 | Curr. Vent: 283
**4/12** Curr. ICU: 440 | Curr. Vent: 294 
These numbers were inferred from the formula on the spreadsheet. 

Additionally, is there any way we can add screenshots for this page (https://www.vhha.com/communications/virginia-hospital-covid-19-data-dashboard/)? We currently take hospitalization data from it. 

Let me know if there are any issues 👍

**Comment by muamichali** [comment]
Hi @quangnguyen1995 

1. We added the hospital dashboard as a secondary source now.
