### ISSUE TITLE
cumulative numbers wrong? or column headings?

### ISSUE THREAD

**Issue by smrgit** [COVID19Tracking/issues#192]
this screen-shot is directly from the google sheet -- the "cumulative" numbers (for in-ICU and on-ventilator) have never made sense -- not sure if this is just a problem with the available data or if it's a bug in the spreadsheet?
![image](https://user-images.githubusercontent.com/3067449/79137848-54bd8a00-7d68-11ea-8f9f-bc7661dbdc57.png)

**Comment by careeningspace** [comment]
Hello,
The issue you are highlighting is that the outcome data is not reported consistently across all states. The headings are correct, but there is a lack of data to be a truly national number

From our website:
![Screen Shot 2020-04-14 at 12 31 49 PM](https://user-images.githubusercontent.com/43073915/79249953-02559980-7e4c-11ea-8dd2-cde278fd9fc8.png)
