### ISSUE TITLE
Total positives dropped for Wyoming

### ISSUE THREAD

**Issue by lcucos** [COVID19Tracking/issues#193]
API: https://covidtracking.com/api/states/daily.json
April 10 Wyoming has 320 positives and  Aprli 11 (after adding one) got to 261. 
Is this a correction on purpose or some other error?
You can easily spot it here: [https://cvd19.info.myroadtime.com/](https://cvd19.info.myroadtime.com/)

**Comment by gitjeff05** [comment]
Duplicate of #187 

It seems that the authority of record is the state website, so whatever is shown there at the time is what is reflected here.

**Comment by lcucos** [comment]
Good to know. Thank you.
