### ISSUE TITLE
AZ: Need a tableau proxy

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/issues#2]
AZ uses Tableau.  We can fetch the page but we don't alert when the numbers change.

This might work with a captive browser model or you might be able to sniff out a data link in the chrome developer tools.

https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/index.php#novel-coronavirus-home

Please create a stand-a-lone endpoint such as http://mysite.org/proxy-tableau?state=AZ and return the data as an HTML table

**Comment by joshellington** [comment]
FYI, there are "Download" links to simpler output structures for these Tableau embeds if you remove the `showAppBanner=false` and `toolbar=no` query params. For example, here are a few simple tables (still not directly embedded data):

- *Cases*: https://tableau.azdhs.gov/vizql/w/COVID-19Table/v/COVID-19table/viewData/sessions/ECAEFF86A8224E18A4020737CB4BE181-1:3/views/8275719771277684273_10329084236957726728?maxrows=200&viz=%7B%22worksheet%22%3A%22Cases%22%2C%22dashboard%22%3A%22COVID-19%20table%22%7D
- *Tests*: https://tableau.azdhs.gov/vizql/w/COVID-19Table/v/COVID-19table/viewData/sessions/520DDAEDDAC74525A2DCC58659B97800-1:0/views/8275719771277684273_2738315765867498942?maxrows=200&viz=%7B%22worksheet%22%3A%22Testing%22%2C%22dashboard%22%3A%22COVID-19%20table%22%7D

**Comment by joshuaellinger** [comment]
I'm providing a updating screenshot at http://covid19-api.exemplartech.com/github-data/captive-browser/az_tableau.html.

Can you confirm that either my approach or yours above is live in production and close the issue?

**Comment by joshuaellinger** [comment]
Resolved
