### ISSUE TITLE
MA Hospitalization Number Inconsistent

### ISSUE THREAD

**Issue by enkiddo** [COVID19Tracking/issues#203]
For several days, cumulative hospitalizations in MA have been stuck at 2340.  The most recent current figure for hospitalizations is over 3400.  It is implausible that hospitalizations have been zero for the last 3 days, and impossible for the cumulative number to be less than the current number.

**Comment by muamichali** [comment]
Hi @enkiddo 

Thanks for your feedback

MA is now reporting hospitalizations on their dashboard, and we are regularly updating them based on the information they provide.
