### ISSUE TITLE
Issue with Arkansas data

### ISSUE THREAD

**Issue by chadmira** [COVID19Tracking/issues#204]
The Arkansas data you have as far as hospitalizations and new tests don't seem to line up with the daily numbers provided on the state website.

**Comment by muamichali** [comment]
Hi @chadmira
Are you still seeing issues with Arkansas data? Can you please give us more specific input on what the mismatch is?

**Comment by chadmira** [comment]
Hi. Thanks for writing. If you look at the hospitalized number on covidtracking.com under historical data, it has listed 291 for several days now. However, the state of Arkansas is currently reporting under 110. The hospitalizations the state has reported daily has never been in the 200s. It also has fluctuated every day.

[cid:image001.png@01D61CA4.53188B20][cid:image004.png@01D61CA5.0717A520]


As for the “new tests” column, I’m not sure where that data is getting pulled from. Covidtracking.com has several days where test numbers are over 2,000. But in the daily numbers reported by the state, there has only been one day over 2,000 test results have been submitted. Below is a graph the governor used last week to show the number of tests being conducted on a daily basis.


[cid:image008.png@01D61CA5.0717A520][cid:image007.png@01D61CA4.DE69FAB0]





Best,
Chad Mira
Evening Anchor
KNWA News
609 W. Dickson Street, Suite 300
Fayetteville, AR 72701
O: 479-571-5100
E: cmira@knwa.com<mailto:cmira@knwa.com>
https://www.nwahomepage.com/

**Comment by erfgottlieb** [comment]
Thanks for your input @chadmira ! We have been taking the cumulative hospitalization numbers from the Arkansas DOH page https://www.healthy.arkansas.gov/programs-services/topics/novel-coronavirus and the number for Total Tested for COVID-19 from the state dashboard https://adem.maps.arcgis.com/apps/opsdashboard/index.html#/f533ac8a8b6040e5896b05b47b17a647 
Arkansas updated its testing numbers after our publish time cutoff. If a state updates testing numbers after that time, we catch that update on the following day. So far, the historicals we keep seem to agree with this pattern. We're working internally to best represent this data as well as shifting our time to catch states that update only slightly after our publish time.
