### ISSUE TITLE
NY Numbers

### ISSUE THREAD

**Issue by Josh0883123** [COVID19Tracking/issues#205]
Any plans to update the NY numbers, to include the new death #s, and thus, the new case numbers?

World Meters has NYS at 226,198... and deaths at 16,106.

Believe Cuomo said they might start including these numbers in the future, but the difference is the "probable deaths" category that was recently added.

I bring this up, because while NY is the big one, other states are starting to do the same... 5 to be exact so far. Michigan is also tracking different "death" categories. 

Any plans to add these to this tracker for a closer to accurate count?

**Comment by muamichali** [comment]
Thanks for writing @Josh0883123  

Please see this response https://github.com/COVID19Tracking/issues/issues/331#issuecomment-621381956 

We're working on separate accounting of lab-confirmed and probable deaths for all states where we can do so.
