### ISSUE TITLE
FL April 16 2020

### ISSUE THREAD

**Issue by fishjumping** [COVID19Tracking/issues#207]
The last two screenshots (assuming they were taken) are not showing and none of the screenshots agree with the number of hospitalizations   saw 3458 and the page is showing 3460

**Comment by muamichali** [comment]
Hi @fishjumping 

There are only two screenshots available for that day due to a technical issue. 

We report FL hospitalizations using the raw data provided by FDOH. On 3/26 their dashboard stopped including non-residents in its visible counts, but they still track them behind the scenes.

**Comment by fishjumping** [comment]
thanks
