### ISSUE TITLE
inIcuCurrently and inIcuCumulative mixed up?

### ISSUE THREAD

**Issue by sdangt** [COVID19Tracking/issues#210]
I just downloaded the [US historical data](https://covidtracking.com/api/us/daily.csv), and "inIcuCurrently" is both larger than "inIcuCumulative" and goes up continuously, implying that these two column headers might be reversed.

I got this from the [API page](https://covidtracking.com/api).

Neither of those figures seem to line up well with data from elsewhere about serious cases, such as [from Worldometer](https://www.worldometers.info/coronavirus/).

The columns are not referenced on the API page, so maybe they are new or experimental.

Anyway, I have seen this data referenced elsewhere, and I think it's a very worthwhile project.

Dan

**Comment by muamichali** [comment]
Thanks, Dan! 

From https://covidtracking.com/data:

> States are currently reporting two fundamentally unlike statistics: current hospital/ICU admissions and cumulative hospitalizations/ICU admissions. Across the country, this reporting is also sparse. In short: it is impossible to assemble anything resembling the real statistics for hospitalizations, ICU admissions, or ventilator usage across the United States. As a result, we will no longer provide national-level summary hospitalizations, ICU admissions, or ventilator usage statistics on our site.
> 
> We will continue tracking these numbers on a state-by-state basis, but it does not feel responsible to continue to display these US-wide statistics for a general audience. These heavily caveated numbers will remain in the API for advanced data users.

**Comment by sdangt** [comment]
Thanks for that explanation.  I noticed that Johns Hopkins is displaying
<https://coronavirus.jhu.edu/map.html> US-wide hospitalization data now
(click the right arrow on the panel in the upper right).  I'm surprised
they are reporting these.  They do have higher numbers than you do at the
moment.

Are the numbers still some guide though because for instance wouldn't
numbers in the past also be similarly incomplete, so that we can at least
compare these incomplete numbers to those for some rough comparison?

But perhaps there will be an analysis afterwards that yields at least
slightly more accurate results.  It's too bad that we aren't tracking these
things better.  It seems inconceivable ("you keep using that word") that we
aren't tracking even some these basic metrics better at a time like this,
when there are so many data tools available.

Thanks for your reply.

Dan

**Comment by catawbasam** [comment]
JHU is using COVID1i9Tracking as its source for US hospitalizations:
_"COVID Tracking Project: https://covidtracking.com/data. (US Testing and Hospitalization Data. We use the maximum reported value from "Currently" and "Cumulative" Hospitalized for our hospitalization number report ed for each state.)"_
-- https://github.com/CSSEGISandData/COVID-19

We still have 3 states not reporting either hospitalization metric: Indiana, Nebraska and Nevada.  
Indiana appears to be working on it.   

If you know people in Nebraska or Nevada, please encourage then to add hospitalization stats to their daily updates.

**Comment by shgsousa** [comment]
> I just downloaded the [US historical data](https://covidtracking.com/api/us/daily.csv), and "inIcuCurrently" is both larger than "inIcuCumulative" and goes up continuously, implying that these two column headers might be reversed.
> 
> I got this from the [API page](https://covidtracking.com/api).
> 
> Neither of those figures seem to line up well with data from elsewhere about serious cases, such as [from Worldometer](https://www.worldometers.info/coronavirus/).
> 
> The columns are not referenced on the API page, so maybe they are new or experimental.
> 
> Anyway, I have seen this data referenced elsewhere, and I think it's a very worthwhile project.
> 
> Dan

I have noticed exactly the same issue. The two columns are most likely swapped.
