### ISSUE TITLE
CO: new daily report currently hospitalized=858, discharged last 24 hours=203 (4/17)

### ISSUE THREAD

**Issue by catawbasam** [COVID19Tracking/issues#213]
https://covid19.colorado.gov/hospital-data

**Comment by muamichali** [comment]
Thank you so much @catawbasam 

We added this to our sources list for CO

**Comment by muamichali** [comment]
**Before**
![CO Currently Hospitalized Before](https://user-images.githubusercontent.com/1749380/79676915-09b4d400-81b9-11ea-9787-55e5ccf28cc2.png)
