### ISSUE TITLE
California data issue

### ISSUE THREAD

**Issue by n8levine** [COVID19Tracking/issues#217]
The proper number for deaths in CA on Sat, April 11 is 609. (You have 541 two days in a row.) You can see 609 in the 9:03pm screenshot for Sat. April 11. Do you think someone could look at and adjust? We are huge fans of all work on this, from the graphics team at The Sacramento Bee in California

**Comment by muamichali** [comment]
Thanks for letting us know about this issue @n8levine!

We are going to patch the data. 

Before 
![CA 4 -11 Deaths Before](https://user-images.githubusercontent.com/1749380/79675656-76c56b00-81b3-11ea-8205-4e04881e66e1.png)

After 
![CA 4 -11 Deaths After](https://user-images.githubusercontent.com/1749380/79675749-7fb63c80-81b3-11ea-968e-cdb66ba003e4.png)

So glad to hear you are fans of the work and likewise from our end.

**Comment by Jmuccigr** [comment]
@n8levine, please see #181.
