### ISSUE TITLE
Wyoming

### ISSUE THREAD

**Issue by mlgnight** [COVID19Tracking/issues#218]
Curious about the data at https://covidtracking.com/data/state/wyoming#historical for Wyoming April 9-11. Goes from 230 to 320 then down to 261

**Comment by muamichali** [comment]
Hi @mlgnight,
The 320 number included lab confirmed tests as well as probable cases as reported on WY website at the time. We are going to revise it down to include only lab confirmed cases. 

https://covidtracking.com/screenshots/WY/WY-20200410-181945.png
