### ISSUE TITLE
DC negatives dropped on Wed Apr 15

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#219]
It appears the correct numbers are recorded for positives and totals. But it's odd/doesn't really make sense to see negatives drop. 

![image](https://user-images.githubusercontent.com/1327983/79670191-3522c900-818f-11ea-9b31-5c84d477e08e.png)

**Comment by muamichali** [comment]
Hi @jdmaresco 

The 4/14 negatives number was incorrect. We are going to amend it based on hisorical information [DC provides here ](https://coronavirus.dc.gov/sites/default/files/dc/sites/doc/page_content/attachments/DC-COVID-19-Data-for-April-22-2020.xlsx)
Looking at screenshots it seems that the state reported a total number of tests and then revised it down the next day.

**Before**
<img width="261" alt="Screen Shot 2020-04-23 at 10 08 00 AM" src="https://user-images.githubusercontent.com/1749380/80108815-b80aa180-854a-11ea-9874-8a94003c675c.png">

**After**
<img width="241" alt="Screen Shot 2020-04-23 at 10 08 24 AM" src="https://user-images.githubusercontent.com/1749380/80108865-ca84db00-854a-11ea-93b3-ecdfa95faec7.png">
