### ISSUE TITLE
April 18 #'s appear to be doubled

### ISSUE THREAD

**Issue by emmjayvee68** [COVID19Tracking/issues#220]
Number of states tracked in US stats shows 112. Prior days show 56. Other metrics look doubled as well.

**Comment by muamichali** [comment]
Thanks for letting us know @emmjayvee68! Looking into it ASAP

**Comment by careeningspace** [comment]
Hello,

We apologize for the confusion. The issue has been rectified.  

Thank you for your vigilance!

**Comment by emmjayvee68** [comment]
Excellent! Thanks for the quick response and all of your hard work!
