### ISSUE TITLE
R0

### ISSUE THREAD

**Issue by ltbjtw** [COVID19Tracking/issues#224]
please generate R0 for each state and county. To open up, we need R0 certainly less than one, ideally less than .8
Thank you.

**Comment by muamichali** [comment]
Hi @ltbjtw 

We are working to expand the data visualizations on the site using our data. In the meantime, here is a website which uses our data to calculate Rt, in every state. 

https://rt.live/

**Comment by ltbjtw** [comment]
This is awesome -- thank you so much!

Best,
jw
