### ISSUE TITLE
DC hospitalization data source

### ISSUE THREAD

**Issue by mekongfm** [COVID19Tracking/issues#225]
Hi - thanks for great work on this project. 

Could you share the sourcing for your DC hospitalization numbers? They don't seem to be public anywhere else, but they are critical for tracking purposes. 

Thanks,
John

**Comment by muamichali** [comment]
Thanks, John. 

The DC hospitalization numbers are from Mayor Bowser's 4/13 press conference https://www.facebook.com/MayorMurielBowser/videos/846453305836225/
