### ISSUE TITLE
California COVID Data

### ISSUE THREAD

**Issue by mlgnight** [COVID19Tracking/issues#226]
At https://covidtracking.com/data/state/california#historical it appears that the data around April 10-12 seems odd. Flat, then big jump?

**Comment by muamichali** [comment]
@mlgnight  Thank you for reporting. There was an earlier issue https://github.com/COVID19Tracking/issues/issues/217 and the data has been patched. It should be reflected on the site this afternoon around 5.30pm EST.

**Comment by Jmuccigr** [comment]
This doesn't really explain CA's weird ups and downs, but more significantly, the total tests numbers on their data page are clearly rounded. Every day's total ends in -00. Your counts don't match theirs all the time, but they do right now.

Of course you have to use what the states report, but it really would be good to get to the bottom of what's going on with CA's reporting.

**Comment by Jmuccigr** [comment]
What's the "best data source" for CA? I ask because the link and the screen shots on the data page are to their health dept page, but you say in the text that 

>  until 4/1, when we standardized on California's new data dashboards

So which is it?
