### ISSUE TITLE
Sequences and outcomes

### ISSUE THREAD

**Issue by LuisMatheu** [COVID19Tracking/issues#230]
Hi My name is Luis Matheu,
I want to sugest sequences and patient outcome currently there is www,nextstrain.org effort for genome sequences for Covid 19.  but also we need to link outcome of patients to sequences as to find if there is any link for viral mutatiion and less severe virus, and the opposite also.

with this info things may be useful to learn is there are more pathogenic and les pathogenic strains, to develop dignostic tools fo diferentiate and also find a non lethal strain that could be domisticated for vaccine pourposes.

best regards
Luis Matheu

**Comment by muamichali** [comment]
Dear @LuisMatheu 
Thank you for the information about the project at https://nextstrain.org/
It looks like very interesting and important work. 

At this time, there are no reports from states that we are aware of detailing the strains of virus, so there is not a direct course of action for this project, but we will watching this with great interest.

**Comment by LuisMatheu** [comment]
Dear all

The reason we áre not seen information on covid 19 strains Is because Is so
NEW.

But data Is emerging
https://www.abc12.com/content/news/New-strains-of-Covid-19-found-in-Michigan-569705351.html

Also wish i could share some others.

All efforts on sequencing of the virus Is good but results áre not enough
because nobody isnlinking secuencia to outcome

Please Sequence virus from patients that where no so sick,, an Lets find
the nonpathogenic strain
Best regards Luis matheu
