### ISSUE TITLE
Add-on for Google Sheets

### ISSUE THREAD

**Issue by acmeyer** [COVID19Tracking/issues#231]
Thanks for making this API!

Like many others, I've been using the API data in a Google Spreadsheet so I built a Sheets Add-on to make it easier to pull the data directly into a spreadsheet: https://github.com/acmeyer/sheets-covid-tracker

It allows users to pull it in as raw data, much like your existing Google Spreadsheet, but also allows users to pull specific data. For example, you can simply use `= GET_STATES_DATA("NY", "positive")` to get the latest number of positive cases for New York.

Anyway, I was going to release the add-on myself but thought it would be better as part of the official project since it would get a larger audience and can have more people contributing to it. I'm happy to help walk you through how to get it launched if that helps too.

Let me know if this is of any interest, and thanks again for doing this!

**Comment by careeningspace** [comment]
@acmeyer This is really cool! We will review it and get back to you!
