### ISSUE TITLE
New York Patient Recovered Data not updated since 04/13

### ISSUE THREAD

**Issue by canyonero2012** [COVID19Tracking/issues#232]
Here are some useful links of recovered data:

https://coronavirus.health.ny.gov/past-coronavirus-briefings

https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_New_York_(state)

**Comment by muamichali** [comment]
Thanks for writing and providing the links @canyonero2012 .
We are now calculating the recoveries based on the numbers given in the daily briefings. 

Please note that there is a state wide call for the governor to provide this information in a more straightforward way, as many other states already do.  https://reinventalbany.org/2020/04/watchdogs-urge-governor-to-publish-covid-19-data-as-open-data/
