### ISSUE TITLE
discrepancy in US deaths - your site versus Johns Hopkins University

### ISSUE THREAD

**Issue by johnindenver** [COVID19Tracking/issues#234]
After weeks of nearly matching the Johns Hopkins University dashboard figures, today's at 5,000 lower than theirs.  
I checked, but don't see an explanation for the extensive variation ... can you add one to the FAQ?

**Comment by muamichali** [comment]
Thanks for writing, @johnindenver 

The reason for the discrepancy is that NYC on 4/14 added more than 3700 presumed deaths retroactively to its deaths count.
https://www.reuters.com/article/us-health-coronavirus-usa-idUSKCN21W20G

We have not yet added these presumed historical deaths into our reports.

In recent days,  additional states are starting to report probable cases and deaths along with confirmed. We are analyzing the availability of data from states so we can continue to aggregate the most accurate and transparent view of the data that the states are providing.
