### ISSUE TITLE
CA deaths fix?

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/issues#235]
> Hi. I'm REDACTED at The Sacramento Bee in California. I think the proper number for deaths in CA on Sat, April 11 is 609. (You have 541 two days in a row.) You can see 609 in the 9:03pm screenshot for Sat. April 11. Do you think someone could look at and adjust? We are huge fans of all work on this

**Comment by muamichali** [comment]
Hi @kissane :)

We got this issue in github here https://github.com/COVID19Tracking/issues/issues/217 and fixed it.
