### ISSUE TITLE
Guam

### ISSUE THREAD

**Issue by mlgnight** [COVID19Tracking/issues#237]
https://covidtracking.com/data/state/guam#historical dropped from 136 to 133 from 4/19 to 4/20

**Comment by goldfarb** [comment]
Thank you for pointing that out, @mlgnight 

We chose to use the 'confirmed' value (133 this morning), although Guam uses slightly different language in different places.

Once we have confirmation about what they consider probable or confirmed cases, we'll updated our historical data to match.
