### ISSUE TITLE
Hospitalizations figure should be 3x higher

### ISSUE THREAD

**Issue by GumbyTheGreen1** [COVID19Tracking/issues#242]
Your "Hospitalized – Cumulative" figure ([found here](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#)) should probably be around 3x higher. It's currently at 82,879 while deaths are at 37,321, implying a hospitalizations-to-deaths ratio of 2.22. This is only a third of what [the IHME calculated](http://www.healthdata.org/sites/default/files/files/Projects/COVID/Estimation_update_041320.pdf) on the 13th using data from 23 states.

IHME aside, it's obvious that nowhere close to half of those being hospitalized are dying. Is it possible to either drastically improve this data or remove it altogether? It would be better to have no figure at all than one that's this far off.

**Comment by catawbasam** [comment]
The main page  documents this problem -- see quote below. However, "https://covidtracking.com/about-data" has nothing about it.  Caveats should be added there too.

"States are currently reporting two fundamentally unlike statistics: current hospital/ICU admissions and cumulative hospitalizations/ICU admissions. Across the country, this reporting is also sparse. In short: it is impossible to assemble anything resembling the real statistics for hospitalizations, ICU admissions, or ventilator usage across the United States. As a result, we will no longer provide national-level summary hospitalizations, ICU admissions, or ventilator usage statistics on our site.

We will continue tracking these numbers on a state-by-state basis, but it does not feel responsible to continue to display these US-wide statistics for a general audience. These heavily caveated numbers will remain in the API for advanced data users."

**Comment by careeningspace** [comment]
Hello, 
As @catawbasam pointed out, the national roll-up of this data is not very useful, and the hospitalization data is best looked at on a state-by-state basis. We are working on removing some of the more confusing historical data.

Thank you!
