### ISSUE TITLE
MA has changed reporting methodology for cumulative hospitalized from 4/13 onward

### ISSUE THREAD

**Issue by camille-le** [COVID19Tracking/issues#243]
Hello, reporting a change in MA's count for hospitalized. They are now including suspected and confirmed. 
* Prior to 4/13 only confirmed cases were included in the hospitalization count data
* Starting 4/13 both confirmed and suspected cases are included

Source, page 6: 
https://www.mass.gov/doc/covid-19-dashboard-april-20-2020/download

Can we update 4/13 data - 4/19? Note, 4/20 is being updated now.

Thanks!
Camille

**Comment by muamichali** [comment]
<img width="991" alt="MA Hospitalizations Source" src="https://user-images.githubusercontent.com/1749380/79926591-52fc6200-840b-11ea-8674-e06a9ce08acf.png">
 
<img width="404" alt="MA Hospitalizations Before" src="https://user-images.githubusercontent.com/1749380/79926609-5c85ca00-840b-11ea-94ea-48fb9d5a434d.png">

<img width="357" alt="MA Hospitzalitions After" src="https://user-images.githubusercontent.com/1749380/79926620-61e31480-840b-11ea-98ec-f247d05a6a1f.png">

Hi Camille, 
The spreadsheet was updated based on the data in the PDF. I am assigning to AFG to double check before closing the ticket.
