### ISSUE TITLE
County level data

### ISSUE THREAD

**Issue by kabronkline** [COVID19Tracking/issues#245]
Any possibility that we can add county level data in the API? Daily updated source available here:

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

'Admin2' column has county name and FIPS code corresponds to the county.

**Comment by ilyaeck** [comment]
+100
It would also be extremely useful to get hospitalizations and total tests done per county, whenever available.  For instance NY state has this downloadable CSV: https://health.data.ny.gov/api/views/xdss-u53e/rows.csv, Florida has an ESRI plugin, ...

**Comment by ggrowe** [comment]
Hey - GG from the Support Desk.  Any chance that we'll address the feature request of tracking and reporting on county level data?  We have received several inquiries recently.

**Comment by muamichali** [comment]
Hi all and GG

This request is being evaluated by the editorial team for potential implementation.
