### ISSUE TITLE
MD: data added for hospitalized and ICU 

### ISSUE THREAD

**Issue by nfritts** [COVID19Tracking/issues#246]
Announcement: 
https://twitter.com/MDHealthDept/status/1252601187586772993

Data is now present on the current "Best source" page now as well: 
https://coronavirus.maryland.gov/

**Comment by muamichali** [comment]
Thanks for letting us know about this @nfritts 

We will make sure and check the source for the added data starting today.

**Comment by catawbasam** [comment]
This is good to hear. Thanks!
