### ISSUE TITLE
GA data discrepancy (~ APR 20)

### ISSUE THREAD

**Issue by dcorbin** [COVID19Tracking/issues#247]
On Apr 20, in Georgia, you're data table shows about ~ 700 new cases.  I looked at the source page for that data (also visible in the screen shots).  The only place on that page that I can find to extract a "new cases" is from a chart (hover), and it is showing 36 new cases. I strongly suspect there is a data inconsistency on the source page, but I need more information on how the GA data is extracted from that page.

**Comment by muamichali** [comment]
Hi @dcorbin 

Thanks for writing
The Georgia source page shows a total of 18,301 cases on 4/19 
https://covidtracking.com/screenshots/GA/GA-20200419-180551.png

and a total of 18,947 cases on 4/20 
https://covidtracking.com/screenshots/GA/GA-20200420-180537.png

18,947-18301 = 646 
https://covidtracking.com/data/state/georgia#historical
