### ISSUE TITLE
Massachusetts data source change

### ISSUE THREAD

**Issue by salmasian** [COVID19Tracking/issues#248]
Data source for Massachusetts has changed. The data used to be on [this web page](https://www.mass.gov/info-details/covid-19-response-reporting) but now it is in a PDF linked from that page. [This](https://www.mass.gov/doc/covid-19-dashboard-april-20-2020/download) is the PDF for April 20th. You will see the total cases, positive cases, and newly reported deaths. These numbers are currently inaccurate on covidtracking.com and should be corrected. Going forward, they should be updated using the same PDF.

**Comment by muamichali** [comment]
Thank you @salmasian for the link.

We publish the daily data around 4.30pm EST. You should see the updated data for Massachusetts based on the PDF then.
