### ISSUE TITLE
Cov-Tra State hospitalization data order of magnitude different from CDC hospitalization data

### ISSUE THREAD

**Issue by archibaldtuttleri** [COVID19Tracking/issues#249]
This seems to be one of the hardest but most important indicia to nail down. CDC has weekly data for 14 states in the EIP and IHSP networks:

https://gis.cdc.gov/grasp/COVIDNet/COVID19_3.html

for instance new york, april 11th, CDC cume total is 22.9/100,000 which with population of approx 19.5 million would imply 4466 hospitalizations but your cume dats shows 40679.  similar divergence on their noncume product but that is not well defined and not clear how to relate it to the current hospitalization number.  I don't know if the CDC really means per 10,000 in which case this wouldn't be so far off or . . .?

I can't find the regular source of hospitalization data for NY on the link you provide. searching the domain:A health.ny.gov , i do find some weekly reports with numbers that track your daily hospital population fairly well. e.g March 9th: 18279 which precisely matches your archive.

At least in a limited number of states the CDC has supposedly uniform hospitaliziation data, I nonetheless can't make heads nor tails of where they could be getting these numbers compared to  covidtracking, but establishing some LCD in this critical area of resource utilization seems to go begging in favor of case count and deaths.

**Comment by catawbasam** [comment]
Per the disclaimer on the CDC page you link, their data includes 100 counties -- these are not statewide totals.  CDC is estimating rates based on a sample.  Not meant to be used for total counts.
