### ISSUE TITLE
AK Death Issu

### ISSUE THREAD

**Issue by thaddeuspompidou** [COVID19Tracking/issues#255]
For AK in historical data  on 2020/03/24 the death property does not exist

**Comment by muamichali** [comment]
Hi @thaddeuspompidou 

We will update the data on our end from nothing to zero so it will be visible in the API. The change should be reflected tomorrow afternoon. 

![Screenshot_2020-04-22 Coronavirus numbers by state (CovidTracking, DEV COPY)(1)](https://user-images.githubusercontent.com/1749380/80043375-87d1ed00-84cf-11ea-9465-edbeb3af4cad.png)
![Screenshot_2020-04-22 Coronavirus numbers by state (CovidTracking, DEV COPY)](https://user-images.githubusercontent.com/1749380/80043377-87d1ed00-84cf-11ea-8f9d-d513987f8239.png)
