### ISSUE TITLE
Kansas data for April 8

### ISSUE THREAD

**Issue by cainecarolyn** [COVID19Tracking/issues#256]
Thanks so much for your work! 

The data posted for April 8 for Kansas is incorrect. The deaths for that date should be 38 rather than 27. At that point, we had 1046 cases according to a news source or 1048 cases according to KDHE.

See: https://www.kwch.com/content/news/Kansas-cases-of-COVID-19-jump-by-nearly-100-in-a-day-569411541.html 

and 

screenshot of KDHE data attached.
<img width="949" alt="Screen Shot 2020-04-22 at 2 00 38 PM" src="https://user-images.githubusercontent.com/64162921/80022465-b76a0080-84a1-11ea-9555-88d1ea16c2da.png">

**Comment by muamichali** [comment]
Thanks @cainecarolyn for reporting this issue. I verified your report using our screenshots for KS. We will update the historical data 

https://covidtracking.com/screenshots/KS/KS-20200409-094218.png
