### ISSUE TITLE
California Testing data for 4/22 isn't matching the data source by a large margin

### ISSUE THREAD

**Issue by Grumpicorn** [COVID19Tracking/issues#257]
I checked the testing total and saw a huge jump in number of tests conducted.  This seems to be from California but the reported figures in historical data (165,229) do not match the state's dashboard (8600).  Has there been a new data source or is this in error?

**Comment by muamichali** [comment]
Hi @Grumpicorn 

The tests were announced in Governor Newsom's today and are not reflected on the dashboard yet. 

Here is our tweet about this:

![CA tests](https://user-images.githubusercontent.com/1749380/80036407-a8924680-84bf-11ea-9a71-92de1bd2cc52.png)

**Comment by howchik** [comment]
Hello, 

I believe Total number of test should be 308K. 


https://covid19.ca.gov/

All the way on the bottom: 

"Latest numbers
April 22 Numbers: As of April 21st, there are 35,396 positive cases and 1,354 deaths in California. Approximately 308,700 tests have been conducted. At least 292,906 results have been received and 7,200 are pending."

**Comment by muamichali** [comment]
California has updated their dashboard and page to report the tests now. Closing this issue.

![Screenshot_2020-04-24 Most recent data](https://user-images.githubusercontent.com/1749380/80212883-50b22780-8606-11ea-88a7-79a6bab551b0.png)
![Screenshot_2020-04-24 California Coronavirus COVID-19 Response](https://user-images.githubusercontent.com/1749380/80212884-50b22780-8606-11ea-9543-62ff2c684dbe.png)
