### ISSUE TITLE
NY: Adding historical testing data from 3/3-3/12

### ISSUE THREAD

**Issue by Jordan-Zino** [COVID19Tracking/issues#26]
I pulled historical total tests for NY from Gov. Cuomo's press conference on 3/13.  Data starts from 3/3 and is complete through 3/12 and partial for 3/13.  We can use it to backfill historical tests for NY from 3/3 by adding each day's total tests to the previous.  Now that users of the site can see historical data at the state level, I thought this would be useful to see NY's trend and the % testing positive.  The #reporterwatch tab on Slack suggest I open an issue here.  Picture attached and link to press conference below.  Thanks!

![NYtests3-13](https://user-images.githubusercontent.com/62438734/77183790-45b72500-6aa5-11ea-9dd6-8a44ddd80331.jpg)

6:00 mark at below 3/13 press conference
https://www.youtube.com/watch?v=oN6H4J32fz4.

**Comment by careeningspace** [comment]
Thank you - will get to this later today

**Comment by Jordan-Zino** [comment]
Great thanks!

**Comment by careeningspace** [comment]
I looked at our historical for NY and we have something completely different - I will need to dig further.
![Screen Shot 2020-03-27 at 12 09 31 AM](https://user-images.githubusercontent.com/43073915/77720777-45e08480-6fbf-11ea-8714-38533d065acd.png)

**Comment by Jordan-Zino** [comment]
I wasn't helping track back in those early days so I don't know how/what NY
was reporting.  But to my knowledge, that screenshot I sent was the first
time they gave solid retrospective testing data, so I imagine it would be
different from whatever they disclosed piecemeal before perhaps?  Thanks
for taking a look.

Jordan
