### ISSUE TITLE
20200422 data

### ISSUE THREAD

**Issue by pac-71** [COVID19Tracking/issues#261]
Double the number of tests. Same number of positive results ... at around 27,000

Date | States | Positive | Negative | Pending | Total test | new Positive | New test
20200422 | 56 | 826,936 | 3,639,623 | 4,191 | 4,470,750 | 27,219 | 311,616
20200421 | 56 | 799,717 | 3,355,461 | 3,956 | 4,159,134 | 27,193 | 151,546
20200420 | 56 | 772,524 | 3,231,027 | 4,037 | 4,007,588 | 23,321 | 130,400
20200419 | 56 | 749,203 | 3,116,661 | 11,324 | 3,877,188 | 27,021 | 168,748

is this correct ?

**Comment by muamichali** [comment]
Hi @pac-71 

California catching up a backlog of testing reports is the reason that 4/22 had such a large number of tests, so the numbers are correct here.

https://twitter.com/COVID19Tracking/status/1253071863946698752
