### ISSUE TITLE
Agrregated data integrity issues from automated checks 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#265]
https://www.covidcharts.com/data_check.html

<img width="1336" alt="Screen Shot 2020-04-23 at 10 25 46 AM" src="https://user-images.githubusercontent.com/1749380/80110665-ea1d0300-854c-11ea-84a2-2c2d78d911f5.png">

**Comment by loglow** [comment]
https://www.covidcharts.com/data_check.html updated
- added "decreased from the previous day" checks
- added total number of issues found
- removed checks on deprecated "total" and "posNeg" values

**Comment by muamichali** [comment]
Thanks @loglow !
