### ISSUE TITLE
VA data for 4/21 and 4/22 needs update

### ISSUE THREAD

**Issue by nhinze** [COVID19Tracking/issues#266]
VA had some data reporting issues on 4/21 and 4/22. Data needs to be updated to the respective 6PM screenshots.

**Comment by muamichali** [comment]
Thanks for reporting this issue @nhinze 

We will update the data based on the screenshots. 
https://covidtracking.com/screenshots/VA/VA-20200421-181818.png
https://covidtracking.com/screenshots/VA/VA-20200422-181901.png

**Before**
![VA cases Before](https://user-images.githubusercontent.com/1749380/80212394-66731d00-8605-11ea-9894-01f3e12ca611.png)

**After** 
![VA Cases After](https://user-images.githubusercontent.com/1749380/80212422-725edf00-8605-11ea-9480-bf3fb5e4a270.png)

**Comment by nhinze** [comment]
Note that the "Negative", "Total", "Death" and "Hospitalization" columns for those dates is also incorrect.

**Comment by goldfarb** [comment]
Thank you @nhinze 

We have made the updates here, and it will be reflected on the site soon.

Before 
![image](https://user-images.githubusercontent.com/3722037/80232450-eeb3eb00-8622-11ea-8885-c11c199d6bcd.png)

After

![image](https://user-images.githubusercontent.com/3722037/80232468-f4a9cc00-8622-11ea-869f-f033409fc89e.png)

**Comment by astrowonk** [comment]
The Virginia Dept of Health's [CSV](https://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv) (recently switched to https and alas has some certificate validation issues on some clients) has:

```
2020-04-22 | 10266
2020-04-23 | 10998
2020-04-24 | 11594
2020-04-25 | 12366

Why are the totals here different from the state?


```

I'm not sure where your 10627 is coming from.

**Comment by nhinze** [comment]
Actually, the numbers are all off starting 4/23 now compared to the screenshots.
