### ISSUE TITLE
Virginia data counts are off for 4-22-2020

### ISSUE THREAD

**Issue by drRussClay** [COVID19Tracking/issues#269]
The Virginia data counts for 4-22-2020 are showing 0 new cases, but there was a large increase in cases as indicated by the final screenshot of the day.

**Comment by astrowonk** [comment]
Yes, and now April 23 has a big total which shows a huge increase. I think VA's Department of Health columns changed on their public csv file. The NYT had problems parsing the data on the 22/23 too.

**Comment by muamichali** [comment]
Thanks for reporting @drRussClay and confirming @astrowonk 

We handled this as part of https://github.com/COVID19Tracking/issues/issues/266

**Comment by astrowonk** [comment]
Per my comment on #266,
