### ISSUE TITLE
"Total Test" Confusion

### ISSUE THREAD

**Issue by jasonkalmeida** [COVID19Tracking/issues#27]
Referenced Page: https://covidtracking.com/us-daily/

Hey all, LOVE the work being done here (and actually looking to help out if you need any).

One issue I had was a bit of confusion regarding the "Total Test" numbers on the historical table - is that last column the total for the day or total US from start of tracking?

For example:

Did the US run 103,945 tests on 19 Mar 2020 

**OR**

Has the US run 103,945 from 04 Mar 2020 to 19 Mar 2020?

This is probably just misinterpretation on my part... but I would just be concerned that there might be others like me.

Thanks!

**Comment by kissane** [comment]
Moving it to a new repo for visibility

**Comment by careeningspace** [comment]
It seems difficult to convey that the numbers we report are cumulative.

Maybe a better way to say it is that all of our numbers are a running total? 

Except my least favorite "Pending" - pending is... sporadic at best

**Comment by eukonidor** [comment]
Following on from careeningspace's comment about "Pending": Are the Pending numbers reported as the how many remain pending at the time of reporting? Or is that likewise a cumulative total of the number reported as Pending from each day? Because one would assume that some number of the Pending tests would be returned,so should come off the total.

**Comment by hammer** [comment]
@eukonidor the pending numbers are a source of confusion and most states are no longer reporting them so we will likely eliminate them soon. The cumulative total does not double count tests as we never sum over the total column.

**Comment by jasonkalmeida** [comment]
I think "Test to Date" is a really solid way to phrase it personally.

**Comment by careeningspace** [comment]
We have updated the way we are dealing with "totals". Please see the following link for the most current information:  [COVID Tracking API](https://covidtracking.com/api/)
- [ ] totalTestResults - Calculated value (positive + negative) of total test results.
- [ ] total - DEPRECATED Will be removed in the future. (positive + negative + pending). Pending has been an unstable value and should not count in any totals.
