### ISSUE TITLE
[States Daily CSV] PA deaths is lower 2020-04-23 than 2020-04-22

### ISSUE THREAD

**Issue by hrushka** [COVID19Tracking/issues#274]
Source: https://covidtracking.com/api/v1/states/daily.csv

PA, 2020-04-22: 1,622
PA, 2020-04-23: 1,421

Reference: https://c19.dev/d/4S5AN4CZz/covid-19-us-state-data?orgId=1&from=now-45d&to=now&var-state=PA&var-population=12801989&var-density=475.7437637476716&var-total_cases=36763&var-total_deaths=1720

**Comment by beachhockey** [comment]
Even 4/24 is still lower than 4/22 with only 1,492 deaths reported.

**Comment by hrushka** [comment]
Looks like the reason is that the deathIncrease for **2020-04-23** is negative

**Comment by sgdoerfler** [comment]
This should be merged with issue 325, where I added an explanation already.

**Comment by karaschechtman** [comment]
See [issue 325](https://github.com/COVID19Tracking/issues/issues/325) for an explanation. We are making a public note of the revision.
