### ISSUE TITLE
[States Daily CSV] PR positiveIncrease is negative for 2020-04-22

### ISSUE THREAD

**Issue by hrushka** [COVID19Tracking/issues#276]
Source: https://covidtracking.com/api/v1/states/daily.csv

Reference: https://c19.dev/d/4S5AN4CZz/covid-19-us-state-data?panelId=5&fullscreen&orgId=1&from=now-45d&to=now&var-state=PR&var-population=3193694&var-density=0&var-total_cases=915&var-total_deaths=46

**Comment by Nosferican** [comment]
See #211 for the explanation.

**Comment by karaschechtman** [comment]
Hi @hrushka,
Thank you for pointing this out. As @Nosferican says, see [issue 211](https://github.com/COVID19Tracking/issues/issues/211) for an explanation. We will add a note about this to the PR data.

**Comment by muamichali** [comment]
Hi @Nosferican 
Wanted to give you a heads up on this from our web team

> We are now building the entire API to a repository. All the JSON/CSV files are built every 15 minutes and put into this repo. 
> https://github.com/COVID19Tracking/covid-public-api
> 
> We have a test version of the website available that exposes that repo at the same exact endpoints we have now.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api
> 
> There is a new status endpoint that gives info on when the data was last updated. There's also a run number that we can use to go back and download a snapshot of the API at that moment.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api/v1/status.json
> https://github.com/COVID19Tracking/covid-public-api-build/actions/runs/116895561
> 
> 
> I have reproduced the exact same file structure and format across the different endpoints. The only changes are some additional fields that were in current endpoints are now in every entry for US or states' daily data - for example, dataQualityGrade, There were also some odd time offsets in the old API for fields like dateModified that were presented as UTC, but were in fact not. So they are now UTC.
> Please take some time to test out the new API files and endpoint and give feedback. I hope to have this replace our production API build tool by the

>  end of this week. Any feedback filed as an issue in this repo would be helpful!
