### ISSUE TITLE
[States Daily CSV] Totals for WA data lower 2020-04-23 than 2020-04-22

### ISSUE THREAD

**Issue by hrushka** [COVID19Tracking/issues#277]
Source: https://covidtracking.com/api/v1/states/daily.csv

Fileds: totalTestResults,positive,negative,deaths
Date: 2020-04-23

Reference: https://c19.dev/d/4S5AN4CZz/covid-19-us-state-data?orgId=1&from=now-45d&to=now&var-state=WA&var-population=7614893&var-density=147.46721965695642&var-total_cases=12539&var-total_deaths=696

**Comment by muamichali** [comment]
Hi @hrushka 

Your website is great! I am seeing very different numbers on https://c19.dev/d/4S5AN4CZz/covid-19-us-state-data?panelId=2&fullscreen&orgId=1&from=now-45d&to=now&var-state=WA&var-population=7614893&var-density=147.46721965695642&var-total_cases=12539&var-total_deaths=696 than on our WA numbers. Positives and Testing numbers are off. Can you double check that you are using our numbers please? 

![Screenshot_2020-04-24 Coronavirus numbers by state (CovidTracking, DEV COPY)](https://user-images.githubusercontent.com/1749380/80214344-ab4c8300-8608-11ea-89b2-b310f0f1e367.png)

**Comment by hrushka** [comment]
@muamichali hey thanks for checking on this, I found the error in my import. I was relying on the Hash column to be a primary key for the state and day, so I was duplicating days in certain instances!
