### ISSUE TITLE
NY State Hospitalizations

### ISSUE THREAD

**Issue by thelola** [COVID19Tracking/issues#278]
According to you there have been 0 hospitalizations for 3 days? Really?

**Comment by muamichali** [comment]
Hi @thelola,

Thanks for writing. We are now calculating the hospitalizations based on the numbers given in the daily briefings. 

Please note that there is a state wide call to provide this information in a more straightforward way, as many other states already do.  https://reinventalbany.org/2020/04/watchdogs-urge-governor-to-publish-covid-19-data-as-open-data/
