### ISSUE TITLE
California Daily Testing for 4/22

### ISSUE THREAD

**Issue by mwhibben** [COVID19Tracking/issues#279]
Your data shows California performing 165,000 tests on 4/22.  This completely throws off your data for national testing on that day, double a typical day.  The following day, CA testing subsides to 16.7K, much more the norm for that state.  Please double check this.  California Gov has announced intention to expand testing, but I doubt they could perform anywhere close to that many tests per day.

**Comment by muamichali** [comment]
Hi @mwhibben 
Thanks for writing. We wrote about this on Twitter on 4/22 

https://twitter.com/COVID19Tracking/status/1253071863946698752

<img width="724" alt="Screen Shot 2020-04-24 at 11 14 58 AM" src="https://user-images.githubusercontent.com/1749380/80228301-e35dc100-861c-11ea-8ece-19a734cdf57b.png">
