### ISSUE TITLE
Issue with testing data from CA

### ISSUE THREAD

**Issue by dkondras** [COVID19Tracking/issues#28]
It is taken from CDC site and incomplete. 

Better source is daily news release by CA department of public health 
that provides update for previous day at 6pm PCT, 
and includes testing results from private labs in addition to CDC. 
https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Immunization/nCOV2019.aspx.

For example as of the time of writing, the total tests for CA is 9844, 
while CADPH "Latest COVID-19 Facts 3-20" news release gives 

"As of 6 p.m. PDT on March 19, approximately 23,200 tests had been conducted in California. This includes the latest numbers California has received from commercial and private labs. At least 11,487 results have been received and another 11,700+ are pending."

![Screen Shot 2020-03-20 at 1 01 34 PM](https://user-images.githubusercontent.com/48700483/77202220-24593780-6aab-11ea-91f5-adeaf3ea8f66.png)
![Screen Shot 2020-03-20 at 1 00 24 PM](https://user-images.githubusercontent.com/48700483/77202224-24f1ce00-6aab-11ea-81c8-485aba719ea0.png)

Thanks.

**Comment by hammer** [comment]
Thanks @dkondras! California's data has been very tricky for us to report accurately.

Please read the notes we've written at https://covidtracking.com/data/state/california and let us know if you have any further questions:

> We report positives from the [LA Times](https://www.latimes.com/projects/california-coronavirus-cases-tracking-outbreak/), which is aggregated from county-level data and is ahead of the official California data site. When using LA Times data for positives, we do not add deaths back into the positive count, as they are already included. Previously, we were adding them back in because the California state site was not including them in the positive count. Negative numbers are inferred from Totals - Positives, taken from the [latest press release](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-028.aspx). We ignoring pending numbers when they are irregularly reported from a press conference/non-dashboard source. We're assuming 1 test=1 person, pending further guidance.

**Comment by dkondras** [comment]
Got it, thanks!
