### ISSUE TITLE
Number of tests versus number of individuals tested

### ISSUE THREAD

**Issue by Almijisti** [COVID19Tracking/issues#281]
Do we have any idea which, if any states, are tracking the number of separate individuals tested versus the number of total tests given? Without that, it is impossible to determine the actual number of people actually infected beyond those who are hospitalized.  We could extrapolate and say if hospitalization was needed in, say, 20% of positive cases, then multiply the total number of cumulative hospitla cases by 5 to get a ballpark number of infected, but we don't have usable hospital numbers from most states so that is not possible. The number of negative results is likewise misleading if thousands or tens of thousands of people have been tested multiple times, such as medical personnel.

**Comment by qpmnguyen** [comment]
Thank you @Almijisti for your input! We apologize greatly for the late response. 
The short answer is that each state differs in its policy of reporting people vs tests (or specimens tested) and not all states are clear in what they are reporting. We're working internally to identify and report each data type, where possible. We'll announce it when it's ready.

**Comment by Almijisti** [comment]
Thank you. This is a very important distinction and I'm glad you're aware
of it.
