### ISSUE TITLE
Change in Fields States Daily 4pm ET

### ISSUE THREAD

**Issue by srmarti4** [COVID19Tracking/issues#282]
Were the daily increase fields removed from this table?

**Comment by muamichali** [comment]
Hi @srmarti4 

The increase fields are available in 

https://covidtracking.com/api/v1/states/daily.json
and 
https://covidtracking.com/api/v1/states/daily.csv

Are they visible to you there?

**Comment by srmarti4** [comment]
Yes, thank you!
