### ISSUE TITLE
Mass Data for 4/24/20 Is Wrong

### ISSUE THREAD

**Issue by Mergy** [COVID19Tracking/issues#284]
I disbelieve that nobody died between 4/23 and 4/24.  I've been relying on your data but it's been getting flakey!

**Comment by goldfarb** [comment]
I'm so glad that you've been finding the data useful, @Mergy 

Unfortunately, the Massachusetts [update](https://www.mass.gov/info-details/covid-19-response-reporting) for today, which is usually issued around 16:00 EDT, was delayed and came after we had done our afternoon data capture. We will record today's values during our evening data capture.
