### ISSUE TITLE
Indiana data grade is too low

### ISSUE THREAD

**Issue by samth** [COVID19Tracking/issues#285]
I believe the Indiana data grade  is too low. For example, the state issued an executive order requiring private lab negative results to be reported on April 10. Also, hospitalization data is available from https://www.regenstrief.org/covid-dashboard/

**Comment by muamichali** [comment]
Hi @samth 

Thanks for your feedback. We will pass it on to the state grades team.

If you have not seen it yet, we published a blog post with more information about the state grading methodology here https://covidtracking.com/blog/weve-launched-a-new-state-grading-system

**Comment by samth** [comment]
Yes, I saw that. It would be nice if the state page included information on exactly how the grade was determined, in addition to the overall grade.
