### ISSUE TITLE
[States Daily CSV] RI positiveIncrease is negative for 2020-03-07

### ISSUE THREAD

**Issue by acobolew** [COVID19Tracking/issues#286]
RI has positiveIncrease  < 0 on 2020-03-07
> covidtracking.dt <- fread('https://covidtracking.com/api/v1/states/daily.csv')
> covidtracking.dt[, date := as.Date(as.character(date), '%Y%m%d')]
> covidtracking.dt[order(date, decreasing=FALSE)][ , .(date, state, positive, positiveIncrease) ][positiveIncrease < 0]
         date state positive positiveIncrease
1: 2020-03-07    RI        2               -1
2: 2020-04-20    GU      133               -3
3: 2020-04-22    HI      582               -2
4: 2020-04-22    PR      915             -383

**Comment by muamichali** [comment]
1. RI - anomaly was resolved with two updates we made on 6/11 and 6/25. The first one erroneously updated the positive on 3/7 to 140 and the second one updated it to 3.
2. GU - this anomaly was resolved with an update we made to the data on 04/27- See Issue #287 
3. HI - this anomaly was resolved with Issue #272
