### ISSUE TITLE
[States Daily CSV] GU positiveIncrease is negative for 2020-03-07

### ISSUE THREAD

**Issue by acobolew** [COVID19Tracking/issues#287]
Guam has positiveIncrease  < 0 on 2020-04-20
> library(data.table)
> covidtracking.dt <- fread('https://covidtracking.com/api/v1/states/daily.csv')
> covidtracking.dt[, date := as.Date(as.character(date), '%Y%m%d')]
> covidtracking.dt[order(date, decreasing=FALSE)][ , .(date, state, positive, positiveIncrease) ][positiveIncrease < 0]
         date state positive positiveIncrease
1: 2020-03-07    RI        2               -1
2: 2020-04-20    GU      133               -3
3: 2020-04-22    HI      582               -2
4: 2020-04-22    PR      915             -383

**Comment by muamichali** [comment]
Hi @acobolew 
It turned that the 136 numbers included 3 probable cases, we revised the historical data to exclude them https://covidtracking.com/screenshots/GU/GU-20200420-180557.png

**Before**
<img width="170" alt="Screen Shot 2020-04-27 at 2 10 21 PM" src="https://user-images.githubusercontent.com/1749380/80405894-39d33580-8891-11ea-82fd-73c5118fa9c9.png">

**After**
<img width="161" alt="Screen Shot 2020-04-27 at 2 11 03 PM" src="https://user-images.githubusercontent.com/1749380/80405913-3f308000-8891-11ea-9b69-4e3c2ff4973b.png">
