### ISSUE TITLE
[States Daily CSV] DC deathIncrease is negative for 2020-04-07

### ISSUE THREAD

**Issue by acobolew** [COVID19Tracking/issues#289]
DC deathIncrease is negative for 2020-04-07:
> library(data.table)
> covidtracking.dt <- fread('https://covidtracking.com/api/v1/states/daily.csv')
> covidtracking.dt[, date := as.Date(as.character(date), '%Y%m%d')]
> covidtracking.dt[order(date, decreasing=FALSE)][ , .(date, state, death, deathIncrease) ][deathIncrease < 0]
         date state death deathIncrease
1: 2020-04-05    VA    51            -1
_**2: 2020-04-07    DC    22            -2**_
3: 2020-04-22    AR    42            -1
4: 2020-04-23    PA  1421          -201
5: 2020-04-24    KS   111            -1
6: 2020-04-24    TN   168            -2

**Comment by jaclyde** [comment]
Duplicate of [https://github.com/COVID19Tracking/issues/issues/290](url)
