### ISSUE TITLE
[States Daily CSV] PA deathIncrease is VERY negative for 2020-04-23

### ISSUE THREAD

**Issue by acobolew** [COVID19Tracking/issues#291]
[States Daily CSV] Pennsylvania deathIncrease is VERY negative for 2020-04-23
> library(data.table)
> covidtracking.dt <- fread('https://covidtracking.com/api/v1/states/daily.csv')
> covidtracking.dt[, date := as.Date(as.character(date), '%Y%m%d')]
> covidtracking.dt[order(date, decreasing=FALSE)][ , .(date, state, death, deathIncrease) ][deathIncrease < 0]
         date state death deathIncrease
1: 2020-04-05    VA    51            -1
2: 2020-04-07    DC    22            -2
3: 2020-04-22    AR    42            -1
**_4: 2020-04-23    PA  1421          -201_**
5: 2020-04-24    KS   111            -1
6: 2020-04-24    TN   168            -2

**Comment by muamichali** [comment]
Hi @acobolew 

Thanks for reporting. 

As per a press conference on  4/23, "Death count: 1,421 total COVID-19 deaths, a decrease of 201 than was reported yesterday -- this reflects that the probable deaths had been removed from the count because of further investigating."
