### ISSUE TITLE
[States Daily CSV] KS deathIncrease is negative for 2020-04-24

### ISSUE THREAD

**Issue by acobolew** [COVID19Tracking/issues#292]
[States Daily CSV] KS deathIncrease is negative for 2020-04-24
> library(data.table)
> covidtracking.dt <- fread('https://covidtracking.com/api/v1/states/daily.csv')
> covidtracking.dt[, date := as.Date(as.character(date), '%Y%m%d')]
> covidtracking.dt[order(date, decreasing=FALSE)][ , .(date, state, death, deathIncrease) ][deathIncrease < 0]
         date state death deathIncrease
1: 2020-04-05    VA    51            -1
2: 2020-04-07    DC    22            -2
3: 2020-04-22    AR    42            -1
4: 2020-04-23    PA  1421          -201
**_5: 2020-04-24    KS   111            -1_**
6: 2020-04-24    TN   168            -2

**Comment by muamichali** [comment]
Hi @acobolew 
Thanks for letting us know

This was the data reported by Kansas. Here are the screenshots documenting their reports

https://covidtracking.com/screenshots/KS/KS-20200423-181112.png

https://covidtracking.com/screenshots/KS/KS-20200424-180928.png
