### ISSUE TITLE
Is it possible to have a time-series dataset for Tracking Race and Ethnicity in the COVID-19 Pandemic Blog Data?

### ISSUE THREAD

**Issue by riccardograziani** [COVID19Tracking/issues#295]
I would like to ask you if it is possible to obtain the following dataset as time-series dataset: 

https://docs.google.com/spreadsheets/d/e/2PACX-1vTfUQPxkhP_CRcGmnnpUBihnTNZ9Z8pcizII4_sc2o2n3opOoAJdAM4CRTJBI339tou8LWnQrqbTMgH/pubhtml?gid=1129119811&single=true

Best,
Riccardo

**Comment by muamichali** [comment]
Thank you for the request @riccardograziani I will pass it on to the race data team. 

I also wanted to let you know that we launched the new Covid Racial Data Tracker and homepage today https://covidtracking.com/race

**Comment by riccardograziani** [comment]
Thanks very much for your response!
