### ISSUE TITLE
Screenshots api endpoint not working (404)

### ISSUE THREAD

**Issue by srnelson** [COVID19Tracking/issues#296]
State Website Screenshots - https://covidtracking.com/api/v1/screenshots.json (link from https://covidtracking.com/api) yields:

`{"code":404,"error":"404 - NOT FOUND","pathname":"/v1/screenshots.json"}
`

**Comment by webmasterkai** [comment]
The documentation might need to be updated. The endpoint should be https://covidtracking.com/api/v1/states/screenshots.json
