### ISSUE TITLE
NY State Hospitalizations

### ISSUE THREAD

**Issue by platham1** [COVID19Tracking/issues#299]
I find it somewhat illogical that NY is has reported no new hospitalizations 4/21-4/24 when NYC has reported new hospitalizations each day. 
![NY_Hospitalizations_Error](https://user-images.githubusercontent.com/62257028/80289857-81ca4f00-870f-11ea-9d69-f44e4e9daf18.JPG)
[NYC_Hosp_4212020.pdf](https://github.com/COVID19Tracking/issues/files/4533922/NYC_Hosp_4212020.pdf)
[NYC_Hosp_4222020.pdf](https://github.com/COVID19Tracking/issues/files/4533923/NYC_Hosp_4222020.pdf)
[NYC_Hosp_4232020.pdf](https://github.com/COVID19Tracking/issues/files/4533924/NYC_Hosp_4232020.pdf)
[NYC_Hosp_4242020.pdf](https://github.com/COVID19Tracking/issues/files/4533925/NYC_Hosp_4242020.pdf)

**Comment by muamichali** [comment]
Hi @platham1 

We are now calculating the NYS hospitalizations based on the 3 day rolling average numbers given in the governor's daily press briefings. Thanks for you note.
