### ISSUE TITLE
ND data is completely offline

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/issues#3]
This is completely disconnected and badly needs help. It is a PowerBI dashboard that resists current scraping methods.

**Comment by thairu** [comment]
The PowerBI dashboard is behind an iframe. Tried a quick attempt in node.js

https://gist.github.com/thairu/fb291d6d74bf09f66cdf69ef6a0fa2ab will get you the data in a json array. It currently prints out 
```
[
  { displayName: 'Hospitalized', value: '0' },
  { displayName: 'Positive Cases', value: '1' },
  { displayName: 'First Last Updated Date', value: '3/11/2020' },
  { displayName: 'Total Monitored to Date', value: '26' },
  { displayName: 'Total Tested', value: '27' },
  { displayName: 'Deaths', value: '0' },
  { displayName: 'Currently Monitoring', value: '7' },
  { displayName: 'Positives', value: '1' },
  { displayName: 'Negative', value: '12' },
  { displayName: 'Pending', value: '14' }
]
```

**Comment by joshuaellinger** [comment]
Do we have coverage in urlwatch on ND?  If not, let me know and I'll figure it out.

**Comment by lucasgonze** [comment]
@joshuaellinger My focus has shifted from code to product, so I am not the best person to own this.
