### ISSUE TITLE
How to reference you - limitations in using the data?

### ISSUE THREAD

**Issue by kaz-Anova** [COVID19Tracking/issues#30]
First of all, let me say, you have done great work in putting this data together (on a daily basis) and helping understanding Coronavirus better.  

Do you have some best practice on how could someone could reference you? 

Is there a limitation in using this [data ](https://covidtracking.com/api/states/daily) in Open source projects? 

Could I for example make the data available on kaggle/datasets (https://www.kaggle.com/datasets)
(after some minor reformatting)?

**Comment by kaz-Anova** [comment]
Any feedback on this ?

**Comment by careeningspace** [comment]
I am not sure how best to answer this - from what I saw, uploading to Kaggle creates an isolated copy of the data. While we would love for our data to facilitate research, once it is uploaded into a private space, it is no longer maintained by the COVIDTracking.com team.

**Comment by kaz-Anova** [comment]
I could update that on daily basis (or ever x intervals) and obviously reference this git for more information /access to other data .
