### ISSUE TITLE
Massachussetts data not up to date

### ISSUE THREAD

**Issue by nbenb** [COVID19Tracking/issues#300]
I noticed that historical Massachusetts data in the states historical file is does not coincide with that on Massachusetts COVID-19 dashboard.

**Comment by careeningspace** [comment]
Hello,

It was brought to our attention that MA has been updating its historical data. I have updated the data to match as of 4/26, but this revision process is likely to continue and CTP will do our best to keep pace.

Please see #251 for more details on the revisions.

Thanks!
