### ISSUE TITLE
April 25 data for Louisiana is incorrect

### ISSUE THREAD

**Issue by DavidHinchee** [COVID19Tracking/issues#302]
Pulling data via the R package wrapper  API from Amanda Dobbyn at https://github.com/aedobbyn/covid19us. negative_increase and total_test_results_increase for April 25 are both negative.

**Comment by mlgnight** [comment]
Seriously, over 4000 number tests negative?

**Comment by muamichali** [comment]
Thank you for writing @DavidHinchee 

Louisiana revised previously reported numbers that were found to be duplicated 

See https://www.theadvocate.com/baton_rouge/news/coronavirus/article_69f3f2a8-867b-11ea-9cb2-9700ae7e9a26.html

![image](https://user-images.githubusercontent.com/1749380/80314338-fa3c1900-87be-11ea-965d-dc92c44a870a.png)

**Comment by DavidHinchee** [comment]
Thank you for sending the reference below. What’s the process for updating the data, do you expect the state to revise previously reported data?
