### ISSUE TITLE
Washington Grade

### ISSUE THREAD

**Issue by Kiwiwinelover** [COVID19Tracking/issues#304]
How is Washington State grade a B?.  Hospitalization data incomplete - all hospitals do not report every day, # is meaningless. Hospitalization data does not include % capacity.  Hospitalization # didn't even begin to reported until April 9 (backdated to April 6) - as a result of proclamation by DOH Sec. Weisman on April 2 (17 days after initial lock down).  Presentation of data is incoherent for average person. Takes a 25 min youtube video to interpret data on BI platform and website. https://www.youtube.com/watch?v=jdZwOU1qdWQ.    Data reporting has been inconsistent - days without any information.  Some counties are reporting probables as confirmed and state is counting them as confirmed (Yakima - these are not confirmed by testing, wording that cases include probables was removed on April 19th, but data still includes probables).

**Comment by muamichali** [comment]
@Kiwiwinelover Thanks for your feedback. We will pass it on to the state grades team.

If you have not seen it yet, we published a blog post with more information about the state grading methodology here https://covidtracking.com/blog/weve-launched-a-new-state-grading-system

**Comment by Kiwiwinelover** [comment]
Thanks for the response. Org loses lots of credibility when you give Washington state a B grade for incomplete and irrelevant hospitalization data. 

Thank you!  

Jody Easterday
Easterday Farms Produce Co. 
509-521-5064
