### ISSUE TITLE
NJ Test Increase Incorrect for 4/13/2020

### ISSUE THREAD

**Issue by Prindle19** [COVID19Tracking/issues#305]
Negativeincrease, Positiveincrease, Totalincrease for 4/13 show as: 

6065 | 2734 | 2734 

Total should be 6065 + 2734 = 8,799

**Comment by Prindle19** [comment]
Not stale. Still an issue.

**Comment by camille-le** [comment]
Hi Sean, 
We’re seeing `"negativeIncrease":0,"positiveIncrease":2734,"totalTestResultsIncrease":2734` which matches the best data the state provided that day.
