### ISSUE TITLE
NYS data

### ISSUE THREAD

**Issue by buh2003** [COVID19Tracking/issues#306]
NYS data for hospitalizations (total, new, can infer discharges from deaths) can be obtained from the daily briefing slides from Cuomo.

https://www.governor.ny.gov/news/video-audio-photos-rush-transcript-amid-ongoing-covid-19-pandemic-governor-cuomo-announces-13#

https://spaces.hightail.com/receive/9QuN0BN7Qh
<img width="1453" alt="Screen Shot 2020-04-26 at 1 01 02 PM" src="https://user-images.githubusercontent.com/36245945/80318312-299e5600-87be-11ea-9987-59ae2d87ddb2.png">
<img width="1450" alt="Screen Shot 2020-04-26 at 12 59 25 PM" src="https://user-images.githubusercontent.com/36245945/80318315-2c994680-87be-11ea-8766-2cb4e3de3a72.png">

**Comment by muamichali** [comment]
Hi @buh2003 
Thanks for writing.We are now calculating the hospitalizations based on the numbers given in the daily briefings. 

Please note that there is a state wide call to provide this information in a more straightforward way, as many other states already do.  https://reinventalbany.org/2020/04/watchdogs-urge-governor-to-publish-covid-19-data-as-open-data/
