### ISSUE TITLE
Washington data is completely wrong?

### ISSUE THREAD

**Issue by petewills** [COVID19Tracking/issues#307]
There are two issues with washington 

- it reports late. This is not huge in that I can correct it with a few lines in my download script. I manually read the numbers from 3 AM the next day and insert them in the script

- more seriously, washington tends to, every day, correct its historical data. That means that, really, none of the numbers are currently accurate. Can you write a scraper that, every day, takes data from washington's historical data tab?

- If I provide you with such a scraper, in python, will you use it in your future downloads?

**Comment by careeningspace** [comment]
Hello,
You are correct - WA updates every or close to every day. The older data is becoming more stable, but there is still some flux. Currently, we hand curate the data, so we do not use any scrapers. We are working on implementing some automation, but are moving slowly to make sure any change meets our standard of data integrity.

We would entertain using a python script to generate usable data from WA as it is a serious task to keep it current.

Thanks!
