### ISSUE TITLE
CO data does not match state website 

### ISSUE THREAD

**Issue by stevemcconnell** [COVID19Tracking/issues#309]
for example, this data set has the following info for positive tests by date:
4/23 10,878
4/24 11,262
4/25, 12,256
4/26, 12968

The CO state website (listed as the best source of data on the covid tracking website) lists this data
4/23 12,256
4/24 12,947
4/25, 13,441
4/26, not listed yet

Similarly, on new deaths, the covid tracking project shows 44 new deaths on 4/24, whereas the CO state website shows 2. 

These are not the only issues, just illustrations to show the data doesn't match.

**Comment by erfgottlieb** [comment]
Thank you for your input @stevemcconnell ! Colorado updated its total tests and deaths after our publish time cutoff. If a state updates total tests or deaths after that time, we catch that update on the following day. So far, the historicals we keep seem to agree with this pattern. We're working internally to best represent this data as well as shifting our time to catch states that update only slightly after our publish time.
