### ISSUE TITLE
Counts for Navajo Nation

### ISSUE THREAD

**Issue by justaveragejane** [COVID19Tracking/issues#31]
Our AZ counts include the Navajo Nation but I don't see these cases in your stats.

**Comment by careeningspace** [comment]
Hello - we did begin to include Navajo Nation counts. We are having some discussion about breaking them out separately.

Thank you for your vigilance.

**Comment by careeningspace** [comment]
We have found through our investigative team that Navajo Nation numbers are reported to their respective states, but there may be a lag in the timing

**Comment by justaveragejane** [comment]
I don't think your info is correct. If you come up with 1413 for April 1st you are still missing the Navajo Nation.  AZDHS isn't adding them to our totals. 
![Screenshot_20200401-140246_Chrome](https://user-images.githubusercontent.com/62451322/78186745-1cda4c80-7422-11ea-9a35-de31d7dd44e9.jpg)
![Uploading Screenshot_20200401-135923_Chrome.jpg…]()

**Comment by justaveragejane** [comment]
![Screenshot_20200401-135923_Chrome](https://user-images.githubusercontent.com/62451322/78186789-31b6e000-7422-11ea-8d1d-bd03d11499aa.jpg)
