### ISSUE TITLE
Updating negative tests historicals for MI (4/26)

### ISSUE THREAD

**Issue by quangnguyen1995** [COVID19Tracking/issues#310]
There was a data entry mistake on 4/26 publish shift. The number of reported negatives should be 113,228 instead of 156,101 (which was the reported TOTAL tests).

**Comment by muamichali** [comment]
<img width="271" alt="Screen Shot 2020-04-27 at 12 42 50 PM" src="https://user-images.githubusercontent.com/1749380/80397881-d8a56500-8884-11ea-9f50-dd6c5c0c2ea7.png">

<img width="215" alt="Screen Shot 2020-04-27 at 12 43 54 PM" src="https://user-images.githubusercontent.com/1749380/80397886-d93dfb80-8884-11ea-829f-5c40e2e30513.png">

**Comment by quangnguyen1995** [comment]
Thank you! This looks good.
