### ISSUE TITLE
GA Data is "N/A".

### ISSUE THREAD

**Issue by dcorbin** [COVID19Tracking/issues#313]
GA has change the format of it's dashboard as of today and many covid-tracking fields are "N/A" where I don't think they used to be.

(I looked and did not see a duplicate issue)

**Comment by dcorbin** [comment]
I concur. They've moved change the URL to https://dph.georgia.gov/covid-19-daily-status-report and it _appears very different, with more charts.  I don't know how much different it is structurally.

**Comment by erfgottlieb** [comment]
Thanks @dcorbin ! We are now referring to the updated dashboard for the GA data.
