### ISSUE TITLE
Sourse for Kansas data

### ISSUE THREAD

**Issue by MicaelaAyers** [COVID19Tracking/issues#315]
https://www.coronavirus.kdheks.gov/

Please update using Kansas state Department of Health and Environment

Good work!

micaelaayers@gmailcom

**Comment by alexander-eden** [comment]
As of April 27th EOD, Kansas Department of Health launched a new website sharing state data. Your historical screenshots are now showing a bad page.

Here is the public-facing website with the data: [https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas](https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas)

Here are the embedded dashboards (without the site around them):

- [Case Summary](https://public.tableau.com/views/COVID-19TableauVersion2/CaseSummary?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Fpublic.tableau.com%2F&%3Aembed_code_version=3&%3Atabs=no&%3Atoolbar=yes&%3Aanimate_transition=yes&%3Adisplay_static_image=no&%3Adisplay_spinner=no&%3Adisplay_overlay=yes&%3Adisplay_count=yes&%3AloadOrderID=0)
- [Case Rates by County](https://public.tableau.com/views/COVID-19TableauVersion2/CaseRatesbyCounty?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Fpublic.tableau.com%2F&%3Aembed_code_version=3&%3Atabs=no&%3Atoolbar=yes&%3Aanimate_transition=yes&%3Adisplay_static_image=no&%3Adisplay_spinner=no&%3Adisplay_overlay=yes&%3Adisplay_count=yes&%3AloadOrderID=0)
- [Age & Demographics](https://public.tableau.com/views/COVID-19TableauVersion2/AgeandDemographics?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Fpublic.tableau.com%2F&%3Aembed_code_version=3&%3Atabs=no&%3Atoolbar=yes&%3Aanimate_transition=yes&%3Adisplay_static_image=no&%3Adisplay_spinner=no&%3Adisplay_overlay=yes&%3Adisplay_count=yes&%3AloadOrderID=0)
- [Hospitalization Summary](https://public.tableau.com/views/COVID-19TableauVersion2/HospitalizationandEmergencyDepartment?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Fpublic.tableau.com%2F&%3Aembed_code_version=3&%3Atabs=no&%3Atoolbar=yes&%3Aanimate_transition=yes&%3Adisplay_static_image=no&%3Adisplay_spinner=no&%3Adisplay_overlay=yes&%3Adisplay_count=yes&%3AloadOrderID=0)
- [Dealth Summary](https://public.tableau.com/views/COVID-19TableauVersion2/DeathSummary?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Fpublic.tableau.com%2F&%3Aembed_code_version=3&%3Atabs=no&%3Atoolbar=yes&%3Aanimate_transition=yes&%3Adisplay_static_image=no&%3Adisplay_spinner=no&%3Adisplay_overlay=yes&%3Adisplay_count=yes&%3AloadOrderID=0)
- [Testing Rates](https://public.tableau.com/views/COVID-19TableauVersion2/TestingRatesbyCounty?%3Aembed=y&%3AshowVizHome=no&%3Ahost_url=https%3A%2F%2Fpublic.tableau.com%2F&%3Aembed_code_version=3&%3Atabs=no&%3Atoolbar=yes&%3Aanimate_transition=yes&%3Adisplay_static_image=no&%3Adisplay_spinner=no&%3Adisplay_overlay=yes&%3Adisplay_count=yes&%3AloadOrderID=0)

**Comment by maureenboycebyrne** [comment]
Raising this issue again - please update the source for Kansas data! https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas

**Comment by muamichali** [comment]
HI @maureenboycebyrne (and @MicaelaAyers and @alexander-eden ) 

Sorry for the delay in responding to you. 

We have been capturing screenshots of https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas since April 30. We also use it in our daily data entry shifts.
