### ISSUE TITLE
New link for Georgia data

### ISSUE THREAD

**Issue by jmbarry** [COVID19Tracking/issues#316]
The link  for Georgia data on your site is stale. 

This is the current link:
https://dph.georgia.gov/covid-19-daily-status-report

This is the stale link under "best current data source" for Geogia
https://dph.georgia.gov/georgia-department-public-health-covid-19-daily-status-report

**Comment by muamichali** [comment]
Thank you @jmbarry 

We updated our system and you can see the new link on the website and in the screenshots.
