### ISSUE TITLE
Revise TN negative number for 4/26

### ISSUE THREAD

**Issue by dpthurst** [COVID19Tracking/issues#319]
The 4/26 negative number for TN is the sum of negative tests for non-state labs and **total** tests for state labs. The correct number should be 137807 (adding negative tests for both places).

In addition, the internal screenshotting for the PDF files that Tennessee posts is not working. I thus cannot give screenshots, but there is an internal Slack thread.

**Comment by erfgottlieb** [comment]
Before: 
![Screen Shot 2020-05-21 at 10 34 40 AM](https://user-images.githubusercontent.com/64613495/82569878-d3b79680-9b4e-11ea-9299-01764f1f254d.png)
After:
![Screen Shot 2020-05-21 at 10 35 06 AM](https://user-images.githubusercontent.com/64613495/82569894-dca86800-9b4e-11ea-9c2f-76c914e0b901.png)
