### ISSUE TITLE
Error in Wisconsin data

### ISSUE THREAD

**Issue by brucerthompson** [COVID19Tracking/issues#321]
The cumulative value for Wisconsin tests is less on 3/30 than 3/29.

**Comment by brucerthompson** [comment]
But the error is still there. Wisconsin cannot give negative tests

**Comment by schmian** [comment]
Thank you for reaching out! The reason Wisconsin's total tests went down on March 30th is because Wisconsin revised down their negatives from 16550 to 15856.
