### ISSUE TITLE
URGENT: Very unusual jump in number of recovered patients on 4/28

### ISSUE THREAD

**Issue by ppasquar** [COVID19Tracking/issues#323]
Today (4/28), the national data release reported an increase in recovered patients by more than 40,000 units (from 94,745 to 139,299), after prior changes of no more than a few thousands.

This is either the result of data entry error or the result of a sudden update in the recoveries after days of stale information. Either way, can you please clarify, as this number is crucial to compute Active cases in any reasonable prediction model?

Thanks!

Paolo

**Comment by careeningspace** [comment]
Hello,

The jump in recoveries is from NY. We resolved how to calculate a base line from the data they have been releasing. Unfortunately they stopped publishing a specific number and it took a while to come up with a reasonable solution.

Thanks!

**Comment by ppasquar** [comment]
Thank you!

Will you implement your fix soon and retroactively? If not, I may have to
interpolate the data points.

Paolo

Paolo Pasquariello
Professor of Finance
Stephen M. Ross School of Business
University of Michigan
701 Tappan Street, room R4434
Ann Arbor, MI 48109-1234
email: ppasquar@umich.edu
phone: 734-764-9286

webpage: http://webuser.bus.umich.edu/ppasquar/
SSRN research page:
https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=250093
<http://ssrn.com/author=250093>
Google Scholar page:
https://scholar.google.com/citations?user=ByzWEGMAAAAJ&hl=en
LinkedIn profile: https://www.linkedin.com/in/paolo-pasquariello-376247/

**Comment by careeningspace** [comment]
Hello,

I have backfilled the calculated data for NY:

**Before**
![Screen Shot 2020-04-28 at 11 43 11 PM](https://user-images.githubusercontent.com/43073915/80559822-e2c28300-89ac-11ea-9549-c817772ca2fc.png)

**After**
![Screen Shot 2020-04-29 at 12 02 03 AM](https://user-images.githubusercontent.com/43073915/80559830-ea822780-89ac-11ea-8a17-1b7d09f590f8.png)

**Comment by ppasquar** [comment]
Thank you!

Paolo

Paolo Pasquariello
Professor of Finance
Stephen M. Ross School of Business
University of Michigan
701 Tappan Street, room R4434
Ann Arbor, MI 48109-1234
email: ppasquar@umich.edu
phone: 734-764-9286

webpage: http://webuser.bus.umich.edu/ppasquar/
SSRN research page:
https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=250093
<http://ssrn.com/author=250093>
Google Scholar page:
https://scholar.google.com/citations?user=ByzWEGMAAAAJ&hl=en
LinkedIn profile: https://www.linkedin.com/in/paolo-pasquariello-376247/
