### ISSUE TITLE
Virginia data inconsistent with files from Virginia Department of Health

### ISSUE THREAD

**Issue by astrowonk** [COVID19Tracking/issues#324]
The Virginia Department of Public Health has regularly [updated data files](https://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv) that are inconsistent with the daily totals posted here starting a week ago or so. See my comment and one more on #266 after it was closed.

I am also a little confused why timed screenshots of covidtracking.com are linked to as some sort of definitive historical record, rather than whatever state/government data source you are using to create the records here.

**Comment by femto113** [comment]
@astrowonk while the screenshots are hosted on covidtracking.com they are images of the original datasource.  In the case of Virginia that's https://www.vdh.virginia.gov/coronavirus/

**Comment by astrowonk** [comment]
Ah, thanks @femto113  - the screenshots were of some tableau dashboard I was unfamiliar with and not the VDH main web site. Still, screenshots can capture mistakes that were in place at the time. If a health authority is serving up their own machine-readable historic data, that's probably a better source of truth.

I do see that covidtracking's numbers are now consistent with VDH and the NYT for Virginia in late April so that's good! I'll close this.
