### ISSUE TITLE
PA deaths neagtive on 4/23

### ISSUE THREAD

**Issue by ryansarver** [COVID19Tracking/issues#325]
It appears total deaths goes down by over 200 on 4/23 for Pennsylvania.

**Comment by sgdoerfler** [comment]
The state revised their numbers. According to [Lehigh Valley Live](https://www.lehighvalleylive.com/coronavirus/2020/04/pa-coronavirus-update-new-cases-rise-but-death-toll-drops-heres-why-and-what-it-means-in-the-lehigh-valley-covid-19-case-map-42320.html) (and many other newspapers), reporting on April 23rd 2020:

> The unusual change in the Pennsylvania Department of Health’s daily report is due to its inclusion of probable cases in the death count earlier this week. Per CDC guidelines, those are instances where COVID-19 is listed as a cause or contributing factor in a death where the patients had not been tested, but did have symptoms and a connection to a confirmed case.
> 
> After adding probable cases to the death toll two days ago, Health Secretary Rachel Levine on Thursday said that a number of those deaths require more information before they can be linked with the pandemic virus. She said they were removed from the count in the interest of transparency, citing the difficulty epidemiologists have handling these thousands of cases.
> 
> That resulted in the statewide coronavirus death toll dropping by 201.
