### ISSUE TITLE
Navajo Nation and US Military

### ISSUE THREAD

**Issue by Josh0883123** [COVID19Tracking/issues#326]
Suprised this sight doesn't track these data points... considering there are sites out there that report these numbers daily.

Navajo Nation should certainly be tracked: https://www.ndoh.navajo-nsn.gov/COVID-19

US Military, the DoD provides daily updates: https://www.airforcemag.com/snapshot-dod-and-covid-19/

Also, Veterans Affairs also provides updates: https://www.accesstocare.va.gov/Healthcare/COVID19NationalSummary

These totals are not included in state totals... and account for 15,898 cases to date and 547 deaths.

If you wanted, you could also include Federal Prisons. https://www.bop.gov/coronavirus/

I know this is a state by state tracker but these people are Americans and they should be included in your numbers. At least the Navajo Nation should - as these numbers were removed from New Mexico's totals early on and given their own category.

**Comment by una-smith** [comment]
Navajo Nation cases and deaths are counted in the states and counties where the person was resident.  The Navajo Nation includes many thousands of persons not resident on Navajo Nation lands and all those lands are in counties of NM, AZ, or UT.

**Comment by muamichali** [comment]
Thanks for asking @Josh0883123 and thank you for weighing in @una-smith 

We have been in touch with Navajo Nation, DOD, and VA and they all report these numbers to the states. The states report that they include them in their counts.
