### ISSUE TITLE
WV has revised the total number of tests down on 4/28

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#327]
Historical data should be updated in our system 

https://dhhr.wv.gov/COVID-19/Pages/default.aspx

**Comment by goldfarb** [comment]
On 4/28, WV revised their _Total Number of Laboratory Results Reported to WVDHHR_ from 43,227 to 40,489.

To account, we've updated the total results, which then changed the calculated negative number.

Before:

![image](https://user-images.githubusercontent.com/3722037/80720144-80f83b00-8aca-11ea-801a-d24fb844edff.png)

From 4/28 

![image](https://user-images.githubusercontent.com/3722037/80720171-8b1a3980-8aca-11ea-9b4e-b23230faac4a.png)


From 4/29

![image](https://user-images.githubusercontent.com/3722037/80720194-93727480-8aca-11ea-9928-cd16fd88a7db.png)


After

![image](https://user-images.githubusercontent.com/3722037/80720208-98cfbf00-8aca-11ea-8772-49cf97d89012.png)

**Comment by goldfarb** [comment]
Returned the historical calculations, after WV update their total tests 4/30

![image](https://user-images.githubusercontent.com/3722037/80826866-f0485a80-8bb0-11ea-8cf0-3e7de391576e.png)

![image](https://user-images.githubusercontent.com/3722037/80826897-fe967680-8bb0-11ea-80b3-ce39bbc6ebbb.png)
