### ISSUE TITLE
Oregon Recoveries

### ISSUE THREAD

**Issue by joehud098** [COVID19Tracking/issues#329]
Oregon began tracking recoveries in their weekly report.  Comes out each Tuesday.  See link:
 
https://govsite-assets.s3.amazonaws.com/U2Ui9gUiSxG1oSnXa3hf_COVID-19-Weekly-Report-2020-04-28-FINAL.pdf

The latest data: 

Of the 2,253 surviving [Oregon] COVID-19 cases, 860 (38.2%) are considered recovered and 785 (34.8%) are not yet recovered.

**Comment by muamichali** [comment]
Thank you @joehud098 
We have added this information to the data we track
