### ISSUE TITLE
Error 404 when making HTTP GET request

### ISSUE THREAD

**Issue by brandoniceberg** [COVID19Tracking/issues#330]
I am getting a error code of 404 when making a HTTP GET request to the following API URLs:
- 'https://covidtracking.com/api/v1/us/current.json'
- 'https://covidtracking.com/api/v1/states/daily.json'

This has rendered my Android app in a unusable state :(
Any help/information is appreciated!

**Comment by kevee** [comment]
There was a short API outage, it has been fixed.
