### ISSUE TITLE
Georgia Historical Data Screenshots last 24 hours

### ISSUE THREAD

**Issue by danieljc010** [COVID19Tracking/issues#332]
For the last 24 hours or so clicking the timed screenshots to obtain the picture of Georgia DPH data that is used to make the Georgia historical data has been showing a screenshot that just reads "Access Denied" https://covidtracking.com/screenshots/GA/GA-20200427-180813.png

is there a way you can fix this? I'm a surgeon working at Grady Memorial Hospital in Atlanta and the proof being easily accessible alongside the real numbers is invaluable in a world of skeptical physicians. That exact page is really hard to find on their regular website and the graphs published by them appear to be intentionally misleading.

Thank you so much.

**Comment by muamichali** [comment]
Thank you for reporting this issue @danieljc010 

Our team was also experiencing intemittent issues accessing the URLs for GA yesterday, and unfortunately it seems the automated process was not able to grab any screenshots yesterday. Today things are working more smoothly on the GA websites and we are able to capture screenshots https://covid-data-archive.s3.us-east-2.amazonaws.com/state_screenshots/GA/GA-20200429-000809.png and https://covid-data-archive.s3.us-east-2.amazonaws.com/state_screenshots/GA/GA-secondary-20200429-060917.png correctly.

Those are capturing https://dph.georgia.gov/covid-19-daily-status-report and https://augustagis.maps.arcgis.com/apps/opsdashboard/index.html#/4eec20925b6b4f338368df0ffcba472d respectively. 

Thank you for the work you do.

**Comment by danieljc010** [comment]
Wow thank you SO much for this prompt response and assuring the problem is fixed. This is invaluable to us. Covidtracking is absolutely critical and having this historical data easily accessible is extremely clutch given that Georgia DPH is mucking with the graphs and updating them slowly in order to mislead even high level experts into thinking the numbers are trending down very nicely over the last 14 days. So thank you for the work YOU do. A bastion of sanity.
