### ISSUE TITLE
Indiana April 29th total deaths may be wrong

### ISSUE THREAD

**Issue by GitHubMJW** [COVID19Tracking/issues#335]
I think there may be a problem with Indiana's total-death count. The Indiana total deaths for April 29th shows 1065; an increase of 164 from the previous day. However, the screenshot shows 964 total deaths, with 63 new deaths. The current Indiana webpage shows the same values (at around 2:00 a.m. 4/30/2020 ET).

**Comment by muamichali** [comment]
HI @GitHubMJW 

Thanks for reporting this issue. It seems that there is an issue with the screenshots cutting off. If you visit Indiana's dashboard, and scroll down all the way, you will see the suspected deaths reported on the lower bottom corner of the screen. 

The CDC has issued a guidance on 4/14 that case counts and death counts include confirmed and probable cases [There is more information about the definitions of confirmed and suspected here ](https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html)
We are going to standardize this guideline across all the states that report both numbers. We are also tracking the number of confirmed cases and deaths and we will enahnce our reporting to expose those numbers on the website.

**Comment by GitHubMJW** [comment]
But how is that consistent with the previous day's count for Indiana, which clearly didn't include the probable deaths, since it agreed exactly with the confirmed deaths? If it was because the 29th was the first day you implemented a new method of counting, I think that should be noted somewhere. It's highly misleading to report 164 deaths occurred in one day, in a state that currently shows the maximum daily deaths as 44.

**Comment by schmian** [comment]
We understand your concerns and are in the process of capturing data in the backend that will make 'probable' and 'confirmed' deaths more transparent and consistent between states. We hope to publish this information in the near future
