### ISSUE TITLE
Hospitalization in Texas

### ISSUE THREAD

**Issue by philipus** [COVID19Tracking/issues#336]
Hospitalization for Texas is in the current status included but not in the time series

**Comment by muamichali** [comment]
Hi @philipus 
Thanks for writing to us. The state historical page only shows the cumulative hospitalized numbers, which we do not have for Texas. We are in the process of re-desiginging this page to expose more data on it. It should be live shortly. Until then, the information is available in the data API endpoint https://covidtracking.com/api/v1/states/TX/daily.json
