### ISSUE TITLE
WY data for 4/29 includes probable cases, while it didn't before

### ISSUE THREAD

**Issue by jinghao1994** [COVID19Tracking/issues#337]

**Comment by muamichali** [comment]
@jinghao1994 Thank you for writing about this.

The CDC has issued a guidance on 4/14 that case counts and death counts include confirmed and probable cases [There is more information about the definitions of confirmed and suspected here ](https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html)

We are going to standardize this guideline across all the states that report both numbers. We are also tracking the number of confirmed cases and deaths and we will enahnce our reporting to expose those numbers on the website.
