### ISSUE TITLE
Endpoints Chaning?

### ISSUE THREAD

**Issue by richarddowdy** [COVID19Tracking/issues#339]
4-29-20 @ 16:00
GET to **api/states** returned array of data objects for each state properly.

4-30-20 @ 00:10
CORS errors on GET request to **api/states** even though Insomnia request showed response header of " access-control-allow-origin: * ". Changed endpoint **api/states/current.json** which fetched proper data without errors.

4-30-20 @ 09:00
CORS errors on GET request to **api/states/current.json**. Changed it back to **api/states** and all data is fetched properly again.

**Comment by kevee** [comment]
Hi, Richard. We did have a little outage on Netlify and some routing issues yesterday into today with those legacy API paths. Our actual API endpoints start with `api/v1`, those endpoints you are referring to are deprecated. You can find a [list of all our supported endpoints on our website here](https://covidtracking.com/api/).

**Comment by muamichali** [comment]
Hi @richarddowdy 
Just wanted to give you a heads up on some changes that are coming soon from our web team (hi kevin!)

> We are now building the entire API to a repository. All the JSON/CSV files are built every 15 minutes and put into this repo. 
> https://github.com/COVID19Tracking/covid-public-api
> 
> We have a test version of the website available that exposes that repo at the same exact endpoints we have now.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api
> 
> There is a new status endpoint that gives info on when the data was last updated. There's also a run number that we can use to go back and download a snapshot of the API at that moment.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api/v1/status.json
> https://github.com/COVID19Tracking/covid-public-api-build/actions/runs/116895561
> 
> 
> I have reproduced the exact same file structure and format across the different endpoints. The only changes are some additional fields that were in current endpoints are now in every entry for US or states' daily data - for example, dataQualityGrade, There were also some odd time offsets in the old API for fields like dateModified that were presented as UTC, but were in fact not. So they are now UTC.
> Please take some time to test out the new API files and endpoint and give feedback. I hope to have this replace our production API build tool by the end of this week. Any feedback filed as an issue in this repo https://github.com/COVID19Tracking/covid-public-api-build would be helpful!
