### ISSUE TITLE
TN 4/30 data is repeated from 4/29

### ISSUE THREAD

**Issue by jfwiii** [COVID19Tracking/issues#340]
The new 4/30 data is available at [https://www.tn.gov/content/tn/health/cedep/ncov/data.html](url), and I have pasted a screenshot below.

![image](https://user-images.githubusercontent.com/64617606/80767971-23d6a680-8b17-11ea-9036-7f80ae377e57.png)

**Comment by jawiv** [comment]
The TN 4/30 update was captured in [the Covid Tracking Project's daily screenshot log](https://covidtracking.com/data/state/tennessee#historical). See image from 4/30 at 11:20pm:

![TN 4/30 @ 11:20pm](https://covidtracking.com/screenshots/TN/TN-20200501-002008.png)

**Comment by jawiv** [comment]
I submitted a pull request to the csv data file linked in the covid-tracking-data repository. It looks like Tennessee may have been late to update information at the same time the screenshot automation may have executed fewer times over the 4/28-4/30 time period.

**Comment by schmian** [comment]
Hi @jfwiii 
Thanks for reporting this issue. TN updated late that day so it missed our publication cut off. We are going to update the 4/30 data based on the [4/30 TN evening screenshot](https://covid-data-archive.s3.us-east-2.amazonaws.com/state_screenshots/TN/TN-20200501-002008.png). You should see the correct data reflected on the site shortly.

**Before**
![image](https://user-images.githubusercontent.com/22822706/81079080-0f9afc80-8ebd-11ea-81ff-884b637eb8b7.png)

**After**
![image](https://user-images.githubusercontent.com/22822706/81079269-5ab50f80-8ebd-11ea-82f0-013e3c2ec718.png)
