### ISSUE TITLE
No update for Texas data on 4/30

### ISSUE THREAD

**Issue by johndhancock** [COVID19Tracking/issues#342]
Looks like the Texas data didn't update with figures from 4/30 as of 10 p.m. CST, though Texas Department of Health and Human Services' dashboard has updated.

**Comment by muamichali** [comment]
Thanks for letting us know @johndhancock 

We publish the daily numbers around 4pm EST. It seems Texas did not update its main dashboard in time for us to catch the update. We will be updating the numbers today.

**Comment by johndhancock** [comment]
Saw that the update happened today, but wondering if there's any chance April 30's data will be back-filled? As it is now, April 30s and May 1s updates all rolled into May 1, giving an inaccurate view of the daily totals for May 1.
