### ISSUE TITLE
JHU Comparison Runs / Conflation?

### ISSUE THREAD

**Issue by mezcalhead** [COVID19Tracking/issues#343]
Hi all, I run [covid-19-tools](https://github.com/mezcalhead/covid-19-tools) which is more of a python library for working with covid-data in object oriented structures.  It does a good job of processing JHU's data as well.  One of the things we can do quickly is run the state-by-state comparison, just after midnight EST.

In the following, the first number is JHU's state death count (summed up from the county level).  The second number is the death count from Covid19Tracking's JSON API.  Third number is the delta.  As you can see there are some very good perfect matches here, but NY is obscenely off (JHU problem).

I'm willing to look at calibrating the models a little bit. In fact, calibrating the JHU county level data to the Covid19Tracking because if we're interested in the best possible data, we ought to be synthesizing as many sources as possible.

```
AK,9,9,0
AL,272,269,3
AR,61,61,0
AZ,320,320,0
CA,2031,1982,49
CO,777,766,11
CT,2257,2257,0
DC,224,224,0
DE,152,152,0
FL,1268,1290,-22
GA,1132,1120,12
HI,16,16,0
IA,162,162,0
ID,60,60,0
IL,2355,2355,0
IN,1114,1114,0
KS,134,129,5
KY,240,235,5
LA,1905,1862,43
MA,3562,3562,0
MD,1140,1140,0
ME,53,53,0
MI,3789,3789,0
MN,343,343,0
MO,350,329,21
MS,261,261,0
MT,16,16,0
NC,406,378,28
ND,19,19,0
NE,70,68,2
NH,72,66,6
NJ,7228,7228,0
NM,123,112,11
NV,243,237,6
NY,23587,18321,5266
OH,976,975,1
OK,222,222,0
OR,103,103,0
PA,2475,2292,183
RI,266,266,0
SC,244,244,0
SD,17,17,0
TN,199,195,4
TX,812,732,80
UT,46,46,0
VA,552,552,0
VT,49,49,0
WA,814,801,13
WI,316,316,0
WV,41,41,0
WY,7,7,0
PR,92,92,0
AS,0,0,0
GU,5,5,0
MP,2,2,0
VI,4,4,0

```

**Comment by qpmnguyen** [comment]
Thank you for your input @mezcalhead! The difference in NY can be attributed to the differences between how NYC and NY state reports data. Please refer to issue #331 for a more detailed explanation.
