### ISSUE TITLE
Single state query not working?

### ISSUE THREAD

**Issue by edurxxx** [COVID19Tracking/issues#344]
Requesting https://covidtracking.com/api/v1/states/daily.json?state=MT returns date for all states instead of just Montana and requesting https://covidtracking.com/api/states?state=MT redirects to https://covidtracking.com/api/v1/states/PA/current.json?state=PA instead of Montana

**Comment by kevee** [comment]
The format for individual state requests is:

https://covidtracking.com/api/v1/states/mt/daily.json
