### ISSUE TITLE
api/v1/us/daily.csv "hospitalized" / "hospitalizedIncrease" numbers seem way high

### ISSUE THREAD

**Issue by ffrehner** [COVID19Tracking/issues#345]
The most-recent data update appears to have inflated numbers for these two columns: 

![image](https://user-images.githubusercontent.com/64551166/80848262-8a1b0200-8bc7-11ea-95d5-b88f6eb24e44.png)

**Comment by muamichali** [comment]
Thanks so much for reporting this inconsistency. We are going to look into the root cause of this

**Comment by muamichali** [comment]
Hi @ffrehner 

it looks like the reason for this sudden jump is that the[ state of CT reported its cumulative hospitalizations for the first time](https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary4302020.pdf?la=en). The number was 7758 so it caused the overall number to look very high. Presumably most of the hospitalizations did not happen that date. 

If we can get from CT historical cumulative hospitalizations numbers, we will be able to adjust our previous numbers and smooth out this jump. We can only track numbers reported by the states.
