### ISSUE TITLE
Add hospitalized to website and API

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/issues#35]
We now track this value in the sheet for States and US current, and will add it to States and US daily after the 4 pm push today. We should expose this value on our website and in our API!

**Comment by webmasterkai** [comment]
This will be live when the caches on the various edge servers expires https://covidtracking.com/api/states will begin showing `hospitalized`.

**Comment by hammer** [comment]
Please don’t close until we’ve added this field to the daily counts too.

**Comment by schwartzadev** [comment]
I can tackle this one

**Comment by webmasterkai** [comment]
If it's in the sheet, it's in the API. There is a cache that will have to expire, but it's there. It's working.
