### ISSUE TITLE
[MS - Mississippi] Update "current hospitalized" for 5/2 datapoint 

### ISSUE THREAD

**Issue by camille-le** [COVID19Tracking/issues#350]
Hello, requesting an update for "Currently Hospitalized" for Mississippi for 5/2.  

CURRENTLY: 
* For 5/2, we recorded 424+28 = 452 for Currently Hospitalized. 

REQUESTED CHANGE: 
* Based on the time series below, this should be changed from 452 to 632 (424+208) for 5/2. 

![currHosp_05-02](https://user-images.githubusercontent.com/31285549/80926081-afd01480-8d49-11ea-9b70-3e29646b8fce.png)
[Source](https://msdh.ms.gov/msdhsite/_static/14,21994,420,873.html)

Please note, MS's data is reported from the previous day. So for 5/2, this would reflect data from 5/1. This is why the chart shows the data for 5/1. 

[From the MS page](https://msdh.ms.gov/msdhsite/_static/14,0,420.html): 
_This map and the following table show total cases in Mississippi as of 6 p.m. May 2, 2020, and include all reported cases since March 11, 2020._

Thank you!
Camille

**Comment by muamichali** [comment]
Hi Camille!
I am updating this right now. 

**BEFORE**
![Screenshot_2020-05-03 Coronavirus numbers by state (CovidTracking, DEV COPY)(2)](https://user-images.githubusercontent.com/1749380/80926440-4eb63a00-8d65-11ea-976d-3b6764622824.png)

**AFTER**
![Screenshot_2020-05-03 Coronavirus numbers by state (CovidTracking, DEV COPY)(3)](https://user-images.githubusercontent.com/1749380/80926438-4e1da380-8d65-11ea-916c-135e31b3eb3e.png)
