### ISSUE TITLE
[VA historical data] Using "Unique people tested" instead of "Total people tested" for negative calculations

### ISSUE THREAD

**Issue by quangnguyen1995** [COVID19Tracking/issues#351]
As per conversation today at the publish shift, yesterday's negative numbers do not fit our definition of "Negatives (people and cases)" as the "Total people tested" was used (due to confusing language). The new procedure now uses "Unique people tested" instead. 

Previous number: 
VA [Negatives] : 95471 (=112450 - 16979)

Should be:
VA[Negatives] : 84365 (=101344 - 16979)

**Comment by muamichali** [comment]
Hi @quangnguyen1995 
I updated the data. Please double check. Thanks :)

![Screenshot_2020-05-04 Coronavirus numbers by state (CovidTracking, DEV COPY)(1)](https://user-images.githubusercontent.com/1749380/80983444-8d4a0400-8dfa-11ea-9585-331d3efc6e4a.png)

![Screenshot_2020-05-04 Coronavirus numbers by state (CovidTracking, DEV COPY)](https://user-images.githubusercontent.com/1749380/80983446-8d4a0400-8dfa-11ea-8a3a-6d579f6174d5.png)
