### ISSUE TITLE
CDC Has Slashed COVID-19 Deaths by 40%

### ISSUE THREAD

**Issue by JustOneGuyHere** [COVID19Tracking/issues#352]
I suggest publishing both sets of numbers. I have used this site to track the numbers, but they need to be accurate.

https://www.cdc.gov/nchs/nvss/vsrr/covid19/index.htm

**Comment by muamichali** [comment]
Hi @JustOneGuyHere 

Please see the CDC Data tracker here https://www.cdc.gov/covid-data-tracker/index.html

Currently 65,735 deaths are reported on the page.

**Comment by JustOneGuyHere** [comment]
Thanks, censor.
