### ISSUE TITLE
Wrote a Medium article based on your data

### ISSUE THREAD

**Issue by tirthajyoti** [COVID19Tracking/issues#353]
Hi,

Just wanted to leave a shout-out for the amazing job you guys are doing. I wrote a Medium article, creating some custom visualization functions, based on your data.

Here is the article: **_[Data exploration with the COVID-tracking Project](https://towardsdatascience.com/data-exploration-with-the-covid-tracking-project-d89ac87342bc)_**.

Take a look if you get a chance.

**Comment by quangnguyen1995** [comment]
Thank you very much for the shoutout. We've shared this article internally within our team and everyone enjoyed it!
