### ISSUE TITLE
Proposal: Add stale bot to this issue queue

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/issues#354]
Because the large number of issues, may I propose adding Stalebot to this issue tracker? We could then:

Flag issues with *no* activity for X days with a "stale" label
If an issue with "stale" is inactive for X days more, it is closed
You can add a label like "not stale" to make sure the bot doesn't touch it.

**Comment by muamichali** [comment]
Thanks for the suggestion! I know that @jdmaresco has been thinking of improvments to our flow here. If he is ok with this suggestion based on his thoughts, I am good. I have been organizing all the issues in https://github.com/COVID19Tracking/issues/projects/2 and chipping away at the backlog.

**Comment by kevee** [comment]
He approved, I'll do a PR.
