### ISSUE TITLE
new Florida site available that adds Non-Resident data to Resident data

### ISSUE THREAD

**Issue by jamesmentz** [COVID19Tracking/issues#358]
Florida is currently only showing Resident data instead of data from both Residents and Non-Residents. The latter is now available.

[2] should redirect to get data from [3] instead of [4]. Then
A. Residents and non-residents could be included and
B. Florida would become "Machine Readable" -- the scorecard is showing this is not currently machine readble and this site is via a straightforward html scrape.

According to [1] "We attempt to report numbers that reflect individuals who are isolated and recovering in the state. Most states report this number, but due to cruise ship quarantines and other movements of individuals, some states (like Florida and Montana) report several categories of confirmed cases." The non-Resident category should be added to the Resident category, and this data is now available.

[1] https://covidtracking.com/about-data/faq#are-you-accounting-for-only-residents
[2] https://covidtracking.com/data/state/florida
[3] https://floridahealthcovid19.gov/
[4] https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429/

**Comment by olivierlacan** [comment]
We're aware of this. This data has been available for a few months now. 

We track numbers for both residents and non-residents in Florida via the source data used to power https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429/. But our notes could be clearer on https://covidtracking.com/data/state/florida. 

We aggregate the data sources (ArcGIS feature layers) used for the FDOH dashboard via a project I created: http://o-vid.herokuapp.com/florida (source here: https://github.com/olivierlacan/ovid). 

We need to move this project under the umbrella of COVID19Tracking but I haven't had time to do that yet. 

Feel free to review the sources listed in: https://github.com/olivierlacan/ovid/blob/96c86506b440f6bb765e293ec841f4ee072fde67/states/florida.rb#L16-L30
