### ISSUE TITLE
Important measure is missing

### ISSUE THREAD

**Issue by Stoiko-A** [COVID19Tracking/issues#364]
Hello,

It shouldn't be hard to add the following measurement:
corona deaths / 1M population
This measurement will show completely different global picture on the pandemic.
With this measure correlation with http://www.bcgatlas.org/ would be complete.
For example Ecuador posses highest death rate in South America and it is the only country without BCG in this continent.

Thanks.

**Comment by Stoiko-A** [comment]
Case fatality ration is not good measurement because it depends on tests conducted.

**Comment by Stoiko-A** [comment]
data sample as of today:

Belgium | 684 |   | Europe
-- | -- | -- | --
Andorra | 582 |   | Europe
Spain | 544 |   | Europe
Italy | 481 |   | Europe
UK | 423 |   | Europe
France | 386 |   | Europe
Sint   Maarten | 303 |   | North   America
Netherlands | 297 |   | Europe
Sweden | 274 |   | Europe
Isle of   Man | 270 |   | Europe
Ireland | 267 |   | Europe
Channel   Islands | 236 |   | Europe
USA | 211 |   | North   America
Switzerland | 206 |   | Europe
Montserrat | 200 |   | North   America
Luxembourg | 153 |   | Europe
Bermuda | 112 |   | North   America
Portugal | 104 |   | Europe
Monaco | 102 |   | Europe
Canada | 102 |   | North   America
Ecuador | 89 |   | South   America
Denmark | 85 |   | Europe
Germany | 83 |   | Europe
Saint   Martin | 78 |   | North   America
Iran | 75 |   | Asia
Austria | 67 |   | Europe
Panama | 47 |   | North   America
Slovenia | 47 |   | Europe
Finland | 43 |   | Europe
Romania | 43 |   | Europe
Turkey | 41 |   | Asia
Peru | 41 |   | South   America
Estonia | 41 |   | Europe
North   Macedonia | 41 |   | Europe
Norway | 39 |   | Europe
Hungary | 38 |   | Europe
Martinique | 37 |   | North   America
Brazil | 35 |   | South   America
Moldova | 33 |   | Europe
British   Virgin Islands | 33 |   | North   America
World | 32.4 |   | All
Dominican   Republic | 32 |   | North   America
Antigua   and Barbuda | 31 |   | North   America
Guadeloupe | 30 |   | North   America
Iceland | 29 |   | Europe
Bahamas | 28 |   | North   America
Israel | 27 |   | Asia
Liechtenstein | 26 |   | Europe
Turks   and Caicos | 26 |   | North   America
Czechia | 24 |   | Europe
Bosnia   and Herzegovina | 24 |   | Europe
Barbados | 24 |   | North   America
Serbia | 23 |   | Europe
Mayotte | 22 |   | Africa
Aruba | 19 |   | North   America
Croatia | 19 |   | Europe
Poland | 18 |   | Europe
Mexico | 18 |   | North   America
Lithuania | 17 |   | Europe
Cayman   Islands | 15 |   | North   America
UAE | 14 |   | Asia
Chile | 14 |   | South   America
Greece | 14 |   | Europe
Sao   Tome and Principe | 14 |   | Africa
Armenia | 13 |   | Asia
Montenegro | 13 |   | Europe
Cyprus | 12 |   | Asia
Belarus | 11 |   | Europe
Albania | 11 |   | Europe
Bulgaria | 11 |   | Europe
Guyana | 11 |   | South   America
Algeria | 11 |   | Africa
Russia | 10 |   | Europe
Kuwait | 9 |   | Asia
Malta | 9 |   | Europe
Latvia | 9 |   | Europe
Mauritius | 8 |   | Africa
Honduras | 8 |   | North   America
Ukraine | 7 |   | Europe
Colombia | 7 |   | South   America
Bolivia | 7 |   | South   America
Cuba | 6 |   | North   America
Argentina | 6 |   | South   America
Curaçao | 6 |   | North   America
Philippines | 6 |   | Asia
Trinidad   and Tobago | 6 |   | North   America
Bahrain | 5 |   | Asia
Saudi   Arabia | 5 |   | Asia
Slovakia | 5 |   | Europe
S.   Korea | 5 |   | Asia
Uruguay | 5 |   | South   America
Morocco | 5 |   | Africa
Belize | 5 |   | North   America
Qatar | 4 |   | Asia
Cabo   Verde | 4 |   | Africa
New   Zealand | 4 |   | Australia/Oceania
Australia | 4 |   | Australia/Oceania
Japan | 4 |   | Asia
Lebanon | 4 |   | Asia
Tunisia | 4 |   | Africa
Egypt | 4 |   | Africa
Liberia | 4 |   | Africa
Singapore | 3 |   | Asia
French   Guiana | 3 |   | South   America
Malaysia | 3 |   | Asia
Azerbaijan | 3 |   | Asia
Gabon | 3 |   | Africa
Jamaica | 3 |   | North   America
China | 3 |   | Asia
Indonesia | 3 |   | Asia
Djibouti | 2 |   | Africa
Maldives | 2 |   | Asia
Oman | 2 |   | Asia
Brunei | 2 |   | Asia
Equatorial   Guinea | 2 |   | Africa
Kazakhstan | 2 |   | Asia
Georgia | 2 |   | Asia
Kyrgyzstan | 2 |   | Asia
South   Africa | 2 |   | Africa
Pakistan | 2 |   | Asia
El   Salvador | 2 |   | North   America
Cameroon | 2 |   | Africa
Afghanistan | 2 |   | Asia
Iraq | 2 |   | Asia
Somalia | 2 |   | Africa
Congo | 2 |   | Africa
Burkina   Faso | 2 |   | Africa
Niger | 2 |   | Africa
Suriname | 2 |   | South   America
Costa   Rica | 1 |   | North   America
Bangladesh | 1 |   | Asia
Paraguay | 1 |   | South   America
Guatemala | 1 |   | North   America
India | 1 |   | Asia
Mali | 1 |   | Africa
Sierra   Leone | 1 |   | Africa
Togo | 1 |   | Africa
Haiti | 1 |   | North   America
Eswatini | 0.9 |   | Africa
Jordan | 0.9 |   | Asia
Sudan | 0.9 |   | Africa
Thailand | 0.8 |   | Asia
Nicaragua | 0.8 |   | North   America
Guinea | 0.7 |   | Africa
Ghana | 0.6 |   | Africa
Senegal | 0.6 |   | Africa
Ivory   Coast | 0.6 |   | Africa
Chad | 0.6 |   | Africa
Guinea-Bissau | 0.5 |   | Africa
Hong   Kong | 0.5 |   | Asia
Nigeria | 0.5 |   | Africa
Palestine | 0.4 |   | Asia
Sri Lanka | 0.4 |   | Asia
Venezuela | 0.4 |   | South   America
Botswana | 0.4 |   | Africa
Kenya | 0.4 |   | Africa
Libya | 0.4 |   | Africa
DRC | 0.4 |   | Africa
Gambia | 0.4 |   | Africa
Uzbekistan | 0.3 |   | Asia
Tajikistan | 0.3 |   | Asia
Taiwan | 0.3 |   | Asia
Tanzania | 0.3 |   | Africa
Zimbabwe | 0.3 |   | Africa
Benin | 0.2 |   | Africa
Zambia | 0.2 |   | Africa
Syria | 0.2 |   | Asia
Malawi | 0.2 |   | Africa
Mauritania | 0.2 |   | Africa
Myanmar | 0.1 |   | Asia
Burundi | 0.08 |   | Africa
Yemen | 0.07 |   | Asia
Angola | 0.06 |   | Africa
Ethiopia | 0.03 |   |

**Comment by Stoiko-A** [comment]
![bcg2](https://user-images.githubusercontent.com/64833920/81070235-9e267280-8eeb-11ea-903e-366449e1b581.jpg)

**Comment by muamichali** [comment]
Hi @Stoiko-A 
Thank you for the suggestion and for showing these visualizations. We are working on adding this data to our website.

**Comment by Stoiko-A** [comment]
Hello, when this will be available?
