### ISSUE TITLE
WI hospitalization data is inconsistent

### ISSUE THREAD

**Issue by witj** [COVID19Tracking/issues#365]
![image](https://user-images.githubusercontent.com/64861442/81097662-d15a0900-8ecd-11ea-8817-5b5dab69494d.png)

On April 28 the number of current hospitalizations went up by 207 from 336 to 544, but the cumulative hospitalizations only went up 41.  See attached image.

Something doesn't add up.

**Comment by erfgottlieb** [comment]
Thanks for this @witj 
As of 4/27, WI started reporting people tested. Our Currently Hospitalized number reflects total COVID patients plus inpatients w. COVID tests pending. The Cumulative Hospitalized number is taken from https://www.dhs.wisconsin.gov/outbreaks/index.htm and only reflects confirmed hospitalized COVID patients.
