### ISSUE TITLE
FL Data Inconsistent With State Data

### ISSUE THREAD

**Issue by rgurnitz** [COVID19Tracking/issues#366]
From the Governor's Conference of today:

**_May 4th represented the best testing for Florida since   the start of the pandemic.
--
Florida received 23,884 test results, which   yielded only 589 new Florida cases
and the lowest statewide positivity rate –   2.61% - on record for new cases._**

For May 4th, you show about 7,000 less in terms of test results.  Can you comment on the gap?

Thank you.

Bob

**Comment by erfgottlieb** [comment]
Thanks @rgurnitz. We take our testing data from the FL department of health dashboard:
https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429/
Lots of states say the lag on total tests reported can be > 72hrs. So, the total test number might not have been updated on the dashboard by our publish time on 5/4. Our Positive and Negative test numbers for 5/4 our consistent with archived screenshots from that day: https://covid-data-archive.s3.us-east-2.amazonaws.com/state_screenshots/FL/FL-secondary-20200504-180746.png
