### ISSUE TITLE
API Changed

### ISSUE THREAD

**Issue by john2014** [COVID19Tracking/issues#367]
Two new columns were added to the csv file below (dataQualityGrade and lastUpdateEt):

https://covidtracking.com/api/v1/states/daily.csv

These two new columns did not exist in csv file before. Is this the new format or is this a bug?

**Comment by muamichali** [comment]
Hi @john2014 

Thanks for asking. We added these two data points yesterday. 
Please see https://covidtracking.com/api

**Comment by muamichali** [comment]
Hi @john2014 
Wanted to give you this update from our web team

> 
> We are now building the entire API to a repository. All the JSON/CSV files are built every 15 minutes and put into this repo. 
> https://github.com/COVID19Tracking/covid-public-api
> 
> We have a test version of the website available that exposes that repo at the same exact endpoints we have now.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api
> 
> There is a new status endpoint that gives info on when the data was last updated. There's also a run number that we can use to go back and download a snapshot of the API at that moment.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api/v1/status.json
> https://github.com/COVID19Tracking/covid-public-api-build/actions/runs/116895561
> 
> 
> I have reproduced the exact same file structure and format across the different endpoints. The only changes are some additional fields that were in current endpoints are now in every entry for US or states' daily data - for example, dataQualityGrade, There were also some odd time offsets in the old API for fields like dateModified that were presented as UTC, but were in fact not. So they are now UTC.
> Please take some time to test out the new API files and endpoint and give feedback. I hope to have this replace our production API build tool by the end of this week. Any feedback filed as an issue in this repo https://github.com/COVID19Tracking/covid-public-api-build would be helpful!
