### ISSUE TITLE
why change the columns?

### ISSUE THREAD

**Issue by sdangt** [COVID19Tracking/issues#369]
I appreciate what you guys are doing.

I will just note that I think it's helpful once you have columns established to leave them where they are.

I think next time I may choose a different data source, because I've run into a time-wasters.

First, and least troublesome, the time series are in backwards order, so have to be reversed for charting.  Secondly the dates are not readable by Excel (have to be parsed even though Excel can read a wide variety of standard date formats).  And as I [mentioned before](https://github.com/COVID19Tracking/issues/issues/210), data for hospitalizedCurrently and hospitalizedCumulative were for awhile swapped (now are switched back), so Currently was larger than Cumulative.

But this is maybe the biggest glitch.  I don't see why once you have a data file going, you need to change the columns.  Yesterday the file reads into Excel with Column O being "death", and today it reads in with that column being "hash".

That's the [state data](https://covidtracking.com/api/v1/states/daily.csv) from [the API](https://covidtracking.com/api).

And the [US data](https://covidtracking.com/api/v1/us/daily.csv) file still has "death" in Column O, so now the two files are inconsistent with each other.

It's both easier and faster computationally to just read Column O rather than to actually search for specific text, and usually that works.  In this case, it's obvious enough that the hash is not even a number no less the number of deaths.  But were it a different column with similar-type numbers, say "recovered" then it would be harder to notice right away.

Column Q used to be "total" -- tests -- so that's at least an integer so would plug into analysis and produce wrong results.

The "total" column header name also indicates another little glitch, which is that they are not descriptive.  Why have a column titled "total"?  Total what?  The "positive" and "negative" columns are at the beginning of the spreadsheet and it's not clear that they are what would be totaled there.  The total column isn't even entirely necessary.  Presumably anyone who is analyzing this data is able to add two columns, although this does save some computation time.

The column-swapping though means that as with the date we have to do this the hard way, make sure that you haven't moved things around.  However, even if you have, you might put the data in the wrong column as with the hospitalized before.

I have VBA automatically reverse the time series order when I paste it, but in general, it's easier to work with time series data that is in incremental order.  It's possible to overcome any hurdles.  It just sort of wastes time and risks unnecessary glitches.

So you are springing a few unnecessary traps for people here, I think.

I'm not sure why "death" is all the way over in Column O (now Column Q) anyway.  This is probably the single-most-important statistic.  But once it's there, maybe just leave it there -- and certainly don't push it even farther away from the first column.

Anyway, good job overall with all of the tracking.  I think this is very important.  And all things considered I think the glitches have been minimal.

Dan

**Comment by muamichali** [comment]
Hi @sdangt 

We appreciate your feedback. I am sorry that the change created issues for your implementation and I am glad you were able to catch it quickly. We wanted to provide the information about the `as of` timestamp and the state grade which were requested by some users. 

We are discussing how to communicate these kinds of changes better in the future in addition to the doucmented API on the website https://covidtracking.com/api

**Comment by sdangt** [comment]
Thanks for your reply.  I did alter the way I use the data, just to double-check that the column is right, but I think that could throw some people.  Good job overall.  Dan

**Comment by muamichali** [comment]
Hi @sdangt,

Wanted to give you a heads up on this from our webteam

> We are now building the entire API to a repository. All the JSON/CSV files are built every 15 minutes and put into this repo. 
> https://github.com/COVID19Tracking/covid-public-api
> 
> We have a test version of the website available that exposes that repo at the same exact endpoints we have now.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api
> 
> There is a new status endpoint that gives info on when the data was last updated. There's also a run number that we can use to go back and download a snapshot of the API at that moment.
> https://5ece700c83e8e9b0cd122372--upbeat-lovelace-3e9fff.netlify.app/api/v1/status.json
> https://github.com/COVID19Tracking/covid-public-api-build/actions/runs/116895561
> 
> 
> I have reproduced the exact same file structure and format across the different endpoints. The only changes are some additional fields that were in current endpoints are now in every entry for US or states' daily data - for example, dataQualityGrade, There were also some odd time offsets in the old API for fields like dateModified that were presented as UTC, but were in fact not. So they are now UTC.
> Please take some time to test out the new API files and endpoint and give feedback. I hope to have this replace our production API build tool by the end of this week. Any feedback filed as an issue in this repo would be helpful!

**Comment by sdangt** [comment]
Thanks, and you have made a great effort in tackling a tough set of data.  You all have made a noteworthy contribution to our store of knowledge, and I do appreciate it.

**Comment by sdangt** [comment]
Well, you changed the columns around now for the other data -- https://covidtracking.com/api/v1/us/daily.csv at https://covidtracking.com/api -- which in my view is unnecessary and only results in people who have created charts tied to specific columns having to redo them.

What's the reasoning for changing the columns around as you add data to the same dataset?  Is there a good justification for it?  Because it just means I have to do more work to use your data.  If there's no good reason for it, then why do it?  But I've already stated my opinion on it, and I guess someone disagrees.

I do appreciate the data you provide, and you provide a valuable resource, but as I said, I might have used a different source if I had to do it all over again.  Obviously if I were to start out from scratch, I would assume that you move your columns around when you please, and so not assume they are fixed, but I didn't know that in the beginning.  I automated it for the other column in the other data, but didn't change this one.

In Excel for example it is significantly more work to create a chart if you cannot assume that the data is going to be in the same place every time.  It means using some rather ugly formulas and extra processing time.

But I just don't see the point in changing the columns around.  If you remove one, perhaps just don't add data to that column going forward, or indicate in its name that it's inactive.

Just my opinion.  Thanks for listening.

**Comment by sdangt** [comment]
You changed the columns yet again.

https://covidtracking.com/api/v1/states/daily.csv

It seems to me just an unnecessary inconvenience for data-users.  Just leave the columns alone until the end.  Why keep moving them around?

Anyway, I don't get the sense that you are interested in my input, since you keep doing this and haven't provided any explanation as to why it's necessary to do it.

So this will probably be my last comment.  Thanks anyway for your contribution to COVID-19 knowledge.
