### ISSUE TITLE
MI: save screenshots for top-level page

### ISSUE THREAD

**Issue by timeFractal** [COVID19Tracking/issues#37]
Hi, presently I'm only seeing screenshots for dashboard. I explained the difference btw the two in the last comment in #29. since site updates only post at 2p, I would say the 5a screenshot is not needed. Also, on a few occasions, the website doesn't update till after 2p (but 6p and 11p should be sufficiently time-buffered for update latency). 

why this matters: I have noticed a day where the daily reported new cases (top page) is greater than the difference btw dashboard from day before and day of. each table respectively does add up correctly. I have reached out to state officials for further clarification to account for either lack or abundance of cases.

I would like top-level page cached for future usage in case mistakes like this occur again in the future.

note: both pages Are updated at the same time. this would be a correction for your footnote for MI.

**Comment by joshuaellinger** [comment]
I'm trying to understand the issue.  

Julia archives specific states.  Here is MI: http://covid-data-archive.s3-website.us-east-2.amazonaws.com/state_screenshots/MI.

Did you want an additional page capture for MI (which we can do)?  Or an alternative time for everything (which we can do)?  Or are you looking at a completely different set of pages (so it is not a task for us)?

**Comment by timeFractal** [comment]
I am asking screenshots for

https://www.michigan.gov/coronavirus (not saved)

to be taken in addition to

https://www.michigan.gov/coronavirus/0,9753,7-406-98163-520743--,00.html (saved)

the mentioning of time is if it would make you guy's lives easier, the 5am capture isn't needed bc MI only updates once / day.

and also to update the footnote regarding the two sites being out of date, they aren't. I believe that's a misunderstanding. I explained why the two pages differ in #29 .

**Comment by muamichali** [comment]
We are currently capturing two URLs for MI 

https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html 
and 
https://www.michigan.gov/coronavirus/0,9753,7-406-98159-523641--,00.html

You can see them at
http://covid-tracking-project-data.s3-website.us-east-1.amazonaws.com/state_screenshots/MI/

I hope this is sufficient to close this issue
