### ISSUE TITLE
Should Georgia still be graded with an A?

### ISSUE THREAD

**Issue by merepinto** [COVID19Tracking/issues#370]
Georgia recently changed the way they were reporting confirmed cases - they are now retroactively adding cases to the "date of symptom onset" or the "date the test was taken" if date of symptom onset is not available.  They say on the website that this means that within a 14-day window the case count may not be correct since they are continuing to add cases as their results come in (which is understandable and I like the transparency).  

However, they are still showing current numbers on their "COVID-19 cases over time" chart, which means that to a lay audience it looks like Georgia's cases have decreased RAPIDLY within the last two weeks - which may not be the case. Considering all of these factors, I wanted to see if Georgia's data quality should still be an A?

**Comment by quangnguyen1995** [comment]
Thank you for your comment! We've passed the issue to the states grade team.
