### ISSUE TITLE
Ga total test number not unique tests - includes retesting

### ISSUE THREAD

**Issue by tracyterrill** [COVID19Tracking/issues#371]
so it’s not an accurate representation of total people tested. As far as I can tell the confirmed case number represents  unique cases and not simply  all tests that came back positive.

![3DB95047-7885-4BE9-999A-B15070585554](https://user-images.githubusercontent.com/64918328/81205549-dc2da000-8f98-11ea-853f-80f05f556757.png)

**Comment by quangnguyen1995** [comment]
Thank you very much for letting us know! We are aware of the differences between total tests and unique people tested and are currently working internally to improve the reporting process given this information.

**Comment by tracyterrill** [comment]
Thx. Ga DPH recently redesigned the dashboard in a way that seems to be misleading. Thanks for all the work you guys are doing.!!-----Original Message-----
