### ISSUE TITLE
CA daily Deaths data not correct since 4/26. How do we get the corrected data?

### ISSUE THREAD

**Issue by grant-renier** [COVID19Tracking/issues#373]
CA daily Deaths data not correct since 4/26. How do we get the corrected data?
2020/04/26 00:00:00,8187,59,8187
2020/04/27 00:00:00,7276,7276,7276
2020/04/28 00:00:00,3126,3126,3126
2020/04/29 00:00:00,1332,1332,1332
2020/04/30 00:00:00,3333,3333,3333
2020/05/01 00:00:00,7450,7450,7450
2020/05/02 00:00:00,2170,2170,2170
2020/05/03 00:00:00,2870,2870,2870
2020/05/04 00:00:00,3175,3175,3175
2020/05/05 00:00:00,95,-95,-95

**Comment by schmian** [comment]
Hi @grant-renier,

Thanks for reaching out about this! California's dashboard is not always up to date so we also pull data from the [CDPH News Releases](https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx) which often provide more recent data.
