### ISSUE TITLE
New Jersey 5/6 Testing numbers seem innacurate

### ISSUE THREAD

**Issue by jaketk33** [COVID19Tracking/issues#374]
It shows 1,297 new tests on 5/6, down from over 10,000 on 5/5, and goes alongside 1297 new cases. This seems...very wrong

**Comment by karaschechtman** [comment]
Hi @jaketk33,

Thank you for flagging this. It appears that [on 5/6](https://covidtracking.com/screenshots/NJ/NJ-20200507-001735.png), the negative count decreased from 157,030 to 154,686. As a result, we carried the negative value from 5/5, as we do not record data that results in a decrease in negatives over time. This makes it appear as if all new tests are all positive on 3/28. 

We reverted to using the NJ data [on 5/7 ](https://covidtracking.com/screenshots/NJ/NJ-20200507-181600.png)when NJ reported an increase in negatives to 159,023.
