### ISSUE TITLE
NY death counts using city or state data?

### ISSUE THREAD

**Issue by caspiegel** [COVID19Tracking/issues#376]
I have been tracking data using the Johns Hopkins data set for some time. The total deaths being reported through that source on 2020-05-05 is 25,124. Your data set is reporting 19,877 for the same date. Recognizing that the two sources might be somewhat different, that is still quite off. I looked through the data and found that the New York, New York data (excluding other cities and counties) in the JH dataset shows 19,067. This is the closest number I can find. I am therefore wondering if the data you are using is only for New York City proper and not accounting for the entire state?

Your test positives certainly match the JH dataset confirmed cases, so that is good, but still wondering why deaths are so different.

**Comment by muamichali** [comment]
Hi @caspiegel 

Thanks for writing 
Please see this issue for the explanation: https://github.com/COVID19Tracking/issues/issues/331
