### ISSUE TITLE
New York Data 

### ISSUE THREAD

**Issue by Hel-chick** [COVID19Tracking/issues#379]
The New York data shows no new tests on May 06, the positive tests remained at 321,192. However, on the link on the New York page for the New York data from the New York Dept. of Public Health says that on May 06 the positive tests total rose to 323,978.

**Comment by muamichali** [comment]
Hi @Hel-chick 

Thank you for writing. 

We publish the data around 4pm daily. At the time we published, NY had not yet provided the updated numbers of positives/tests. We are going to update the numbers NY is now showing (which reflect tests as of 5/5) and they will get published with our daily publish shift this afternoon.
