### ISSUE TITLE
New York data for may 6 is missing new numbers

### ISSUE THREAD

**Issue by hackerlikecomputer** [COVID19Tracking/issues#380]
Currently shows 321,192 — the same exact number as yesterday. [The actual number is 323,978.](https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Map?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n)

**Comment by muamichali** [comment]
Thanks for writing @hackerlikecomputer . I just answered about[ this in this issue ](https://github.com/COVID19Tracking/issues/issues/379)--> closing this one.

**Comment by hackerlikecomputer** [comment]
thanks!
