### ISSUE TITLE
Changes in cases 2 weeks after opening state

### ISSUE THREAD

**Issue by Rojoster** [COVID19Tracking/issues#384]
Is it possible start with the number of reported cases the day a state opens and then track that for the next 2-3 weeks?  We all believe we will see a rise.  Having it represented graphically would add clarity to what is happening.  Probably need to add testing with it as that plays an important role in the number of cases reported.  Thank you.

**Comment by muamichali** [comment]
Hi @Rojoster 

Thank you for this feature suggestion. We are working on updating the information on the website and will definitely look into whether this can be incorporated.
