### ISSUE TITLE
Same data for PosNeg and totalTestResults?

### ISSUE THREAD

**Issue by thehammah** [COVID19Tracking/issues#385]
These two data elements seem to have identical data?  Is that by design?  What was the reason if any?

Wendy Weissman

**Comment by muamichali** [comment]
Hi @thehammah 

Thanks for writing about this. This duplicate reporting is on our radar.

You can[ follow this issue on our website repo](https://github.com/COVID19Tracking/website/issues/774) to be updated when this is resolved.
