### ISSUE TITLE
MO Total Tests is a day behind

### ISSUE THREAD

**Issue by JonRyanL** [COVID19Tracking/issues#386]
I've been tracking the Missouri data for two weeks now and recently the total tests have been a day behind. The Health Department updates the total positives around 2 PM, but the total gets updated around 5 PM (Central). I think the problem was they never updated total deaths for 5/2, but since then:
5/3 was 91083
5/4 was 100747
5/6 was 103622
They just updated 5/7 to 108721

Your data has gotten me incredibly interested in the numbers and how they track, thanks!

**Comment by qpmnguyen** [comment]
Thank you for your input @JonRyanL! MO updated its total tests after our publish time cutoff. If a state updates the number of tests or cases after that time, we catch that update on the following day. So far, the historicals we keep seem to agree with this pattern. We're working internally to best represent this data as well as shifting our time to catch states that update only slightly after our publish time.
