### ISSUE TITLE
New York - revised deaths

### ISSUE THREAD

**Issue by datadict** [COVID19Tracking/issues#388]
All,

I noted the recent jump in New York deaths that is higher than the number Cuomo gives at the press conference (e.g. for 5th to 7th 230, 232, 231).

Where do these additional deaths come from? And is it possible to allocate these deaths to exact dates, so that it is consistent and growth rates can still be calculated?

**Comment by muamichali** [comment]
Hi @datadict 

Thanks for contacting us. The numbers come from https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Fatalities?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n. They are a result of a data reconciliation effort by the state. 

> The 5/6 numbers displayed are a result of a comprehensive accounting of current and retrospective data, provided by facilities. This data captures COVID-19 confirmed and COVID-19 presumed deaths within nursing homes and adult care facilities. This data does not reflect COVID-19 confirmed or COVID-19 presumed positive deaths that occurred outside of the facility. Retrospective data reporting dates back to March 1, 2020.

![Screenshot_2020-05-08 Workbook NYS-COVID19-Tracker](https://user-images.githubusercontent.com/1749380/81401590-a7872900-90fd-11ea-8967-f2263bb3346c.png)

[The state has provided more information here](https://www.health.ny.gov/statistics/diseases/covid-19/fatalities_nursing_home_acf.pdf), but there is no daily breakdown and we are not sure if it will be provided in the future.
