### ISSUE TITLE
Chart of % positives on Intro page does not track data

### ISSUE THREAD

**Issue by mjbevier** [COVID19Tracking/issues#389]
The chart showing daily new tests and positives, as well as the 7-day running average is inconsistent with the national totals data.

**Comment by muamichali** [comment]
Hi @mjbevier 

I am not exactly sure what chart you are asking about. Perhaps it was already removed from the site?

If you are asking about this image https://covidtracking.com/static/55d468ec2af9325aa9844f8c3aa7dda8/f3583/john-hopkins-chart.png it is a static image that reflected a point in time, not a dynamic chart.

 I am closing the ticket for now but please re-open with clarifications if I misunderstood your question.

**Comment by mjbevier** [comment]
Michael,

 

Thanks for looking at this. I probably should have realized it was static. I continue to use your data daily and appreciate the care you seem to take with it. Given the recent revelations that the CDC as well as some states have been including antibody as well as diagnostic tests, without distinction, in their testing data you might wish to include on your site a prominent announcement that COVID Tracking does not do this (or so I assume).

 

Mike

 

Michael BeVier

Phone:  434-979-1189
