### ISSUE TITLE
Recovery Cumulative & Daily Increases

### ISSUE THREAD

**Issue by jiecai1997** [COVID19Tracking/issues#391]
Hi, thanks so much for making this open source API! Could you clarify whether the _recovery_ column is cumulative? Could you also make a _recoveryIncrease_ field for daily recovery increases (like you did for the other metrics)? Thanks

**Comment by quangnguyen1995** [comment]
Thank you for your input @jiecai1997! Yes, our recovery column is indeed cumulative. I have passed your suggestion of a *recoveryIncrease* column to the data team.
