### ISSUE TITLE
County level data

### ISSUE THREAD

**Issue by thoo** [COVID19Tracking/issues#392]
First of all, thank you for all the hard work you all are doing. 
 Is there any plan to add the county level data? Since now each state has its plan to reopen , the county level data (positive tests, negative tests ) for each state is more important than ever. Without vaccines, the county level data could play an important role.

**Comment by quangnguyen1995** [comment]
Thank you for your input @thoo! Unfortunately, we do not have county-level data at this point. We will make an announcement should we pivot to reporting such data.
