### ISSUE TITLE
Why totalTestResultsIncrease can be minus

### ISSUE THREAD

**Issue by MCPRLab** [COVID19Tracking/issues#393]
My understanding is that  totalTestResults are cumulative. So totalTestResultsIncrease can't be minus

**Comment by quangnguyen1995** [comment]
Thank you very much for your input @MCPRLab! Unfortunately, we only report what we can from the states as per our principles [here](https://covidtracking.com/about-data/faq). This means that when the state performs a massive data revision or changing reporting standards, our data will be affected. If you have any specific entries you want to be investigated, please let us know here.

**Comment by qpmnguyen** [comment]
I'm going to close this issue for now but feel free to reopen if you have further questions.
