### ISSUE TITLE
MN NHPI Data is way off

### ISSUE THREAD

**Issue by ChadBrock** [COVID19Tracking/issues#397]
On the race dashboard Minnesota is currently being shown with 4,289 positive cases attributed to HNPI people, though there are only 42 HNPI cases listed on the Race Data spreadsheet.

**Comment by goldfarb** [comment]
Thank you @ChadBrock - it looks like there was a miscalculation which read a percentage as a full number for the May 3rd data capture.

We've updated the historical data.
