### ISSUE TITLE
IN: rebuild urlwatch on EC2 to deploy custom JSON filter

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/issues#4]
> IN: Ken Riley setup a custom JSON filter (for ARCGIS embed) which should work, but need to get urlwatch re-built on the EC2 box before we can deploy the filter. if Zach Lipton can assist here, that’d be great (not sure how he is building the forked version of urlwatch on the box).

(Quoting @Joshua Ellinger)

**Comment by joshuaellinger** [comment]
Is this still open?

**Comment by lucasgonze** [comment]
@joshuaellinger my work has migrated away from code towards product, so I am not the right person to own this.
