### ISSUE TITLE
Incorrect Massachusetts negative number published on 3/23

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#40]
A math error resulted in an incorrect number for negative results in Massachusetts 

Original
![image](https://user-images.githubusercontent.com/1327983/77340687-0cc8bb80-6d04-11ea-8e1a-1d135062571b.png)

Adjusted
![image](https://user-images.githubusercontent.com/1327983/77340746-20742200-6d04-11ea-9879-46b42157f824.png)

Also made adjustment on the daily snapshot:
![image](https://user-images.githubusercontent.com/1327983/77340828-3a156980-6d04-11ea-9dae-e4c085b4fe37.png)

**Comment by careeningspace** [comment]
I cleaned up the totals on the Daily Tab:
![Screen Shot 2020-03-25 at 9 58 19 AM](https://user-images.githubusercontent.com/43073915/77544349-470a9800-6e7f-11ea-9885-62740d9f4bb1.png)

and the Checks tab:
![Screen Shot 2020-03-25 at 9 58 43 AM](https://user-images.githubusercontent.com/43073915/77544366-4d007900-6e7f-11ea-8800-d69f39844bfe.png)
