### ISSUE TITLE
Georgia ‘A’ grade should be revisited. They recently changed reporting methodology to deceive public

### ISSUE THREAD

**Issue by lkhemani** [COVID19Tracking/issues#400]
Please reconsider your grade A rating for Georgia. At the end of April, they changed their reporting, and it is now very deceptive. They’ve started reporting cases as the date where patient exhibited symptoms OR the date they first requested medical care OR the date of the test...so that past totals are constantly changing and the curve always appears to be going down. This is ridiculous. It would make sense if they always reported on one of the three dates, but they’ve created a chaotic arrangement of data where past numbers are constantly in flux and it’s nearly impossible to track.

**Comment by lkhemani** [comment]
articles referencing confusion:

https://www.ajc.com/news/state--regional-govt--politics/confused-and-scared-georgians-frustrated-over-shifting-virus-data/k9oUbZDE3z6iyouWQBF7gJ/

https://www.ajc.com/news/state--regional-govt--politics/new-changes-state-virus-data-confuse-experts-residents-alike/T6EbPkqGJt1RhK3qtYp6hL/

**Comment by qpmnguyen** [comment]
Thank you very much for your input @lkhemani! We've passed our concerns to our States Grades team

**Comment by lkhemani** [comment]
I see this was closed and their grade was update to A+. This was done even though Ga has made an apology for heir inaccurate data. They are now in the national news today along with FL, for misleading data.

Even after their apology, Georgia is still misrepresenting their COVID data to deceive us into thinking the curve is going down. Look at your screen shots from May 3 vs okay. Evaluate their number of new cases for May 2nd on each of those dates. On May , their reported # of cases on May 2nd was only 13 and the 7-day moving average was 316.6. However, if you look at May 2nd on the same chart today from Georgia dept of public health, the number of new cases on May 2nd was actually 333 and the 7-day moving average was actually 669.85. They have been forced to now say *pending on their daily numbers because they were caught, but the visual still inaccurately reflects that the curve is constantly dropping.

I hope you will reconsider your A+ grade!
