### ISSUE TITLE
New York Death number from May 6th to May 7th has to be wrong

### ISSUE THREAD

**Issue by ecksteini** [COVID19Tracking/issues#404]
New York Death number from May 6th to May 7th has to be wrong. It is a jump up by 400%. See below
289, May 1st
299, May 2nd
280, May 3rd
226, May 4th
230, May 5th
232, May 6th
951, May 7th => can not be!
217, May 8th
226, May 9th
207, May 10th

**Comment by muamichali** [comment]
On 5/7 NY reported 941 deaths, most of which were newly confirmed, but did not occur in the last 24 hours. 
https://riverheadlocal.com/2020/05/07/suffolks-coronavirus-death-toll-leaps-by-227-new-york-states-by-952/
