### ISSUE TITLE
incorrect data in current.json

### ISSUE THREAD

**Issue by ExperimentalHypothesis** [COVID19Tracking/issues#407]
this is the result of current.json

```
[{'positive': 1322807,
  'negative': 7664717,
  'pending': 3095,
  'hospitalizedCurrently': 44943,
  'hospitalizedCumulative': 144780,
  'inIcuCurrently': 11393,
  'inIcuCumulative': 6445,
  'onVentilatorCurrently': 6395,
  'onVentilatorCumulative': 547,
  'recovered': 216169,
  'hash': 'd3b82b6b23fe73c384e58d789fb768498ef68b2f',
  'lastModified': '2020-05-11T13:14:49.280Z',
  'death': 74270,
  'hospitalized': 144780,
  'total': 8990619,
  'totalTestResults': 8987524,
  'posNeg': 8987524,
  'notes': 'NOTE: "total", "posNeg", "hospitalized" will be removed in the future.'}]
```

are you sure that the cummulative data are less then the current?

```
  'inIcuCurrently': 11393,
  'inIcuCumulative': 6445,
  'onVentilatorCurrently': 6395,
  'onVentilatorCumulative': 547
```

shouldnt it be vice verca?

**Comment by goldfarb** [comment]
@ExperimentalHypothesis Thank you for checking. Because there are sparse data provided about hospitalizations (including ICU and Ventilator reporting), we cannot reliably calculate it in states that only report current statistics. So while perhaps counterintuitive, the sources for cumulative often lag the sources for current. Please see the disclaimer on [our data page](https://covidtracking.com/data)

> States are currently reporting two fundamentally unlike statistics: current hospital/ICU admissions and cumulative hospitalizations/ICU admissions. Across the country, this reporting is also sparse. In short: it is impossible to assemble anything resembling the real statistics for hospitalizations, ICU admissions, or ventilator usage across the United States. As a result, we will no longer provide national-level summary hospitalizations, ICU admissions, or ventilator usage statistics on our site.
> 
> We will continue tracking these numbers on a state-by-state basis, but it does not feel responsible to continue to display these US-wide statistics for a general audience. These heavily caveated numbers will remain in the API for advanced data user
