### ISSUE TITLE
Michigan Testing in the UP Increased Dramatically Even Though % Positive is < 4%

### ISSUE THREAD

**Issue by MichiganObserver** [COVID19Tracking/issues#408]
On Friday and Saturday Michigan tested 2,368 individuals in the UP with only 4 positive results.  Prior to Thursday, Michigan had been averaging less than 100 tests per day in the UP with minimal positive results.  Why the huge ramp up in testing there, especially when down state there remains complaints that testing is hampered by a lacking of testing supplies.  Why not shift some of those tests to areas of the state with higher % Positive and in need of testing supplies?

**Comment by schmian** [comment]
Hi @MichiganObserver - thanks for reaching out! If you have suggestions regarding state testing, we recommend that you reach out to that state to communicate your concerns and ask any questions you may have.
