### ISSUE TITLE
May 3 Kentucky data discrepancy

### ISSUE THREAD

**Issue by ctp-support** [COVID19Tracking/issues#410]
reported by Twitter user @vslyke18 via DM

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_23uoh)

**Comment by jdmaresco** [comment]
note from twitter DM: Thanks for this invaluable service! I think your data may be messed up for May 3 in Kentucky - it currently shows no new cases or tests. However the screenshots show that there was a change that day.

**Comment by goldfarb** [comment]
Thank you for passing that along, @jdmaresco 

Checking the snapshots, and the state's history, and it looks like KY updates once every weekend, so there's been a day with zero updates reported either on Saturday or Sunday of most weeks.
