### ISSUE TITLE
Kansas Data Incorrect since May 7th

### ISSUE THREAD

**Issue by dger90** [COVID19Tracking/issues#411]
On May 7th, KDHE started to include Probable Cases in their Case total. These are individuals that were not tested. You can figure out how many people tested positive and the testing totals by reading the PDF document under the "Daily Case Summary & Historical Data" subheading, the most recent one located here: https://www.coronavirus.kdheks.gov/DocumentCenter/View/1125/Historical---May-6?bidId=

Total tests for 5/11/2012 should be 53,913.

**Comment by schmian** [comment]
Thanks for pointing up toward this document. As more states began reporting total people tested we have begun collecting this data but have not posted it yet since not all states are providing this information. We hope to report a more detailed breakdown of state testing in the near future.
