### ISSUE TITLE
Feature Request - Can we add a column for case fatality rates (CFR) to the breakdown grid?

### ISSUE THREAD

**Issue by jklaus** [COVID19Tracking/issues#412]
Can we add a column for case fatality rates (CFR) to the breakdown grid?  It'd be interesting to be able to compare the CFRs among states and countries as things open back up, and also to compare northern and southern areas - without having to crunch the numbers manually every time.

**Comment by jklaus** [comment]
I would probably have the unit be percent, with an accuracy of hundredths.

**Comment by muamichali** [comment]
Thank you for the suggestion @jklaus 
We will pass it on to the editorial team.

**Comment by jklaus** [comment]
@muamichali - could you possibly send me a link to the work item associated with it so I can track, ,and possibly contribute toward, it.

**Comment by muamichali** [comment]
Hi @jklaus 

Thanks so much. 

The suggestion will need to be considered and prioritized by the editorial team before a work item is created. Our website repo is a good place to monitor for issues that are looking for helpers.  https://github.com/COVID19Tracking/website/issues
