### ISSUE TITLE
MN "recovered" numbers include deaths

### ISSUE THREAD

**Issue by dpthurst** [COVID19Tracking/issues#414]
Under "patients no longer needing isolation" Minnesota reports a number that includes deaths, which we have been reporting as recovered. Those historical numbers should be deleted.
![mn-isolation](https://user-images.githubusercontent.com/13771964/81748373-c37d2880-9477-11ea-9a0a-ab0cbcd4be73.png)

**Comment by schmian** [comment]
It looks like before 5/13 "Patients no longer needing isolation" included cumulative deaths (patients and non-patients". We've corrected Recovered for dates before 5/13.
**Before**
![image](https://user-images.githubusercontent.com/22822706/81942915-bf145500-95c8-11ea-8043-49d22c9c2cbb.png)
**After**
![image](https://user-images.githubusercontent.com/22822706/81943334-3ba73380-95c9-11ea-8cd5-8baf5373ad9b.png)
**Calculations**
![image](https://user-images.githubusercontent.com/22822706/81943396-524d8a80-95c9-11ea-96d1-08ccf16cae38.png)
