### ISSUE TITLE
No update for Texas May 12

### ISSUE THREAD

**Issue by johndhancock** [COVID19Tracking/issues#415]
Looks like the Texas Department of State Health Services had another day where they updated later than usual today (around 5 p.m.), missing COVID19Tracking's update window. This happened a couple of weeks ago, so you all may already be aware of the missed update today, but wanted to raise a flag just in case.

**Comment by mathcoder3141** [comment]
Oh cool, somebody already opened the issue. I took the liberty to take the screenshot of the stats for May 12. It looks like where y'all extract the data from.
![image](https://user-images.githubusercontent.com/22652147/81775140-cdbc1880-94b1-11ea-9a30-1d1fcf08d229.png)

**Comment by egribbin** [comment]
Yep, this resulted in erroneous data for 5/12 and 5/13.

**Comment by kevinp2** [comment]
It looks like correct numbers should be:

5/12: 538172 - 525697 = 12,475 new tests
5/13: 587431 - 538172 = 49,259 new tests

**Comment by goldfarb** [comment]
Thank you @kevinp2 @egribbin @mathcoder3141 @johndhancock 

As noted above, the later on 5/12 update gave new positive, total, recovered, and fatalities numbers.

From 

![image](https://user-images.githubusercontent.com/3722037/81941114-6479f980-95c6-11ea-9c68-cfdb0009565c.png)

Before:

![image](https://user-images.githubusercontent.com/3722037/81941160-70fe5200-95c6-11ea-97ac-7d23ffcbd191.png)


After:

![image](https://user-images.githubusercontent.com/3722037/81941185-78256000-95c6-11ea-998c-f44c77c51075.png)

**Comment by kevinp2** [comment]
Thanks for the quick fix, @goldfarb :-)

A question:  Do you recommend obtaining the current spreadsheet from GitHub or from the web site?  I am currently obtaining current.csv from here: https://covidtracking.com/api

I notice that there is also a GitHub counterpart: states_current.csv in https://github.com/COVID19Tracking/covid-tracking-data/tree/master/data
