### ISSUE TITLE
New Delaware Data with 'In ICU' > 'Hospitalization

### ISSUE THREAD

**Issue by BrettBoval** [COVID19Tracking/issues#416]
Reposting this over here. https://github.com/COVID19Tracking/covid-tracking-data/issues/66.

**Comment by BrettBoval** [comment]
Here's an example of a snapshot where that change was incorporated.
https://github.com/COVID19Tracking/covid-tracking-data/commit/5ec9962d5f5f6505bb0593df150ab62867af98f7

**Comment by BrettBoval** [comment]
![image](https://user-images.githubusercontent.com/20585842/81862532-b6ffdb00-951e-11ea-8f54-cb6e9360af5c.png)

**Comment by muamichali** [comment]
I answered in #420
