### ISSUE TITLE
Data Quality issue - headings incorrect on US daily 4pm ET tab

### ISSUE THREAD

**Issue by ggrowe** [COVID19Tracking/issues#417]
From an external source submitted to the Support Desk:
The dataset https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml# 
![image001](https://user-images.githubusercontent.com/65028546/81864965-2e833980-9522-11ea-9525-2f7e384796e8.png)
the headings for “in ICU currently” and “In ICU Cumulative” and ditto the “On Ventilator” headings seem to be the wrong way around (they need to be swapped)

Sincerely, GG from the Support Desk

**Comment by muamichali** [comment]
The headings are not reversed. There is sparse data provided about cumulative hospitalizations, and we cannot reliably calculate it in states that only report current statistics. 
See the disclaimer on [our data page](https://covidtracking.com/data)

> States are currently reporting two fundamentally unlike statistics: current hospital/ICU admissions and cumulative hospitalizations/ICU admissions. Across the country, this reporting is also sparse. In short: it is impossible to assemble anything resembling the real statistics for hospitalizations, ICU admissions, or ventilator usage across the United States. As a result, we will no longer provide national-level summary hospitalizations, ICU admissions, or ventilator usage statistics on our site.
> 
> We will continue tracking these numbers on a state-by-state basis, but it does not feel responsible to continue to display these US-wide statistics for a general audience. These heavily caveated numbers will remain in the API for advanced data user

**Comment by ggrowe** [comment]
Thank you!!!  Appreciate your attention to this and responding!  I sent your detailed response to the external user.
