### ISSUE TITLE
Data Quality - WV cumulative positive tests does not match value on DHHR

### ISSUE THREAD

**Issue by ggrowe** [COVID19Tracking/issues#419]
From the external support message:
...there also seem to be discrepancies concerning cumulative positive tests. When I compare the amount of change between your totals for 5/11 and 5/12, I get 5 cases. But when I hover over the "Cumulative Number of Laboratory Confirmed Cases" on the DHHR site, the "cases" number for 5/12 (which I take to be "new cases being reported as of 5/12) is 14. 

Note from GG on the support team:
This is a bit too deep in the weeds for me, can you help explain?  Thx!

**Comment by muamichali** [comment]
Hi GG,

This is a publishing time issue. The numbers of cases that we report in WV 
![Screenshot_2020-05-14 West Virginia](https://user-images.githubusercontent.com/1749380/81946708-b2463000-95cd-11ea-8dc6-a451f958ccef.png) match the number of positive cases that the state reported around 4pm EST.

https://covidtracking.com/screenshots/WV/WV-20200511-122437.png

https://covidtracking.com/screenshots/WV/WV-20200512-124717.png
