### ISSUE TITLE
Large Change in Delaware ICU Data ('In ICU' > 'Hospitalized')

### ISSUE THREAD

**Issue by BrettBoval** [COVID19Tracking/issues#420]
![image](https://user-images.githubusercontent.com/20585842/81859834-b5341880-951a-11ea-8d75-468f85adf291.png)

Our staged build of Covid Act Now is showing a major shift because of this. Where's this number coming from?

**Comment by muamichali** [comment]
Hi @BrettBoval 
Thanks so much for letting us know about this anomaly. It seems that a number reported in a FL press release mistakenly made it into the DE record. We are correcting this now, and you should see the update in the afternoon after we publish our data. 
**BEFORE**
![Screenshot_2020-05-14 Coronavirus numbers by state (CovidTracking, DEV COPY)(1)](https://user-images.githubusercontent.com/1749380/81942726-7f4d6d80-95c8-11ea-9c39-b1ee109c49e3.png)

**AFTER**
![Screenshot_2020-05-14 Coronavirus numbers by state (CovidTracking, DEV COPY)(2)](https://user-images.githubusercontent.com/1749380/81942766-8bd1c600-95c8-11ea-935c-52050bce2fed.png)
