### ISSUE TITLE
Showing Invalid Date Time in the date column

### ISSUE THREAD

**Issue by mayaeb** [COVID19Tracking/issues#422]
We've gotten a few reports of this error over the past few days (for DE, NY, and CA, specifically)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_23xn5)

**Comment by muamichali** [comment]
I am not seeing it @mayaeb can you please paste a screenshot?

**Comment by kevee** [comment]
Closed in https://github.com/COVID19Tracking/website/pull/874
