### ISSUE TITLE
CO Total Tests Dropped on 5/12

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#423]
"I think there's an issue with Colorado 5-12-20 info. It indicated that there was "-133" new tests, which makes no sense."

Based on the screenshots form 5/11 it appears that Positive Cases should have be 19,703 instead of 19,899, causing the there to be negative new test and cases on 5/12 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_23xqp)

**Comment by muamichali** [comment]
The higher numbers entered on 5/11 came from a press release but they never showed up on the dashboard. I am revising 5/11 CO numbers to the dashboard. 

See https://covid-tracking.slack.com/archives/C0116LT5CTT/p1590073899348700

**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/82672837-e396af80-9c0e-11ea-90a7-3fd4b69f069b.png)

**AFTER** 
![image](https://user-images.githubusercontent.com/1749380/82673215-7d5e5c80-9c0f-11ea-95cf-face669f2fc9.png)

**Comment by muamichali** [comment]
Hi @the-daniel-lin oops - I did not see this --- will work now (or get @space-buzzer to do it lol)

**Comment by the-daniel-lin** [comment]
Issue being resolved here: https://github.com/COVID19Tracking/issues/issues/797

**Comment by the-daniel-lin** [comment]
I mentioned the wrong issue... This is being resolved here: https://github.com/COVID19Tracking/issues/issues/812
