### ISSUE TITLE
api/v1/states/current NJ deaths are way high

### ISSUE THREAD

**Issue by ffrehner** [COVID19Tracking/issues#426]
The most-recent data update appears to an incorrect (high) death count for NJ...
![image](https://user-images.githubusercontent.com/64551166/82131664-6b526900-978c-11ea-869f-0bfbdfda9a16.png)

**Comment by qpmnguyen** [comment]
Hi @ffrehner! It was a mistake by entry today and we have fixed it on our API. If you retrieve the data now it should be fixed. 
[Our public spreadsheet](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml) have reflected this change
