### ISSUE TITLE
AK 4/13 - Incorrect data - Negative new tests and total negatives

### ISSUE THREAD

**Issue by scarson** [COVID19Tracking/issues#428]
The state must have adjusted the values down that day.
Cannot have negative 208 new tests or a decrease in total negatives.

The [official state records](https://coronavirus-response-alaska-dhss.hub.arcgis.com/datasets/covid-tests-dataset) show 67 new tests on the day that the state reached 277 cumulative positives. This number was added to the previous day's total and the negatives were calculated from that.
AK official state data as of 5/17 pulled into Excel sheet for easy comparison:
https://drive.google.com/file/d/1OU65DQDNgsglxK38SIL0uu4OaDBSTGqf/view?usp=sharing

Change:
- New Tests = 67
- Negative = 7828.

@thaynedye
@dcmoyer

**Comment by jaclyde** [comment]
Negatives were removed in [this issue](https://github.com/COVID19Tracking/issues/issues/1082).
