### ISSUE TITLE
CA 3/11 - 3/17 - Data doesn't match CA official press releases/screenshots

### ISSUE THREAD

**Issue by scarson** [COVID19Tracking/issues#431]
Quite a few issues here.

Because the screenshots are inconsistent, I reference the current official [CA press release archive](https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx) instead.

[March 12 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR-019.aspx) "As of March 13, 2020, 8 a.m. PDT" (Taking early morning report as for previous day).
**3/12 should have 198 Positives instead of 202.**

[March 13 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-022.aspx) "As of March 14, 2020, 8 a.m. PDT" (Taking early morning report as for previous day).
**3/13 should have 288 Positives instead of 202.**
**3/13 should have 5 Deaths instead of 4.** 

[March 14 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-023.aspx) "As of March 14, 2020, 6 p.m. PDT"
**3/14 should have 335 Positives instead of 252.**
**3/14 should have 6 Deaths instead of 5.** 

[March 15 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-024.aspx) "As of March 15, 2020, 6 p.m. PDT"
**3/15 should have 392 Positives instead of 252.**
**3/15 should have 6 Deaths instead of 5.** 

[March 16 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-025.aspx) "As of March 16, 2020, 6 p.m. PDT"
**3/16 should have 472 Positives instead of 335.**
**3/16 should have 11 Deaths instead of 6.** 

[March 17 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-026.aspx) "As of March 17, 2020, 6 p.m. PDT"
**3/17 should have 598 Positives instead of 438.**
**3/17 should have 13 Deaths instead of 11.** 

Starting March 18th California started reporting test data in their press releases, so I'm going to open a separate issue that picks up there.

It makes sense to use official state reported confirmed case and death numbers for a date when those are higher than current CTP reported values. It is unlikely the state is making up higher positive case and death counts.

Note 1: Original source for CTP deaths appears to be the [L.A. Times Data Desk CA state totals](https://github.com/datadesk/california-coronavirus-data/blob/master/latimes-state-totals.csv).

Note 2:
[March 17 6:00 pm](https://covidtracking.com/screenshots/CA/CA-20200317-180052.png) screenshot is bad (image says "Sorry, something went wrong") and should be removed.
[March 18 7:01 pm](https://covidtracking.com/screenshots/CA/CA-20200318-140251.png) screenshot is bad (image says "Sorry, something went wrong") and should be removed.

@thaynedye
@dcmoyer

**Comment by karaschechtman** [comment]
Hi @scarson,
Thank you for bringing this to our attention. For those dates, we do not use the press releases to get case information, but the CA COVID homepage (see [this screenshot](https://covidtracking.com/screenshots/CA/CA-20200316-105418.png) for an example). The press releases for CA seem to have come out later than we would check the website, explaining why the numbers are different than ours on these early days. We publish the daily stats every afternoon. If a state updates the number of tests or cases after that time, we catch that update on the following day. You can check the exact time we looked at the CA website in the "lastUpdateET" field of the API.
I hope this is helpful!
