### ISSUE TITLE
CA 3/18 - 3/31 - Data doesn't match CA official press releases 

### ISSUE THREAD

**Issue by scarson** [COVID19Tracking/issues#432]
Quite a few issues here. Some typos in data entry and a running off-by-a-day issue.

Because the screenshots are inconsistent, I reference the current official [CA press release archive](https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx) instead.

California started reporting total and pending test numbers on March 18th, so I'm including those here too. The CTP March CA numbers have "N/A" values for Pending through 3/23. It's unclear where some of the earlier Total test numbers come from.

[March 18 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-027.aspx) "As of March 18, 2020, 6 p.m. PDT"
**3/18 should have 675 Positives instead of 611.**
**3/18 should have 16 Deaths instead of 13.** 
**3/18 should have 6,300 Total [Tests] instead of 8,592.** 
**3/18 should have 10,000 Pending [Tests] instead of N/A.** 
"At least 6,300 results have been received and another 10,000+ are pending."

[March 19 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-028.aspx) "As of March 19, 2020, 6 p.m. PDT"
**3/19 should have 1,006 Positives instead of 924.**
**3/19 should have 19 Deaths instead of `18.** 
**3/19 should have 11,487 Total [Tests] instead of 9,711.** This is currently an off-by-one for the 20th.
**3/19 should have 11,700 Pending [Tests] instead of N/A.** 

[March 20 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-029.aspx) "As of March 20, 2020, 6 p.m. PDT"
**3/20 should have 1,224 Positives instead of 1,063.**
**3/20 should have 23 Deaths instead of 20.** 
**3/20 should have 12,528 Total [Tests] instead of 9,711.** This is currently an off-by-one for the 21st.
**3/20 should have 12,700 Pending [Tests] instead of N/A.** 

**Note: CA daily reporting cutoff moves up four hours from 6 p.m. to 2 p.m. PDT between 3/20 and 3/21. 

[March 21 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-030.aspx) "As of March 21, 2020, 2 p.m. PDT"
**3/21 should have 1,468 Positives instead of 1,279.**
**3/21 should have 27 Deaths instead of 24.** 
**3/21 should have 13,467 Total [Tests] instead of 12,528.** This is currently an off-by-one for the 22nd.
**3/21 should have 12,700 Pending [Tests] instead of N/A.** 

[March 22 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-031.aspx) "As of March 22, 2020, 2 p.m. PDT"
**3/22 should have 1,733 Positives instead of 1,536.**
**3/22 correctly lists deaths at 27.** 
**3/22 should have 14,317 Total [Tests] instead of 12,840.** This is currently an off-by-one for the 23rd.
**3/22 should have 12,100 Pending [Tests] instead of N/A.** 

[March 23 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-032.aspx) "As of March 23, 2020, 2 p.m. PDT" This is currently an off-by-one for the 24th.
**3/23 should have 2,102 Positives instead of 1,733.**
**3/23 should have 40 Deaths instead of 27.**
**3/23 should have 15,554 Total [Tests] instead of 14,300.** 
**3/23 correctly lists 12,100 Pending [Tests].** 

[March 24 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-033.aspx) "As of March 24, 2020, 2 p.m. PDT" This is currently an off-by-one for the 25th.
**3/24 should have 2,535 Positives instead of 2,102.**
**3/24 should have 53 Deaths instead of 40.**
**3/24 should have 18,276 Total [Tests] instead of 15,554.** 
**3/24 should have 48,600 Pending [Tests] instead of 12,100.** 

[March 25 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-034.aspx) "As of March 25 2020, 2 p.m. PDT" This is currently an off-by-one for the 26th.
**3/25 should have 3,006 Positives instead of 2,355.** This is both off-by-one and a typo of "2,535".
**3/25 should have 65 Deaths instead of 53.**
**3/25 should have 20,386 Total [Tests] instead of 18,276.** 
**3/25 should have 57,400 Pending [Tests] instead of 48,600.** 

[March 26 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-035.aspx) "As of March 26 2020, 2 p.m. PDT" This is currently an off-by-one for the 27th.
**3/26 should have 3,801 Positives instead of 3,006.** 
**3/26 should have 78 Deaths instead of 65.**
**3/26 should have 23,480 Total [Tests] instead of 20,386.** Current number is wrong, not just off-by-one.
**3/26 should have 65,000 Pending [Tests] instead of 57,400.** 

[March 27 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-036.aspx) "As of March 27 2020, 2 p.m. PDT" 
**3/27 should have 4,643 Positives instead of 3,879.** Current number is wrong, not just off-by-one.
**3/27 should have 101 Deaths instead of 78.**
**3/27 should have 25,192 Total [Tests] instead of 21,259.** 
**3/27 should have 64,400 Pending [Tests] instead of 57,400.** 

March 28 state data is missing for positives and deaths. The next CA state data report is for the 29th. Unclear where CTP data comes from. Treat as non-reporting day for positives and deaths.
CA notes "***This week’s cumulative testing numbers are lower than last week due to an inadvertent over-reporting error discovered by one of the private labs."
[March 28 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-037.aspx) "As of March 28 2020, 2 p.m. PDT" 
**3/28 should have 27,251 Total [Tests] instead of 21,259.** 
**3/28 should have 56,550 Pending [Tests] instead of 57,400.** 

[March 29 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-037.aspx) "As of March 29 2020, 2 p.m. PDT". This report includes March 28th's total and pending test numbers. There are no reported total and pending numbers for March 29. Treat as non-reporting day.
**3/29 should have 5,763 Positives instead of 5,708.** Current number is wrong, not just off-by-one.
**3/29 should have 135 Deaths instead of 123.**

[March 30 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-038.aspx). CA stopped reporting a time cutoff starting with the March 31 press release w/ March 30 data.
**3/30  should have 6,932 Positives instead of 6,447.**
**3/30  should have 150 Deaths instead of 133.**
**3/30  should have 28,704 Total [Tests] instead of 26,996.** 
**3/30  should have 57,400 Pending [Tests] instead of 64,400.** 

[March 31 state data](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-039.aspx). 
**3/30  should have 8,155 Positives instead of 7,482.**
**3/30  should have 171 Deaths instead of 153.**
**3/30  should have 31,038 Total [Tests] instead of 29,254.** 
**3/30  should have 59,100 Pending [Tests] instead of 57,400.** 

Off-by-a-day errors aside, it makes sense to use official state reported confirmed case and death numbers for a date when those are higher than current CTP reported values. It is unlikely the state is making up higher positive case and death counts.

@thaynedye
@dcmoyer

**Comment by karaschechtman** [comment]
Hi @scarson,
Thanks again for bringing these discrepancies to our attention. For an explanation of why these numbers may differ from ours, see #431. You are 100% right that these discrepancies for 3/18-31 are big. We have a team working to determine how and whether to update data from historical sources in event of discrepancies like this. I will flag this as a potential source of data to them.
