### ISSUE TITLE
CA 4/1 to current 5/17 - Data is off by one day from official CA press releases

### ISSUE THREAD

**Issue by scarson** [COVID19Tracking/issues#433]
Starting on March 30th, the California reporting structure changed, displaying a “California COVID-19 By the Numbers” infographic. This image reports the data for the day according to the end-of-day values from the previous day. The CTP starts recording this data as a primary source on April 2nd, except it enters the data on the day the graphic is published, not the day referenced in the graphic. So the [April 2nd graphic](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-041.aspx) matches the CTP data for April 2nd, however the graphic lists them as end-of-day numbers for April 1st.

Need to shift **all** CA numbers so that they reflect CA's "Numbers as of $date", not the press release date ($date+1). Day forward recording needs to be enter numbers for $date in the actual matching day as well.

This change is important for consistency and modeling.

For March fixes (which include similar off-by-one errors, among others), please see:
#432 
#431 

@thaynedye
@dcmoyer

**Comment by karaschechtman** [comment]
Hi @scarson,
Thanks for bringing this to our attention! CA updated its data after our publish time cutoff. If a state updates after that time, we catch that update on the following day. See my response to #431 and #432 for further discussion.
