### ISSUE TITLE
[Historical MO]: Total tests was accidentally put in as negative tests on 5/17

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#434]
On 5/17, there was an entry error in MO where the number of total tests was put in place of the number of the negative tests. 

Entry Negative Tests (5/17) should be fixed from 146255 to 146255-10789 = 135466

**Comment by qpmnguyen** [comment]
Fixed the issue for you Quang!

Before screenshot
![Before](https://user-images.githubusercontent.com/25627274/82256784-f2d2e000-9924-11ea-8147-1f9ca20a7a50.JPG)

After screenshot
![after](https://user-images.githubusercontent.com/25627274/82256801-f9615780-9924-11ea-8cd8-1fa4f79e3037.JPG)

**Comment by muamichali** [comment]
On 5/17 the Total Tests PCR value is blank. It should be updated to 146255 


**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/95147184-03f28100-074e-11eb-8f63-76159398841e.png)

**AFTER**
![image](https://user-images.githubusercontent.com/1749380/95147247-2daba800-074e-11eb-905e-3a1768325a27.png)
