### ISSUE TITLE
Florida 5/16 and 5/17 data 

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#435]
Possible mistake for Florida on 5/16 and 5/17. 
State updated on 5/16 with 826 new cases and on 5/17 with 777 cases.  

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24235)

**Comment by kevinp2** [comment]
Also Florida shows zero tests for May 15.

**Comment by muamichali** [comment]
Both of the issues in this ticket are now moot because we have backfilled Florida's tests and cases from timeseries provided by the states. More information is available at 
https://github.com/COVID19Tracking/issues/issues/914
and
https://github.com/COVID19Tracking/issues/issues/873
