### ISSUE TITLE
[Historical GA] Trend on state website not matching our trends

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#436]
Possible revision of historicals by the GA

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2424x)

**Comment by careeningspace** [comment]
We need to add this to our historical clean-up list

**Comment by careeningspace** [comment]
https://app.frontapp.com/open/msg_dme1zv5

**Comment by muamichali** [comment]
Closing with note to say that we have settled on capturing cumulative metrics by date of report rather than trying to combine manual capture of cumulative data with constantly revising metrics. Therefore, the changes requested in these two tickers were not performed.
