### ISSUE TITLE
Revise VT historical numbers to exclude serology tests

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/issues#437]
https://twitter.com/EPetenko/status/1263194375133241344

Erin is in the Slack and presumably flagged this somewhere, IDK

**Comment by muamichali** [comment]
Thank you @kissane! I found Erin's post in slack. We are going to revise VT numbers based on the link she provided https://geodata.vermont.gov/datasets/vt-covid-19-daily-counts-table/data?orderBy=date&orderByAsc=false

**Comment by muamichali** [comment]
[This spreadsheet ](https://docs.google.com/spreadsheets/d/e/2PACX-1vRoB1Yz2W8DXocpGlAkxdJzFNNkS5mxwKIEDL4_9ac91uKm4R_Hkez9zsOOzXpkDzWX4HGZxW5lQfN_/pubhtml)contains:

[1] Current values of VT historicals
[2] Before and After values for positives, negatives, and last updated columns for VT
I made the update in States Daily. It should be reflected on the API/website in an hour.
