### ISSUE TITLE
suggestion/offer to include state-level population and land-area information

### ISSUE THREAD

**Issue by smrgit** [COVID19Tracking/issues#44]
I have created my own [google sheet](https://docs.google.com/spreadsheets/d/1IJIc1A6n5i26glEJ5-UpBiQe9Kc4Ts3EBRFSxdYECqs/) in which I import your state-level data and then I'm copying it manually over to a 2nd tab where I also have state-level population and land-area size.  Using those two I calculate cases-per-million people and plot that against population density.  I think it makes for an interesting graph.

If you're interested I'd be happy to have you incorporate this into your main google sheet.  Or perhaps you already have other plans/ideas about nicer plots.

**Comment by careeningspace** [comment]
The data you are referencing is already publically available for your consumption. We do not have the bandwidth to host and maintain another copy. 

We are working on some additional visualization tools that may answer your request from another angle so stay tuned.

Thanks!
