### ISSUE TITLE
Couple issues with Texas data 5/21 and 5/22

### ISSUE THREAD

**Issue by johndhancock** [COVID19Tracking/issues#444]
Looks like there were no positives captured for Texas on 5/21 (same figure as 5/20) and no testing figures are odd for 5/22 (total same as 5/21, negatives went down from 5/21, no new tests figure)

**Comment by muamichali** [comment]
![image](https://user-images.githubusercontent.com/1749380/82720583-bf74b600-9c82-11ea-9a51-935b1c2368e8.png)

**Comment by johndhancock** [comment]
Awesome. Thanks for the quick work!
