### ISSUE TITLE
[TX Historical] cases for 5/11,5/12,5/23

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#449]
> Looking at the “Positive” data for Texas I’m seeing two likely errors. First on, 5/11/20 and 5/12/20 the number of reported cases was 39,869 for both days. This would mean that no new cases occurred of 5/12/20 at a time when the daily average number of new cases in the two weeks before and after 5/11/20 was 1,256. Second, the “Positive” count for 5/22/20 and 5/23/20 was 53,449 for both days. Again, this occurred during a period where the daily average new cases was 1,202. Entries for 5/12/20 and 5/23/20 appear suspect.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_247f5)

CASES Source:

05/22/2020 | 53,449
05/23/2020 | 54,509
05/24/2020 | 55,348

*BEFORE*
![image](https://user-images.githubusercontent.com/1749380/82768005-e86b8700-9df9-11ea-873c-b44337c5743d.png)

*AFTER*
![image](https://user-images.githubusercontent.com/1749380/82768094-abec5b00-9dfa-11ea-8942-38533974e138.png)

**Comment by johndhancock** [comment]
Seconded on the 5/23 data. Looks like Texas DSHS data has the total for 5/22 at 54509 (1060 new cases). See OBJECTID 81 (here)[https://services5.arcgis.com/ACaLB9ifngzawspq/ArcGIS/rest/services/DSHS_COVID19_Cases_Service/FeatureServer/8/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=]
