### ISSUE TITLE
[UT Historical] Repair data for May 19, 22, 23

### ISSUE THREAD

**Issue by jedludlow** [COVID19Tracking/issues#450]
The state of Utah had an outage on May 19 which caused that day's data to be a duplicate of May 18.

Hospitalization data for May 22 and 23 was incorrect with respect to totals on the state's site as retrieved around 11:30 am on May 23 and May 24, respectively.

This pull request documents the required repairs. I realize that directly incorporating the pull request into `covid-tracking-data` may not be the best repair strategy, but it served as a convenient way to convey the required changes and allowed me to continue plotting without strange aberrations.

https://github.com/COVID19Tracking/covid-tracking-data/pull/73

**Comment by jedludlow** [comment]
For simplicity, here are the minimal required repairs spelled out for the days in question ignoring the deprecated data fields.

### 2020-05-19

There was an outage on the state's data website for this day, causing it to be a duplicate of May 18. The correct data was posted later in the evening and can be obtained from a [KSL News story](https://www.ksl.com/article/46754950/utah-reports-highest-single-day-covid-19-death-total-of-8-with-134-new-cases) from that day:
- `positive`: 7518
- `negative`: 16793
- `hospitalizedCumulative`: 619
- `death`: 88

### 2020-05-22

Cumulative hospitalization data for May 22 is incorrect. The [historical screenshot](https://covidtracking.com/screenshots/UT/UT-20200522-185327.png) shows that this should read 660 instead of 1036.

### 2020-05-23

Cumulative hospitalization data for May 23 is incorrect. The [historical screenshot](https://covidtracking.com/screenshots/UT/UT-20200523-184524.png) shows that this should read 676 instead of 1053.

**Comment by camille-le** [comment]
Hi Jed, thank you for your input and for sharing the KSL News Story. We've reviewed the historical screenshots from 5/18, 5/19, 5/22 and 5/23 for Utah. The cumulative hospitalization data will be updated in our next publish. We are still reviewing the remaining changes you've mentioned for 5/19. 

**BEFORE:** 
![2020-06-07_UT_BEFORE](https://user-images.githubusercontent.com/31285549/83981114-e6acc380-a8cf-11ea-835d-bbd6bb3d845f.png)

**AFTER:** 
![2020-06-07_UT_AFTER](https://user-images.githubusercontent.com/31285549/83981116-eca2a480-a8cf-11ea-91b3-e38d6ab0f687.png)

Thank you,
Camille

**Comment by camille-le** [comment]
For the remaining changes for 5/19, data will be updated in our next publish for positive cases, negative cases, hospitalized (currently), hospitalized (cumulative), recovered and deaths. 

**BEFORE:** 
![UT_05-19_BEFORE](https://user-images.githubusercontent.com/31285549/83981446-b0247800-a8d2-11ea-8961-0a08684a5c8a.png)

**AFTER:** 
![UT_05_19_AFTER](https://user-images.githubusercontent.com/31285549/83981447-b4509580-a8d2-11ea-8e00-a75d5aba6ea8.png)
