### ISSUE TITLE
In latest CSV export, Rhode Island is "REF"...

### ISSUE THREAD

**Issue by rypan** [COVID19Tracking/issues#452]
In the latest export of `Current state data - /api/v1/states/current JSON and CSV` oddly, the row for Rhode Island has "REF" for the `dataQualityGrade`.

![image](https://user-images.githubusercontent.com/442198/82781417-984aef80-9e0e-11ea-90f0-630338884b6b.png)

I believe it was A+ two days ago...

The website says N/A:

![image](https://user-images.githubusercontent.com/442198/82781461-b1ec3700-9e0e-11ea-9cfd-c0be51b3a06c.png)

**Comment by muamichali** [comment]
Thanks for the heads up, Ryan. 
Fixed by @careeningspace & they are back to their A+ grade now.
