### ISSUE TITLE
Someone tried to add WA counties to counties.csv from covid-tracking-data

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/issues#454]
https://github.com/COVID19Tracking/covid-tracking-data/pull/64

(in case this is something we want to fix upstream, not sure what this affects)

**Comment by muamichali** [comment]
I am not sure if the counties endpoint is used internally, maybe by visualization or race data folks? Perhaps @kevee knows?

**Comment by kevee** [comment]
We don't use it for anything ATM.
