### ISSUE TITLE
[MI historicals] MI hospitalization numbers weren't updated in a few days

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#456]
![image](https://user-images.githubusercontent.com/1749380/82968411-4b485400-9f9b-11ea-9615-39fe989e5e16.png)

**Comment by camille-le** [comment]
Hi @muamichali, thanks for opening the issue. After reviewing our screenshots of [Michigan's COVID-19 site](https://www.michigan.gov/coronavirus/0,9753,7-406-98159-523641--,00.html), I'm confirming Michigan reported the # of Inpatients as 953 on 5/24, 5/25 and 5/26. 

In addition, on 5/26, Michigan also updated the # of Inpatients from 953 to 882 after we published. We publish the daily stats every afternoon. If a state updates the number of tests or cases after that time, we catch that update on the following day.

Thank you,
Camille
