### ISSUE TITLE
[VT Historicals]May 20th numbers

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#457]
testing numbers from 5/19 to 5/20

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24a4x)

**Comment by brianskli** [comment]
We will be able to fix this issue once https://github.com/COVID19Tracking/covid-public-api-build/issues/58 is resolved. The logic for calculating total tests may have caused this error.

**Comment by the-daniel-lin** [comment]
Like @brianskli said above, this seems to be an issue with the positive+negative logic. Since we now report explicit totals for VT, so I'm closing this issue.
