### ISSUE TITLE
[SC Historicals] 13 cases where the state changed the data but our report does not reflect it

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#458]
Secondly, there are several states that for some reason on the COVID Tracking Project sometimes repeat the numbers from day to day. This happens at South Carolina in 13 instances. In none of those 13 instances did the numbers fail to change in the daily reports.

From https://app.frontapp.com/open/msg_dl7uc7l

**Comment by cout** [comment]
Is this the same as #375?
