### ISSUE TITLE
New URL for Kansas

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#46]
Current URL for KS in DEV COPY spreadsheet is https://govstatus.egov.com/coronavirus -- new ARCGIS dashboard with stats is https://kdhe.maps.arcgis.com/apps/opsdashboard/index.html#/05f4169dc6394aa98895072b94734134

**Comment by careeningspace** [comment]
Thank you @amandafrench - you are a rockstar. The link has been updated!
