### ISSUE TITLE
MA Historical 4/25-3/20 - Deaths don't match MA Archive

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#460]
The reported deaths are not consistent with the MA historical information from 3/20-4/25.

The states archived data is found here: https://www.mass.gov/info-details/archive-of-covid-19-cases-in-massachusetts

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24btd)

**Comment by muamichali** [comment]
Hi @schmian 

We patched MA data after this ticket, so it should have been fixed
