### ISSUE TITLE
May 17 positive cases total for South Carolina

### ISSUE THREAD

**Issue by chriscanipe** [COVID19Tracking/issues#464]
**State**
South Carolina

**Describe the problem**
The Sunday, May 17 case total is off in the data API. The May 17 SC Health Dept. press release shows 8,816 cases as of May 17. But the CTP historical data shows 8,661 for that date. Possible to get that fixed? (The last screenshot is correct. Looks like the feed still includes the screenshot from earlier in the day).

**SC Health Dept. data source:**
https://www.scdhec.gov/news-releases/south-carolina-announces-latest-covid-19-update-may-17-2020

**TCP SC data**
https://www.scdhec.gov/news-releases/south-carolina-announces-latest-covid-19-update-may-17-2020

Thanks!

**Comment by camille-le** [comment]
Hi Chris, thanks for your input. On 5/17, South Carolina updated total positive cases from [8661](https://covidtracking.com/screenshots/SC/SC-20200517-124509.png) to [8816](https://covidtracking.com/screenshots/SC/SC-20200517-184615.png) after we published. 

We are going to update the 5/17 data based on the South Carolina 5/17 evening screenshot. You should see the correct data reflected on the site shortly.

**BEFORE:** 
<img width="421" alt="2020-05-17_SC_BEFORE" src="https://user-images.githubusercontent.com/31285549/83265707-b9953e00-a176-11ea-93da-f47ac61cba62.png">

**AFTER:** 
<img width="425" alt="2020-05-17_SC_AFTER" src="https://user-images.githubusercontent.com/31285549/83265726-c154e280-a176-11ea-99fb-c9076250bff6.png">

Thank you,
Camille
