### ISSUE TITLE
[LA] Negatives reported same as total on 28-May

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/issues#465]
On 28-May both total and negative were reported as the "total" value, which increased the total reported through the API.

Total from dashboard = `355,027`
Negative should be  (35,5027 - 38,802) = `316,225`

Links: https://covidtracking.com/api/v1/states/LA/20200528.json

**Comment by muamichali** [comment]
![image](https://user-images.githubusercontent.com/1749380/83260449-ce2e0200-a187-11ea-9f11-9985d0f28917.png)

**Comment by muamichali** [comment]
Looks like I fixed is already but forgot to close the ticket. Thanks, stale bot!
