### ISSUE TITLE
[TN Historicals] May 22 numbers

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#468]
Dear Covid Tracking Project (and RT.live):

 

First, great job and I appreciate your efforts to distribute good data to everyone.  Thank you.

 

It appears your data for May 22 for the state of Tennessee has an error in the number of tests.  It is stated at the level of positives (433).  The data set download from the state of Tennessee has it at 7,587.  The correction will also impact your number of tests for May 23, which you have at 12,742 versus the state data set at 5,588.  I think this is impacting the algorithm at rt.live which uses your data for its calculation (and whom I am copying on this email so they also know) for the state of Tennessee.

 

Thanks,

 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24d01)

**Comment by MattHilliard** [comment]
Looks like a data entry mistake; the negative number was not updated on 6/22 but all the other numbers in States Daily are correct. I've fixed the negative number to 348776 (331393+17383) based on the secondary TN screenshots, which fortunately were fixed that day.

Before:
![image](https://user-images.githubusercontent.com/404503/85209120-59239780-b303-11ea-9b3a-6258a2f23837.png)

After:
![image](https://user-images.githubusercontent.com/404503/85209179-ce8f6800-b303-11ea-972c-eaaa29dbcd47.png)
