### ISSUE TITLE
New URL for American Samoa 

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#47]
We have apparently been using the URL for Samoa, which is not the same as American Samoa. The current URL in the data entry spreadsheet (and probably urlwatch) is http://www.samoagovt.ws/category/latest-news/  -- no one is quite sure what a good source for American Samoa is, but we do know that Samoa URLs end in the top level domain .ws and American Samoa URLs end in the top level domain .as. Might have to check FB page at https://www.facebook.com/amsamgov/

**Comment by careeningspace** [comment]
This is still a sore spot - part of the issue may be related to the fact that they have ZERO capacity to test...

**Comment by schwartzadev** [comment]
The [new URL](https://www.americansamoa.gov/covid-19-advisories) is at americansamoa.gov.
