### ISSUE TITLE
Missing data for Texas for 5/30 (included in 5/31 update)

### ISSUE THREAD

**Issue by johndhancock** [COVID19Tracking/issues#471]
**State or US**: Texas

**Describe the problem**
Looks like Texas DSHS missed CTP's update window on 5/30, causing 5/30's numbers to fold into 5/31. Think 5/30 should have 62,338 positives, 35,242 new tests, 866,179 negatives. Screenshot from DSHS from 5/30 included.

**Link to data source**
https://covidtracking.com/screenshots/TX/TX-20200530-184446.png

**Comment by muamichali** [comment]
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/83422660-ddb38200-a3f7-11ea-99f5-6cebc101c724.png)

**Comment by muamichali** [comment]
@kevinp2 graciously provided the XLS in https://github.com/COVID19Tracking/issues/issues/442#issuecomment-637772812

Here is a screenshot of the state XLS
![image](https://user-images.githubusercontent.com/1749380/83642703-2e081c80-a57d-11ea-9a76-4c197deb80df.png)

I am just updating that data point of positive antibody tests on 5/30
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/83642852-58f27080-a57d-11ea-8536-82d634afb176.png)

**AFTER**
![image](https://user-images.githubusercontent.com/1749380/83642943-745d7b80-a57d-11ea-9f42-70bce844fe7b.png)
