### ISSUE TITLE
MN changed test numbers to per-test from per-person 

### ISSUE THREAD

**Issue by Minibadger** [COVID19Tracking/issues#475]
**State or US**: Minnesota

**Describe the problem**
As of June 5, Minnesota changed its reporting of Tests from per-person to per-test. This appears to be retroactive to an extent. Today's COVID Tracking Project derived New Tests falsely by seeing the difference in Total over yesterday, when arriving at over 46k new tests, when in reality some of the historical data was updated with substantially higher counts. 

See the Testing Data Table 
https://www.health.state.mn.us/diseases/coronavirus/situation.html#test2

And compare to the COVID Tracking Project numbers. They'll need to be updated. 

**Link to data source**
https://www.health.state.mn.us/diseases/coronavirus/situation.html#test2

**Comment by Minibadger** [comment]
This issue still exists. The resolution would be to edit the historical data to match the "testing data table" on the MN Department of Health website.

**Comment by MattHilliard** [comment]
Hi @Minibadger, thanks for bringing this to our attention! Today we updated our Minnesota historical numbers for positives, negatives, and PCR tests to bring them in line with the updated state data.
