### ISSUE TITLE
Illinois June 8 and 12th data is wrong

### ISSUE THREAD

**Issue by oharatso** [COVID19Tracking/issues#481]
**State or US**: IL

**Describe the problem**
June 8th Illinois new positive cases of 1382 should be 658 and deaths of 198 should be 23
June 12th Illinois new positive cases should be 595 and deaths should be 77

**Link to data source**
June 8th:  https://www2.illinois.gov/Pages/news-item.aspx?ReleaseID=21652
June 12th:  https://www2.illinois.gov/Pages/news-item.aspx?ReleaseID=21672

**Comment by MattHilliard** [comment]
Hi @oharatso, thanks for raising this issue. When available, our published data for cases and deaths includes probables. As mentioned in both [our notes](https://covidtracking.com/data/state/illinois) on Illinois and in the first press release you linked, starting on June 8th Illinois began reporting probable cases and probable deaths on its state page. If you look at the screenshots linked from [our Illinois historical data](https://covidtracking.com/data/state/illinois#historical), the probable cases and deaths account for the apparent discrepancies you noticed. Note they aren't providing these every day, so there are little spikes when the new probable numbers come in.
