### ISSUE TITLE
Total tests performed in All states historical data

### ISSUE THREAD

**Issue by paldhous** [COVID19Tracking/issues#482]
**US**

**Describe the problem**
The API [description of data fields](https://covidtracking.com/api) seems to have no field for total tests that isn't deprecated, see:

total
Field type:integer
Deprecated

totalTestResults
Field type:integer
Deprecated

Can you advise what should be used to represent total tests?

Thanks!

**Comment by muamichali** [comment]
Hi @paldhous Please use totalTestResults 

We are going to update the documentation. Thanks for letting us know about this.
