### ISSUE TITLE
[MN Historicals] MN switched their test reporting from people to tests on 6/5

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#484]
Historical data needs to be updated to match current reporting.

**Comment by MattHilliard** [comment]
We updated MN historicals today to address this. See also https://github.com/COVID19Tracking/issues/issues/475

Analysis spreadsheet, including old and new versions of States Daily: https://docs.google.com/spreadsheets/d/1Y0ZtCoyZHOf_p0X12msYe9oKI6L38UgnGZHN8JddOHU/edit#gid=1869230983
