### ISSUE TITLE
The Date is missing in column 1 of the "States Daily 4PM ET" file.  What happened?

### ISSUE THREAD

**Issue by sluggo1133** [COVID19Tracking/issues#488]
**State or US**: [State name, or "US" if this is an issue with country-wide data]

**Describe the problem**
A clear and concise description of what the data problem is.

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.

**Comment by muamichali** [comment]
I think this is fixed @sluggo1133 - Can you please let me know otherwise?

**Comment by sluggo1133** [comment]
Michal,

 

Thursday night and the data looks good, meaning everything is where I expected it to be.  Case close.

 

Thanks,

slg
