### ISSUE TITLE
Tweaks to the public-facing spreadsheet

### ISSUE THREAD

**Issue by metasj** [COVID19Tracking/issues#489]
The main [data spreadsheet](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#) is an excellent single-page source of information, but could be cleaned up a bit.

I wasn't sure which repo to add this to, including it here since it's just spreadsheet update.   
A dash of suggestions:

== Tab headers
**States Current** - lowercase Current  
**US current** - fine  
**States daily** 4 pm ET - remove time  
**US daily** 4 pm ET   
**States** - "States notes" would be clearer  

== Header row within each tab
**States current**
Close to the ideal -- no extra vertical space in the header, double-thick lines indicating frozen first col and row.  Column nitpicks:   
* Positive - "Positive cases"
* Negative - "Negative cases"
* Pending - drop this column. 
* Last update - "Source last updated"
* Check time  - drop this column; confusing (and not included in States daily).  If it must be included, rename for clarity, to something like "Source last checked for updates"

**US current**  
Reduce the whitespace in the header row.  Freeze that row (double-thick line below)  
* Add "Date" column as the first column, as with _US daily_
* Add "Last update" column - add a timestamp column w/ the time this was updated from the previous day

**States daily** 
Reduce whitespace in the header. Drop the "4pm" in the title - that's not always accurate.  Freeze the header row and first two columns.
* State - make narrower to match _States current_
* Pending - remove column
* Deaths - make narrower

**US daily** 
Reduce whitespace in the header. Freeze the first two columns.
* Positive, Negative, Pending - "Positive cases", "Negative cases", "Pending cases"  [once tests/cases is normalized]
* Add "Last update" column, as with _US current_, for the full timestamp.

**States** 
Make header row unbold, and centered.  Freeze first column.
* Make URL columns a bit narrower, and Notes column a bit wider.

**Comment by muamichali** [comment]
Sorry @metasj I didn't mean to close it. Was trying to make sure it won't go stale...
