### ISSUE TITLE
Hospitalized - Clarification on ever or current

### ISSUE THREAD

**Issue by timmmichaud** [COVID19Tracking/issues#49]
How do you account for "Hospitalized"? 

Is the current number of hospitalized **at this time**? Or the running total **over all time**?

It would be good to have this added to the FAQ to clear up which number that column represents. Or maybe even add a second column to show current hospitalization stats today vs. total for all time.

**Comment by timmmichaud** [comment]
I just noticed NYC has started to label this column as "Ever Hospitalized Cases"

![Screen Shot 2020-03-25 at 23 21 45](https://user-images.githubusercontent.com/134873/77616732-98527000-6eef-11ea-8c19-34af104d6903.jpg)

Screenshot from here - 
https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary-hospitalizations.pdf

**Comment by careeningspace** [comment]
Hello,
We are in the process of expanding our outcome data reporting as I type. We will struggle with collecting the data, but you can be assured that we will be pressing governments to provide this data as accurately as possible. Soon we will report cumulative and current hospitalization data as it is available.

Thanks!

**Comment by timmmichaud** [comment]
I saw the new label above Hospitalized for "Cumulative". Looks good, thanks! 👍🏼
