### ISSUE TITLE
MA updated backlog of presumed cases from March 1

### ISSUE THREAD

**Issue by erfgottlieb** [COVID19Tracking/issues#490]
MA

On June 1, Massachusetts reported a backlog of unconfirmed presumed cases from March 1. Need to update CTP data.

Raw data cases by date:
https://www.mass.gov/info-details/covid-19-response-reporting

Worksheet:
https://docs.google.com/spreadsheets/d/1M6dx2tYAhTT45uJ9gAF0ZiW4cEk0H7Sw8jzo9Cspopo/edit#gid=1681653028

**Comment by space-buzzer** [comment]
We have an ongoing issue for MA for cases and tests -- #689, so this one should be OK to close
