### ISSUE TITLE
DE Death Total on 6/11 was entered incorrectly

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#491]
DE

**Describe the problem**
Data entry error

**Link to data source**
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1591987123059900

**Comment by MattHilliard** [comment]
Looks like they added probable deaths that day and the person entering misinterpreted, adding the probables to the total and then reporting the total as confirmed deaths. Fixed both numbers:

Before:
![image](https://user-images.githubusercontent.com/404503/85083769-b6eb9e80-b1a0-11ea-9b97-651a6ad058a0.png)

After:
![image](https://user-images.githubusercontent.com/404503/85083837-003bee00-b1a1-11ea-9535-a74562bc9aa3.png)
