### ISSUE TITLE
MN Data, 6/13

### ISSUE THREAD

**Issue by goldfarb** [COVID19Tracking/issues#492]
**MN**: 

**Describe the problem**
The positive cases were entered as 30,712, MI site has 30,172

**Link to data source**
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1592097495326000

**Comment by goldfarb** [comment]
![image](https://user-images.githubusercontent.com/3722037/84582996-71565c80-adc1-11ea-8f01-63a448046d1e.png)


For Positives: 407992-30712=377280 -> 407992-30172=377820

Updated `Worksheet2` : AC, AE and AF

![image](https://user-images.githubusercontent.com/3722037/84582889-fc365780-adbf-11ea-810c-3b51461ae041.png)

Updated `States Daily`

![image](https://user-images.githubusercontent.com/3722037/84582966-13297980-adc1-11ea-83dd-9275b7d05154.png)
-> 
![image](https://user-images.githubusercontent.com/3722037/84582970-1a508780-adc1-11ea-83ca-35685a8ac200.png)

![image](https://user-images.githubusercontent.com/3722037/84582973-2a686700-adc1-11ea-958d-e6e5ce3f640f.png)
 -> 
![image](https://user-images.githubusercontent.com/3722037/84582975-318f7500-adc1-11ea-9757-9b29b578217e.png)



Was not certain how to update `States Current` so the color is indicating a smaller value in Positive Cases (AE)

**Comment by muamichali** [comment]
@goldfarb had fixed this. Closing ticket.
