### ISSUE TITLE
[NV Historicals Error]

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#493]
Two errors in your NV data. 

First, there's a random 50 that appears where there should be a 1 in the cumulative positive cases... taking your daily.csv file and pulling out the NV data, see these rows: 

... 
20200305	NV	1 
20200306	NV	50 
20200307	NV	1 
... 

Second, there is a cumulative death error where an error seems to have slipped in, then was subsequently corrected, but this wasn't back-corrected in the cumulative totals. 

Here are the deaths for NV around June 1st. Note the 421 DOWN to 420 error... 
... 
417	2020-05-30T10:30:00Z 
417	2020-05-31T11:30:00Z 
421	2020-06-01T11:00:00Z 
420	2020-06-01T00:00:00Z 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24pzl)

**Comment by camille-le** [comment]
Hey Michal, 
Thank you for writing. We've updated the data for cumulative positive cases for March 6, 2020. 

**BEFORE:** 
<img width="259" alt="2020-03-06_NV_BEFORE" src="https://user-images.githubusercontent.com/31285549/85025569-68042180-b12c-11ea-8221-61ce00171471.png">

**AFTER:**
<img width="242" alt="2020-03-06_NV_AFTER" src="https://user-images.githubusercontent.com/31285549/85025673-8702b380-b12c-11ea-9e59-6e582084ca61.png">

We have also updated the data for cumulative deaths for June 1 and June 2, 2020 as reported by the [Nevada Health Response team on June 4. 
](https://nvhealthresponse.nv.gov/wp-content/uploads/2020/06/06.4.20-Daily-SitRep-final.pdf) 
**BEFORE:** 
<img width="718" alt="2020-06-01_06-02_NV_BEFORE" src="https://user-images.githubusercontent.com/31285549/85030532-676e8980-b132-11ea-833e-72d312ef877c.png">

**AFTER:** 
<img width="715" alt="2020-06-01_06-02_NV_AFTER" src="https://user-images.githubusercontent.com/31285549/85030018-cd0e4600-b131-11ea-9bb9-cc584e7028ae.png">
