### ISSUE TITLE
OR: bad data for today?

### ISSUE THREAD

**Issue by adamdavis40208** [COVID19Tracking/issues#494]
I'm using a few fields for a pet project:
```
deathIncrease
death
positiveIncrease
totalTestResultsIncrease
```
![image](https://user-images.githubusercontent.com/19850646/84611661-5f34f680-ae73-11ea-96b7-912f11922bc8.png)

All of these numbers have generally been populated and accurate, except for today. Just thought I'd drop you a note!

**Comment by muamichali** [comment]
Hi Adam

If you look at the screenshots on our website https://covidtracking.com/data/state/oregon#historical you will see that Oregon has not been updating the numbers on their dashboard since 6/12. Is this possibly the answer to your question?

**Comment by adamdavis40208** [comment]
Ah. I didn't realize the data source only updated monday-friday

https://govstatus.egov.com/OR-OHA-COVID-19
>Data current as of 6/12/2020, 12:01 a.m. Updated Monday - Friday.*

Good to know, sorry for the false alarm!
