### ISSUE TITLE
Washington state historical new cases

### ISSUE THREAD

**Issue by chriscanipe** [COVID19Tracking/issues#495]
Washington state — new case numbers seem off for the last couple of weeks.

The historical new cases data isn't lining up with what NYT or WaPo (via Johns Hopkins) are showing. Specifically, both sources show steady modest increases in the last two weeks. Whereas the CTP data shows a sharp drop in the first week of June (and no new cases on June 6th) followed by an increase. See the attached spreadsheet.

Any chance somebody can reconcile tomorrow (Monday, June 15th)?

**Link to data source**
https://www.nytimes.com/interactive/2020/us/washington-coronavirus-cases.htmlhttps://www.washingtonpost.com/graphics/2020/national/coronavirus-us-cases-deaths/

[WA_hist_2020-06-14.xlsx](https://github.com/COVID19Tracking/issues/files/4777862/WA_hist_2020-06-14.xlsx)

**Comment by muamichali** [comment]
Hi Chris,

Please stand by. We are working on this while designing a long term solution for this issue.

**Comment by theomichel** [comment]
Hi @chriscanipe, we have updated with Washington data for cases and tests today, using the latest historical data from the washington DOH. (at the time of the update, their data was up to 6/20)

The update process is now a bit smoother, but not fully automated. Feel free to file additional github issues if you see problems in the future.
