### ISSUE TITLE
MA positive cases inaccurate for June 1st

### ISSUE THREAD

**Issue by salmasian** [COVID19Tracking/issues#496]
**State or US**: MA

**Describe the problem**
The number of confirmed cases in Massachusetts on June 1st is shown as 96,965 which is the same as the day before. This is inaccurate. The 6:34 PM update (linked [here](https://covidtracking.com/screenshots/MA/MA-20200601-183437.png) and on the COVIDtracking project) shows the number was 100,805. This also impacts the positiveIncrease column for June 2nd, where currently a jump of more than 4000 cases is shown, but in reality it was two smaller jumps of ~2000 cases in the two days.

**Link to data source**
https://covidtracking.com/screenshots/MA/MA-20200601-183437.png

**Comment by muamichali** [comment]
Hi salmasian,

Thanks for letting us know. We fixed it via #473 last night.
