### ISSUE TITLE
MA 6/1 Data

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#497]
Our data for Massachusetts on 6/1 was not updated from 5/31. https://www.mass.gov/doc/covid-19-dashboard-june-1-2020/download has the new data for 6/1

"I was reading an article in The NY Times which referenced your database in an analysis of incidence per state and resulting risk. I live in MA Which was ranked as high risk so I went to look at that data. There is a day (around 6/1) where there is an uncharacteristically high number of tears and positives, and the ratio is also unusually high. I went to the historic tracking at mass.gov and couldn’t replicate that data. Can you share your source please?"

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24qz5)

**Comment by muamichali** [comment]
Hi @schmian 

I think this was fixed by Issue #473
