### ISSUE TITLE
AZ historical data

### ISSUE THREAD

**Issue by saijanai** [COVID19Tracking/issues#498]
[AZ]

The hospitalizedIncrease in arizona says 817 increase on 28 May, but the actual figure is an increase of 34 according to the currentlyHospitalized numbers.

**Link to data source**
https://covidtracking.com/api/v1/states/az/daily.csv

See:

20200528,AZ,17763,185151,,**945**,2848,374,,222,,4452,A+,5/28/2020 00:00,2020-05-28T00:00:00Z,05/27 20:00,857,2848,2020-05-28T00:00:00Z,202914,,,,04,501,6147,202914,202914,6648,202914,26,**817**,c51ec45ecd5a03739295f1a37edb330f2d8a63a0,0,0,0,0,0,
20200527,AZ,17262,179004,,**911**,2031,375,,237,,4361,A+,5/27/2020 00:00,2020-05-27T00:00:00Z,05/26 20:00,831,2031,2020-05-27T00:00:00Z,196266,,,,04,479,5056,196266,196266,5535,196266,24,43,894e69524aefc2edd5da2c2ca6945ec57a7d16ed,0,0,0,0,0,

**Comment by muamichali** [comment]
Hi @saijanai 

The hospitalizedIncrease is reflecting the change in cumulative hospitalizations (from 2031 to 2848) as reported by AZ

**Comment by saijanai** [comment]
But 817 is a nonsensical figure no matter what AZ says about it as it doesn't jibe with the hospitalizedCurrently figure.

In other words it is useless data

In fact, the entire 10 days surrounding that figure are in error. The rest of the days seem to match between the current and accumulated, but not that 10 day period.
