### ISSUE TITLE
WA: all scraped data null

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/issues#5]
> The data is still there but the parser is not finding the data.  My generic table scanner picks it up.  It is probably just an ID change.

![image](https://user-images.githubusercontent.com/111581/76450857-be263380-638b-11ea-85cf-6515c271e676.png)

**Comment by joshellington** [comment]
Possibly getting thrown a loop through a load balancer/ddos:
![image](https://user-images.githubusercontent.com/92450/76473662-65b85b80-63b6-11ea-9e87-925f4e4775aa.png)

Initial `curl` investigation is showing a time-based, expiring (~30s?) cookie requirement, routed through: https://www.doh.wa.gov/TSPD/08d53046a7ab200005e61969b75632c19fd50c8e240a4437520fdcf1a06b6fdce989b827dd851460?type=8

**Comment by joshuaellinger** [comment]
Is this resolved?  Please close or assign it back to me.

**Comment by lucasgonze** [comment]
This was stale.
