### ISSUE TITLE
MO Numbers Not Updated 3/24

### ISSUE THREAD

**Issue by eschmidt2** [COVID19Tracking/issues#50]
The numbers for Missouri were not updated on the States Daily 4PM ET tab in the spreadsheet.  They have updated however on States Current tab so you should have the correct numbers.  Can you update the daily tab?

**Comment by careeningspace** [comment]
Hello, 
MO has been updated as the state provides. 
- [ ] From our Data Logs:
![Screen Shot 2020-03-27 at 1 06 48 AM](https://user-images.githubusercontent.com/43073915/77723645-6e6c7c80-6fc7-11ea-8bbc-4272a57cae4e.png)

- [ ] The Daily (only at 4 pm)
![Screen Shot 2020-03-27 at 1 09 33 AM](https://user-images.githubusercontent.com/43073915/77723769-b7243580-6fc7-11ea-95ef-0d67e5bb184f.png)
