### ISSUE TITLE
[WV]Change internal tracking of probable vs confirmed deaths - they do not separate

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#503]
https://covid-tracking.slack.com/archives/C012C4BEAR4/p1592489962311800

**Comment by the-daniel-lin** [comment]
WV began to report probable/confirmed deaths on 8/12 , but CTP began capture on 8/13 (https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1597351199389100).

archive.org doesn't allow us to see the actual breakdown from 8/12, so we can't backfill 8/12.

There's a stretch of 8 days from 5/4 - 5/11 where we have confirmed deaths. I was unable to find anything about them, but they're exactly the same as the lumped death column. I deleted the values from the confirmed deaths column from 5/4-5/11.
