### ISSUE TITLE
[CT Historicals] May 27th numbers 

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#509]
"Connecticut May 27 positive tests are 41,303 The COVID Tracking Project historical and current, but the Connecticut snapshot lists 41,288. Based on the snapshot it appears that Connecticut subtracted 15 positive tests."

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24x8x)

**Comment by MattHilliard** [comment]
CT actually subtracted a couple hundred positives and more total tests. The net change was -15. See CT's note is here: https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary5272020.pdf?la=en

Before:
![image](https://user-images.githubusercontent.com/404503/85338057-a04e8b80-b4af-11ea-927d-96b6ccf729aa.png)

After:
![image](https://user-images.githubusercontent.com/404503/85338137-bc522d00-b4af-11ea-9131-8011cca1cca5.png)

Added the following to CT's public note: ```On May 27, CT reported they had "removed 356 cases and 808 tests...which were identified as duplicates in the system." When combined with actual new cases, these removals resulted in a net reduction of 15 positives on 5/27.```
