### ISSUE TITLE
Show daily, rather than cumulative, figures on history pages

### ISSUE THREAD

**Issue by breyed** [COVID19Tracking/issues#51]
How many cases we have now matters much more for decision-making than how many we've ever had.

For example, an increase in daily positive results relative to daily total results is generally indicative of the disease spreading, and likewise a decrease indicative of receding. With all-time cumulative numbers, that kind of analysis doesn't hold.

The cumulative is useful for a retrospective. At some point, that's what we'll want to do. But first we've got to make smart trade-offs to curb the disease. Let's focus the data there.

**Comment by mymil** [comment]
Agreed, but there are issues with converting the cumulative data (see eg #41: almost half of states have at least one apparent "negative" daily value)

**Comment by careeningspace** [comment]
- [ ] You can calculate the daily delta by subtracting yesterday from today. 
- [ ] We are deprecating the datapoint that included "pending" which was causing a lot of confusion. you can find more about it here:   [COVID API](https://covidtracking.com/api/)
- [ ] Most states share a cumulative number and that is what we have chosen to report.
- [ ] We are working on some additional dashboards that may slice the data in different ways, but our primary goal is to report accurate data

**Comment by breyed** [comment]
@careeningspace What do you think about having a JavaScript toggle on the history page and including the pros and cons of daily versus cumulative metrics on the [methodology](https://covidtracking.com/about-tracker/) page?

Any plans to make the page templates open source? I'd be happy to submit a PR for the JavaScript toggle.

**Comment by breyed** [comment]
Another approach is with tabs, like John Hopkins does on its [dashboard](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) with its `Cumulative Confirmed Cases` and `Active Cases` tabs and `Confirmed` and `Daily Increase` tabs. I think a checkbox would fit better with the style of the covidtracking site, but I thought I'd mention it as a useful point of reference.

In any case, the labeling on covidtracking should be updated. Currently, it's technically ambiguous as to whether it's reporting daily or cumulative data. Other sites, like John Hopkins and the [CDC](https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html), are careful to specify that aspect.
