### ISSUE TITLE
[SC Historical] 6/6 Numbers

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#510]
SC data was not updated on 6/6. The last screenshot of the day has the new data.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24xe9)

**Comment by MattHilliard** [comment]
The current hospitalization number is on a different page that doesn't seem to be screenshotted, but I was able to update everything else using the last 6/6 screenshot.

Before:
![image](https://user-images.githubusercontent.com/404503/85336291-616b0680-b4ac-11ea-8d85-37f4c633e528.png)

After:
![image](https://user-images.githubusercontent.com/404503/85336497-af800a00-b4ac-11ea-8717-99d36bf31788.png)
