### ISSUE TITLE
[AZ] Data mismatch

### ISSUE THREAD

**Issue by shorebound1336** [COVID19Tracking/issues#511]
When reviewing daily admissions, there are big discrepancies between state reported and covid project data; specifically on 5/28 (53 vs 817). https://azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php

**Comment by MattHilliard** [comment]
@shorebound1336, thanks for reporting this issue! Each day, CTP records data like "cumulative hospitalization" based on the current number provided by state sources. This can result in reporting artifacts like the huge jump you mentioned as the state reports a big bunch of past hospitalizations all on the same day. AZ's "hospitalized by date admitted" chart shows there are some major lags in the reporting of this data...the most recent is a few days old and from day to day they revise the number for older days. Between yesterday and today, for example, they added a hospitalization to May 9th!

I've updated our historical data to match what they provide as of tonight. This should be live on the website within an hour. Unfortunately, we don't yet have a way to make historical updates every day for states like AZ that do this so there will be divergence again as we go forward. We are looking at how best to improve our process to handle situations like this.

**Comment by shorebound1336** [comment]
Thank you for the clarification. I did notice after I sent this that the
totals reconcile despite the count discrepancies day to day.
