### ISSUE TITLE
[ME] Maine data page is now wrong

### ISSUE THREAD

**Issue by cvermilion** [COVID19Tracking/issues#512]
The Maine CDC page that hosts daily data updates changed a few days ago.

The new link is: https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/airborne/coronavirus/data.shtml

The historical data seems to be ok, but the screenshots are broken since the URL change.

**Comment by MattHilliard** [comment]
@cvermilion Thanks for letting us know! This should be fixed going forward.
