### ISSUE TITLE
Georgia numbers duplicated on 6/21 from 6/20

### ISSUE THREAD

**Issue by lkhemani** [COVID19Tracking/issues#513]
**State or US**: [Georgia]

**Describe the problem**
https://covidtracking.com/data/state/georgia 
the entry for the date Sun June 21 is a duplicate of Sat June 22.  You have the accurate data on your screen prints, just not in the grid on the main page.

**Link to data source**
https://covidtracking.com/screenshots/GA/GA-20200622-003304.png
this is actually your own source - it looks like the data just got added to the main page incorrectly.

thanks!

**Comment by muamichali** [comment]
Hi @lkhemani 

Our publish shift might have missed the GA update on Sunday. I am going to update the numbers based on the screenshot.

Here is the after snapshot 
![image](https://user-images.githubusercontent.com/1749380/85346389-363fe180-b4c3-11ea-93ac-200c3736ba85.png)

**Comment by lkhemani** [comment]
Thanks for your time!  The service you guys are providing is invaluable to our country!
