### ISSUE TITLE
Odd Data Number

### ISSUE THREAD

**Issue by shivenspatel** [COVID19Tracking/issues#515]
**State or US**: [State name, or "US" if this is an issue with country-wide data]
US

**Describe the problem**
A clear and concise description of what the data problem is.

In the JSON data, on 2020-03-01, the data shows an increase in 83 total test results, but 88 positive test results, effectively representing a 106% positive rate, which should technically be impossible. 

![image](https://user-images.githubusercontent.com/24969290/85497715-07e60300-b5a4-11ea-87d2-f561386c8061.png)

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.

**Comment by camille-le** [comment]
Hi @shivenspatel, I took a look at the [daily.json](https://covidtracking.com/api/v1/us/daily.json) for 2020-03-01 and the previous day 2020-02-09. 

- The "positiveIncrease" value is in the increase in "positive" from 2020-02-29 to 2020-03-01. 
- For 2020-03-01, we report "positiveIncrease" as 89 (388-299). 

```javascript
{
   "date":20200301,
   "states":3,
   "positive":388,
   "negative":14,
   "pending":null,
   "hospitalizedCurrently":null,
   "hospitalizedCumulative":null,
   "inIcuCurrently":null,
   "inIcuCumulative":null,
   "onVentilatorCurrently":null,
   "onVentilatorCumulative":null,
   "recovered":null,
   "dateChecked":"2020-03-01T00:00:00Z",
   "death":8,
   "hospitalized":null,
   "lastModified":"2020-03-01T00:00:00Z",
   "total":402,
   "totalTestResults":402,
   "posNeg":402,
   "deathIncrease":3,
   "hospitalizedIncrease":0,
   "negativeIncrease":-3,
   "positiveIncrease":89,
   "totalTestResultsIncrease":86,
   "hash":"3d4d65c707c4ebccea4304d86716fb6e265762e1"
},
{
   "date":20200229,
   "states":1,
   "positive":299,
   "negative":17,
   "pending":null,
   "hospitalizedCurrently":null,
   "hospitalizedCumulative":null,
   "inIcuCurrently":null,
   "inIcuCumulative":null,
   "onVentilatorCurrently":null,
   "onVentilatorCumulative":null,
   "recovered":null,
   "dateChecked":"2020-02-29T00:00:00Z",
   "death":5,
   "hospitalized":null,
   "lastModified":"2020-02-29T00:00:00Z",
   "total":316,
   "totalTestResults":316,
   "posNeg":316,
   "deathIncrease":1,
   "hospitalizedIncrease":0,
   "negativeIncrease":17,
   "positiveIncrease":24,
   "totalTestResultsIncrease":41,
   "hash":"27c8dfcf504c66796dd4842c82d37d8a8b7d0c88"
},
```
