### ISSUE TITLE
[KS] PCL Historicals and WS2

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#516]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for KS. However, KS's death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by karaschechtman** [comment]
Updated WS2 tooltips

**Comment by karaschechtman** [comment]
Deleting KS values on States Daily in the confirmed field
Before: 
![Before1](https://user-images.githubusercontent.com/15933271/85742360-2c8bc900-b6d1-11ea-8d8e-e01ebcb6229e.png)
![Before2](https://user-images.githubusercontent.com/15933271/85742454-41685c80-b6d1-11ea-999d-04c89da241a4.png)

After:
![After1](https://user-images.githubusercontent.com/15933271/85742550-547b2c80-b6d1-11ea-9c49-1167ea9a705f.png)
![After2](https://user-images.githubusercontent.com/15933271/85742545-53e29600-b6d1-11ea-87e6-a9092a377c19.png)

**Comment by jesseandersonumd** [comment]
DC'ed by JJA 6/26 9:57:00 a.m. ET
