### ISSUE TITLE
Wisconsin Confidence grade A+ doesn't match description

### ISSUE THREAD

**Issue by mheubusch** [COVID19Tracking/issues#519]
Wisconsin 
**Describe the problem**
Grade today shows an A+ rating but the description on  the Atlantic says "We're not sure about the quality of this data"  - not sure if this ia COVID19Tracking issue or an Atlantic issue

**Link to data source**
https://www.theatlantic.com/health/archive/2020/03/how-many-people-tested-sick-coronavirus-covid-each-state-america/608413/
<img width="694" alt="CleanShot 2020-06-24 at 20 17 23@2x" src="https://user-images.githubusercontent.com/20115914/85643640-5a81f680-b65a-11ea-93f9-bf7ef44e330a.png">

**Comment by camille-le** [comment]
Hi @mheubusch, I checked the link you shared. The grade reflects our [current data quality grade for Wisconsin](https://covidtracking.com/data/state/wisconsin): 
<img width="708" alt="2020-07-09_WI" src="https://user-images.githubusercontent.com/31285549/87121761-6368ef80-c238-11ea-8be8-48b2c381f863.png">
