### ISSUE TITLE
[RI] PCL Historicals and WS2

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#523]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for RI. However, RI’s death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

**Comment by MattHilliard** [comment]
Confirmed the data matched "Deaths", then removed "Deaths (Confirmed)" for RI between today and 5/12.

**Comment by MattHilliard** [comment]
Updated RI's source note for Deaths (confirmed) to Not Provided and explained in RI private notes

**Comment by the-daniel-lin** [comment]
DC'd by Daniel Lin
