### ISSUE TITLE
[ME] PCL Historicals and WS2

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#524]
As of 6/23, ME now provides separate confirmed and probable deaths. Deaths provided in the "Cumulative COVID-19 Cases by County" table are lumped but Confirmed and Probable can be separate by changing the "Case Status" in the "COVID-19 Case Trends" chart.

Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for ME. However, ME’s total death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field and confirmed and probably deaths should be separated beginning on 6/23.

**Comment by schmian** [comment]
**Changed the Worksheet2 tooltips**
Updated source for Deaths (confirmed) to "Select "Confirmed" in Case Status dropdown to view Confirmed Deaths" to reflect ME separating confirmed and probable deaths in "Case Trends" chart

**Comment by the-daniel-lin** [comment]
DZL is DCing this

**Comment by karaschechtman** [comment]
**BEFORE**
![before-deaths confirmed missing](https://user-images.githubusercontent.com/15933271/86131061-21f77800-bab3-11ea-98b0-c929d7c64b92.png)
**AFTER**
![after-deaths confirmed added](https://user-images.githubusercontent.com/15933271/86131174-4ce1cc00-bab3-11ea-9066-959e6c6f0af0.png)
