### ISSUE TITLE
[VA] Deaths - PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#525]
Need to amend historical total-deaths, historical confirmed-deaths and historical probable-deaths on 5/13 and prior.  

Confirmed-deaths missing or incorrect on 5/13 and prior (ex. on 5/2, we recorded 454 confirmed-deaths, but historical screenshot shows 572).  

Note historical screenshots for VA from COVID Tracking Project external-facing website.  https://covidtracking.com/data/state/virginia#historical Confirmed and probable began to be reported in the dashboard starting with the 4/21 12:19pm screen capture (not 6am one).  Here is the first one where we see confirmed and probable called out. https://covidtracking.com/screenshots/VA/VA-20200421-121931.png

**Comment by muamichali** [comment]
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/86368929-ca404480-bc4b-11ea-929d-db7a20ca0223.png)
