### ISSUE TITLE
[UT] PCL Historicals and WS2

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#526]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for UT. However, UT's death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

On 5/19, there was a discrepancy between the two values - "Deaths" was reported as 88 while "Deaths (confirmed)" was 80. State screenshots show that "Deaths" _should_ be 88, not 80 for that date.

**Comment by MattHilliard** [comment]
Confirmed the values matched "Deaths" (except the 5/19 mistake mentioned above), then removed "Deaths (confirmed) for UT between today and 5/12.

**Comment by MattHilliard** [comment]
Updated NH's source note for Deaths (confirmed) to Not Provided and explained in NH private notes

**Comment by the-daniel-lin** [comment]
DZL is DCing this
