### ISSUE TITLE
[NH] PCL Historicals and WS2

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#527]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for NH. However, NH's death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

**Comment by MattHilliard** [comment]
Confirmed the values matched "Deaths", then removed "Deaths (confirmed) for NH between today and 5/12.

**Comment by MattHilliard** [comment]
Updated NH's source note for Deaths (confirmed) to Not Provided and explained in NH private notes

**Comment by jesseandersonumd** [comment]
DC'ed by JJA 6/26 9:40:00 a.m. ET
