### ISSUE TITLE
[WY] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#530]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for WY. However, WY's death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Added note in Worksheet 2 

![Screen Shot 2020-06-25 at 7 59 39 AM](https://user-images.githubusercontent.com/67423649/85744553-d7908880-b6b9-11ea-8c65-8b09e2e30fd2.png)

**Comment by pscsharon** [comment]
![Screen Shot 2020-06-25 at 8 00 35 AM](https://user-images.githubusercontent.com/67423649/85744738-f8f17480-b6b9-11ea-819b-048f1efd7953.png)

**Comment by MattHilliard** [comment]
Confirmed the data matched "Deaths", then removed "Deaths (Confirmed)" between yesterday and 5/12 (today's cell was blank).

**Comment by MattHilliard** [comment]
Updated WY's source note for Deaths (confirmed) to Not Provided. KWS already wrote a private note about this.

**Comment by jesseandersonumd** [comment]
DC'ed by JJA 6/26 9:48:00 a.m. ET
