### ISSUE TITLE
[MO] PCL Historicals and WS2

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#531]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for MO. However, MO’s death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

5/12: Started reporting same value for deaths (probable and confirmed) and confirmed deaths

**Comment by jesseandersonumd** [comment]
“Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for MO. However, MO’s death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.”

**Comment by MattHilliard** [comment]
Confirmed the values matched "Deaths", then removed "Deaths (confirmed) for MO between today and 5/12.

**Comment by MattHilliard** [comment]
(Jesse updated the source note for Deaths (confirmed) and the private note this morning)

**Comment by jesseandersonumd** [comment]
JJA is double-checking this issue.
