### ISSUE TITLE
[NV] PCL Historicals and WS2

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#532]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for NV. However, NV's death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

**Comment by MattHilliard** [comment]
Confirmed they were identical to "Deaths", then removed "Deaths (confirmed)" from today back through 5/12.

**Comment by MattHilliard** [comment]
Updated NV's source note for Deaths (confirmed) to Not Provided and explained in NV private notes

**Comment by jesseandersonumd** [comment]
DC'ed by JJA 6/26 9:44:00 a.m. ET
