### ISSUE TITLE
[GA] PCL Historicals and WS2

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#533]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for GA. However, GA’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

5/12: CTP started to report values in both deaths (confirmed) and deaths.

**Comment by MattHilliard** [comment]
Confirmed they matched what we already had in "Deaths", then removed "Deaths (confirmed)" for GA between today and 5/12 when they were first recorded.

**Comment by MattHilliard** [comment]
(Jesse updated the source note for Deaths (confirmed) and the private note this morning)

**Comment by jesseandersonumd** [comment]
DC'ed by JJA 6/26 10:00:00 a.m. ET
