### ISSUE TITLE
[OK] PCL Historicals and WS2

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#534]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for OK. However, OK's death values represent lumped probable and confirmed figures, so they should only be recorded in the main "Deaths" field.

**Comment by MattHilliard** [comment]
Removed from Deaths (confirmed). The values matched Deaths so this screenshot is just evidence of where it previously stopped (5/12): 
![image](https://user-images.githubusercontent.com/404503/85798763-0c2d3000-b70c-11ea-8b81-b6f559728cda.png)

**Comment by the-daniel-lin** [comment]
DZL is DCing this
