### ISSUE TITLE
[WA] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#537]
On 6/21, we recorded 28,255 total cases, but it should be 28,225.  

This affects "Positive Cases (PCR)" and "Positive Cases (People, confirmed + probable)".

**Comment by camille-le** [comment]
**BEFORE** 
<img width="1054" alt="2020-06-21_WA_BEFORE" src="https://user-images.githubusercontent.com/31285549/86022780-a973b700-b9df-11ea-9518-3fe3bf2e0d47.png">

**AFTER** 
<img width="1045" alt="2020-06-21_AFTER_WA" src="https://user-images.githubusercontent.com/31285549/86022786-ac6ea780-b9df-11ea-97d9-747303459c5c.png">

Source: [Washington State Department of Health (CTP Screenshot)](https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/WA/WA-20200621-185137.png)
