### ISSUE TITLE
[AR] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#538]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for AR for only 6/15 - 6/23. However, AR's death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Added tooltip to the Confirmed-deaths cell and also added note in Process-notes. 

![Screen Shot 2020-06-25 at 3 50 06 PM](https://user-images.githubusercontent.com/67423649/85803367-d1230080-b6fb-11ea-8841-53f46ffced63.png)

**Comment by muamichali** [comment]
![image](https://user-images.githubusercontent.com/1749380/85961469-b1e4d700-b978-11ea-966d-8397d611e321.png)

Deleting values from Confirmed Deaths column that were captured 6/15-6/23
