### ISSUE TITLE
[DC] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#539]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for DC. However, DC’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

Note we started recording confirmed-deaths starting 5/12.  The numbers have matched total-deaths each day.

**Comment by pscsharon** [comment]
![Screen Shot 2020-06-25 at 4 02 07 PM](https://user-images.githubusercontent.com/67423649/85803961-3d523400-b6fd-11ea-8804-cacb95a27e83.png)

**Comment by muamichali** [comment]
1. I deleted the value from Worksheet2

2. I deleted the values from States Daily
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/85961576-57984600-b979-11ea-9ee7-ca91d726260b.png)

**AFTER**
![image](https://user-images.githubusercontent.com/1749380/85961600-7f87a980-b979-11ea-8d10-84082a3d60a6.png)
