### ISSUE TITLE
Forgot to add deaths back into positives on Illinois

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#54]
Today's 4pm publish had an error on Illinois numbers.

Changed from:
![image](https://user-images.githubusercontent.com/1327983/77596782-57e4f900-6ed3-11ea-9458-f095ebb20425.png)

To:
![image](https://user-images.githubusercontent.com/1327983/77596811-70edaa00-6ed3-11ea-9ea2-99219563ee94.png)

**Comment by jdmaresco** [comment]
reverting this temporarily, they may have changed process

**Comment by jdmaresco** [comment]
we didn't add deaths back in, because we pulled the reported positives from this release:
http://www.dph.illinois.gov/news/public-health-officials-announce-330-new-cases-coronavirus-disease

however with the numbers now present on the site, it's clear that positive valued didn't have the deaths added back in. so we will go ahead with the change detailed above, and reach out to Illinois to confirm that our assumption is correct

**Comment by careeningspace** [comment]
![Screen Shot 2020-03-26 at 12 00 12 PM](https://user-images.githubusercontent.com/43073915/77671294-c2427b80-6f5d-11ea-9700-0256382773b9.png)
