### ISSUE TITLE
NJ data appears to be incorrect again

### ISSUE THREAD

**Issue by ffrehner** [COVID19Tracking/issues#540]
Hello.  The NJ data appears to be incorrect again.

Thanks.
![image](https://user-images.githubusercontent.com/64551166/85807051-9756f780-b705-11ea-8f0d-8c9a5e4e3574.png)

**Comment by muamichali** [comment]
Hi @ffrehner 

NJ has just added 1854 probable deaths to their count, but we are still awaiting the time series of when they occurred. 
We hope to get that information as soon as possible so we can correct the time series... 

If you are following us on Twitter, we also try to explain these kinds of anomalies there. 
![image](https://user-images.githubusercontent.com/1749380/85815753-4102ac80-b737-11ea-8f1c-7470fb264acc.png)
