### ISSUE TITLE
[WI Historicals] Time Series of Probable Cases

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#541]
**State or US**: Wisconsin

**Describe the problem**
On 6/25 Wisconsin released about 2800 probable cases without a time series, so they were all attributed to today.

**Link to data source**
[WEDSS Probable COVID-19 Cases 6.25.2020.xlsx](https://github.com/COVID19Tracking/issues/files/4834592/WEDSS.Probable.COVID-19.Cases.6.25.2020.xlsx)

**Comment by MattHilliard** [comment]
@muamichali and I updated our historical numbers based on the state spreadsheet. It should be visible on the web site within an hour. Analysis spreadsheet: https://docs.google.com/spreadsheets/d/1CddFkiCKCY6zs5NsrILox6obhfqudAxHDzxC61vSxds/edit#gid=455785625
