### ISSUE TITLE
[FL] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#542]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for FL. However, FL’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Added tooltip as well as process note.  

<img width="886" alt="Screen Shot 2020-06-26 at 6 25 13 AM" src="https://user-images.githubusercontent.com/67423649/85861895-db81e080-b775-11ea-9343-e8ea52c89b04.png">

**Comment by pscsharon** [comment]
Updated change log to show we started recording confirmed deaths on 5/12.  However, there was no change in notes on state's website. 

5/11 6pm screenshot: https://covidtracking.com/screenshots/FL/FL-20200511-183619.png
5/12 noon screenshot: https://covidtracking.com/screenshots/FL/FL-20200512-122938.png

**Comment by pscsharon** [comment]
On 6/27, Restored confirmed deaths since the data dictionary reflects that FL deaths are confirmed.   

Tooltips and process notes in WS2 were updated. 

REFERENCE:
Screenshot of current dashboard here.  Full text of fine print in bottom right says this: "The Deaths by Day chart shows the total number of Florida residents with confirmed COVID-19 that died on each calendar day (12:00 AM - 11:59 PM). Death data often has significant delays in reporting, so data within the past two weeks will be updated frequently."

<img width="1390" alt="Screen Shot 2020-06-29 at 7 05 05 AM" src="https://user-images.githubusercontent.com/67423649/86017942-85ad7280-b9d9-11ea-9209-befe8f766686.png">

**Comment by pscsharon** [comment]
Updated "State Website Deaths" and "Reasoning" in PCL to correspond to note added in "Misc Notes."

**Comment by karaschechtman** [comment]
Restoring deaths (confirmed) value for 6/26 and closing the issue
![Screen Shot 2020-06-29 at 10 53 49 AM](https://user-images.githubusercontent.com/15933271/86021317-f6af5300-b9f6-11ea-89af-98f30bef72c5.png)
![Screen Shot 2020-06-29 at 10 54 40 AM](https://user-images.githubusercontent.com/15933271/86021316-f57e2600-b9f6-11ea-80bc-70b01e4eabfa.png)
