### ISSUE TITLE
[GU] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#543]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for GU. However, GU’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Updated tooltip to "no data" and added process note. 

<img width="884" alt="Screen Shot 2020-06-26 at 6 35 45 AM" src="https://user-images.githubusercontent.com/67423649/85862965-51d31280-b777-11ea-9940-1f6e66bf9e34.png">

**Comment by muamichali** [comment]
**Before**
![image](https://user-images.githubusercontent.com/1749380/86015371-7b966e80-b9ef-11ea-86de-2ef85fa45f15.png)

**AFTER** 
![image](https://user-images.githubusercontent.com/1749380/86015507-a84a8600-b9ef-11ea-8cd8-915bdcb1e4fb.png)
