### ISSUE TITLE
[IA] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#545]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for IA. However, IA’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Updated tooltip from "Dashboard" to "no data" as well as added process note. 

<img width="876" alt="Screen Shot 2020-06-26 at 7 02 03 AM" src="https://user-images.githubusercontent.com/67423649/85865599-ff93f080-b77a-11ea-92b7-737124960494.png">

**Comment by muamichali** [comment]
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/86019558-c1096a80-b9f4-11ea-9ffb-221dbcdba7af.png)

**AFTER**
![image](https://user-images.githubusercontent.com/1749380/86019687-e39b8380-b9f4-11ea-9e9b-c7f38505d80b.png)
