### ISSUE TITLE
[MT] PCL Historicals and WS2

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#546]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for MT. However, MT’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by karaschechtman** [comment]
WS2 edits:
![Screen Shot 2020-06-26 at 10 11 25 AM](https://user-images.githubusercontent.com/15933271/85866465-6b835280-b795-11ea-82b6-6d1720751e45.png)
![Screen Shot 2020-06-26 at 10 12 58 AM](https://user-images.githubusercontent.com/15933271/85866591-a08fa500-b795-11ea-941e-97b305532503.png)

**Comment by karaschechtman** [comment]
States Daily edits

Before:
![Screen Shot 2020-06-26 at 10 14 49 AM](https://user-images.githubusercontent.com/15933271/85866784-f1070280-b795-11ea-8f1f-f6624e2d360f.png)
![Screen Shot 2020-06-26 at 10 14 58 AM](https://user-images.githubusercontent.com/15933271/85866822-fe23f180-b795-11ea-9b96-33284d5f44c9.png)
After:
![Screen Shot 2020-06-26 at 10 16 22 AM](https://user-images.githubusercontent.com/15933271/85866932-2d3a6300-b796-11ea-845e-4e116017779f.png)
![Screen Shot 2020-06-26 at 10 16 29 AM](https://user-images.githubusercontent.com/15933271/85866940-2f042680-b796-11ea-916f-739aa142e5ce.png)

**Comment by jesseandersonumd** [comment]
JJA DC-ed 6/26, 10:30:00 a.m. ET
