### ISSUE TITLE
[NE] PCL Historical and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#547]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for NE. However, NE’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Added tooltip saying "no data" and process note. 

<img width="909" alt="Screen Shot 2020-06-26 at 7 10 51 AM" src="https://user-images.githubusercontent.com/67423649/85866425-3585a480-b77c-11ea-9d14-dd5bad1a8b9a.png">

**Comment by camille-le** [comment]
Thank you @pscsharon ! 

**BEFORE**
<img width="800" alt="BEFORE_NE" src="https://user-images.githubusercontent.com/31285549/86021281-c7d8b300-b9dd-11ea-8f28-1ff4d2c6f23a.png">

**AFTER**
<img width="815" alt="AFTER_NE" src="https://user-images.githubusercontent.com/31285549/86021290-cb6c3a00-b9dd-11ea-9ef2-cb67e5448f1f.png">
