### ISSUE TITLE
[OR] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#549]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for OR. However, OR’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Added tooltip saying "no data" as well as process note. 

<img width="884" alt="Screen Shot 2020-06-26 at 7 16 16 AM" src="https://user-images.githubusercontent.com/67423649/85866943-0a4f8500-b77d-11ea-9fa4-69f764917568.png">

**Comment by muamichali** [comment]
### Cases
There are some missing values for Positive Cases PCR in States Daily...... so I am leaving this ticket open for further investigation

### Deaths

**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/85962382-69c8b300-b97e-11ea-923d-d197ee658ef7.png)

**AFTER**
![image](https://user-images.githubusercontent.com/1749380/85962471-e2c80a80-b97e-11ea-8c74-6880d6fc3717.png)

**Comment by karaschechtman** [comment]
DC'd by JJA
