### ISSUE TITLE
[WV] PCL Historicals and WS2

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#550]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for WV. However, WV’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

5/12: CTP started reporting same values for deaths (confirmed) and deaths.

**Comment by muamichali** [comment]
Updated States Daily

**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/85961901-acd55700-b97b-11ea-8c41-1e3ddb8368cc.png)

**AFTER** 
![image](https://user-images.githubusercontent.com/1749380/85961932-da220500-b97b-11ea-8bc2-d85a9ca47b74.png)

NOTE: Between 5/23 and 6/4 the values for **positive cases (PCR)** are missing
