### ISSUE TITLE
[NY] PCL Historicals and WS2

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#552]
Death values are historically recorded in both the "Deaths" and "Deaths (Confirmed)" columns for NY. However, NY’s death values are unclear about what they represent, so they should only be recorded in the main "Deaths" field.

**Comment by pscsharon** [comment]
Updated tooltip and added process note. 

<img width="886" alt="Screen Shot 2020-06-26 at 7 21 24 AM" src="https://user-images.githubusercontent.com/67423649/85867396-ae393080-b77d-11ea-9e9a-edcff80af41c.png">

**Comment by muamichali** [comment]
States Daily 

**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/85961653-e60cc780-b979-11ea-8619-a0a7912b504c.png)

**AFTER**
![image](https://user-images.githubusercontent.com/1749380/85961671-0ccafe00-b97a-11ea-9e40-9ed2b7b5655f.png)

**Comment by karaschechtman** [comment]
DC'd by SNW
