### ISSUE TITLE
MD 3/16 wrong historical value

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#554]
In the MD csv file the entry on 3/16 for positive cases is 2895. This is much larger than that for 3/15 or 3/17. It also doesn't match the MD department of health value for that day of 37. I think the 3/16 value is in error.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_259sh)

**Comment by space-buzzer** [comment]
Here's what I'm downloading now from CTP:

```
$ curl -s https://covidtracking.com/api/v1/states/md/daily.csv | cut -d, -f1-3 | grep -A 1 -B 2 20200316
20200318,MD,85
20200317,MD,57
20200316,MD,37
20200315,MD,31
```

The 16th is 37 cases, just like in MD's published time series.

**Comment by dmv6002** [comment]
Agree with space-buzzer. The csv file I was using was from  6/20/20 and I had only gotten around to to using it a day or two ago while testing some data reduction software. The 3/16 entry must have been corrected in the interim.

**Comment by MattHilliard** [comment]
This was addressed by @muamichali on 24 June
