### ISSUE TITLE
[WV] PCL Cases Historicals in States Daily 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#555]
**State or US**: WV

**Describe the problem**
### Cases
NOTE: Between 5/23 and 6/4 the values for positive cases (PCR) are missing

**Link to data source**
Discovered while working on #550

**Comment by camille-le** [comment]
Per Slack thread, between 5/22 and 6/4, we don't have the values for **Positive Cases (PCR)**. Prior to 5/22, WV was reporting confirmed cases only. From 6/5 onward, we were able to access confirmed vs. probable cases from WV. 

Removed **Positive Cases (PCR)** for 5/22: 
BEFORE: 
<img width="1086" alt="BEFORE" src="https://user-images.githubusercontent.com/31285549/86688436-f137a700-bfba-11ea-8751-d1c3e553c8a5.png">

AFTER: 
<img width="1097" alt="AFTER" src="https://user-images.githubusercontent.com/31285549/86688470-f98fe200-bfba-11ea-9078-9638d184da24.png">

Added **Positive Cases (PCR)** for to 5/2   
BEFORE: 
<img width="1094" alt="BEFORE2" src="https://user-images.githubusercontent.com/31285549/86688563-0f9da280-bfbb-11ea-95a4-e7cc0b3dd3a4.png">

AFTER: 
<img width="1092" alt="AFTER2" src="https://user-images.githubusercontent.com/31285549/86688631-1fb58200-bfbb-11ea-9d5c-293dce6841b2.png">
