### ISSUE TITLE
[OR] PCL Case Historicals in States Daily

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#556]
**State or US**: OR

**Describe the problem**
Cases
There are some missing values for Positive Cases PCR in States Daily.

**Link to data source**
Found while working on #549

**Comment by camille-le** [comment]
Hey @muamichali, on May 4th, [Oregon started reporting confirmed and presumptive cases](https://www.oregon.gov/oha/ERD/Pages/Oregon-reports-65-confirmed-COVID-19-cases-14-presumptive-cases-no-deaths.aspx). We've removed "Positive Cases (PCR)" from 2020-04-30 and 2020-04-29. 

So while it appears there were missing values between 2020-05-01 and 2020-05-02, that is not the case. 

**BEFORE** 
<img width="911" alt="BEFORE_OREGON" src="https://user-images.githubusercontent.com/31285549/86478496-3039d400-bcff-11ea-819a-65fd16823b4a.png">

**AFTER** 
<img width="914" alt="AFTER_OREGON" src="https://user-images.githubusercontent.com/31285549/86478515-38920f00-bcff-11ea-8345-4cfadfc59ee2.png">

Thanks!
Camille
