### ISSUE TITLE
[WI] PCL Historicals and WS2 

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#557]
We currently report deaths (confirmed) and deaths as the same value, but we should be differentiating between deaths (confirmed) and deaths (probable) to obtain the total value for deaths.

**Comment by karaschechtman** [comment]
IMPORTANT. Make a public note before we release: "WI started breaking out its probable deaths in early June. We caught these figures on 6/29, on which there were 7 cumulative probable deaths, and only have data for them past that date. We are in the process of securing a historical time series."
Then we should reach out to WI to get that data
I am flagging WI as an "Other" problem with deaths (we should keep it as that) and making a note we should do this before release.
