### ISSUE TITLE
[FL] Hospitalization Data

### ISSUE THREAD

**Issue by preddy17** [COVID19Tracking/issues#558]
FL doesn't report daily numbers for hospitalizations. Can we please remove or amend it in the API?

**Comment by camille-le** [comment]
As of July 10, Florida is reporting current hospitalizations as those with a "[primary diagnosis of COVID-19](https://bi.ahca.myflorida.com/t/ABICC/views/Public/COVIDHospitalizationsCounty?%3AshowAppBanner=false&%3Adisplay_count=n&%3AshowVizHome=n&%3Aorigin=viz_share_link&%3AisGuestRedirectFromVizportal=y&%3Aembed=y)."
