### ISSUE TITLE
[DC] Cases - PCL Historicals and WS2 

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#560]
Cases reported in DC are not clearly defined as confirmed cases. However, from 4/29 - 6/30, this value was reported in the confirmed column (`Positive Cases (PCR)`). Should correct for historicals and WS2 to not reflect this any more.

**Comment by jesseandersonumd** [comment]
BEFORE - 
![Screen Shot 2020-07-07 at 11 01 14 AM](https://user-images.githubusercontent.com/57415941/86800716-5209c280-c041-11ea-9683-f12929b2c563.png)

**Comment by jesseandersonumd** [comment]
AFTER - Corrected historicals by removing values from Positive Cases (PCR).

![Screen Shot 2020-07-07 at 11 02 01 AM](https://user-images.githubusercontent.com/57415941/86800790-6352cf00-c041-11ea-8680-f705cf4b1ba6.png)
