### ISSUE TITLE
[IN] Cases - PCL Historicals and WS2

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#561]
Cases reported in IN were not clearly annotated as confirmed cases. However, this number was still reported in the confirmed cases column (`Positive Cases (PCR)`) from 4/29 to 6/30. Should correct historicals and WS2 as needed.

**Comment by jesseandersonumd** [comment]
BEFORE -

![Screen Shot 2020-07-07 at 10 57 33 AM](https://user-images.githubusercontent.com/57415941/86800232-cee86c80-c040-11ea-8e2a-205c7d380fb0.png)

**Comment by jesseandersonumd** [comment]
AFTER - Corrected historicals by removing the value from the positive cases (PCR) column, as IN lumps confirmed and probable values. 

![Screen Shot 2020-07-07 at 10 58 04 AM](https://user-images.githubusercontent.com/57415941/86800334-ea537780-c040-11ea-8107-79c9e0dc495b.png)
