### ISSUE TITLE
[LA] Cases - PCL Historicals and WS2

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#562]
Cases reported in LA were not clear as to whether they're confirmed. However, this value was reported in the confirmed column `Positive Cases (PCR)` on WS2 from 4/22 - 6/30. Historicals and WS2 needs to be corrected to reflect this annotation.

**Comment by jesseandersonumd** [comment]
BEFORE
![Screen Shot 2020-07-07 at 10 19 44 AM](https://user-images.githubusercontent.com/57415941/86795400-87131680-c03b-11ea-8aca-d61894af1696.png)

**Comment by jesseandersonumd** [comment]
AFTER - Corrected to remove values from positive cases (PCR), as LA lumps probables and confirmed for cases. 

![Screen Shot 2020-07-07 at 10 20 36 AM](https://user-images.githubusercontent.com/57415941/86795485-9db96d80-c03b-11ea-913d-b5258186436c.png)
