### ISSUE TITLE
[MS] 6/30 total test numbers were used instead of PCR tests only

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#563]
**State or US**: MS

**Describe the problem**
6/30 total test numbers were used instead of PCR tests only

**Link to data source**
https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/MS/MS-20200630-184210.png

**Comment by brianskli** [comment]
Thank you! Our records displayed an incorrect value (299511) for MS' PCR testing totals on 6/30. This has been updated to reflect the correct number (287546) for 6/30 PCR totals by means of a screenshot of MS' website.
<img width="845" alt="MS 6:30 Before" src="https://user-images.githubusercontent.com/66738237/86286905-4f2c4f00-bbb5-11ea-850a-f204f39bddfd.png">
<img width="791" alt="MS 6:30 After" src="https://user-images.githubusercontent.com/66738237/86286921-55223000-bbb5-11ea-8010-a42d06a3c6fe.png">
