### ISSUE TITLE
[CA Historicals] 7/1 California backfilled test information from the last few days

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#567]
**State or US**: California

**Describe the problem**
On 7/1 CA reported ~9k tests;, but  actually some were from yesterday, some from the day before that etc.

**Link to data source**
![image](https://user-images.githubusercontent.com/1749380/86360510-7da33c00-bc40-11ea-9214-267872b6455e.png)

**Comment by space-buzzer** [comment]
We have 5 values that differ between what's currently reported by the state of California and CTPs data.



Date | CA | CTP
-- | -- | -- 
20200701 |   | 232657
20200630 |  232657 | 222917
20200629 |  **226759** | 216550
20200628 |  **218539** | 211243
20200627 |  **211851** | 206433
20200626 |  **206731** | 200461
20200625 |  **200545** | 195571
20200624 |  195571 | 190222


We're also shifted by 1 day from CA's published data

**Comment by space-buzzer** [comment]
The numbers keep changing, we can patch now and repeat later, as needed. I don't know whether it's a process change from what they've been doing

**Comment by space-buzzer** [comment]
This stabilized now, so we'll backfill with the numbers displayed on the dashboard now

2020-07-05 | 260155 | 265985 |  
-- | -- | -- | --
2020-07-04 | 254745 | 257388 |  
2020-07-03 | 248235 | 248235 |  
2020-07-02 | 240195 | 242547 |  
2020-07-01 | 232657 | 236139 |  
2020-06-30 | 222917 | 228732 |  
2020-06-29 | 216550 | 219252 |  

![Screenshot from 2020-07-17 10-45-53](https://user-images.githubusercontent.com/62236447/87815670-e979cd00-c81a-11ea-9b6a-6483bb6da6a3.png)
