### ISSUE TITLE
Official testing data for Puerto Rico

### ISSUE THREAD

**Issue by sacundim** [COVID19Tracking/issues#568]
**State or US**: Puerto Rico

**Describe the problem**

Since Puerto Rico's Department of Health doesn't publish tests data regularly, and when it does it doesn't do so in any manner or medium that's amenable to automatic capture, the testing data in the Project for Puerto Rico is very sorely out of date, leading to [reports that show, for example, Puerto Rico's COVID-19 positive test rate at 100%](https://coronavirus.jhu.edu/testing/testing-positivity) which then [get picked up by the press](https://www.metro.pr/pr/noticias/2020/07/02/puerto-rico-tiene-la-mayor-tasa-de-casos-positivos-de-coronavirus-en-estados-unidos.html).

I have been manually compiling a set of the official data that has been available. The official reports linked below are shared with some journalists by the Department of Health, with no appreciable schedule. These journalists tweet images of these reports out, which I have collected and copied their data into a CSV (also linked) over at my repo for my Puerto Rico data project: 

* https://github.com/sacundim/covid-19-puerto-rico

Insomuch as it is required I grant permission for you to use my CSVs (which I understand are facts and therefore not copyrightable anyway).

* [CSV file with data from all of the below](https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/data/PuertoRico-bioportal.csv)
* [Bio Portal report dated June 30, with data up to June 29](https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-06-29/2020-06-29_bioportal.jpg)
* [Bio Portal report dated June 15, with data up to June 12](https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-06-12/2020-06-12_bioportal.jpeg)
* [Bio Portal report dated June 8, with data up to June 6](https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-06-06/2020-06-06_bioportal.jpeg)
* [Bio Portal report dated May 29, with data up to May 28](https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-05-28/2020-05-28_bioportal.jpeg)
* [Bio Portal report dated May 23, with data up to May 21](https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-05-21/2020-05-21_bioportal.jpeg)

While there is no evident path to automating the capture of this data, even a small one-time manual update to your numbers would likely avoid some modest amount of public misinformation.

**Comment by MattHilliard** [comment]
@sacundim, thank you for bringing this to our attention! I've updated our historical data based on these five data points. It should be visible on the web site within an hour. Hopefully we can get a more reliable official source at some point, but in the meantime if you catch more things like this, please don't hesitate to open more Github issues!

**Comment by muamichali** [comment]
@sacundim would you kindly share with us the twitter handles of the journalists that post this info so we can follow them as well?

**Comment by sacundim** [comment]
@muamichali The two journalists I follow who post these on Twitter are @angelicaserran0 and @RobbyCortes.
