### ISSUE TITLE
Michigan negatives posted for 3/25/2020

### ISSUE THREAD

**Issue by catawbasam** [COVID19Tracking/issues#57]
https://www.michigan.gov/coronavirus/0,9753,7-406-98163-520743--,00.html
Cumulative    Number of Specimens Tested for COVID-19 - Last Updated 3/25/2020
--
Lab Type | Negative    Tests | Positive    Tests | Total    Specimens Tested
Commercial | 713 | 30 | 744
Hospital | 3296 | 1866 | 5261
Public Health | 2541 | 557 | 3104
Grand Total | 6550 | 2453 | 9109

**Comment by mdturner** [comment]
Came here to share the same issue--Michigan now shows the number of negative tests.  Please pull these and stop rolling forward the number from 3/20.

**Comment by careeningspace** [comment]
We are actively debating this issue. MI is actually reporting **specimens** which does not equal people tested:
![Screen Shot 2020-03-27 at 1 16 34 AM](https://user-images.githubusercontent.com/43073915/77724159-a7592100-6fc8-11ea-93ff-a008f5c4bb4a.png)

We have reached out to the state for more clarification, but it is hard for us to translate into a "People tested" which us what we strive to report

**Comment by catawbasam** [comment]
Michigan is not being updated according to the covid19tracking web page because it is reporting specimens rather than people tested. I urge you to report the specimen counts (with caveats) for the following reasons:

1. Other states are very likely double-counting people who have been tested multiple times.
2. Michigan’s confirmed case count is close to the reported positive count, suggesting they are not systematically taking multiple specimens (e.g. nose and mouth) per person.
3. Ramp up in total test capacity is important to track in its own right.

**Comment by catawbasam** [comment]
Another reason: Your data is the primary source of US test counts in the worldwide tracker at:
https://finddx.shinyapps.io/FIND_Cov_19_Tracker/  
They are tracking tests performed as opposed to people tested.

**Comment by schwartzadev** [comment]
See #60 . This has been noted in the MI notes.
