### ISSUE TITLE
[WA] 200 count lag in data 

### ISSUE THREAD

**Issue by camille-le** [COVID19Tracking/issues#570]
**State or US**: WA 

**Describe the problem**
"WA question from Front - looks like we have a 200ish count lag that causes a blip in our data. I didn't want to match the historical data without checking in" - @careeningspace 

**Link to data source**
N/A

**Comment by space-buzzer** [comment]
Cumulative cases and death downloaded from WA's dashboard today

[wa_cases_death_20200703.zip](https://github.com/COVID19Tracking/issues/files/4871735/wa_cases_death_20200703.zip)
