### ISSUE TITLE
[HI] PCL Historicals and WS2

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#571]
Hawaii's positive cases appear to lump together probables and confirmed, but WS2 reports this value under 'positive cases (PCR)'. We should delete this value and only put it in 'Positive Cases (People, confirmed + probable)'

**Comment by space-buzzer** [comment]
Same goes for PCR positive/negative test results. Since we use the same source data to calculate them

**Comment by jesseandersonumd** [comment]
BEFORE

![Screen Shot 2020-07-07 at 10 05 09 AM](https://user-images.githubusercontent.com/57415941/86793765-c6d8fe80-c039-11ea-9447-a99252f7ec03.png)

**Comment by jesseandersonumd** [comment]
AFTER - Corrected historicals for cases by removing values in positive cases (PCR) and leaving the values in positive (confirmed and probable) only. 

![Screen Shot 2020-07-07 at 10 07 19 AM](https://user-images.githubusercontent.com/57415941/86793806-d1939380-c039-11ea-8e34-a9a419e09568.png)

**Comment by jesseandersonumd** [comment]
BEFORE -
![Screen Shot 2020-07-07 at 10 34 42 AM](https://user-images.githubusercontent.com/57415941/86797434-a7dc6b80-c03d-11ea-83bb-4ea5f4340627.png)

**Comment by jesseandersonumd** [comment]
AFTER - removed positive tests (PCR) and negative tests (PCR) values _**because both of these values are calculated based on positive cases (PCR), as noted by Rebma**_

![Screen Shot 2020-07-07 at 10 35 31 AM](https://user-images.githubusercontent.com/57415941/86797542-c8a4c100-c03d-11ea-8850-656c8ab2823a.png)
