### ISSUE TITLE
[ID] Historicals Fill out historical info for current COVID-19 hospitalizations & ICU

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#572]
**State or US**: Idaho

**Describe the problem**
We did not capture these values before but they are available, so we should fill out the historical values

**Link to data source**
https://public.tableau.com/profile/idaho.division.of.public.health#!/vizhome/DPHIdahoCOVID-19Dashboard_V2/Story1 Click Hospitalizations

**Comment by muamichali** [comment]
[2020-07-03__CTP_ID_Update.xlsx](https://github.com/COVID19Tracking/issues/files/4871347/2020-07-03__CTP_ID_Update.xlsx)

**Comment by camille-le** [comment]
Hey @muamichali, I took a look at [Idaho's Tableau dashboard](https://public.tableau.com/profile/idaho.division.of.public.health#!/vizhome/DPHIdahoCOVID-19Dashboard_V2/Story1) and exported data from the Hospitalizations tab. Attached is a spreadsheet with a proposed update - please see "CTP_Update" tab: [2020-07-03__CTP_ID_Update.xlsx](https://github.com/COVID19Tracking/issues/files/4871351/2020-07-03__CTP_ID_Update.xlsx)

Can you please review before we make an update for 2020-03-26 to 2020-06-28 for **In ICU   – Currently** and **Hospitalized –   Currently**?  

Thanks!
Camille 

**Link to Data Source(s)**: 
* **ICU**: "Number of hospitalized and ICU with confirmed COVID-19" [C_in_ICU_Full_Data_data.xlsx](https://github.com/COVID19Tracking/issues/files/4871342/C_in_ICU_Full_Data_data.xlsx)
* **Hospitalizaitons**: "Patients currently hospitalized in an inpatient bed who have suspected or confirmed COVID-19" [S_and_C_Hospitalized_Full_Data_data.xlsx](https://github.com/COVID19Tracking/issues/files/4871343/S_and_C_Hospitalized_Full_Data_data.xlsx)

**Comment by camille-le** [comment]
Update - closing this ticket and moving to double-check.
