### ISSUE TITLE
[IL] 7/2 numbers weren't updated on dash, they are provided via a press release 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#573]
**State or US**:  IL

**Describe the problem**
7/2 numbers weren't updated on dash, they are provided via a press release 

**Link to data source**
http://dph.illinois.gov/news/public-health-officials-announce-869-new-confirmed-cases-coronavirus-disease

**Comment by muamichali** [comment]
DATA 

> Currently, IDPH is reporting a total of 144,882 cases, including 6,987 deaths
> Within the past 24 hours, laboratories have reported 30,262 specimens for a total of 1,666,317.  


BEFORE 
![image](https://user-images.githubusercontent.com/1749380/86495215-5cc50e80-bd46-11ea-9118-052ea943d5a0.png)

**Comment by hackerlikecomputer** [comment]
came here to post this. 

I just contacted the state department of health -- they've updated the page. Do a hard refresh of the page if it's not showing updated numbers. I expect the covid tracking project's data will be updated withe the new figures whenever they run an update next.

**Comment by qpmnguyen** [comment]
The press release linked above does not include probable counts -- carrying over probable cases and deaths from the previous day (1093 probable cases and 201 probable deaths). 
AFTER
![image](https://user-images.githubusercontent.com/25627274/86496782-dbbd4580-bd4c-11ea-8b22-c5125db22b4d.png)
![image](https://user-images.githubusercontent.com/25627274/86496798-ec6dbb80-bd4c-11ea-9453-2cec43f676e8.png)
