### ISSUE TITLE
[Data Quality] Add Captured Data

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#574]
Adding columns to capture (WS2 & States Daily):

**Cases**
1. Probable Cases

**Deaths**
2. Deaths Column - All the Deaths with COVID 19 lab test regardless of cause of death

**AntiGen**
3. Antigen tests total (people)
( [Example in MI](https://services6.arcgis.com/Bd4MACzvEukoZ9mR/ArcGIS/rest/services/Dashboard_Daily_Numbers_Automated/FeatureServer/0/query?where=Board%3D%27Test+Antigen%27&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) )
4. Antigen tests positive (people)
5. Antigen tests 
6. Antigen tests positive

---
**Finalize Decision & Naming**
- [ ] Meet with Amanda, Quang, Kara and Michal to discuss (CC ESK & PR)
--- 
**Update DEV SHEET**
_Do in a test sheet first!_
- [ ] Add column to WS2 
- [ ] Add column to States Daily 
- [ ] Add column to Checks
- [ ] Update Apps Script to copy values to Checks and States Daily
- [ ] Check that auxiliary spreadsheets aren't impacted (race, state grades, terminology)
---
**Documentation Update**
- [ ] Update [Data Dictionary](https://docs.google.com/spreadsheets/d/13Lb_qJXwgtx5ySeXf_XyZkod9VAxEPGb3rmj8KUMQ8o/edit#gid=0)
--- 
**Capture Documentation** 
More steps for morning shift - @karaschechtman to add 

**Backfill Documentation** 
Deaths ^& Cases can be backfilled

**Comment by amandafrench** [comment]
I would also like to add a column & and API field to explicitly capture Probable cases! I think there's a case to be made for breaking them out on our web tables as well.

**Comment by amandafrench** [comment]
Thanks for editing @muamichali

**Comment by muamichali** [comment]
Hi stale-bot! For once this really is done. Back-filling of probable cases still ongoing but this can be closed.
