### ISSUE TITLE
[AR] SVP Historicals and WS2

### ISSUE THREAD

**Issue by jaclyde** [COVID19Tracking/issues#575]
We have been recording AR's Total Tests as "Total PCR Tests (people)", however we received information from outreach that they are (partly) specimens. Need to move values to column "Total Tests (PCR)." 

See --- AR 6/26 SvP Update --- in Slack for details.

**Comment by jaclyde** [comment]
I updated WS2.
<img width="441" alt="Screen Shot 2020-07-03 at 7 02 33 PM" src="https://user-images.githubusercontent.com/66583275/86503163-11b7f500-bd60-11ea-8ef7-c62f8f41af75.png">
<img width="822" alt="Screen Shot 2020-07-03 at 7 01 18 PM" src="https://user-images.githubusercontent.com/66583275/86503164-12e92200-bd60-11ea-965d-ebe8270011e2.png">

**Comment by MattHilliard** [comment]
Before we move the column, a couple concerns:
(a) Before 5/15, the column is calculated via formula. Are there really supposed to be formulas on States Daily?
(b) From 5/12 to 5/14, the formula adds "Positive Cases (PCR)" to Negatives. This doesn't seem like something we want to put in "Positive Tests (PCR)"
(c) Before 5/12, the formula is Positives + Negatives.
