### ISSUE TITLE
[AK] Histoicals 7/5 update was missed by pub shift

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#579]
BEFORE
![image](https://user-images.githubusercontent.com/1749380/86630660-1ddbc680-bf9b-11ea-938d-982eda623222.png)

AFTER
![image](https://user-images.githubusercontent.com/1749380/86631186-ce49ca80-bf9b-11ea-8aa1-649ff5626d58.png)

**Comment by camille-le** [comment]
Hey @muamichali, would this update be for July 6? I checked out two of the AK press releases below. This is what I think should be the updated for July 6: 

* Total Tests (PCR): 
* Positive Cases: 1166 
* Negative:  128330 - 1166 = 127164
* Currently Hospitalized: 25 
* Currently on Ventilator: 2 
Recovered: 552 
* Deaths: 16 

> CASE COUNT SUMMARY, Sunday, **July 5, 2020** 
> DHSS today announced 32 people with COVID-19 in Alaska. 27 are residents in four communities: Anchorage (22), Fairbanks (2), Seward (2) and Palmer (1). The total number of Alaska cases is now **1,138.** 

[Source](https://content.govdelivery.com/accounts/AKDHSS/bulletins/2941ee6)

> CASE COUNT SUMMARY, Monday, **July 6, 2020**
> DHSS today announced 30 people with COVID-19 in Alaska. 28 are residents in seven communities: Anchorage (19), Fairbanks (3), North Pole (2), Kenai (1), Seward (1), Sterling (1) and Wasilla (1). The total number of Alaska cases is now **1,166.** 

[Source](https://content.govdelivery.com/accounts/AKDHSS/bulletins/2944fcf)

**Comment by camille-le** [comment]
Per Slack thread, we updated July 5 already. Closing this issue.
