### ISSUE TITLE
Maryland has ordered weekly reporting of negative counts (nothing posted yet)

### ISSUE THREAD

**Issue by catawbasam** [COVID19Tracking/issues#58]
Maryland issued an order requiring negative results weekly on Monday March 23. No numbers have been posted yet.

DIRECTIVE AND ORDER REGARDING VARIOUS HEALTHCARE MATTERS
Pursuant to Md. Code Ann., Health-Gen. §§ 2-104, 18-102, 18-103, 18-205, 18-902, 18-904,
and Public Safety § 14-3A-03

I, Robert R. Neall, Secretary of Health, finding it necessary for the prevention and control of
2019 Novel Coronavirus (“SARS-CoV-2” or “2019-NCoV” or “COVID-19”), and for the
protection of the health and safety of patients, staff, and other individuals in Maryland, hereby
authorize and order the following actions for the prevention and control of this infectious and
contagious disease under the Governor’s Declaration of Catastrophic Health Emergency:

COVID-19 TESTING
1. Positive COVID-19 Test Reporting
A. Pursuant to Health General Article §§ 18-205 and 18-904, and COMAR 10.06.01.03
and .04, a medical laboratory performing a diagnostic test for COVID-19 shall report a
positive test result of an individual immediately to the Maryland Department of Health
(“MDH”) and the appropriate local health officer.
B. The medical laboratory shall immediately notify the requesting healthcare provider
of the positive test result and provide a written or electronic report of the positive test result
to the requesting healthcare provider to give to the patient.
2. Negative COVID-19 Test Reporting
A. Pursuant to Health General Article §§ 18-205, 18-206, 18-904, a medical laboratory
performing a diagnostic test for COVID-19 shall report the total number of tests performed
and its negative test results for tested individuals no less than once a week to MDH at
Mdh.CovidAggLab@maryland.gov.
B. A laboratory that is already submitting HL-7 formatted electronic laboratory reports
(ELRs) to MDH shall send reports for negative and inconclusive test results in addition to
positive test results.
C. A laboratory that does not already submit HL-7 formatted ELRs to MDH shall
submit a summary report to MDH at Mdh.CovidAggLab@maryland.gov at least once per
week that contains the following: the total number of specimens tested, the number of
positive results, the number of inconclusive results, and the number of negative results.

**Comment by hammer** [comment]
We saw that! https://twitter.com/COVID19Tracking/status/1242337011387600897

Very good news, thanks for passing along.

**Comment by catawbasam** [comment]
Jeff,
Thanks.  You saw the Michigan data is updated at
https://www.michigan.gov/coronavirus/0,9753,7-406-98163-520743--,00.html?

These counts are higher than what is posted at
https://covidtracking.com/data/#MI:
Cumulative Number of Specimens Tested for COVID-19 - Last Updated 3/25/2020

Lab Type Negative Tests Positive Tests Total Specimens Tested
Commercial 713 30 744
Hospital 3296 1866 5261
Public Health 2541 557 3104
Grand Total 6550 2453 9109
