### ISSUE TITLE
[KS]Data entry errors in Positive Cases PCR column - we actually don't have a source for it. so the full time series should be deleted.

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#581]
**State or US**: KS

**Describe the problem**
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1593895521467900?thread_ts=1593893959.453600&cid=CUQ4MMTPD
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1594066085184900?thread_ts=1594064128.159200&cid=CUQ4MMTPD

**Link to data source**

**Comment by amandafrench** [comment]
That takes care of one item on my To Do list, which was listed as "KS PCR ARGH" and I was going to have to go back and figure out what that meant

**Comment by camille-le** [comment]
**BEFORE**
<img width="626" alt="BEFORE" src="https://user-images.githubusercontent.com/31285549/86723608-e8f06380-bfdc-11ea-9fd1-f31c393bbdef.png">

**AFTER** 
<img width="545" alt="AFTER" src="https://user-images.githubusercontent.com/31285549/86723621-ec83ea80-bfdc-11ea-9bb9-674eadcf368d.png">
