### ISSUE TITLE
Improve Google Sheets Performance

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#585]

**Comment by space-buzzer** [comment]
Suggestions that we can attempt/remove things to get the most "bare-bones" variant and then add them back gradually:
This is mostly an aggregation of what we already discussed:

- Taking States Daily out to a separate spreadsheet
- Removing unused tabs: Do we need the new reporting there? vs just have links to other sheets in the README
- State Grades? we ref it, is it used?
- Remove Checking Order, it runs filter over ranges
