### ISSUE TITLE
[OR] Wrong values were entered in Negative Tests (PCR) column 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#587]
**State or US**: Oregon

**Describe the problem**
 It should not be Dashboard > Negative Tests / WEEKEND use Other link and check most recent press release  just WEEKEND use Other link and check most recent press release  

**Link to data source**
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1594239559460200

**Comment by MattHilliard** [comment]
@muamichali Was this related to https://github.com/COVID19Tracking/issues/issues/582 or something else? I can't tell based on the description.
