### ISSUE TITLE
Need to go back and update Illinois data to reflect new findings about positives/deaths

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#59]
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1585252030467100

We found out that, despite the poorly-chosen pie chart showing up lower on the page, the positive case count actually *does* include deaths. We need to go back through available screenshots and update the positive and negative counts, at least for the daily updates.

**Comment by careeningspace** [comment]
Before clean-up:
![Screen Shot 2020-03-27 at 1 30 10 AM](https://user-images.githubusercontent.com/43073915/77725130-15064c80-6fcb-11ea-800c-8c2b25b1bac4.png)

After clean-up:
![Screen Shot 2020-03-27 at 1 33 11 AM](https://user-images.githubusercontent.com/43073915/77725120-10419880-6fcb-11ea-84d2-5aab234e1709.png)
