### ISSUE TITLE
NJ: Backfilling probable deaths from 6/26 & 7/8

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#590]
**State or US**: [NJ]

**Describe the problem**
NJ has twice now reported previously-determined Probable deaths. We have asked them for the data so we can backfill but have not received it yet. Placeholder issue for doing the backfill once we receive it. "On May 16, New Jersey had a significant jump in recovered (about 7,000) due to backfilling previous days after a shift in how this figure was reported on April 28. On June 25th, New Jersey reported 1854 probable deaths that occured in the past. This causes a perecived increase in the daily number of deaths." 89 new probable deaths on 7/8. 

**Link to data source**
https://covid19.nj.gov/#live-updates 
https://covidtracking.com/data/state/new-jersey

**Comment by amandafrench** [comment]
Just testing comments here

**Comment by amandafrench** [comment]
How do we feel about having issues, commits, comments, etcetera from the https://github.com/COVID19Tracking/issues repo posted directly to the #patch-notes channel?

**Comment by the-daniel-lin** [comment]
NJ dashboard now has a time series for their deaths separated by probable and confirmed. However, we should note that these are by 'Date of Death.' (Dash --> Top tab labeled 'Case and Mortality Summaries' --> Bottom tab labeled 'Mortality Summary')

![image](https://user-images.githubusercontent.com/67408226/89193392-c4939280-d55a-11ea-98ba-41e1e93c5709.png)

**Comment by MattHilliard** [comment]
New Jersey probable deaths have been backfilled based on the state's historical time series. Total deaths were updated to take into account the new distribution of probable deaths. This smooths out the big jumps that took place on 6/25 and 7/8 as well as the declines on 7/22 and 7/29. Confirmed deaths were not backfilled; this column remains as reported by the state each day on its dashboard.

Total deaths before/after:
![image](https://user-images.githubusercontent.com/404503/89676797-44eb2800-d8ba-11ea-93a4-99ebaa467cac.png)

Probable deaths before/after:
![image](https://user-images.githubusercontent.com/404503/89676819-4caacc80-d8ba-11ea-90f8-23eff860c03e.png)

State data source: https://covid19.nj.gov/#live-updates
Backfill spreadsheet with NJ raw data, old copy of States Daily, etc: https://docs.google.com/spreadsheets/d/1HCQSdm9mpEOY3vCd3E9sBqxPoui4MB0M--DMrFxBTNU/edit#gid=466605614

The backfill team plans to do this weekly on Wednesday, the same cadence NJ uses for updating its probable death numbers.
