### ISSUE TITLE
[RI] 7/8 now provides tests & negatives in people in addition to specimens. Backfill of full data series

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/issues#591]
We can backfill specimens information for RI and also update the way "Negative"s are reported

Link to datasource:
https://docs.google.com/spreadsheets/d/1c2QrNMz8pIbYEKzMJL7Uh2dtThOJa2j1sSMwiDo5Gz4/edit#gid=1592746937

**Comment by space-buzzer** [comment]
[ri_backfill.zip](https://github.com/COVID19Tracking/issues/files/4893994/ri_backfill.zip)

Updated the following columns:
* Specimens: 
  * totalTestsViral
  * positiveTestsViral
  * negativeTestsViral
* People: 
  * positiveCasesViral
  * totalTestResults
  * positive
  * negative

The attached file shows the before/after values.

*Notice* RI is now publishing full data about specimens (total number of tests, with a breakdown to positive and negative results).
Additionally, RI publishes unique people tested, including people with positive and negative results. This is now used as the source for `positiveCasesViral`, `positive` and `negative` API fields.

**Comment by muamichali** [comment]
![image](https://user-images.githubusercontent.com/1749380/86989207-e8d09f00-c167-11ea-93e3-6dce910c9d15.png)
