### ISSUE TITLE
[Data Quality] Post Launch Tasks for publishing confirmed/probable deaths in API

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#592]
### Can be done post launch
- [x] Compile a [list of any public notes that need to be added](https://covid-tracking.slack.com/archives/C012C4BEAR4/p1593657054040400) when we release the columns including release dates for PCL in each state (KWS)
- [x] Do GH issues for low-priority states requiring them: ID, MN, OH, PR (KWS)
- [x] Float the suggestion of adding an "All the people who died with positive COVID-19 test" column to our capture and starting morning shift work to make this happen after confirmed/probable release (MM)
- [ ] Publish Blog Post

**Comment by karaschechtman** [comment]
Folding these into pre-existing tabs
