### ISSUE TITLE
[ID]As of July 8 Idaho's revised all daily hospitalizations

### ISSUE THREAD

**Issue by waded** [COVID19Tracking/issues#593]
**State or US**: Idaho

**Describe the problem**
On July 8, if not before, Idaho updated history of daily hospitalizations, such that what COVID Tracking Project reports now doesn't match the state's dashboard. It appears COVID Tracking Project first captured the history with https://github.com/COVID19Tracking/issues/issues/572.

e.g. Idaho's now reporting daily hospitalizations on May 5 2020 = 27, but CTP reports 45 at https://covidtracking.com/data/state/idaho. That's a bit of an exception, but almost every day's number has changed. Generally March-May numbers are down, and more recent numbers are up.

It appears daily ICU history also changed, but I didn't investigate further.

**Link to data source**
State COVID dashboard: https://public.tableau.com/profile/idaho.division.of.public.health#!/vizhome/DPHIdahoCOVID-19Dashboard_V2/Story1 tab "Hospitalizations"

Here's a screenshot of the daily hospitalizations chart and the May 5 example point as of now:

![image](https://user-images.githubusercontent.com/1535656/87062008-ba83ab80-c1c9-11ea-853e-c0e56daeeb15.png)

**Comment by waded** [comment]
To add a little more context, in case helpful, here's a screenshot of the same chart from the dashboard I captured July 3, showing the old numbers, I think as CTP originally captured.

![image](https://user-images.githubusercontent.com/1535656/87063304-6b3e7a80-c1cb-11ea-8d20-0d07a76538c4.png)

**Comment by space-buzzer** [comment]
CSVs of data.
Hospitalizations and ICU, ICU starts only end of May, and includes only confirmed patients, hospitalization is confirmed + suspected, goes back to end of March

[confirmed_and_suspected_in_hospital_20200714.txt](https://github.com/COVID19Tracking/issues/files/4921977/confirmed_and_suspected_in_hospital_20200714.txt)
[confirmed_in_icu_20200714.txt](https://github.com/COVID19Tracking/issues/files/4921978/confirmed_in_icu_20200714.txt)

**Comment by waded** [comment]
Idaho updated this data again today, 7/15. I do see a historical difference again, but perhaps not as far back, vs. what @space-buzzer provided on 7/14. I'll attach the latest files here since I have them, but these can be downloaded by 

-  clicking on the desired visualization at dashboard link provided (there's no visual feedback when you do this, but it gives the next step context)
- clicking the "Download" button on Tableau Public's bottom toolbar
- click "Data"
- click "Download all rows as a text file"

[S_and_C_Hospitalized_Full_Data_data-20200715.csv.txt](https://github.com/COVID19Tracking/issues/files/4928492/S_and_C_Hospitalized_Full_Data_data-20200715.csv.txt)
[C_in_ICU_data-20200715.csv.txt](https://github.com/COVID19Tracking/issues/files/4928491/C_in_ICU_data-20200715.csv.txt)

**Comment by waded** [comment]
For whoever's planning out work on this

- an [Idaho Statesman article implies](https://amp.idahostatesman.com/news/local/investigations/watchdog/article244260242.html) that the reason the numbers has changed in the past is "Idaho’s hospitals and Health and Welfare also spent time updating numbers for prior days, when necessary, to make sure the records were as accurate as possible, according to Idaho’s deputy state epidemiologist."

- the same article, and the footnote on the dashboard page, indicates this data was derived from NHSN, so depending how it takes for the HHS Protect switch to sort out, it may be a while before it updates beyond the update I mentioned today.

**Comment by theomichel** [comment]
Worksheet: https://docs.google.com/spreadsheets/d/1IYateWMArXt6dVCi1ydhleZwenBijsxeD6s_9BD06xk/edit#gid=1639376863

Generally updated numbers (for hospitalizations and ICU) look good, but date alignment is an issue. Data Entry has been using the last day in the graph as "today", but it's actually ~3 days old. This update shifts things back to the actual dates on the graph, which results in zeros for some recent days. (followed by values again as DE continues to enter data)

**Comment by theomichel** [comment]
Update complete!
