### ISSUE TITLE
[WY] PCL Cases Historicals

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#595]
**State or US**: Wyoming

**Describe the problem**
CTP Positive Cases (PCR) goes back until 4/29. There's also a gap for Positive and Negative Tests (PCR) from 5/5 - 5/14. WY provides hover-over graphs for lab-confirmed cases (line graph - people) until 3/12 and tests (bar graph - specimens) back until 3/4. 

**Link to data source**
Lab-Confirmed Cases: https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-map-and-statistics/ 

COVID-19 Resulted Tests by Collection Date: https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-testing-data/

**Comment by jesseandersonumd** [comment]
Data backfilled using https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-map-and-statistics/ Data recorded on graph on a day will be recorded in sheet as the subsequent day

**Comment by jesseandersonumd** [comment]
BACKFILLED (BEFORE)
![Screen Shot 2020-07-10 at 10 58 10 AM](https://user-images.githubusercontent.com/57415941/87168347-5847ab00-c29c-11ea-90c6-40a9d5f2d89f.png)

**Comment by jesseandersonumd** [comment]
BACKFILLED (AFTER) BACK TO 3/12
![Screen Shot 2020-07-10 at 10 58 10 AM](https://user-images.githubusercontent.com/57415941/87168401-6dbcd500-c29c-11ea-821a-be76deb7c793.png)

**Comment by muamichali** [comment]
I am seeing some slight discrepancies. Need to look at this again. Might be shifted by one day.

**Comment by jesseandersonumd** [comment]
Note for backfill team - we've backfilled the confirmed cases (PCR) but have yet to adjust for negatives. Please adjust negatives and review the graph "**Lab Confirmed Cases by Date of Report,** Total Number of Recovered Lab Confirmed Cases; and Percent of Cases with Community Spread or Unknown Exposure" located at: https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-map-and-statistics/

**Comment by karaschechtman** [comment]
We're handling this in #739
