### ISSUE TITLE
[IA] PCL Case Historicals 

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#596]
IA started recording Positive Cases (PCR) on 4/29.  Their dashboard, where we source the data, launched on 4/14.  https://idph.iowa.gov/News/ArtMID/646/ArticleID/158335

It is unlikely that IA used lumped values and then went to lab-confirmed only, given the consistent time-series for Positives. The wording before the dashboard changed also is in line with our definition for Lab Confirmed Only.

> The state only reports cases confirmed by viral test. State must explicitly use the word "confirmed", inviting interpretation by CSTE case definition, or specify they are using PCR/viral tests, to be labelled as lab-confirmed. 

Positives should therefore be copied into Positive Cases (PCR).

**Comment by jesseandersonumd** [comment]
**UPDATE: 7/13** 

_While backfiling, we came across a graph on the website that reports confirmed cases by day [https://coronavirus.iowa.gov/pages/case-counts]. Here is the graph:_

![Screen Shot 2020-07-13 at 9 32 39 AM](https://user-images.githubusercontent.com/57415941/87318053-d0f57400-c4f5-11ea-8341-946e5864d253.png)

This graph is **hoverable** and **the data can be automatically fetched from ArcGIS layers.**

**Comment by brianskli** [comment]
Using IA's data definition, it was confirmed that IA reports in lab-confirmed cases. Values from Positives were then copied into Positive Cases (PCR) in States Daily.

Before:
<img width="783" alt="Screen Shot 2020-07-23 at 9 37 14 AM" src="https://user-images.githubusercontent.com/66738237/88293478-0e61ba80-ccc9-11ea-9eaf-eec7c39dcce8.png">
After:
<img width="784" alt="Screen Shot 2020-07-23 at 9 39 52 AM" src="https://user-images.githubusercontent.com/66738237/88293487-115cab00-ccc9-11ea-80db-30fa59c31542.png">
