### ISSUE TITLE
[IL] PCL Cases Historicals

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#598]
**Issue:** Our coverage IL has a gap in Positive Cases (PCR) between 6/04 and 5/25, although confirmed cases were being reported during that time. There is also a two day gap between 6/5-6/6 in Total Tests (PCR)

**Data source:**
IL state dashboard charts

**Link to data source**
http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus

**Comment by pscsharon** [comment]
Note that our research found IL only started separating confirmed and probable in June.  The bar chart now displayed by IL for historical cases (when hovering over each bar) is likely only confirmed, but we may need to check.  

<img width="735" alt="Screen Shot 2020-07-10 at 7 54 03 AM" src="https://user-images.githubusercontent.com/67423649/87167908-8ae4aa00-c282-11ea-9cee-ace40b898826.png">

**Comment by space-buzzer** [comment]
The data for this bar chart
It's a `CSV` file with `TXT` extension so GitHub agrees to upload it as is, without zipping.
[date_totalTested_confirmedCases_deaths_20200712.txt](https://github.com/COVID19Tracking/issues/files/4909679/date_totalTested_confirmedCases_deaths_20200712.txt)

**Comment by the-daniel-lin** [comment]
Using the above `CSV` file
BEFORE:
![image](https://user-images.githubusercontent.com/67408226/88405482-319d7000-cd84-11ea-9fea-a45820e6ca88.png)

AFTER:
![image](https://user-images.githubusercontent.com/67408226/88406152-20a12e80-cd85-11ea-8089-d8b36a9d782a.png)
