### ISSUE TITLE
[WV] PCL Cases Historical

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#599]
**State or US**: West Virginia

**Describe the problem**
1. Historical "Positive Cases (PCR)" goes back until 4/29. There's a gap from 5/22 - 6/4 (https://github.com/COVID19Tracking/issues/issues/555) that we may be able to fill now.

2. States Daily antibody test values go back until 5/23, but our long formulas sheet dates back to 4/12. The WV website has hover-over line graphs that date back to 3/17 for cases and 3/11 for lab tests.

3. Under the "Positive Case Trends" tab, cumulative historical cases on the WV website combine probable and confirmed cases, but in the graph underneath, historical daily cases are separated by probable and confirmed cases. Since WV updates data multiple times every day and backfills their own data consistently, current CTP historical values for cases and testing do not match with the hover-over line graphs on the WV website. 

**Link to data source**
Dashboard: https://dhhr.wv.gov/COVID-19/Pages/default.aspx 
Daily Press Releases (at 10AM and 5PM): https://dhhr.wv.gov/News/2020/Pages/default.aspx

**Comment by muamichali** [comment]
IN #822 we filled out the gap in "Positive Cases (PCR)" from 5/22 to 6/4 by carrying over values since the screenshots do not enable us to hover.

**Comment by jaclyde** [comment]
Antibody tests are a low priority, so we will not be extending the timeline in our data, as mentioned above the antibody tests are available in a graph on the West Virginia dashboard.
