### ISSUE TITLE
STATE TIPS changes: put them here please

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/issues#6]
We are running this http://covidtracking.com/notes/ as our live Tips doc now, please put your requested edits right here and we'll get them done.

**Comment by hammer** [comment]
Consider adding the Twitter account for each state to this doc? They're in the "States" tab of the main sheet and also in a handy Twitter list we made: https://twitter.com/i/lists/1237806341634306048

**Comment by kissane** [comment]
@hammer that is a good idea, I can take that this evening if it doesn't get handled sooner.

**Comment by webmasterkai** [comment]
Perhaps the page should be built from the google sheet that has the states info? The sheet has the twitter links already. Editing the google sheet may also be a lower barrier of entry to get an edit/update to the website?

**Comment by kissane** [comment]
I think the thing to do is NOT put it into our existing dev spreadsheet, which is fragile in some ways. Not yet, at least. But I am totally fine with throwing it into another sheet, today's solution is not at all a sustainable one.

**Comment by webmasterkai** [comment]
Any data source is fine as long as one of the fields/columns is the state abbreviation used elsewhere.

**Comment by kissane** [comment]
That's very doable. One sec.

**Comment by webmasterkai** [comment]
Not to confuse things but we could add a state content type to the CMS if that is the preferred interface. Then each state would have a file with various fields. Whatever is easiest for the team.

**Comment by kissane** [comment]
How's this? https://docs.google.com/spreadsheets/d/1d0VlFiUWfT0fAe1PfoLH_J6mTMiUNNsLaaWYPnsrH3w/edit#gid=0

It would be nice to keep things in a single data source (like one tab with a list) vs many chunks right now, just for sanity as we do upkeep on the list.

**Comment by anticrisis** [comment]
State of Hawaii has more complete information, including negative results, which are not currently included in the tracker, here: https://health.hawaii.gov/news/covid-19-updates/

The data is in tables in each of the daily updates linked to from that page.

**Comment by joshuaellinger** [comment]
Can we close this out?  It doesn't look actionable.

**Comment by joshuaellinger** [comment]
CLOSING -- Please post individual issues
