### ISSUE TITLE
[KS] PCL Cases Historicals ***Awaiting Outreach Results***

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#600]
Need to finalize decision on whether we can or cannot use KS's historical case data for our Positive Cases (PCR) historicals. If yes, please backfill all days.  We have not yet recorded any.  

WS2: 
<img width="1225" alt="Screen Shot 2020-07-10 at 8 00 27 AM" src="https://user-images.githubusercontent.com/67423649/87170432-304d4d00-c286-11ea-8886-2baff2a9aff3.png">

States Daily:
<img width="1060" alt="Screen Shot 2020-07-10 at 8 00 11 AM" src="https://user-images.githubusercontent.com/67423649/87170445-34796a80-c286-11ea-9401-ff1b540c0b88.png">

KS Dashboard Comments:  (Note that KS explicitly states they lump confirmed and probable in their case count.)
<img width="1121" alt="Screen Shot 2020-07-10 at 7 58 52 AM" src="https://user-images.githubusercontent.com/67423649/87170508-46f3a400-c286-11ea-93ee-f45f5317a28b.png">

<img width="1215" alt="Screen Shot 2020-07-10 at 7 58 42 AM" src="https://user-images.githubusercontent.com/67423649/87170505-4529e080-c286-11ea-9632-c03991c1f0fe.png">

KS Dashboard showing historical numbers:
<img width="1137" alt="Screen Shot 2020-07-10 at 7 59 25 AM" src="https://user-images.githubusercontent.com/67423649/87170666-7d312380-c286-11ea-992e-bb2a21a9159e.png">

PRESS RELEASES:  _Strange.  They just add the current day’s to the front and re-PDF the whole thing.  This action leads me to think their historicals are not updated to be only confirmed… if they just keep adding today’s press release to prior days, but I am stretching - yes._
https://www.coronavirus.kdheks.gov/DocumentCenter/View/1125/Historical---July-8?bidId=

**Comment by the-daniel-lin** [comment]
The historical hover-over graph is most-likely a lumped figure, so we can't use it for backfill. We are waiting for confirmation from outreach.

There is a separate number on the [state page](https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas) through the 'Testing Rates' button. In the 'Positive PCR Tests by Performing Lab' table, under 'Number of Cases,' we suspect that this number indicates lab-confirmed cases. We are waiting for confirmation from outreach on this and are working to take screenshots in order to have a record for potential back-filling.

**Comment by karaschechtman** [comment]
We decided to use the number from this graph as "Confirmed" (TBD how we will backfill it):
![Screen Shot 2020-07-28 at 11 00 22 AM](https://user-images.githubusercontent.com/15933271/88683210-8d883180-d0c1-11ea-8aa3-5a16f5c77d11.png)

**Confirmed tooltip**
![Screen Shot 2020-07-28 at 10 59 23 AM](https://user-images.githubusercontent.com/15933271/88683130-7ba68e80-d0c1-11ea-84c9-dd50da88a7a9.png)
**Probable tooltip**
![Screen Shot 2020-07-28 at 10 59 27 AM](https://user-images.githubusercontent.com/15933271/88683140-7ea17f00-d0c1-11ea-86ce-f90e3077b6b2.png)
