### ISSUE TITLE
[WV] SVP Tests Historicals

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#601]
**State or US**: West Virginia

**Describe the problem**
We've been historically recording "Confirmatory Lab Test" numbers under "Total PCR Tests (People)." However, from 7/7 outreach, the figures under WV "Lab Test Trends" tab refer to specimens tested, NOT people.

**Link to data source**
https://dhhr.wv.gov/COVID-19/Pages/default.aspx

**Comment by jaclyde** [comment]
Didn't see this issue earlier. This issue was taken care of in Issue #769
