### ISSUE TITLE
[FL] remove one-off hospitalization data point from reporting as of 5/14

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#602]
**State or US**: FL

**Describe the problem**
One-off data point from reporting was carried over for 7 days and does not reflect the trend of the time. 

**Link to data source**
https://www.facebook.com/GovRonDeSantis/videos/239526690673386/ 4:09

**Comment by muamichali** [comment]
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/87193122-0287f880-c2c6-11ea-98b6-c89ae9e36ffb.png)
![image](https://user-images.githubusercontent.com/1749380/87193161-19c6e600-c2c6-11ea-849f-97eff77a0705.png)


**AFTER**
![image](https://user-images.githubusercontent.com/1749380/87193255-5266bf80-c2c6-11ea-9966-42e64637f9f2.png)

**Comment by qpmnguyen** [comment]
This looks good @muamichali
