### ISSUE TITLE
[PR] New Puerto Rico testing data report (as of 2020-07-09)

### ISSUE THREAD

**Issue by sacundim** [COVID19Tracking/issues#603]
**State or US**: Puerto Rico

This is a continuation of https://github.com/COVID19Tracking/issues/issues/568

As infuriatingly usual, the only way to get official data on the number of tests in Puerto Rico is to follow certain journalists on Twitter who pester the Department of Health periodically for the numbers. We just got a new set today:

* https://twitter.com/angelicaserran0/status/1281694446233497602
* https://twitter.com/RobbyCortes/status/1281697289279545344

I've got the images and copied the data into a CSV file with all of the previous ones here:

* https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/data/PuertoRico-bioportal.csv
* https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-07-09/2020-07-09_bioportal.jpg
* https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/source_material/2020-07-09/2020-07-09_bioportal_p2.jpg

**Comment by MattHilliard** [comment]
PCR Columns Before:
![image](https://user-images.githubusercontent.com/404503/87213903-74783600-c2f6-11ea-8831-2a88af0f8589.png)

PCR Columns After:
![image](https://user-images.githubusercontent.com/404503/87213943-ba34fe80-c2f6-11ea-8126-b58cc7299dbe.png)

Negative column before:
![image](https://user-images.githubusercontent.com/404503/87213992-21eb4980-c2f7-11ea-95ff-a5e0d88890a2.png)

Negative column after (using Total Tests PCR - Positive Cases PCR from first day (258001 - 2235 = 255766) per extensive discussion with @muamichali last time:
![image](https://user-images.githubusercontent.com/404503/87213990-1ac43b80-c2f7-11ea-81a7-d24f55a3686c.png)

**Comment by MattHilliard** [comment]
Oh and thank you so much @sacundim for passing along this data! Your help is very much appreciated!
