### ISSUE TITLE
[PR] Historical Puerto Rico hospitalizations data

### ISSUE THREAD

**Issue by sacundim** [COVID19Tracking/issues#604]
**State or US**: Puerto Rico

**Describe the problem**

So, on Thursday (July 9) the number of COVID-19 hospitalizations in Puerto Rico climbed to 147, prompting a leading local paper to publish a story pointing out that, according to the data they had, this was a record high:

* ["Record patients: hospitalizations for COIVD-19 increase to 147"](https://www.elnuevodia.com/noticias/locales/notas/record-de-pacientes-las-hospitalizaciones-por-covid-19-aumentan-a-147/) *El Nuevo Día*, July 9, 2020.

This seemingly didn't sit well with the Secretary of Health, who responded by saying that his department's records refute this and that there were 201 hospitalizations on April 30:

* https://twitter.com/DeptSaludPR/status/1281261229403713537

And as part of this, he also shared a table of historical hospitalization data with some journalists. It goes from April 18 to July 9, and also breaks the totals down by region:

* https://twitter.com/angelicaserran0/status/1281256666881802241
* https://twitter.com/RobbyCortes/status/1281536898230558720

I have dutifully transcribed this data into a CSV, and used a spreadsheet to check that the regional totals add up to the listed totals:

* https://github.com/sacundim/covid-19-puerto-rico/blob/master/assets/data/PuertoRico-hospitalizations.csv

**Comment by MattHilliard** [comment]
Thank you yet again @sacundim! Your CSV made this really easy for me to check against our numbers. All our recent data matched, just a discrepancy or two around the edges of our gaps. And of course this fills in a vastly better picture of the "first wave" than we had before.

Our existing current hospitalization data:
![image](https://user-images.githubusercontent.com/404503/87235845-f9268b00-c3ae-11ea-8e64-dc1b5e2e0929.png)

Fixed data:
![image](https://user-images.githubusercontent.com/404503/87235846-ffb50280-c3ae-11ea-8a32-d98765f40764.png)

[Details](https://docs.google.com/spreadsheets/d/1t3SJqFsQjuUI8NEIHZpkC2lNG15XFIe1NX0fc0Obkt4/edit#gid=0), including before/after of States Daily
