### ISSUE TITLE
[AL] PCL Cases Historicals

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#610]
Alabama has been using a dashboard since Mar 20th, when it also began reporting confirmed-cases.  Historicals can be found in the archive of daily screenshots here: http://covid-tracking-project-data.s3-website.us-east-1.amazonaws.com/state_screenshots/AL/

WS2 instructs the data-entry team to pull Confirmed Cases from the dashboard, and per States' Daily, we started doing so on Apr 29th. 

<img width="1287" alt="Screen Shot 2020-07-13 at 6 33 03 AM" src="https://user-images.githubusercontent.com/67423649/87311075-a4306500-c4d3-11ea-9ce9-58b24d30ad64.png">

<img width="1428" alt="Screen Shot 2020-07-13 at 6 32 22 AM" src="https://user-images.githubusercontent.com/67423649/87311104-abf00980-c4d3-11ea-8d7c-fedaffd43227.png">

Please backfill historical confirmed cases to Mar 20th, which is the earliest date when the state provides this number.  Prior to Mar 20th, AL reported cases and it is unclear if the case count includes probable cases or not.

**Comment by brianskli** [comment]
Values from C were transferred to V. This change acknowledges that AL's reporting of confirmed cases. WS2 verified to have correct pop-ups.

Before:
<img width="781" alt="Screen Shot 2020-07-20 at 10 24 31 AM" src="https://user-images.githubusercontent.com/66738237/87949010-7323d780-ca73-11ea-9da2-358e3798d04d.png">
After:
<img width="785" alt="Screen Shot 2020-07-20 at 10 25 00 AM" src="https://user-images.githubusercontent.com/66738237/87949017-75863180-ca73-11ea-8a85-f79abf82bd34.png">

**Comment by muamichali** [comment]
Double checked.
