### ISSUE TITLE
[AK] PCL Cases Historicals

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#611]
Alaska has been reporting Confirmed Cases. Please backfill the Confirmed Cases.

Background:

In WS2, we do not populate “Positive Cases (PCR)” which feeds column V in States’ Daily.
<img width="1391" alt="Screen Shot 2020-07-13 at 6 16 58 AM" src="https://user-images.githubusercontent.com/67423649/87311351-f96c7680-c4d3-11ea-82ab-8a3c6db81430.png">

So, column V in States' Daily is blank.
<img width="1403" alt="Screen Shot 2020-07-13 at 6 16 45 AM" src="https://user-images.githubusercontent.com/67423649/87311394-06896580-c4d4-11ea-8858-698e5f9fc121.png">

It appears we said cases were unclear if they are distinct or lumped.  From re-review of their testing guidance on arcgis, I believe now it is lab-confirmed.  Refer to questions 1 in this linked PDF. https://coronavirus-response-alaska-dhss.hub.arcgis.com/datasets/cases-and-testing-frequently-asked-questions

**Comment by brianskli** [comment]
AK confirmed to report only lab-confirmed cases. WS2 pop-ups was also modified to account for this.

States daily corrected, values in C also added to V.

Before:
<img width="803" alt="Screen Shot 2020-07-20 at 10 01 52 AM" src="https://user-images.githubusercontent.com/66738237/87946781-779ac100-ca70-11ea-9771-79eb3997b5d0.png">
After:
<img width="801" alt="Screen Shot 2020-07-20 at 10 02 55 AM" src="https://user-images.githubusercontent.com/66738237/87946800-7c5f7500-ca70-11ea-9221-583246a95094.png">
