### ISSUE TITLE
[CA] PCL Cases Historicals

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#615]
It appears CA has reported Confirmed-Cases using the phrase confirmed positive cases since their first report on Mar 15th.  

Please backfill Positive Cases (PCR) using archive of screenshots. http://covid-tracking-project-data.s3-website.us-east-1.amazonaws.com/state_screenshots/CA/

**Comment by MattHilliard** [comment]
I took a quick look at this and the screenshots are kind of a mess before April. Maybe a better source is the California  health department press releases, which are nearly daily? https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx  However even there, we will have to decide how to deal with a bunch of old school issues like whether to include "Federal repatriation flights".

**Comment by space-buzzer** [comment]
We can take all the dashboard data from CA's data portal.
They do not separate it into citizens/non-citizens

**Comment by space-buzzer** [comment]
PDF for comparison and DC: 
[CA - Analysis #615.pdf](https://github.com/COVID19Tracking/issues/files/4933381/CA.-.Analysis.615.pdf)

**Comment by jaclyde** [comment]
Backfill from screenshots or the state data was unnecessary for this issue. The values we recorded as Cases (confirmed plus probable) were copied to the Confirmed cases metric from April 28, 2020 to March 4, 2020. 

Values copied: 
[Changes (17).txt](https://github.com/COVID19Tracking/issues/files/6347231/Changes.17.txt)
