### ISSUE TITLE
OR: Incorrect data

### ISSUE THREAD

**Issue by tedder** [COVID19Tracking/issues#62]
Comparing my dataset for Oregon (pulled from the official source) against yours, it looks like 3/25 is missing, causing 3/26 to be wrong.

my cases on 3/24-3/26: 209, 266, 316
my increases: 20, 50, 57
your cases: 209, 209, 327
your increases: 18, 0, 118

This may be because of this issue: https://github.com/COVID19Tracking/covid-tracking-api/issues/22

Spotchecking the 'positive' counts, they are correct except for 3/25, 3/21, and everything before about 3/19. Most of the older ones are a date-off-by-one error.

I wouldn't mind being invited to the Slack, if possible. I'm trying to replace my OR and FL datasets with yours to generate some graphs on Wikipedia.

**Comment by careeningspace** [comment]
Unfortunately, I am not seeing a screen-capture of historical data, so all I have is a copy of the data we have collected:
- [ ] Data collection log:
![Screen Shot 2020-03-27 at 1 51 34 AM](https://user-images.githubusercontent.com/43073915/77726250-e0e05b00-6fcd-11ea-8766-dcc85a52e86a.png)

- [ ] Daily Report (cut off at 4pm)
![Screen Shot 2020-03-27 at 1 36 27 AM](https://user-images.githubusercontent.com/43073915/77725254-67476d80-6fcb-11ea-8ae3-930230861321.png)

**Comment by asheragy** [comment]
The same is happening between 4/8 and 4/11 for positives and deaths.  Other columns are most likely effected too but unable to verify the correct values.  Appears to be the issue outlined in #135
