### ISSUE TITLE
[DE] PCL Cases Historical

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#622]
**State or US**: Delaware

**Describe the problem**
From 4/28-6/9, we report confirmed+probable lumped values in "Positive Cases (PCR)." Delaware began separating the numbers on 6/10, which we have reflected in that same column. We should delete the lumped values prior to 6/10

**Link to data source**
![image](https://user-images.githubusercontent.com/67408226/87436572-140d2100-c5a2-11ea-951c-927b8d84f00e.png)

**Comment by camille-le** [comment]
From 2020-04-29 through 2020-06-10 (inclusive), CTP reported the same value for positive and positiveCasesViral columns. 

- The positiveCasesViral column data has been removed for this date range. _Please note, this reflects a total 337,159 removed from positiveCasesViral (over this 43 day timeframe)_ 
- The positive column has been unaltered for this date range. 

Separately, on 2020-06-11, [Delaware reported 9,158 confirmed cases, 948 probable cases which is 10,106 total cases](https://covidtracking.com/screenshots/DE/DE-20200611-183200.png). This is reflected on 2020-06-11 in CTP's dataset. 


**BEFORE** 
<img width="823" alt="BEFORE_DE" src="https://user-images.githubusercontent.com/31285549/87859133-a8032380-c8e7-11ea-99d4-349e12ce5e87.png">

**AFTER** 
<img width="794" alt="AFTER_DE" src="https://user-images.githubusercontent.com/31285549/87859141-ac2f4100-c8e7-11ea-8a96-2cf7c82d12fd.png">
