### ISSUE TITLE
[SD] Unclearly defined case count included in confirmed cases

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#623]
**State or US**: [SD]

**Describe the problem**
Unclearly defined case count included in confirmed cases. SD has unclear case definitions.

**Link to data source**
https://doh.sd.gov/news/Coronavirus.aspx

**Comment by brianskli** [comment]
Steps taken to address issue:
1) WS2 source note updated
2) States Daily changed (numbers in confirmed column cleared)
<img width="723" alt="Screen Shot 2020-07-14 at 10 23 57 AM" src="https://user-images.githubusercontent.com/66738237/87437391-4297f580-c5bc-11ea-83a7-52effafdd76d.png">
<img width="719" alt="Screen Shot 2020-07-14 at 10 24 30 AM" src="https://user-images.githubusercontent.com/66738237/87437408-475ca980-c5bc-11ea-917b-d84a355fd13d.png">

**Comment by the-daniel-lin** [comment]
On 7/17, we began incorrectly reporting the unclearly defined case count in the confirmed cases column:
![image](https://user-images.githubusercontent.com/67408226/88806337-21f7a000-d165-11ea-9b4b-780fae2c9349.png)

Slack Thread:
https://covid-tracking.slack.com/archives/C012C4BEAR4/p1595946823327700

**Comment by the-daniel-lin** [comment]
We have a new issue for this: https://github.com/COVID19Tracking/issues/issues/687
