### ISSUE TITLE
California 3/25 data is incorrect

### ISSUE THREAD

**Issue by plusCubed** [COVID19Tracking/issues#63]
See [CA press release from 3/25](https://www.cdph.ca.gov/Programs/OPA/Pages/NR20-033.aspx):
![image](https://user-images.githubusercontent.com/6379975/77703587-6e915b80-6f78-11ea-95c2-cfb8f4f5576a.png)

vs COVID Tracking:
![image](https://user-images.githubusercontent.com/6379975/77703553-5d484f00-6f78-11ea-9e8b-50bc69a2ca5c.png)

EDIT: 3/26 seems fine

**Comment by plusCubed** [comment]
Might be duplicate of #55, feel free to close

**Comment by careeningspace** [comment]
Yes - California was/is struggling to report current data. For an entire day, they reported nothing.

![Screen Shot 2020-03-26 at 11 51 20 PM](https://user-images.githubusercontent.com/43073915/77720254-c7cfae00-6fbd-11ea-9069-c1cb49dfddf3.png)
