### ISSUE TITLE
[AZ] No cum. hosp update between 6/21-6/23

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#630]
AZ did not update cum. hospitalizations at 4225 during this time. AZ habitually updates, even during weekends, so it is unusual that such is the case. Screenshot history and Slack threads were unavailable, further investigation may be needed.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_266xd)

**Comment by hmhoffman** [comment]
We don't have screenshots, and web archive isn't loading this section of the page, so I am going to close the issue, as it seems unlikely that we'll be able to patch it, and log it in the DQ log.
