### ISSUE TITLE
[AL] is reporting Specimens not Individuals

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#636]
**State or US**: [AL]

**Describe the problem**
Per Outreach information, AL "Total Tested" is reporting in units of specimens not people. We have changed the capture field as of today (7/15) and need to backfill the series and put it into the correct column. 

Related to #610 

**Link to data source**
<img width="1164" alt="Screenshot 2020-07-15 15 59 15" src="https://user-images.githubusercontent.com/227453/87590042-2b3c3380-c6b4-11ea-8693-cfbb545cce91.png">

**Comment by brianskli** [comment]
In States Daily, pre-7/15 test counts from Total PCR Tests (People) were copied over into Total Tests (PCR).

Before:
<img width="799" alt="Screen Shot 2020-08-07 at 9 34 15 AM" src="https://user-images.githubusercontent.com/66738237/89650990-38060e80-d891-11ea-96ed-9b05c568e6e5.png">

After:
<img width="790" alt="Screen Shot 2020-08-07 at 9 34 33 AM" src="https://user-images.githubusercontent.com/66738237/89651003-3a686880-d891-11ea-930b-dc423051e5a5.png">
