### ISSUE TITLE
[OR] Add missing data points via state data reports?

### ISSUE THREAD

**Issue by MattHilliard** [COVID19Tracking/issues#638]
**State or US**: OR

**Describe the problem**
We have a fair number of days without new data in various columns for OR. It seems like the "data reports" (below the press releases on the linked page) may allow filling in some of this data but I haven't investigated yet.

**Link to data source**
https://www.oregon.gov/oha/erd/pages/covid-19-news.aspx
"Data Reports" section

**Comment by MattHilliard** [comment]
I looked at days we had no negative tests and found of the 15 days we don't have an updated data point, 6 of them can be repaired using OR data reports:

No data report available: 7/4, 6/28, 6/26, 6/20
Data reports available: 5/14, 5/12, 4/28, 4/10, 4/4, 4/1
Data report available but no test data: 4/22
Dates preceding data report horizon of 3/26: 3/25, 3/21, 3/14, 3/12

Some of those days have other data missing as well, e.g. positive cases or hospitalization.

**Comment by terwilliger42** [comment]
Thanks a lot @MattHilliard !!

**Comment by muamichali** [comment]
On 12/9/2020 we backfilled Oregon's entire time-series of positiveTestsViral,totalTestsViral,negativeTestsViral from a table published on their website. This renders moot the proposal to repair testing numbers from the daily reports. 
https://github.com/COVID19Tracking/issues/issues/997

**Comment by muamichali** [comment]
The changes above were performed in two batches. Info below:
[Changes (5).txt](https://github.com/COVID19Tracking/issues/files/6359433/Changes.5.txt)
[Changes (4).txt](https://github.com/COVID19Tracking/issues/files/6359434/Changes.4.txt)
