### ISSUE TITLE
[AK] Non resident cases in Alaska

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/issues#640]
Alaska reports non residents separately from cases
![Screenshot from 2020-07-16 21-47-35](https://user-images.githubusercontent.com/62236447/87749900-cd404680-c7ae-11ea-9cc8-7f37a61a68ac.png)

Alaska has a case-line data table for the out of state table, with their "report date". This is a time series built from this data

[statewide_cases_cumsum.csv.txt](https://github.com/COVID19Tracking/issues/files/4935816/statewide_cases_cumsum.csv.txt)
[out_of_state_cumsum.csv.txt](https://github.com/COVID19Tracking/issues/files/4935817/out_of_state_cumsum.csv.txt)

**Comment by crockettcobb** [comment]
In case folks are interested in viewing the data directly, here's the source:
[https://coronavirus-response-alaska-dhss.hub.arcgis.com/datasets/covid-cases-out-of-state](https://coronavirus-response-alaska-dhss.hub.arcgis.com/datasets/covid-cases-out-of-state)

The CSV linked below updates daily with the non-resident cases:
[https://opendata.arcgis.com/datasets/f34c6b1e58f34939bb6d2d721eb7a1e7_0.csv](https://opendata.arcgis.com/datasets/f34c6b1e58f34939bb6d2d721eb7a1e7_0.csv)
