### ISSUE TITLE
[OH] 4/27-28 Incorrectly recorded only confirmed cases in our lumped column

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#641]
**State or US**: Ohio

**Describe the problem**
Where we report "positive" as "people with confirmed or probable COVID-19," we recorded only the confirmed values from 4/27-28. This causes a decrease in our "positive" trend. We should revise these values as such:
4/27: 15699 --> 16325
4/28: 16128 --> 16769

**Link to data source**
CTP Data: 
![image](https://user-images.githubusercontent.com/67408226/87813313-7ff7bf80-c816-11ea-9371-7975fa38548e.png)

4/27 Screenshot:
![image](https://user-images.githubusercontent.com/67408226/87813356-97cf4380-c816-11ea-9c80-39d4dcff6613.png)

4/28 Screenshot:
![image](https://user-images.githubusercontent.com/67408226/87813436-c6e5b500-c816-11ea-9645-811ce6daab31.png)

**Comment by camille-le** [comment]
**BEFORE** 
<img width="439" alt="BEFORE_OH" src="https://user-images.githubusercontent.com/31285549/87858693-9f5d1e00-c8e4-11ea-85d2-108d6b2e6d29.png">

**AFTER** 
<img width="401" alt="AFTER_OH" src="https://user-images.githubusercontent.com/31285549/87858698-a4ba6880-c8e4-11ea-8033-893bd3edb862.png">
