### ISSUE TITLE
[OR] Data update missed on 7/15

### ISSUE THREAD

**Issue by MattHilliard** [COVID19Tracking/issues#648]
**State or US**: OR

**Describe the problem**
We didn't get updated numbers on 7/15 for OR, probably because they updated after 5pm.

**Link to data source**
Data report:
https://www.oregon.gov/oha/PH/DISEASESCONDITIONS/DISEASESAZ/Emerging%20Respitory%20Infections/Oregon-COVID-19-Update-07-15-2020-FINAL.pdf

Press release (with confirmed + probable cases):
https://www.oregon.gov/oha/ERD/Pages/Oregon-reports-282-new-confirmed-and-presumptive-COVID-19-cases-4-new-deaths.aspx

**Comment by MattHilliard** [comment]
I was able to update everything except Recovered from the OR data report and press release.

Before:
![image](https://user-images.githubusercontent.com/404503/87880807-ba9e5b00-c9c2-11ea-9c6b-6c0aac6b3c21.png)

After:
![image](https://user-images.githubusercontent.com/404503/87881079-defb3700-c9c4-11ea-83d5-eb7add4c30a1.png)

**Comment by terwilliger42** [comment]
Thanks @MattHilliard !
