### ISSUE TITLE
PR: Correct URL for Puerto Rico

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#65]
I think urlwatch might still be tracking an old Puerto Rico public health coronavirus page, since the Status column in the stats sheet says "URL Not Found Anymore" but the most trusted data source is now https://estadisticas.pr/en/covid-19. That URL is correct as of now on http://covidtracking.com and in the States column in the sheet.

**Comment by schwartzadev** [comment]
This looks updated in the [latest screenshots](https://covidtracking.com/screenshots/PR/PR-20200331-001522.png) :+1:
