### ISSUE TITLE
[AL] Current Hospitalization data was updated after pub shift

### ISSUE THREAD

**Issue by jaclyde** [COVID19Tracking/issues#650]
AL had only a partial update of 920 up during all of pub shift, it has since been updated to 1465. 

https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7

<img width="779" alt="Screen Shot 2020-07-19 at 8 12 02 PM" src="https://user-images.githubusercontent.com/66583275/87896116-2b159e00-c9fc-11ea-82f2-f207c494fbf3.png">

**Comment by MattHilliard** [comment]
The older values do not match our data but I'm going to leave that for another issue.

Before:
![image](https://user-images.githubusercontent.com/404503/87956834-7de36a00-ca7d-11ea-95dc-3573fe479ca3.png)

After:
![image](https://user-images.githubusercontent.com/404503/87956905-95225780-ca7d-11ea-87f3-de5990466715.png)
