### ISSUE TITLE
[CA]Data entry error caused CA recoveries number to show up on 7/20. It should be deleted

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#652]
**State or US**: CA

**Describe the problem**
Data entry error caused CA recoveries number to show up on 7/20. It should be deleted

**Comment by space-buzzer** [comment]
Before:
![Screenshot from 2020-07-20 18-07-47-1](https://user-images.githubusercontent.com/62236447/88001578-57412580-cab5-11ea-9d67-55078fa730be.png)
Fix:
![Screenshot from 2020-07-20 18-13-56-2](https://user-images.githubusercontent.com/62236447/88001579-57d9bc00-cab5-11ea-8144-da9bfbe49856.png)

**Comment by space-buzzer** [comment]
Site updated
