### ISSUE TITLE
[MA] New tests being misreported as total molecular + postive antibody

### ISSUE THREAD

**Issue by airhadoken** [COVID19Tracking/issues#657]
Output from covid19-datafetch for Massachusetts yields this table (null columns removed for brevity):

STATE | FETCH_TIMESTAMP | POSITIVE | TOTAL | CURR_HOSP | HOSP | CURR_ICU | CURR_VENT | DEATH_PROBABLE | DEATH_CONFIRMED | PROBABLE | DATE | ANTIBODY_TOTAL | SPECIMENS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MA | 1594767517.597360 | 105986 | 972070 | 560 | 11625 | 93 | 37 | 215 | 8125 | 6144 | 7/14/2020 | 81525 | 1241465

And here's today's corresponding output:

date | state | positive | negative | pending | hospitalizedCurrently | hospitalizedCumulative | inIcuCurrently | inIcuCumulative | onVentilatorCurrently | onVentilatorCumulative | recovered | dataQualityGrade | lastUpdateEt | dateModified | checkTimeEt | death | hospitalized | dateChecked | totalTestsViral | positiveTestsViral | negativeTestsViral | positiveCasesViral | deathConfirmed | deathProbable | fips | positiveIncrease | negativeIncrease | total | totalTestResults | totalTestResultsIncrease | posNeg | deathIncrease | hospitalizedIncrease | hash | commercialScore | negativeRegularScore | negativeScore | positiveScore | score | grade
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
20200714 | MA | 112130 | 866084 |   | 560 | 11625 | 93 |   | 37 |   | 94347 | A+ | 7/14/2020 10:00 | 2020-07-14T10:00:00Z | 07/14 06:00 | 8340 | 11625 | 2020-07-14T10:00:00Z | 1241465 |   |   | 105986 | 8125 | 215 | 25 | 303 | 11768 | 978214 | 978214 | 12071 | 978214 | 10 | 14 | 223685fc192453cac71c42ba8e03d499630ee80e | 0 | 0 | 0 | 0 | 0

As far as I understand from reading over the code, the total test results in the output are calculated from `positive + negative + probable` from the datafetch input (where `negative = total - positive`, so `total + probable`). For reference, the value from the output table above is 978214.

This count leaves out negative antibody tests.  A correct count for `total` in the public api should be `positive + negative + antibody_total`, which would total 1053595 in the example.

**Comment by muamichali** [comment]
Hi @airhadoken 

The total test numbers we report, by design, include only viral/diagnostic tests. 
We do capture Antibody tests as well separately and plan to publish them in the future.

**Comment by airhadoken** [comment]
@muamichali Thanks for clarifying.  However, in the case you are describing, you should not be including Probable cases for Massachusetts at all -- the count of probable cases specifically excludes the results of molecular tests.
