### ISSUE TITLE
[NC] Updated Hospitalization Methodology and Curr. ICU

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#658]
**State or US**: North Carolina

**Describe the problem**
On 7/21, NC announced: "North Carolina has launched new, more detailed hospitalization data to provide more insights into North Carolina's hospital capacity." This slightly altered historical 'current hospitalization' and 'current icu' values until 6/21. On 7/22, we reported the 7/21 numbers for hospitalization and icu. For the backfill, data should be lagged by a day.

**Link to data source**
Slack Thread:
https://covid-tracking.slack.com/archives/C010RFJ0ZD3/p1595306262410800

State Site (bar chart below the chart labeled 'Currently Hospitalized COVID-19 Patients' --> select 'Adult ICU Patients')
https://covid19.ncdhhs.gov/dashboard/hospitalizations#content-container

**Comment by MattHilliard** [comment]
Unfortunately it looks like the state dashboard's Tableau graph only shows one month of data, so we can't get the July statistics at this point unless @space-buzzer knows of a different data source for NC hospitalization data.

**Comment by jaclyde** [comment]
Additional historical hospitalization data is still only available as described above. Closing this issue as we are unable to make the suggested edits'
