### ISSUE TITLE
[GA] Pub Shift missed a late testing update 4/29

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#659]
**State or US**: GA

**Describe the problem**
GA updated their testing a few hours late, causing us to have a lower testing value and an artificially high postivity %.

**Link to data source**
Screenshot from 4/29 morning:
![image](https://user-images.githubusercontent.com/67408226/88313878-fee27180-ccc8-11ea-9658-140bdab5bf92.png)

Screenshot from after the pub shift:
![image](https://user-images.githubusercontent.com/67408226/88313920-0b66ca00-ccc9-11ea-8fbb-ab446c07215d.png)

**Comment by muamichali** [comment]
BEFORE
![image](https://user-images.githubusercontent.com/1749380/88314061-648f2780-cce2-11ea-8dbc-9186e7756c4f.png)
