### ISSUE TITLE
[MP] Switch to People Tested in Calculations

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#666]
**State or US**: Northern Mariana Islands

**Describe the problem**
On 7/9, MP began to report both people and individuals tested. As of July 23rd, we are using the people-wise test totals as the default unit. This caused a perceived drop in the number of tests on 7/23.

**Link to data source**
https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5 and Screenshots (secondary)

**Comment by space-buzzer** [comment]
Duplicate of #627
