### ISSUE TITLE
[Data Quality]Switch Total Test Results Column in the API to use Total Test Results from States Daily in Public Sheet

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#667]
**Target Date:** Tuesday 7/28/2020

**Overview:** Let DE team control calculations of totals so we can switch states one by one

**Contribution to milestone:**  Total Test Results 

**Potential challenges:**  Fill out pos+neg

**Editorial:**  N/A

**Comment by muamichali** [comment]
@karaschechtman I am too tired to figure out if this overlaps with something you already added

**Comment by muamichali** [comment]
@karaschechtman  & @space-buzzer when less tired I think I can fold this into Kara's #665

**Comment by karaschechtman** [comment]
now it is in #664 with the changes we plan to make to the column in #676 and #665
