### ISSUE TITLE
[AK]july 16 report

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#668]
**State or US**: alaska

**Link to data source**
Provide links to original data sources that we can 
![EEED76EC-696E-4050-9EF7-570A9D2367A9](https://user-images.githubusercontent.com/1749380/88362350-38a78c80-cd4a-11ea-9dca-291ae6d562dd.jpeg)
refer to, like a state COVID website.

**Comment by crockettcobb** [comment]
I believe this is already referenced in issue #640 , as all the non-resident cases up to 16 JUL  were added in bulk to that date. The necessary data to backfill the nonresident cases into the total cases is available in this CSV:
https://opendata.arcgis.com/datasets/f34c6b1e58f34939bb6d2d721eb7a1e7_0.csv
