### ISSUE TITLE
[MA] Missed 7/23 Update

### ISSUE THREAD

**Issue by andrewghaly** [COVID19Tracking/issues#673]
Data is missing for 7/23. Will require backfill as well

https://www.mass.gov/doc/covid-19-dashboard-july-23-2020/download - July 23 data

![image](https://user-images.githubusercontent.com/8738663/88459463-b6ab8680-ce63-11ea-870e-ca305d137595.png)

**Comment by the-daniel-lin** [comment]
MA updated their website after our publication shift on 7/23 which resulted in the missed update. On 7/24, MA updated late again, and we used the 7/23 dashboard to fill in numbers on 7/24. Filling in the numbers with their proper dates now:

7/23 dashboard: https://www.mass.gov/doc/covid-19-dashboard-july-23-2020/download
7/24 dashboard: https://www.mass.gov/doc/covid-19-dashboard-july-24-2020/download

BEFORE:
![image](https://user-images.githubusercontent.com/67408226/89672622-d1392300-d899-11ea-8ebe-0b7c14eb7fe6.png)

**Comment by the-daniel-lin** [comment]
AFTER:
![image](https://user-images.githubusercontent.com/67408226/89673868-00509400-d89c-11ea-9f9c-b1294bf9c8f2.png)
