### ISSUE TITLE
[Data Quality] Switch totals column to confirmed+neg rather than pos+neg

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#676]
**Target Date:** TBD
**Overview:** Using the new column, switch the calculation of totals from pos+neg to confirmed+neg for any state where it's available.
**Contribution to milestone:** This will make our totals not include probables.
**Other benefits:** 
**Potential challenges:** None expected
**Editorial:** A blog post explaining the removal of probable cases from total test figures.

- [ ] Switch the pos+neg to confirmed+neg once issue #578 is complete
- [ ] Write a blog post [explaining the change](https://trello.com/c/ilU9117B/67-post-data-integrity-total-tests-probable-tracking)

**Comment by muamichali** [comment]
We are no longer sure whether this intermediate step will be necessary
