### ISSUE TITLE
[NV] Patch timestamps through 7/16 *Low Priority*

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#678]
**Describe the Issue:** 
On 7/26, we switched from using the site update timestamp to the "data through" timestamp for Nevada at 23:59 of the previous date. Both timestamps have been available since 7/16, so we should patch the timestamps until present. See https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1595793116050800 for full thread with discussion of process change.

**Data Source:** 
https://covidtracking.com/data/state/nevada

**Comment by brianskli** [comment]
The 23:59 timestamp was found to be relevant through **7/15**. States Daily was changed accordingly to account for current timestamp practices.

Before:
<img width="493" alt="Screen Shot 2020-08-07 at 9 09 07 AM" src="https://user-images.githubusercontent.com/66738237/89649073-2cfdaf00-d88e-11ea-866e-943707c2b101.png">

After:
<img width="496" alt="Screen Shot 2020-08-07 at 9 12 49 AM" src="https://user-images.githubusercontent.com/66738237/89649082-2f600900-d88e-11ea-9361-7c3270549816.png">
