### ISSUE TITLE
[Historical MO]: Switching to using the "Testing - PCR" tab instead of the "Overview" tab on the dashboard for confirmed cases  

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#679]
**State or US**: MO

**Describe the problem**
We have been using the number of "lab confirmed cases" in the "Overview" tab of the MO dashboard. However, there were concerns they were lumping positive antibody tests in this figure. We propose to use the "individuals with positive PCR results" on the "Testing - PCR" tab instead. This new dashboard links back to May 21st. 

**Link to data source**
[ArcGIS query link](https://services6.arcgis.com/Bd4MACzvEukoZ9mR/ArcGIS/rest/services/Dashboard_Daily_Numbers_Automated/FeatureServer/0/query?where=Description%3D%27PCR+Positive%27&outFields=value+as+confirmed) -- hopefully this can be used to backfill

**Comment by brianskli** [comment]
MO lists a confirmed number in their secondary screenshot history since 3/28 that could be useful.

**Comment by space-buzzer** [comment]
We don't have the "dashboard view" time series for confirmed cases, we only have a continuously backfilled series available from the state -- which we will *not* use for backfilling.
According to screenshots (e.g., https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/MO/MO-secondary-20200428-121449.png) they were publishing *confirmed* case numbers, and this is what we were capturing for positives. 
*Suggestion:* fill from positives

**Comment by space-buzzer** [comment]
![Screenshot from 2020-09-23 11-05-01](https://user-images.githubusercontent.com/62236447/94052188-6d0ce880-fd8d-11ea-90d2-8db7a212b1d7.png)
![Screenshot from 2020-09-23 11-08-27](https://user-images.githubusercontent.com/62236447/94052189-6da57f00-fd8d-11ea-91c2-e00a4a0b17b6.png)
