### ISSUE TITLE
OK: Negative test results note

### ISSUE THREAD

**Issue by lesleemoore** [COVID19Tracking/issues#68]
Please note the comment on https://coronavirus.health.ok.gov/, 

"*Negative testing results are only from the State Public Health Laboratory and do not include private laboratory negative results."

**Comment by una-smith** [comment]
Oklahoma State Department of Health is trying to get negative test results:

[OSDH Commissioner Urges Private Labs to Report All COVID-19 Test Results Daily to State (March 31, 2020)](https://coronavirus.health.ok.gov/articles/osdh-commissioner-urges-private-labs-report-all-covid-19-test-results-daily-state)

**Comment by careeningspace** [comment]
🤞

**Comment by quangnguyen1995** [comment]
Late update but as of now OK is reporting results from both public and private labs in their daily executive orders. This data has been captured.
