### ISSUE TITLE
[TX] Texas added ~600 deaths to their count today but the deaths are from previous dates. We should back-fill them 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#682]
**State or US**: Texas

**Describe the problem**
![image](https://user-images.githubusercontent.com/1749380/88597139-9979e200-d034-11ea-9f8a-051dc114eb87.png)

**Link to data source**
https://www.dshs.texas.gov/coronavirus/TexasCOVID19DailyCountyFatalityCountData.xlsx

**Comment by space-buzzer** [comment]
We've updated the time series for death (by date), to account for the new fatality reporting TX is doing. The new time series matches the site dashboard, and accounts for all new death added 

![Screenshot from 2020-07-28 07-07-33](https://user-images.githubusercontent.com/62236447/88833353-dd7c0b00-d21d-11ea-9e6b-7e3cab34924c.png)

[TX - Analysis #682 [TX] death.pdf](https://github.com/COVID19Tracking/issues/files/4996485/TX.-.Analysis.682.TX.death.pdf)

**Comment by space-buzzer** [comment]
We undid the backfill, based on internal discussion, because the available data for backfilling only reaches to 7/24, which makes the last week death numbers flat, but this is not the case.
We'll do it again, *once Texas publishes a time series up to today*
For now, it'll look like there was a big spike on 7/27

**Comment by space-buzzer** [comment]
This is blocked now, and we cannot backfill based on the cumulative time series published on TX's dashboard because all the recent additions are either not visible in the cumulative time series, or added historically, so daily increments will not presented correctly
