### ISSUE TITLE
[WA] PCL Historicals

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#685]
**State or US**:  Washington

**Describe the problem**
Our best understanding is that Washington reports only lab-confirmed PCR cases. The time series of column "Positive" and "Positive Cases (PCR)"column should be identical. 
However, there are multiple differences between the columns. 
1. From 2/29 to 6/22 the values are very different. [These values were added by a previous back-fill](https://github.com/COVID19Tracking/issues/issues/495)[ Using this sheet ](https://docs.google.com/spreadsheets/d/1HBLpM-CDTvgw8phKtzAD_Mt9CPmCEFSvaso9Rz1nAUs/edit#gid=1869230983)
2. Before 2/29 there are no values in 

**Link to data source**

**Comment by jaclyde** [comment]
All cases were backfilled in [this issue](https://github.com/COVID19Tracking/issues/issues/1017).
