### ISSUE TITLE
[SD] PCL Historicals

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#687]
**State:** SD

**Issue description:** We can't confirm that antibody testing isn't lumped in with RT-PCR testing results. SD has no annotation that explicitly states that cases are **_only confirmed_**, but we started reporting values in **positive cases (PCR)** on **7/17**. These values should be removed from positive cases (PCR). 

**Source:** https://doh.sd.gov/news/Coronavirus.aspx

**Comment by jesseandersonumd** [comment]
BEFORE (positive cases (PCR) column)
![Screen Shot 2020-07-29 at 9 40 45 AM](https://user-images.githubusercontent.com/57415941/88807403-ab1bd080-d17f-11ea-84ee-91034e3508ea.png)

**Comment by jesseandersonumd** [comment]
AFTER (positive cases (PCR) column)
![Screen Shot 2020-07-29 at 9 41 02 AM](https://user-images.githubusercontent.com/57415941/88807432-b5d66580-d17f-11ea-81be-c51ed39acaf5.png)

**Comment by jesseandersonumd** [comment]
POPUP BEFORE (positive cases (PCR) column)
![Screen Shot 2020-07-28 at 10 58 17 AM](https://user-images.githubusercontent.com/57415941/88807544-da324200-d17f-11ea-9367-c63348d1f350.png)

**Comment by jesseandersonumd** [comment]
POPUP AFTER (positive cases (PCR) column)
![Screen Shot 2020-07-28 at 10 51 42 AM](https://user-images.githubusercontent.com/57415941/88807607-f0400280-d17f-11ea-8993-3b76c78e6272.png)

**Comment by the-daniel-lin** [comment]
(DZL) Doublechecked -- 7/31 7:34
