### ISSUE TITLE
[MA] PCL Historicals (& Total Test Historicals)

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#689]
**State or US**: Massachusetts

**Describe the problem**
On 6/1, MA began reporting confirmed and probable cases. Our coverage of Positive Cases (PCR) began on 4/29. However, before 4/29, our entries in Positives does not match confirmed case counts from the daily PDF archive.

**Link to data source**
https://www.mass.gov/info-details/archive-of-covid-19-cases-in-massachusetts

**Comment by MattHilliard** [comment]
@brianskli I spot checked three days and they looked correct:
https://www.mass.gov/doc/covid-19-dashboard-may-15-2020/download
https://www.mass.gov/doc/covid-19-dashboard-may-10-2020/download
https://www.mass.gov/doc/covid-19-dashboard-may-5-2020/download

I know it's been a day but do you remember where you saw discrepancies?

**Comment by brianskli** [comment]
I believe this applies to some dates before 4/29. For example, on 4/20, 39643 was given on the PDF as opposed to 41416 from States Daily.

I believe somebody noticed that MA can occasionally retroactively update data.

**Comment by MattHilliard** [comment]
Oh, you did say before 4/29. Except we don't have Positive Cases (PCR) before 4/29. So this issue is for the **Positives** column not matching confirmed cases, I see.

**Comment by brianskli** [comment]
Yes, my apologies for being unclear. I've cleaned up the issue description as well.

**Comment by MattHilliard** [comment]
It looks like this is the result of the backfill done here: https://github.com/COVID19Tracking/issues/issues/251

I will discuss with the other people on the backfill team and decide whether we want to undo that change. I assume the ultimate goal here is to feel comfortable enough to copy the pre-4/29 Positives into Positive Cases (PCR).

**Comment by brianskli** [comment]
Thank you.

**Comment by muamichali** [comment]
@MattHilliard let's use this ticket for all our in progress MA back-fill work

**Comment by space-buzzer** [comment]
31st July:
> "*PLEASE NOTE: Delays in the reporting of test results to DPH from multiple laboratories, including large national commercial laboratories, are reflected in today’s case counts. However, these positive test results have been assigned retrospectively to the appropriate date of test."

Another reason to backfill, past numbers were changed to fill a backlock fill MA did

**Comment by theomichel** [comment]
We're planning on backfilling total and positive tests from MA's data, but in order to do this we need MA to add positive PCR tests to their dashboard. (so that their dashboard contains data for ongoing data collection) We're reaching out to them with that request.

**Comment by esquared** [comment]
> We're planning on backfilling total and positive tests from MA's data, but in order to do this we need MA to add positive PCR tests to their dashboard. (so that their dashboard contains data for ongoing data collection) We're reaching out to them with that request.

Removing stale tag

**Comment by muamichali** [comment]
[Changes (7).txt](https://github.com/COVID19Tracking/issues/files/6386826/Changes.7.txt)
On April 27, 2020, we restored positive and negative values in MA's timeseries from March 4, 2020 through April 24, 2020 that were previously overwritten by a backfill https://github.com/COVID19Tracking/issues/issues/251
We determined that restoring these values will create the most consistent timeseries of these metrics by date of report.
We also updated the values of Positive Cases (PCR) On April 28, 2020 and earlier to match the number of cases, since we determined that all the cases at that time were confirmed by a PCR test. (
