### ISSUE TITLE
[ME] PCL Historicals (3/15-4/28)

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#691]
**State or US**: Maine

**Describe the problem**
1. ME data capture good after 4/29, with separated confirmed and confirmed+positive reporting.
2. CTP Capture of `Cases (Confirmed and Probable)` can be used to fill in `Positive Cases (PCR)` values between 3/15-4/28, as Maine has always reported confirmed cases.

**Link to data source**
http://covid-tracking-project-data.s3-website.us-east-1.amazonaws.com/state_screenshots/ME/

**Comment by muamichali** [comment]
BEFORE 

![image](https://user-images.githubusercontent.com/1749380/94152834-07326680-fe4a-11ea-9f8e-c0c9a6a7a035.png)
