### ISSUE TITLE
[TX] PCL Historicals

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#692]
**State or US**: Texas

**Describe the problem**
TX does not explicitly say it reports in lab-confirmed, but it says that probables are not included. Positives are not being recorded in Positive Cases (PCR).

**Link to data source**
https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83

**Comment by brianskli** [comment]
Action items:
1/5 File private note in WS2
Before:
<img width="480" alt="Screen Shot 2020-07-29 at 10 23 32 AM" src="https://user-images.githubusercontent.com/66738237/88813653-32207700-d187-11ea-93a8-cf6ea748b474.png">
After:
<img width="478" alt="Screen Shot 2020-07-29 at 10 23 46 AM" src="https://user-images.githubusercontent.com/66738237/88813665-35b3fe00-d187-11ea-8a1f-1cbc1abefdbe.png">

2/5 Change pop-up in State Matrix
Before:
<img width="1191" alt="Screen Shot 2020-07-29 at 10 24 22 AM" src="https://user-images.githubusercontent.com/66738237/88813722-45cbdd80-d187-11ea-8c4b-3b6f08430160.png">
After:
<img width="1191" alt="Screen Shot 2020-07-29 at 10 24 36 AM" src="https://user-images.githubusercontent.com/66738237/88813730-495f6480-d187-11ea-8b66-660bb3645dba.png">

3/5 File GH issue

4/5  Copy over in States Daily
Before:
<img width="784" alt="Screen Shot 2020-07-29 at 10 36 53 AM" src="https://user-images.githubusercontent.com/66738237/88814121-b7a42700-d187-11ea-87f3-04a1d107b0f4.png">
After:
<img width="800" alt="Screen Shot 2020-07-29 at 10 38 54 AM" src="https://user-images.githubusercontent.com/66738237/88814132-ba9f1780-d187-11ea-8a45-87007830feb6.png">

5/5 File patch note form

**Comment by the-daniel-lin** [comment]
We found an unexplained gap in our Positive Cases (PCR) from 7/29-7/30. Filling it in here.

BEFORE:
![image](https://user-images.githubusercontent.com/67408226/89196453-14745880-d55f-11ea-97cc-e206201cc013.png)

AFTER:
![image](https://user-images.githubusercontent.com/67408226/89196560-3bcb2580-d55f-11ea-8c91-2042b0b79710.png)
