### ISSUE TITLE
[SC] PCL Historicals: Backfill Positive Cases PCR values (before 4/29,5-3-5/17) from Positive cases

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#693]
**State:** SC

**Dates impacted:** 5/03-5/17, before 4/29

![Screen Shot 2020-07-29 at 10 27 44 AM](https://user-images.githubusercontent.com/57415941/88812982-5f205a00-d186-11ea-970d-c94029feca16.png)

**Issue:** We had a gap in data reporting for positive cases (PCR) from 5/03-5/17. We reported values prior to 5/03. We need to backfill these values.
[Prior to 6/16 all the values reported by South Caroline were confirmed cases. ](https://scdhec.gov/news-releases/south-carolina-announces-latest-covid-19-update-june-17-2020#:~:text=COLUMBIA%2C%20S.C.%20%E2%80%94%20This%20week%2C%20the%20S.C.%20Department,Disease%20Control%20and%20Prevention%20to%20report%20this%20information)

**Comment by muamichali** [comment]
Hi @jesseandersonumd 
Do we have the source for this or do we need back-fill team to get it? I am not sure based on the issue here..

**Comment by jesseandersonumd** [comment]
**Update (8/1):** The gap in the values from 5/03-5/17 for positive cases (PCR) appears to easily be remedied by a simple copy and paste from positive cases (people, confirmed and probable). I think it might be a good idea for back-fill to confirm that this is doable. The source would simply be where we usually source data for these values, which is here: https://www.scdhec.gov/infectious-diseases/viruses/coronavirus-disease-2019-covid-19/sc-testing-data-projections-covid-19. Thank you for asking, Michal, and calling attention to this issue!

**Comment by muamichali** [comment]
Before and After snapshots in the attached sheet
[GH 693 - SC - Positive Cases PCR Timeseries Backfill.xlsx](https://github.com/COVID19Tracking/issues/files/5232622/GH.693.-.SC.-.Positive.Cases.PCR.Timeseries.Backfill.xlsx)
