### ISSUE TITLE
[HI] Incorrect negatives value 7/28

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#696]
**State or US**: Hawaii

**Describe the problem**
In the Negatives column, the entry for 7/28 was `114052-1620` which is the Total PCR Tests (People) value from 7/27 - an incorrect value also from 7/27 (from edit history digging)

We'll have to go check the historical numbers from those few days to see if the other values are correct.

**Link to data source**
From today's publication shift:
![image](https://user-images.githubusercontent.com/67408226/88858183-7b36f200-d1ac-11ea-8998-8784ce34a913.png)

**Comment by jesseandersonumd** [comment]
BEFORE: 
![Screen Shot 2020-08-04 at 9 48 26 AM](https://user-images.githubusercontent.com/57415941/89301471-b6677400-d637-11ea-8a51-9f52544d622b.png)

**Comment by jesseandersonumd** [comment]
**AFTER (7/28 --> (116387 - 1711))** 
![Screen Shot 2020-08-04 at 9 48 39 AM](https://user-images.githubusercontent.com/57415941/89301513-bd8e8200-d637-11ea-8777-a7902b3cdeeb.png)
