### ISSUE TITLE
[RI] Revisit time series data, especially stale weekend numbers

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/issues#697]
Rhode Island publishes a Google Spreadsheet with full time series for all the metrics we capture. We need to check whether we miss weekend updates because the dashboard is frozen, and backfill from RI's data if this is the case

**Comment by theomichel** [comment]
We concluded that we aren't missing cases in the cumulative counts, but our graphs are ugly with giant dips on weekends followed by spikes on Mondays, because RI doesn't update their dashboard on the weekends.

We decided to go ahead and do a very targeted weekly backfill, where every Monday we backfill in RI's cumulative totals for Saturday and Sunday from their google sheet of data. This will smooth the graph somewhat, although it'll leave a small spike on saturday. 

The likely reason for the saturday spike is that the monday spikes were actually due to 2 factors:
1. the saturday+sunday cases were showing up on Monday
2. the cases from other prior days, that happened to arrive at the website on Monday, would also show up on Monday.

We’ve solved #1, but we have moved #2 to showing up on Saturday instead of Monday.

**Comment by theomichel** [comment]
![image](https://user-images.githubusercontent.com/17862035/89835007-bb856100-db18-11ea-97a1-bc28858bf764.png)The bold cells are the values that we changed. (@space-buzzer made the change)

**Comment by theomichel** [comment]
This is now a weekly task and we (@space-buzzer @muamichali and I) agreed that we'll use a slack shiftbot for the weekly reminder. So now the work for this issue is to create and train the shift bot. : )

**Comment by theomichel** [comment]
I created a workflow for mondays at 11am with the RI reminder. I don’t see a way to manually trigger it now to test it, so I'm moving this card to "needs verification" and set myself a separate reminder for next Monday.

**Comment by space-buzzer** [comment]
Update 2020-08-17
![Screenshot from 2020-08-17 14-33-17](https://user-images.githubusercontent.com/62236447/90446822-e92d5580-e096-11ea-9bf9-f21d01a16706.png)
![Screenshot from 2020-08-17 14-33-42](https://user-images.githubusercontent.com/62236447/90446824-e9c5ec00-e096-11ea-88d0-0a38fc41af52.png)

**Comment by space-buzzer** [comment]
We shifted the days we filled by 1 day, to be compatible with how pub-shift is capturing the numbers.
Every day, during pub shift, we capture numbers for the previous day (and they're added to todays count). For weekend update, we should continue using the same strategy, otherwise, we report the "Sunday" number twice -- for Sunday and Monday

To remedy it, weekend update will behave exactly like pub-shift wrt day attribution

![Screenshot from 2020-08-17 18-38-59](https://user-images.githubusercontent.com/62236447/90461063-3373fe00-e0ba-11ea-87e9-1bf1735dd776.png)
![Screenshot from 2020-08-17 18-42-25](https://user-images.githubusercontent.com/62236447/90461068-340c9480-e0ba-11ea-9a06-a14f0d7452f1.png)

**Comment by space-buzzer** [comment]
Another week, another update
![Screenshot from 2020-08-31 12-15-06](https://user-images.githubusercontent.com/62236447/91757829-d67d4b00-eb83-11ea-873d-85e4786adcd7.png)
![Screenshot from 2020-08-31 12-15-36](https://user-images.githubusercontent.com/62236447/91757831-d715e180-eb83-11ea-8db0-23cdf094726f.png)

**Comment by space-buzzer** [comment]
Laber day weekend
![Screenshot from 2020-09-08 09-49-21](https://user-images.githubusercontent.com/62236447/92505395-e1a22d80-f1b8-11ea-9c6f-cc894c5097cf.png)
![Screenshot from 2020-09-08 09-50-29](https://user-images.githubusercontent.com/62236447/92505400-e23ac400-f1b8-11ea-9f3c-2ddc0c15024e.png)

**Comment by theomichel** [comment]
Weekend fill for 9/12 and 9/13:

Rows edited: 2

RI 2020-09-13
    positive: 23098 (was 22905)
    negative: 284385 (was 280118)
    hospitalizedCumulative: 2644 (was 2620)
    inIcuCurrently: 7 (was 8)
    onVentilatorCurrently: 4 (was 3)
    recovered: 2223 (was 2201)
    death: 1075 (was 1071)
    positiveTestsViral: 32660 (was 32589)
    negativeTestsViral: 600850 (was 583094)
    positiveCasesViral: 23098 (was 22905)
    totalTestEncountersViral: 633510 (was 615683)
    totalTestsPeopleViral: 307483 (was 303023)

RI 2020-09-12
    positive: 22999 (was 22905)
    negative: 283137 (was 280118)
    hospitalizedCumulative: 2639 (was 2620)
    onVentilatorCurrently: 4 (was 3)
    recovered: 2220 (was 2201)
    death: 1072 (was 1071)
    positiveTestsViral: 32558 (was 32589)
    negativeTestsViral: 595533 (was 583094)
    positiveCasesViral: 22999 (was 22905)
    totalTestEncountersViral: 628091 (was 615683)
    totalTestsPeopleViral: 306136 (was 303023)

**Comment by space-buzzer** [comment]
2020-09-21
All done!

![Screenshot from 2020-09-21 10-31-44](https://user-images.githubusercontent.com/62236447/93801319-aa8b3d80-fbf6-11ea-8cfa-415fff2d7875.png)
![Screenshot from 2020-09-21 10-35-09](https://user-images.githubusercontent.com/62236447/93801322-ab23d400-fbf6-11ea-8499-05bfce5bb03f.png)

**Comment by hmhoffman** [comment]
@space-buzzer @theomichel I think this was solved with RI bot! Unless we need to log those edits here, I'm going to close this issue.
