### ISSUE TITLE
[FL] Antibody specimen count backfill

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#698]
**State or US**: Florida

**Describe the problem**
It was determined that CTP's existing antibody test capture refers to people, not specimens. Existing data was copied into the correct columns.

Specimens now need to backfilled using the Serology Report provided by FL.

**Link to data source**
https://floridahealthcovid19.gov/?track_covid19

**Comment by space-buzzer** [comment]
This is the best, because it was already done in the past
