### ISSUE TITLE
"Cumulative" numbers should be greater than or equal to "current" numbers

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/issues#70]
When a state provides a "Currently" (hospitalized, in ICU, on ventilator) number but not a "Cumulative" number, we should add a value in "Cumulative" equal to the "Currently" value, as it is implied. 

After splitting out these values a couple of days ago, we haven't always done this. Our website currently only shows "Cumulative" hospitalized (this will change when we add all the new outcomes data in the next few days). So, while the daily values were accounting for a MAX() between current and cumulative (and weren't affected), the "current data" for hospitalization values is low.

Backfilling the data to add values in Cumulative for any places where Cumulative < Current. 

Affected rows (data filtered to show only these rows)

![image](https://user-images.githubusercontent.com/1327983/77812489-01fd8600-7078-11ea-88b7-bd1c500bc9c2.png)

After backfill/update:
![image](https://user-images.githubusercontent.com/1327983/77812516-2bb6ad00-7078-11ea-8415-cf2b276b9a3a.png)

**Comment by careeningspace** [comment]
This has been rectified

**Comment by wboka** [comment]
Has this been fixed? Shouldn’t the cumulative numbers in this screenshot be higher than the currently numbers? Correct my ignorance if I’m wrong.

![11EEA043-F036-4219-88F8-A8B8765AC8C6](https://user-images.githubusercontent.com/8128394/78500589-51514f80-7725-11ea-8172-3c5c9c4b774d.png)

**Comment by jdmaresco** [comment]
@wboka please see #132 

We reverted the changes originally made. We are still figuring out how to resolve the display of sums on the website but cumulative numbers are not always reported by states, and we aren’t comfortable using “current” numbers as “cumulative”.

Please see the note currently displayed on the site: 
![E1118B45-8928-48F5-95BD-116836C1E491](https://user-images.githubusercontent.com/1327983/78500736-421ed180-7726-11ea-8734-37fa30310a3d.jpeg)

**Comment by jdmaresco** [comment]
Correction: we *will be* reverting the changes originally made. In recent days, we’ve been reporting current/cumulative numbers exactly as reported by the states. Some of the early numbers counted “current” numbers as “cumulative” as shown in screenshots above — this will be reverted.
