### ISSUE TITLE
[MN] Historical Cases

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#704]
State: MN

Issue in brief: Prior to 6/14, we reported separate values for positive cases (PCR) and positive cases (people, probable+confirmed) even though we currently treat the positive cases values that MN reports as lab-confirmed only. It is unclear whether we can simply copy over the values pre-6/14 located in the positive cases (people, probable+confirmed) to the positive cases (PCR) column so that they are identical. Currently, we only have positive cases (PCR) going back to 2020/04/29 in the States Daily sheet, while positive cases (people, confirmed + probable) goes back to 2020/03/06. 

**Image showing the change on 6/14:**
![Screen Shot 2020-07-30 at 9 39 26 AM](https://user-images.githubusercontent.com/57415941/88938132-0074e200-d253-11ea-8e48-3e5fa339a809.png)

**Image showing when we started reporting positive cases (PCR) values:**
![Screen Shot 2020-07-30 at 10 53 57 AM](https://user-images.githubusercontent.com/57415941/88938176-12ef1b80-d253-11ea-9f13-0a114f030e86.png)

**Comment by MattHilliard** [comment]
This was a mistake in a [backfill on 6/14](https://github.com/COVID19Tracking/issues/issues/484)...I updated Positives without also noticing I should also update Positive Cases (PCR).

Data in Positives pre-6/14 has been copied over to Positive Cases (PCR). If we ever need to restore the old values, they are in the original Positives column of the 6/14 [backfill analysis sheet](https://docs.google.com/spreadsheets/d/1Y0ZtCoyZHOf_p0X12msYe9oKI6L38UgnGZHN8JddOHU/edit#gid=1869230983.:
