### ISSUE TITLE
[MA] 7/29 incomplete update

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#708]
**State or US**: MA

**Describe the problem**
7/29 testing numbers were not fully updated. The numbers were retroactively backfilled on 7/30, and States Daily should be updated accordingly.

**Link to data source**
https://www.mass.gov/info-details/covid-19-response-reporting

**Comment by MattHilliard** [comment]
Main source: https://www.mass.gov/doc/covid-19-dashboard-july-29-2020/download
"Recovered" number: https://www.mass.gov/doc/weekly-covid-19-public-health-report-july-29-2020/download

Before (2 screenshots to get the whole row):
![image](https://user-images.githubusercontent.com/404503/88991502-db15c180-d2ae-11ea-99a6-69392c6db4e4.png)
![image](https://user-images.githubusercontent.com/404503/88991544-f1bc1880-d2ae-11ea-8eda-aad51132d418.png)

After (also two screenshots):
![image](https://user-images.githubusercontent.com/404503/88991623-25973e00-d2af-11ea-8166-8ad7e24a2c07.png)
![image](https://user-images.githubusercontent.com/404503/88991666-4790c080-d2af-11ea-884a-29320bee2680.png)
