### ISSUE TITLE
[MP] Historical PCL Cases

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#709]
**State:** MP

**Dates impacted:** 3/16-5/02

**Issue:** We may be able to reasonably backfill **positive cases (PCR)** here by copying over the **positive cases (people, confirmed and probable)** over prior to 5/02, which is when we started reporting positive cases (PCR). We have confirmed that MP reports lab-confirmed cases.

**Comment by jaclyde** [comment]
Values moved: 
[Changes (16).txt](https://github.com/COVID19Tracking/issues/files/6347192/Changes.16.txt)
