### ISSUE TITLE
NY: Latent hospitalized count

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/issues#71]
The hospitalized number for NY [did not change from 3/26 to 3/27](https://covidtracking.com/data/state/new-york/).

Clearly that's not right. According to the Cuomo presser, the cumulative number should be 6481 + 2045 = 8,526.

![CEF3F5BA-C20D-418D-BB61-66268EEAAACA](https://user-images.githubusercontent.com/15233/77813973-375ba100-7083-11ea-86e8-2ca407e7f8cd.jpeg)

**Comment by jdmaresco** [comment]
States daily before
![image](https://user-images.githubusercontent.com/1327983/77814001-9c16fb80-7083-11ea-9cd2-5432b544d84c.png)

States daily after
![image](https://user-images.githubusercontent.com/1327983/77814011-b224bc00-7083-11ea-9499-a4a419554315.png)

**Comment by jdmaresco** [comment]
Checks before
![image](https://user-images.githubusercontent.com/1327983/77814034-e4ceb480-7083-11ea-9355-a671b4a40684.png)

Checks after
![image](https://user-images.githubusercontent.com/1327983/77814053-0465dd00-7084-11ea-9a56-3755802cf9b6.png)
