### ISSUE TITLE
[MO] Re-correct source for Positive (lumped) and Positive Cases PCR (confirmed) 

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#710]
**State or US**: MO

**Describe the problem**
After discussion, we decided to revert the source for MO total cases and confirmed cases back to the original source on the "Overview" tab of the dashboard http://mophep.maps.arcgis.com/apps/MapSeries/index.html?appid=8e01a5d8d8bd4b4f85add006f9e14a9d 

**Link to data source**
Using screenshots to backfill Wednesday (7/29) and Thursday (7/30) and Tuesday (7/28)

**Comment by qpmnguyen** [comment]
Screenshots 
7/30 6pm Screenshot 
![image](https://user-images.githubusercontent.com/25627274/89043453-8017b500-d316-11ea-89e5-1852c2ba0fc0.png)
7/29 6pm Screenshot
![image](https://user-images.githubusercontent.com/25627274/89043481-8e65d100-d316-11ea-8c98-ab49ad149325.png)

**Comment by qpmnguyen** [comment]
Fixes:
BEFORE:
![image](https://user-images.githubusercontent.com/25627274/89044710-58295100-d318-11ea-936e-8a8b0a9e91c9.png)
AFTER:
![image](https://user-images.githubusercontent.com/25627274/89045139-033a0a80-d319-11ea-80f5-5520da0e9a08.png)

**Comment by muamichali** [comment]
LGTM
