### ISSUE TITLE
[MD] Backfill data for Positive Tests (PCR)

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/issues#711]
**Target Date:** 
**Overview:** Currently we do not report _positiveTestsViral_ for Maryland. MD publishes this data at https://coronavirus.maryland.gov/datasets/mdcovid19-testingvolume/data?orderBy=date&orderByAsc=false in a downloadable spreadsheet and in its API. I have entered a new value (July 31, 2020) for this data as of July 29, 2020 an guidance to checkers on updating it subsequently, but we need to backfill the time series.
**Contribution to milestone:** Not related to current milestone but is related to "People vs. Tests" breakout
**Other benefits:** new data
**Potential challenges:** Backfilling
**Editorial:** Public note about new _positiveTestsViral_ data available for MD

**Comment by space-buzzer** [comment]
We backfilled Total-PCR-tests and Positive-PCR-tests from MD's "Testing Volume" ArcGIS dataset, as it was captured on Aug-16th.
The backfill included only Aug-16th and earlier dates, going all the way back to March-24 

[post_update[DataStore]Coronavirus numbers by state - [Raw]StatesDaily.csv.txt](https://github.com/COVID19Tracking/issues/files/5152455/post_update.DataStore.Coronavirus.numbers.by.state.-.Raw.StatesDaily.csv.txt)
[pre_update_[DataStore]Coronavirus numbers by state - [Raw]StatesDaily.csv.txt](https://github.com/COVID19Tracking/issues/files/5152456/pre_update_.DataStore.Coronavirus.numbers.by.state.-.Raw.StatesDaily.csv.txt)
![Screenshot from 2020-08-31 13-12-49](https://user-images.githubusercontent.com/62236447/91764449-2c55f100-eb8c-11ea-82cd-9982064a5a40.png)
![Screenshot from 2020-08-31 13-14-10](https://user-images.githubusercontent.com/62236447/91764450-2d871e00-eb8c-11ea-88ca-b6020c0952f0.png)
