### ISSUE TITLE
[MT] PCL Historicals

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#713]
**State:** MT

**Dates impacted:** 3/07-4/29

**Issue:** We've confirmed that MT is _**lab-confirmed only**_ and started reporting positive cases (PCR) on 4/29. We may be able to reasonably copy over the values from 3/07-4/29 in the positive cases (people, probable and confirmed) over to positive cases (PCR).

**Comment by the-daniel-lin** [comment]
***Note: Our screenshots for MT show that the state began reporting explicit confirmed cases on 4/07, but it seems to imply that they were reporting confirmed cases since the beginning -- needs more investigation.

**Comment by muamichali** [comment]
This is moot since the cases we were capturing at that point were not actually lab confirmed. We do not have a timeseries of lab confirmed cases to backfill with.
