### ISSUE TITLE
[OK] PCL Cases Backfill

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#720]
**Describe the Issue:** We didn't start recording pos. pcr cases for OK until 6/9. EORs from previous dates have a case number which is defined as "*Case: Meets confirmatory laboratory evidence.". We can use this figure to backfill historical pcr cases up to 4/14 when they added to clear definition for the number. 

Data Source:
https://coronavirus.health.ok.gov/executive-order-reports

**Comment by MattHilliard** [comment]
On 4/13, there is a [note](https://coronavirus.health.ok.gov/sites/g/files/gmc786/f/eo_-_covid-19_report_-_4-13-20.pdf) that the total includes 5 probable cases. Perhaps we could just subtract 5 from the total positives to account for that, but I suppose it doesn't quite say explicitly that all the other cases are confirmed.

Before (point where **Positive Cases (PCR)** stopped):
![image](https://user-images.githubusercontent.com/404503/89217881-f593b780-d59a-11ea-8ca7-7cf016a88309.png)

After (new point where **Positive Cases (PCR)** stops):
![image](https://user-images.githubusercontent.com/404503/89218004-3ee40700-d59b-11ea-9555-791d9f6213a1.png)
