### ISSUE TITLE
[CT]Back-fill data added in the last 7 days that reflects cases (& tests?)

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#721]
**State or US**: CT

**Describe the problem**
CT had two dumps of old test results from Enzo Labs, an out of state lab that just submitted their results to CT in two batches in the past 7 days.  These data date back to April, but because they were dumped into CT totals now 
 
Specifically this catch up data included 440 cases reported last Friday + 384 Wednesday = 824 cases that should be removed from our recent totals to better reflect recent trends.

**Link to data source**
<img width="1415" alt="Screen Shot 2020-07-31 at 10 25 14 PM" src="https://user-images.githubusercontent.com/1749380/89092112-cacc1800-d37c-11ea-8b18-d585399e2919.png">   

<img width="1437" alt="Screen Shot 2020-07-31 at 10 26 59 PM" src="https://user-images.githubusercontent.com/1749380/89092138-17175800-d37d-11ea-8ddf-f8448212b966.png">

**Comment by MattHilliard** [comment]
@muamichali CT provides two time series for confirmed cases: positive cases by dashboard time and positive cases by specimen collection time. The former matches what we already have and includes the July 24 jump, the latter smooths that out but would result in mixing. I don't think there's much we can do until we have a "state revised time series" strategy in place.

**Comment by theomichel** [comment]
Based on our meeting yesterday, I would say that this backfill would not meet the mixery-exception bar. (because it's not a new column where we're bootstrapping old history)

So, I would like to close this "won't fix". If CT puts pressure on us, that pressure should go towards adding a new column with approprirate "by date" assignment. I've started a slack conversation to get consensus.

**Comment by theomichel** [comment]
There was some more discussion about just giving CT a new column (similar to RI and CO) instead of this. More to come.

**Comment by muamichali** [comment]
Does not meet the mixery-exception bar.
