### ISSUE TITLE
[MA] Missed 8/1 and 8/5 Update

### ISSUE THREAD

**Issue by andrewghaly** [COVID19Tracking/issues#722]
**State or US**: Massachusetts

**Describe the problem**
Due to late update, 8/1 data from MA was not entered.

**Link to data source**
https://www.mass.gov/doc/covid-19-dashboard-august-1-2020/download - August 1 data

**Comment by jaclyde** [comment]
Adding the missed 8/5 update to this issue. Link to 8/5 update: https://www.mass.gov/doc/covid-19-dashboard-august-5-2020/download

**Comment by jaclyde** [comment]
<img width="1454" alt="Aug 01 BEFORE" src="https://user-images.githubusercontent.com/66583275/89480254-b8b9f300-d749-11ea-94a6-65847ece0483.png">
<img width="1312" alt="Aug 01 AFTER" src="https://user-images.githubusercontent.com/66583275/89480257-ba83b680-d749-11ea-8348-da6e4b254c71.png">

**Comment by jaclyde** [comment]
BEFORE
<img width="1629" alt="Aug 05 BEFORE" src="https://user-images.githubusercontent.com/66583275/89480296-d25b3a80-d749-11ea-8a3d-1195c50cdf36.png">
AFTER
<img width="1610" alt="Aug 05 After" src="https://user-images.githubusercontent.com/66583275/89480300-d424fe00-d749-11ea-9b8c-5109d69c3d95.png">

**Comment by andrewghaly** [comment]
Thanks @jaclyde, #673 is also a similar issue.
