### ISSUE TITLE
[NY] Patch timestamp for 8/01 *Low Priority*

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#723]
**Describe the Issue:** On 8/01 we used the publish time and date of NY's most recent covid press release for the timestamp. Our policy is to use the "testing data as of" date on the dashboard and 23:59. The data from the press releases is as of yesterday, which aligns with out current NY timestamp policy

**Data Source:** https://covidtracking.com/screenshots/NY/NY-20200801-182030.png (screenshot of NY dashboard from yesterday with testing data as of date.

**Comment by brianskli** [comment]
NY's timestamp for 8/1 was changed to 7/31 23:59 per existing guidance.

Before:
<img width="1014" alt="Screen Shot 2020-08-07 at 9 00 55 AM" src="https://user-images.githubusercontent.com/66738237/89648049-9c729f00-d88c-11ea-8be8-37701ab159e1.png">

After:
<img width="1018" alt="Screen Shot 2020-08-07 at 9 01 22 AM" src="https://user-images.githubusercontent.com/66738237/89648055-9f6d8f80-d88c-11ea-8db9-9b2a5e615a10.png">
