### ISSUE TITLE
[SD] Patch Timestamps through 7/13 *Low Priority*

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#724]
**Describe the Issue:** On 8/2 it was discovered that SD has changed their data as of time to 13:00, we are now using previous day 13:00 as the timestamp. Before this change we were using previous day 17:00. This change was made on 7/13, so we should patch timestamps from 8/1 - 7/13 using previous day 13:00.

**Data Source:** https://doh.sd.gov/news/Coronavirus.aspx

**Comment by brianskli** [comment]
Timestamps were patched in States Daily in accordance with current practices.

Before:
<img width="511" alt="Screen Shot 2020-08-07 at 9 25 01 AM" src="https://user-images.githubusercontent.com/66738237/89650279-325bf900-d890-11ea-97c3-8aac8082c07b.png">
After:
<img width="493" alt="Screen Shot 2020-08-07 at 9 26 49 AM" src="https://user-images.githubusercontent.com/66738237/89650285-3425bc80-d890-11ea-8b9f-e3c03ec70df3.png">
