### ISSUE TITLE
[GU] Patch Total PCR Tests (People) for 8/1

### ISSUE THREAD

**Issue by ladyzhetse** [COVID19Tracking/issues#725]
**State or US**: Guam

**Describe the problem**
During pub shift on 8/2, we realized that the "Total PCR Tests (People)" figure had been incorrectly calculated the previous day, 8/1. It should be 22,044 (359+21685), not 22,052 (367+21685).

**Link to data source**
359 = PCR confirmed cases (356 from dashboard + 3 from 8/1 press release); 21685 = negative cases (from press release)
https://ghs.guam.gov/jic-release-no-245-cumulative-results-three-test-positive-covid-19-dphss-tests-doc-employees-new
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1596401618039500

**Comment by qpmnguyen** [comment]
Fixing according to the JIC release number 245 linked above
BEFORE:
![image](https://user-images.githubusercontent.com/25627274/89191969-aedd9780-d571-11ea-9fa2-042ee8ebc255.png)
AFTER: 
![image](https://user-images.githubusercontent.com/25627274/89192048-cb79cf80-d571-11ea-92eb-563338f29b6c.png)
