### ISSUE TITLE
[TX] Patch Data for 8/2

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#729]
**Describe the Issue:** On 8/2, Texas did not release any new data (with the exception of current icu numbers, which we carried over anyway due to a mistake in their calculation) due to planned system maintenance. They said they would release the data for 8/2 on 8/3, but we did not find all of it during the pub shift. However they do have a section on their dashboard with daily new cases and deaths, which only include numbers from 8/3. If we subtract those from the total number of cases/deaths on 8/3 we can patch columns AK, AN, and AX.

**Data Source:** https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83

**Comment by muamichali** [comment]
I am closing this ticket, because I don't think we want to mix up "new" numbers with cumulative numbers. If the state is backfilling while also reporting new cases & deaths as separate numbers, we will end up with a number that they would not have reported had they reported on that day.
