### ISSUE TITLE
[KY] Inputting PCR Tests (Specimens) in PCR Tests (People)

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#730]
**State or US**: Kentucky

**Describe the problem**
On 8/3, we discovered that we're currently reporting total PCR tests (specimens) in the Total PCR Tests (People) column. This is reflected in our SVP sheet and in 6/16 and 6/30 outreaches.

We need to:
- Change popup notes
- Copy over the values from `Total PCR Tests (People)` into `Total Tests (PCR)`

**Link to data source**
6/16 Outreach: https://covid-tracking.slack.com/archives/C0124MP2E5C/p1592314451088800
6/30 Outreach: https://covid-tracking.slack.com/archives/C0124MP2E5C/p1593540304173000

**Comment by brianskli** [comment]
KY's units were confirmed to be in specimens.

Pop-ups were changed
Before:
<img width="667" alt="Screen Shot 2020-08-04 at 10 04 38 AM" src="https://user-images.githubusercontent.com/66738237/89303422-2d9e0780-d63a-11ea-8317-8a8b05b36970.png">
After:
<img width="668" alt="Screen Shot 2020-08-04 at 10 04 46 AM" src="https://user-images.githubusercontent.com/66738237/89303439-31318e80-d63a-11ea-9983-fb2fac2b5302.png">

Values in States Daily were copied over
Before:
<img width="802" alt="Screen Shot 2020-08-04 at 10 03 51 AM" src="https://user-images.githubusercontent.com/66738237/89303475-3c84ba00-d63a-11ea-8f9b-eaa6d1014754.png">
After:
<img width="798" alt="Screen Shot 2020-08-04 at 10 04 09 AM" src="https://user-images.githubusercontent.com/66738237/89303481-40184100-d63a-11ea-9753-4e9c04e5fd16.png">
