### ISSUE TITLE
8/4 new tests -5M

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#733]
**State or US**: US

**Describe the problem**
New tests for 8/4 are showing as negative 5,000,000+

**Link to data source**
N/A

**Comment by brianskli** [comment]
Hi Loglow,

Thanks for your message. We are aware of this duplication which came about due to a publishing error. Our data team is working to resolve this immediately.

**Comment by loglow** [comment]
I'm replying to this again just because now all the 8/4 published data is incorrect, with extremely high values across the board.
