### ISSUE TITLE
[KY] Unresolved #REF! errors for KY Total Tests (PCR) 

### ISSUE THREAD

**Issue by zachlipton** [COVID19Tracking/issues#734]
**State or US**: KY

**Describe the problem**
A number of `Total Tests (PCR)` fields for KY in States Daily display `#REF!` instead of the expected value.  Looks like it happened for all dates `20200512` and earlier.

A search of States Daily for `REF!` has 61 results. The formula in these cells is just `=#REF!+#REF!`

**Comment by zachlipton** [comment]
I'm guessing this occurred in the process of addressing #730

**Comment by space-buzzer** [comment]
The bad refs in KY was a formula that got moved too many cells to the left

[States Daily.zip](https://github.com/COVID19Tracking/issues/files/5037544/States.Daily.zip)
