### ISSUE TITLE
[HI]Back fill current ICU numbers from the lt. governor's Instagram page 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#737]
**State or US**: Hawaii

**Describe the problem**
This data point is only reported on Instagram. We should back-fill from there

**Link to data source**
8/4 HOSP 138 ICU 15 VENT 10
8/3 HOSP 75 ICU 15 VENT 10
8/2 HOSP 75 ICU 15 VENT 10
7/31 HOSP 65 ICU 14 VENT 10
7/30 HOSP 61 ICU 11 VENT 9
https://www.instagram.com/p/CDX-wtKjo1v/?igshid=1ux0dry15wg4y

![HI 7-30-20](https://user-images.githubusercontent.com/1749380/89457117-e0519100-d732-11ea-98b9-49e115b21d1e.png)
![HI 7-31-20](https://user-images.githubusercontent.com/1749380/89457125-e182be00-d732-11ea-849f-98a0f9e922b0.png)
![HI 8-1-20](https://user-images.githubusercontent.com/1749380/89457127-e182be00-d732-11ea-9b68-3ab01768366e.png)
![HI 8-2-20](https://user-images.githubusercontent.com/1749380/89457128-e21b5480-d732-11ea-9f3a-64a125a4e579.png)
![HI 8-4-20](https://user-images.githubusercontent.com/1749380/89457130-e21b5480-d732-11ea-9681-5a09acfbb867.png)

**Comment by muamichali** [comment]
**BEFORE**
![image](https://user-images.githubusercontent.com/1749380/89458062-6ae6c000-d734-11ea-82e8-c2828f0d1cb0.png)

**Comment by the-daniel-lin** [comment]
The data was released on Instagram after our publish shift time, so backfilling 8/5 hospitalization numbers with: 

![image](https://user-images.githubusercontent.com/67408226/89540858-75e03580-d7b2-11ea-8360-bea55db58458.png)


BEFORE:

![image](https://user-images.githubusercontent.com/67408226/89540839-6eb92780-d7b2-11ea-9d11-2660e6fa1ce5.png)

AFTER:

![image](https://user-images.githubusercontent.com/67408226/89540936-901a1380-d7b2-11ea-807b-1f069e93a4be.png)

**Comment by the-daniel-lin** [comment]
Changed in WS2 as well

BEFORE:

![image](https://user-images.githubusercontent.com/67408226/89569960-5230e580-d7da-11ea-818e-809bff5d4c1a.png)

AFTER:

![image](https://user-images.githubusercontent.com/67408226/89570020-6d035a00-d7da-11ea-8a3b-dc3061c255ae.png)

**Comment by muamichali** [comment]
I am closing this @the-daniel-lin
