### ISSUE TITLE
[GU] Backfill current icu values 8/6-8/8

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#747]
**State**: GU 
**Dates impacted**: 8/6-8/8
**Issue described**: On 8/10, we discovered a new source for current icu figures. GU has began posting daily "Guam COVID-19 Case Update", which include current icu numbers. We should patch current icu for 8/6, 8/7, and 8/8 using the case updates from that day. 
**Sources**: https://www.facebook.com/GHSOCD/?tn-str=k*F

**Comment by MattHilliard** [comment]
Before:
![image](https://user-images.githubusercontent.com/404503/92287259-4585d700-eed7-11ea-8cec-98b5cbad02d6.png)

After:
![image](https://user-images.githubusercontent.com/404503/92287373-98f82500-eed7-11ea-8e2d-22943651e84c.png)
