### ISSUE TITLE
[AR] SVP Fixes; Move 3/6-7/3 values from Total PCR Tests (People) to Total Tests (PCR) since reporting units are unclear

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#748]
**State**: Arkansas

**Dates impacted**: pre-7/3 (inclusive) 

**Issue**: Prior to 7/3, CTP was capturing total tests in _Total PCR Tests (People)_, after 7/3 we started reporting total tests in _Total Tests (PCR)_. But, we are still reporting negative tests in people, even though negatives are reported in specimens. We think we should copy negative tests from people to Negative Tests (PCR) **KEEP all values in Negative (People or Cases) and copy values to Negative Tests (PCR)** to reflect the fact that negatives are reported in specimens as confirmed by outreach. We also think we should move total tests pre-7/3 to Total Tests (PCR) from Total PCR Tests (People). We should also flag that the AR total tests number is calculated by (positives cases (people) + negatives tests (specimens)). :( 

**Action Plan**:
- [x] Start Capturing in Negative Tests (PCR)  
- [x] Move  _Total PCR Tests (People)_, captured from 3/6-7/3 to  _Total PCR Tests (People)_
[AR Moved Values from Total Tests PCR People to Total Tests PCR.txt](https://github.com/COVID19Tracking/issues/files/5091254/AR.Moved.Values.from.Total.Tests.PCR.People.to.Total.Tests.PCR.txt)

**Comment by brianskli** [comment]
**Interim changes:** Negatives are now listed in both Negative Tests (People or Cases) _and_ Negative Tests (PCR)

**1/2: WS2**
Before:
<img width="1124" alt="Screen Shot 2020-08-11 at 10 33 11 AM" src="https://user-images.githubusercontent.com/66738237/89910444-3fddef80-dbbe-11ea-8060-ec40ae14ac86.png">
After:
<img width="1115" alt="Screen Shot 2020-08-11 at 10 33 32 AM" src="https://user-images.githubusercontent.com/66738237/89910454-42d8e000-dbbe-11ea-8482-351ab7135662.png">

**2/2: States Matrix**
Before:
<img width="1327" alt="Screen Shot 2020-08-11 at 10 35 03 AM" src="https://user-images.githubusercontent.com/66738237/89910536-5be19100-dbbe-11ea-9411-0c17c78ad928.png">
After:
<img width="1324" alt="Screen Shot 2020-08-11 at 10 35 12 AM" src="https://user-images.githubusercontent.com/66738237/89910551-61d77200-dbbe-11ea-8e14-54ba4a202be8.png">

**Comment by muamichali** [comment]
@the-daniel-lin would you mind working on this tomrrow? I think you have a good understanding of it.

**Comment by muamichali** [comment]
Moved 3/6 - 7/3 values from `Total Tests PCR (People)` to `Total Tests (PCR)` - the values moved are recorded in a txt CSV file in the issue description.
