### ISSUE TITLE
[FL] Incorrect Testing Value, 5/17;  Total Tests PCR (People) before 5/13; missing Total Tests (PCR) before 5/17

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#749]
**State:** FL

ISSUE ONE - resolved
**Date impacted:** 5/17
**Issue:** We incorrectly reported Total Tests (PCR) on 5/17 as 653081 when it should be 746124. 
**Source:** http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/state_reports_20200517.pdf

ISSUE TWO
**Date impacted:** Before 5/13
**Issue:** missing Total Tests PCR (People) before 5/13
**Source:** http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/state_reports_20200517.pdf

ISSUE THREE
**Date impacted:** 5/17
**Issue:**  missing Total Tests (PCR) before 5/17
**Source:** http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/state_reports_20200517.pdf

**Comment by jesseandersonumd** [comment]
BEFORE: 
![Screen Shot 2020-08-11 at 10 51 52 AM](https://user-images.githubusercontent.com/57415941/89913825-2b9bf180-dbc2-11ea-8e0a-64025873b20f.png)

**Comment by jesseandersonumd** [comment]
AFTER: 

![Screen Shot 2020-08-11 at 11 02 57 AM](https://user-images.githubusercontent.com/57415941/89913892-3c4c6780-dbc2-11ea-87fd-165ad9c64281.png)

**Comment by jaclyde** [comment]
Double-checked. Everything looks good.
