### ISSUE TITLE
In addition to cumulative

### ISSUE THREAD

**Issue by SarahMaeSmith** [COVID19Tracking/issues#75]
Is there data about the number of people who have recovered. The current numbers appear to be cumulative, but some of those people have recovered. In predicting the load on medical facilities isn't it more useful to have the number of currently ill patients? By looking at the growing cumulative total, the curve will be skewed high. So, needed statistics:
Non-hospitalized patients recovered
Hospitalized patients recovered
Current hospitalizations (not cumulative)

Great project. Better data than is provided by the CDC. I do like the format of the Florida dashboard: https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429

**Comment by realfuture** [comment]
We can only provide what the states provide us. We hear that recovered is going to be an extremely difficult statistic to generate. I would not expect anything but current hospitalizations to be a reliable indicator of what you are interested in.

**Comment by schwartzadev** [comment]
As states report new data, we will try to report it in turn.

We are hoping to add recoveries data in the coming days.

Thank you @realfuture :+1:

**Comment by SarahMaeSmith** [comment]
I understand. Working with spotty data. Still, I see you have added columns for current in addition to cumulative. Kudos on a spectacular effort to gather information and present it to the public. This data should also be valuable in the future for creating models that are more reliable than the current ones, which are based on guess work and sketchy data from China. The CDC should be requiring states to report data for current and cumulative for: tests, ill, hospitalized, recovered, ICU, ventilators. If states don't have the data, they are woefully unprepared to predict equipment and personnel needs.
