### ISSUE TITLE
[GU] Unclear Units for Total Tests (PCR), Positive Tests (PCR) and Negative Tests (PCR)

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#751]
State/Territory: GU

Dates impacted: 5/19-8/11 and 5/25-5/26

Issues: On 7/1, we stopped reporting **positive tests (PCR)** and **negative tests (PCR)** because were unsure about the units that they were reported in (we suspected they were reported in people as opposed to specimens). A Guam annotation says **Total Tests (PCR)** is in _specimens_, but **positive tests (PCR)** and **negative tests (PCR)** summed to Total Tests (PCR). We are not sure about the units of **Total Tests (PCR)** because **positive tests (PCR)** and **negative tests (PCR)** are both unclear unit-wise. 

Currently, we are summing **Positive Cases (PCR)** and **negative (people or cases)** in order to get **Total PCR Tests** **(People).** The **Total PCR Tests (People)** value is consistently equal or roughly the same as the value in **Total Tests (PCR)**, even though **Total Tests (PCR)** is supposedly in specimens and **Total PCR Tests (People)** is in people. 

We need to outreach to confirm whether **Total Tests (PCR)** is in people or in specimens as well as whether **positive tests (PCR)** and **negative tests (PCR)** are in people or specimens. 

Source: https://www.ghs.guam.gov/jic-release-no-210-updated-reporting-procedures-results-end-day-results-four-test-positive-covid-19

**Comment by muamichali** [comment]
This issue is moot. See https://github.com/COVID19Tracking/issues/issues/964
