### ISSUE TITLE
[TN] Historical values now available for ICU and ventilator usage

### ISSUE THREAD

**Issue by MattHilliard** [COVID19Tracking/issues#752]
**State or US**: TN

**Describe the problem**
Tennessee recently added current ICU and ventilator usage to their dashboard. This includes numbers going back to 7/28. These appear to be "current" numbers, so backfilling the two weeks of available history should not conflict with the DE pub shift going forward.

**Link to data source**
https://www.tn.gov/health/cedep/ncov/data/hospitalization-data/current-covid-hospitalizations.html

**Comment by muamichali** [comment]
TN hospital data is constantly revised by the state so this is not currently possible to do reliably
