### ISSUE TITLE
[HI] Total PCR Tests (People) 5/13 - 5/22 

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#753]
**State or US**: Hawaii

**Describe the problem**
On 5/23, we began reporting total testing values in Total Tests (PCR), switching from Total PCR Tests (People). On 6/8, we resumed reporting in Total PCR Tests (People) with a different source.

1. From 5/13 - 5/22, the Total PCR Tests (People) values should be moved to the Total Tests (PCR) column
2. HI has press releases with which we can back fill: https://health.hawaii.gov/news/covid-19-updates/

~~2. Using the Wayback Machine, we should be able to backfill Total PCR Tests (People) with this link: https://hawaiicovid19.com/~~

**Comment by muamichali** [comment]
We have backfilled the "tests" wise data for HI on 10/9/2020 which makes this issue moot See https://github.com/COVID19Tracking/issues/issues/892
