### ISSUE TITLE
Arizona data quality grades not current

### ISSUE THREAD

**Issue by ghost** [COVID19Tracking/issues#755]
**Arizona**: 

**Describe the problem**
COVID19Tracking describes Arizona data as including all tests. This is wrong. **This error in how COVID19Tracking describes these data has resulted in researchers and analysts who use these data incorrectly calculating test positivity by using all positives, but only a portion of negatives.** This issue has not received attention for 15 days. It is an important, but thankfully simple fix. Update the data quality grades.

COVID19Tracking Data quality grades for Arizona have a check for "Machine readable" and "Reporting total test conducted". There are two issues here:

- Reporting total test conducted
The Director of the Arizona Department of Health Services, Dr. Cara Christ, is quoted in local media today as saying they do not report total tests. The dashboard reports a figure for "total tests", but Dr. Christ explains in her interview that this is not "total tests".  Some labs are not reporting negative results to the state, so DHS is unable to include those negative results in the total. They report all positive tests, but only some of the negative tests, making the "total test" figure the sum of the all the tests they have, rather than the actual total conducted. Please update the data quality grade accordingly.

- Machine readable
Confirmed/probable cases and confirmed/probable deaths are reported as a tableau vizintooltip. The data itself is an image of numbers, with no alt text. I'm unable to parse the image with OCR, so I'm not sure how this is machine readable. I could be missing something, though.

**Link to data source**
- Total tests
See [azfamily.com](https://www.azfamily.com/news/continuing_coverage/coronavirus_coverage/the-reason-why-there-are-so-many-conflicting-covid-19-positivity-rates-for-arizona/article_83fa2d80-dc33-11ea-8d38-17fac0e3733a.html)

> Dr. Christ says some labs across the state report all their negative and positive cases while other labs only report their positive cases.
> 
> When calculating the positivity, the state does not include positive cases unless the lab also provides negative cases. Johns Hopkins uses all data collected.
> 
> Dr. Christ says using the positives without the negatives creates a falsely high number.
> 
> "You could have one person get tested, and it gets reported to the department, but there could have been 1,000 people tested. If those negatives don't get included, you'd have 100% positivity, and that's not accurate," says Dr. Christ.

Dr. Christ says more in the video. The relevant section starts at 4:06. Dr. Christ is saying that you (the source of JHU's calculation) do not, in fact, have the denominator for the percent positivity statistic (total tests) because they (DHS) are not reporting it. This should be reflected in the data quality grade.

Further reporting on this issue with comments from state public health authorities:
https://www.abc15.com/news/state/arizonas-handling-of-covid-19-health-data-gets-new-challenge
https://www.azcentral.com/story/news/local/arizona-health/2020/08/17/arizona-leaves-out-written-faxed-test-results-when-calculating-covid-19-percent-positivity/5587283002/
https://www.azfamily.com/news/continuing_coverage/coronavirus_coverage/state-of-arizona-johns-hopkins-have-different-covid-19-stats-for-same-data/article_76bde470-de3d-11ea-957d-9f65c34e435c.html

- Machine readable 
Re: confirmed/probable, see [the state dashboard](https://azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php)

Extracting the vizintooltip from the page source, the breakdown of confirmed/probable (for example) is an image. The url for that image is [here](https://tableau.azdhs.gov/vizql/tilecache/5E489168531A4CCF8BD4EE43C78B91F9-4:2/8483/VizInTooltip/157767/640CF13950CD4D8BB5F6500C2295831F.A115AB9711DD42D2835EC54DEC8E9B71.1.300.300.png). There is no alt text.

**Comment by mentalplex** [comment]
This issue should receive some attention. Arizona data quality grades are in error and need to be updated. The state is not reporting total tests conducted, and not reporting all negative tests.

See further news reports:

https://www.abc15.com/news/state/arizonas-handling-of-covid-19-health-data-gets-new-challenge
https://www.azfamily.com/news/continuing_coverage/coronavirus_coverage/the-reason-why-there-are-so-many-conflicting-covid-19-positivity-rates-for-arizona/article_83fa2d80-dc33-11ea-8d38-17fac0e3733a.html
https://www.azcentral.com/story/news/local/arizona-health/2020/08/17/arizona-leaves-out-written-faxed-test-results-when-calculating-covid-19-percent-positivity/5587283002/
https://www.azfamily.com/news/continuing_coverage/coronavirus_coverage/state-of-arizona-johns-hopkins-have-different-covid-19-stats-for-same-data/article_76bde470-de3d-11ea-957d-9f65c34e435c.html

**Comment by mentalplex** [comment]
This issue could use some attention. The Arizona data quality grades are not accurate (not all tests are reported, see above) and they are being used by the state to avoid addressing data transparency issues. Arizona governor Doug Ducey cited their A+ data quality grade in a recent [press conference](https://youtu.be/1tM8njdKj7k) to side step press questions about problems with data transparency. Please fix the error.

**Comment by muamichali** [comment]
The account has been deleted so I can't respond. But we are re-vamping the state grades and will take this feedback into consideration.
