### ISSUE TITLE
[HI] Test Data 7/27-28

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#756]
**State or US**: Hawaii

**Describe the problem**
Suggested corrections to CTP's numbers from Jul 27 and 28 for Negative Tests and Total Tests from HI user based on state data.

Date | New Tests | Cases | Negative | Pending | Hospitalized | Deaths | Total
-- | -- | -- | -- | -- | -- | -- | --
Tue Jul 28 | **564** | 1,711 | **114,676** | N/A | 165 | 26 | **116,387**
Mon Jul 27 | **1,771** | 1,683 | **114,140** | N/A | 163 | 26 | **115,823**

**Link to data source**
https://hawaiicovid19.com/
https://experience.arcgis.com/experience/eb56a98b71324152a918e72d3ccdfc20/

**Comment by jesseandersonumd** [comment]
**BEFORE:** 
![Screen Shot 2020-08-13 at 9 10 35 AM](https://user-images.githubusercontent.com/57415941/90138705-65e1cc00-dd45-11ea-95f5-fc747ba376fe.png)

**Comment by jesseandersonumd** [comment]
AFTER: 
![Screen Shot 2020-08-13 at 9 11 42 AM](https://user-images.githubusercontent.com/57415941/90138730-6ed29d80-dd45-11ea-8c54-a05a44150766.png)

SAVED: 
![Screen Shot 2020-08-13 at 9 15 48 AM](https://user-images.githubusercontent.com/57415941/90138743-742fe800-dd45-11ea-9252-b54f313f3d6c.png)
