### ISSUE TITLE
[HI] Hospitalization Data for 8/13

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#761]
**State or US**:  HI

**Describe the problem**
Updates were provided after publishing the daily data

**Link to data source**
Lt Governor Josh's Instagram Account
![image](https://user-images.githubusercontent.com/1749380/90201379-a6266600-dda8-11ea-8f09-aa721943b915.png)

**Comment by jaclyde** [comment]
It looks like at this time we were regularly using the previous day's values due to timing. So these values were used for 8/14, and on 8/13 we used the 8/12 values. No action needed.
