### ISSUE TITLE
[SD] Total PCR Tests (People) backfill through 3/15 with screenshots

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#763]
**State or US**: South Dakota

**Date Range:** 3/15 - 5/13
**Data Points:** Total PCR Tests (People)

**Describe the problem**
On 8/3, SD updated their dashboard to include "Total Tests," which we have recorded in **Total Tests (PCR)**.

We also have **Total PCR Tests (People)**, but this only goes back until 5/13. After some digging, I found that all of our **Total PCR Tests (People)** values are sums of the pos+neg values from the pie chart on the SD dashboard. This pos+neg pie chart dates back until 4/20, and prior to this, they have a table separating pos/neg through our earliest screenshot for 3/15. We should be able to sum these pos+neg values for a complete time series.

The 3/15 screenshot shows data "as of" 3/14 and confirms that these values refer to individual people: 
![image](https://user-images.githubusercontent.com/67408226/90265746-dbae6c00-de07-11ea-8402-9a45f4240268.png)

**Link to data source**
State screenshots

**Comment by jesseandersonumd** [comment]
**BEFORE:**  
Reasoning for deletion: this value appeared to be an entry error, as it doesn't align with our current process for reporting **Total Tests (PCR)**, which only began on **8/3**. 
![Screen Shot 2020-08-17 at 9 40 56 AM](https://user-images.githubusercontent.com/57415941/90402718-dbafa580-e06d-11ea-99ec-372b92a271ee.png)

**Comment by jesseandersonumd** [comment]
**AFTER:** 
![Screen Shot 2020-08-17 at 9 44 34 AM](https://user-images.githubusercontent.com/57415941/90403023-54166680-e06e-11ea-9322-df0ee83f2b74.png)

**Comment by jesseandersonumd** [comment]
BEFORE: 
The two highlighted values for Total PCR Tests (People) appear to be miscalculated. sum(c(positive,negative)) for 5/13 and 5/14 does not equal the associated values for Total PCR Tests (People). 
![Screen Shot 2020-08-17 at 9 46 06 AM](https://user-images.githubusercontent.com/57415941/90403211-9f307980-e06e-11ea-8d5f-a8e4522bbc64.png)

**Comment by jesseandersonumd** [comment]
AFTER: 
(22681+3792) = 26473
(22112+3732) = 25844

![Screen Shot 2020-08-17 at 9 52 01 AM](https://user-images.githubusercontent.com/57415941/90403716-5927e580-e06f-11ea-857c-32fc894fe2a2.png)

**Comment by jesseandersonumd** [comment]
BEFORE BACKFILL: 
![Screen Shot 2020-08-17 at 9 54 27 AM](https://user-images.githubusercontent.com/57415941/90403950-af952400-e06f-11ea-96a0-62de45d5fccd.png)

**Comment by jesseandersonumd** [comment]
AFTER: 
![Screen Shot 2020-08-17 at 10 38 55 AM](https://user-images.githubusercontent.com/57415941/90408518-e8d09280-e075-11ea-92c0-8ae98458c866.png)

ALL VALUES IN TOTAL PCR TESTS (PEOPLE) 3/7-5/13:

25844
25197
24578
23894
22952
21293
20114
19416
19022
18713
18417
18091
17363
17028
16833
16612
16375
16274
15596
14824
14065
13446
12815
12326
12062
11660
11062
10550
9859
9296
9002
8553
8004
7647
7147
6748
6268
6020
5593
5224
4780
4382
4032
3717
3579
3217
2660
2445
2019
860
820
790
761
705
677
562
562
562
504
336
191
82
35
18
11
5
5
5

**Comment by muamichali** [comment]
Looks like this is done!
