### ISSUE TITLE
[Data Quality]Add columns to capture negative Antigen tests (people & tests units)

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#770]
**Target Date:** 8/21
**Overview:** Add columns to capture negative antigen tests in both "tests" and "people" units
**Editorial:** Data definitions

### For Capture
- [x] Update Data Dictionary
- DEV Sheet
  - [x] Add columns to [DEV SHEET] WS2 - paint them green so people know they are not live yet
  - [x] Add columns to  [DEV SHEET] Stage WS2 
  - [x] Add columns to [DEV SHEET] States Matrix
  - [x] Update range for copying to Data Store (or just create a named range)
- Easy DC
  - [x] Update EasyDC for the new columns
  - [x] Run New Checks Rebuild
  - [x] Update `importrange` for Easy-DC
* Data Store sheet
  - [x] Add columns to [Data Store] Raw States Daily
  - [x] Add columns to [Data Store] States Daily + update formula
- [x] Notify data infra team so they can update database, and code
- [ ] Check in the new code to data entry repo

### For Data Entry Shifts
- [ ] TODO Add source notes in States Matrix for negative

### For Publish
- [ ] TODO Add steps to publish these columns

**Comment by zachlipton** [comment]
- DB
  - [ ] Add columns to DB
  - [ ] Deployed to staging
  - [ ] Deployed to production

**Comment by zachlipton** [comment]
`negativeTestsPeopleAntigen` and `positiveTestsPeopleAntigen` are now live in the DB and await data from WS2+DataStore.
