### ISSUE TITLE
[MP] Remove unclear deaths from confirmed deaths column

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#774]
**State or US**: Northern Mariana Islands

**Describe the problem**
Unclear deaths being reported in the confirmed deaths column. Data will need to be removed from States Daily, WS2 should be corrected via States Matrix.

**Link to data source**
https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5

**Comment by brianskli** [comment]
Source notes were edited accordingly. Death counts were deleted from the **Deaths (confirmed)** column in States Daily.

Before:
<img width="942" alt="Screen Shot 2020-08-18 at 11 52 57 PM" src="https://user-images.githubusercontent.com/66738237/90590262-1587c580-e1ae-11ea-94b0-61a480b28198.png">
After:
<img width="937" alt="Screen Shot 2020-08-18 at 11 53 31 PM" src="https://user-images.githubusercontent.com/66738237/90590265-17518900-e1ae-11ea-89c8-caff539d4632.png">
