### ISSUE TITLE
Server CORS (Access-Control-Allow-Origin) header issue

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#776]
**Describe the problem**
The server does not appear to be returning `Access-Control-Allow-Origin` headers along with API requests.

This results in web browser errors such as:
`XMLHttpRequest at 'https://covidtracking.com/api/v1/us/daily.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I believe that the API server should be returning an `Access-Control-Allow-Origin: *` header, and that this would resolve the problem.

I don't have prior experience with these kinds of issues, so please forgive my ignorance if any of this is incorrect. I only began receiving these errors today for the first time, and I've been using this API for months now. I've temporarily mitigated the problem by routing all API requests through `https://cors-anywhere.herokuapp.com/` but this doesn't seem like a great permanent solution.

Thanks for all your time and efforts!

**Comment by muamichali** [comment]
@kevee can you please transfer to the website repo? 🙏

**Comment by loglow** [comment]
Well, this just became more urgent because `https://cors-anywhere.herokuapp.com/` is now giving me `429 Too Many Requests` errors. Please fix ASAP.

**Comment by loglow** [comment]
<img width="616" alt="cors" src="https://user-images.githubusercontent.com/3103472/90690258-63004300-e23f-11ea-8e7d-963787726ef8.png">

**Comment by loglow** [comment]
Safari flavor of errors below. Above was Chrome.

<img width="890" alt="cors2" src="https://user-images.githubusercontent.com/3103472/90690664-1d904580-e240-11ea-8488-028424016dd7.png">

**Comment by loglow** [comment]
PS. Firefox 72.0.2 (latest version) is **working** because apparently it's not yet strictly enforcing CORS policy.

For the above screenshots:
- Chrome is 84.0.4147.135
- Safari is 13.1.2 (14609.3.5.1.5)

**Comment by kevee** [comment]
Please switch to using `api.covidtracking.com` instead of `https://covidtracking.com/api/v1/us/daily.json`.

**Comment by loglow** [comment]
Thanks!
