### ISSUE TITLE
[SC] Incorrect recovered value entered On 8/18. 

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#779]
**State or US**: South Carolina

**Describe the problem**

The recovered amount was entered incorrectly on 8/18. Someone used the wrong n value for the calculation. 

**Link to data source**

https://www.scdhec.gov/infectious-diseases/viruses/coronavirus-disease-2019-covid-19/sc-demographic-data-covid-19

![Screen Shot 2020-08-19 at 3 50 01 PM](https://user-images.githubusercontent.com/69436257/90697693-3565ca80-e23c-11ea-9c0e-888c5b4dc627.png)

**Comment by brianskli** [comment]
Based on the screenshot, a recovered formula of `=FLOOR(49676*0.91,1) ` is needed. The resulting correct value of 45205 was entered in States Daily.

Before:
![Screen Shot 2020-08-19 at 8 58 33 PM](https://user-images.githubusercontent.com/66738237/90704608-f8f79600-e25e-11ea-8fa4-dc7a139f7638.png)
After:
![Screen Shot 2020-08-19 at 8 58 49 PM](https://user-images.githubusercontent.com/66738237/90704614-fbf28680-e25e-11ea-8b54-57ad09c0d73e.png)
