### ISSUE TITLE
 How do I submit changes during the day?

### ISSUE THREAD

**Issue by nowherenearithaca** [COVID19Tracking/issues#78]
Hey I'm watching Arkansas and Tennessee kinda carefully.  How do I submit changes during the day?

**Comment by schwartzadev** [comment]
Thanks for reaching out!

tldr: you can't.

We currently do reporting through shifts of our volunteers, who update data for all of the states at once. In other words, we don't operate on an ad-hoc state-by-state basis. We value high-quality data and thus have multiple people independently check each update.

Feel free to reach out on Twitter @COVID19Tracking
