### ISSUE TITLE
NH backfill Total PCR Tests/ Total Tests (PCR)

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#780]
**State or US**: [State name, or "US" if this is an issue with country-wide data]

NH

**Describe the problem**

We found an official source for Total PCR Tests for NH. We need to backfill that data (if possible). Please and thank you. 

**Link to data source**

link > Total PCR Tests

https://www.nh.gov/covid19/dashboard/overview.htm#dash

**Comment by space-buzzer** [comment]
We started capturing daily values on the 20-Aug.
We backfilled with data captured on the 19-Aug.

Notice: These values are continuously updated by the state, so data today will not be the same as yesterday (and any day before) on the same dates

![Screenshot from 2020-08-24 12-59-32](https://user-images.githubusercontent.com/62236447/91090687-4f235b00-e60a-11ea-842f-95f6229d2338.png)
![Screenshot from 2020-08-24 13-00-01](https://user-images.githubusercontent.com/62236447/91090689-4fbbf180-e60a-11ea-8106-6c0cd3666acc.png)

**Comment by space-buzzer** [comment]
Backfilled antibody total tests with data captured on Aug-19th

![Screenshot from 2020-08-24 13-10-49](https://user-images.githubusercontent.com/62236447/91091701-d6bd9980-e60b-11ea-8557-e8aaa618ad1e.png)
![Screenshot from 2020-08-24 13-11-54](https://user-images.githubusercontent.com/62236447/91091703-d7563000-e60b-11ea-9ef2-fdb929c1d5c8.png)

**Comment by space-buzzer** [comment]
[NH - [NH] Analysis PCR & Antibody testing PR-780.pdf](https://github.com/COVID19Tracking/issues/files/5131386/NH.-.NH.Analysis.PCR.Antibody.testing.PR-780.pdf)
