### ISSUE TITLE
Mississippi positive test rate

### ISSUE THREAD

**Issue by chriscanipe** [COVID19Tracking/issues#789]
**Target Date:** The date by which we hope to complete this issue.
ASAP

**Overview:** Briefly describe what work the issue entails.
I maintain our tracker for [Reuters](https://tmsnrt.rs/34uv6Zm), and the 1-week positive test rate for Mississippi seems very high this week (40.8% for Monday Aug. 17 to Sun. Aug 23). I'm calculating that on total new cases and total new tests. But I see several days this week where the number of new cases is equal to the number of new tests, which suggests they are only reporting positive tests on some days. Can we confirm that?

**Contribution to milestone:** Explain how the issue contributes to the overall milestone.
Just making sure these numbers are valid as reported. If not, can we add a note similar to what you show for Washington State and Puerto Rico, which also don't report negative tests?

**Other benefits:** Explain any side benefits we could get from completing this issue.
**Potential challenges:** Explain any potential blockers.
**Editorial:** The specific editorial content we expect to come out of this issue.

**Comment by jaclyde** [comment]
Hi Chris,

Can you send this issue via email to media-inquiries@covidtracking.com?

Thank you!

**Comment by mentalplex** [comment]
Related to this Arizona issue: #755 
COVID19tracking's data quality grade for Arizona is wrong. Arizona is graded as A+, but the state does not report all tests and does not report all negatives. The state reports all positives cases, and a subset of negative results. The reported number for total tests is in fact all positive cases + subset of negatives. This causes problems with positivity calculations for Arizona based off of COVID19tracking data. We need to be accurate when describing the data we aggregate, and stop saying Arizona is reporting all tests when they are not.
