### ISSUE TITLE
MI: screenshots not correct

### ISSUE THREAD

**Issue by maxerickson** [COVID19Tracking/issues#79]
3/29 and 3/28 are not current data. I guess they changed their format yet again...

Using total - new from 3/29, the new for 3/28 are 993 cases and 19 deaths.

The totals for 3/28 are then 4650 cases and 111 deaths.

**Comment by schwartzadev** [comment]
Potential duplicate of #80

**Comment by careeningspace** [comment]
Hello,

We did update Michigan data after the state updated its reporting process. Please find more detailed information at #173
