### ISSUE TITLE
8/26 huge negative number of new cases (tests also)

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#794]
**State or US**: US

**Describe the problem**

Reporting (NEGATIVE) -39k new daily cases!

**Comment by loglow** [comment]
Daily new tests is also a huge negative number

**Comment by muamichali** [comment]
Hey @loglow is it resolved now? We had some issues during the publish process

**Comment by loglow** [comment]
Different values now, but still very wrong:

```
"date":20200826
"positiveIncrease":119436
"totalTestResultsIncrease":1880079

"date":20200825
"positiveIncrease":-39986
"totalTestResultsIncrease":-571175
```

**Comment by muamichali** [comment]
Thanks for letting us know @loglow! A backfill of Washington's numbers inadvertently overwrote Wyoming's 08/25 numbers.  See #793 

This should now be fixed. Please re-open the ticket otherwise.

**Comment by loglow** [comment]
Looks fixed to me!
