### ISSUE TITLE
[TN] Probables backfill May 5-July 28

### ISSUE THREAD

**Issue by jaclyde** [COVID19Tracking/issues#795]
State: Tennessee

Problem: We added a metric to store Probable Case data separately on July 28 and need to backfill the previous dates. Coincidentally TN updated late on 7/28/2020 so we initially entered the value from 7/27/2020 for 7/28. That value will be overwritten with the correct value from the state. 

Action Plan:

- [x] Fix 7/28 from state xls (pos,neg,confirmed,probable)
- [x] Calculate probables from total-confirmed from 7/27-6/10
- [x] Back-fill probables from state xls for 5/4 - 6/9

Data Source: TN provides the full time series in a csv: https://www.tn.gov/health/cedep/ncov/data/downloadable-datasets.html
[Public-Dataset-Daily-Case-Info.XLSX](https://github.com/COVID19Tracking/issues/files/5133781/Public-Dataset-Daily-Case-Info.XLSX)

**Comment by jaclyde** [comment]
BEFORE:
<img width="171" alt="Screen Shot 2020-08-26 at 8 01 57 PM" src="https://user-images.githubusercontent.com/66583275/91379716-2b157480-e7d8-11ea-97d5-3d1e11248a85.png">

**Comment by muamichali** [comment]
[TN - Probable Timeseries Backfill .xlsx](https://github.com/COVID19Tracking/issues/files/5258879/TN.-.Probable.Timeseries.Backfill.xlsx)
