### ISSUE TITLE
[SD] Backfill 8/25-8/26 cases and total tests

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#796]
**[State]:** South Dakota 
**[Dates impacted]:** 8/25-8/26 
**[Issue described]:** On 8/27 SD's update included cases that were not reported on August 25th and 26th due to a reporting aberration. They also included the corrected data for cumulative cases and cumulative people tested, which we can backfill.

**Comment by the-daniel-lin** [comment]
Backfilling with this press release: https://news.sd.gov/newsitem.aspx?id=27213

**Comment by the-daniel-lin** [comment]
BEFORE:

![image](https://user-images.githubusercontent.com/67408226/91580586-2ea51a80-e902-11ea-9637-e6fe924133c9.png)


AFTER:

![image](https://user-images.githubusercontent.com/67408226/91580839-86438600-e902-11ea-808d-756485dc6128.png)
