### ISSUE TITLE
[LA] Back-fill probable cases for 8/26 & 8/27, Copy Positive to Positive Cases (PCR), update Positive to include Confirmed plus Probable

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#798]
**State or US**:  Louisiana

**Describe the problem**
As of 8/26, Louisiana is reporting probable cases on their dashboard. CTP will start capturing them today. 
1. Backfill the values for 8/26 and 8/27
2. LA's data dictionary now confirms explicitly that reported cases are lab confirmed via a PCR test, so we should copy the cases numbers we captured previously into the `Positive Cases (PCR) `column
3. Add the probable values to the confirmed values in our **Total cases** (`positive`) metric.

**Link to data source**

![image](https://user-images.githubusercontent.com/1749380/91571729-6d43d080-e914-11ea-9d2a-861f4f102f4a.png)
![image](https://user-images.githubusercontent.com/1749380/91572060-82206400-e914-11ea-86c7-6cebce793d07.png)

**Comment by muamichali** [comment]
BEFORE - 1
![image](https://user-images.githubusercontent.com/1749380/91574713-37ebb280-e915-11ea-9410-d9ccacf00c3e.png)
BEFORE - 2
![image](https://user-images.githubusercontent.com/1749380/91575272-5b166200-e915-11ea-859e-3016a064f12f.png)
AFTER
![image](https://user-images.githubusercontent.com/1749380/91575908-88fba680-e915-11ea-8cb0-b5b06614771e.png)

**Comment by jaclyde** [comment]
Updating Total cases (positive):

BEFORE: 
<img width="406" alt="Screen Shot 2020-09-03 at 7 53 51 PM" src="https://user-images.githubusercontent.com/66583275/92194317-3ba09d00-ee1f-11ea-9d59-5c0b53bbf755.png">

AFTER:
<img width="432" alt="Screen Shot 2020-09-03 at 7 58 02 PM" src="https://user-images.githubusercontent.com/66583275/92194554-d305f000-ee1f-11ea-9a68-571edb77dece.png">

Sources: [screenshot 8/26](https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/LA/LA-20200826-181415.png), [screenshot 9/3](https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/LA/LA-20200903-061314.png), 
<img width="652" alt="Screen Shot 2020-09-03 at 7 46 59 PM" src="https://user-images.githubusercontent.com/66583275/92194706-33952d00-ee20-11ea-9644-882107f9f05e.png">
