### ISSUE TITLE
[IA] Total PCR tests (people) on 8/27 accidentally included antigen tests

### ISSUE THREAD

**Issue by qpmnguyen** [COVID19Tracking/issues#800]
**State or US**: IA

**Describe the problem**
There was a mistake on 8/27 where the testing number lumping antigen was inputted into of total tests (people) field in IA  

**Link to data source**
We have no viable screenshot to backfill 😢

**Comment by muamichali** [comment]
We should carry over the previous day's number.

**Comment by jaclyde** [comment]
Value updated: 
[Changes (13).txt](https://github.com/COVID19Tracking/issues/files/6339593/Changes.13.txt)
