### ISSUE TITLE
[AS] total tests (PCR) is specimens, but is stored as people

### ISSUE THREAD

**Issue by theomichel** [COVID19Tracking/issues#802]
**Overview:** 
Tests for American Samoa are going into Total PCR Tests (People), but in fact (according to the annotations sheet) they are specimens. 

So we need to:
1. update the WS2 instructions to put the testing data for AS into Total Tests (PCR)
2. move the data in the data store from Total Tests (PCR) to Total PCR Tests (People)

**Comment by muamichali** [comment]
BEFORE
![image](https://user-images.githubusercontent.com/1749380/91870035-8ca86980-ec44-11ea-8fdf-447b230976fa.png)
