### ISSUE TITLE
[MP] Negative (People or Cases) for 8/29 needs to be edited

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#805]
**State or US**: [State name, or "US" if this is an issue with country-wide data]
Northern Marianas Islands

**Describe the problem**

MP (who updates infrequently) had new testing values on 8/27 (13540) and then new case values (specifically confirmed) on 8/29 (56). Because MP doesn't post explicit negatives, we calculate the negatives by subtracting Confirmed cases from Total PCR Tests (People). It's our policy not to update the negatives when the testing metric in the calculation doesn't update, however the calculation was updated on 8/30. Backfilling 8/30-9/9 to stay the same as 8/27-8/29 until the testing metric updated on 9/10. 

**Link to data source**

https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5

**Comment by jaclyde** [comment]
Values updated: 
[Changes (12).txt](https://github.com/COVID19Tracking/issues/files/6339555/Changes.12.txt)
