### ISSUE TITLE
WA: state changed the format of their reporting page

### ISSUE THREAD

**Issue by rainiernate** [COVID19Tracking/issues#81]
Normally data was being pushed around 3p but today it went long overtime to about 9pm and they changed the whole format. I can't find a table unless I scroll down to the WA state map and click "Table View". The data pull for 3/29 is inaccurate. 
<img width="802" alt="Screen Shot 2020-03-29 at 9 06 49 PM" src="https://user-images.githubusercontent.com/13302862/77874248-410b1300-7201-11ea-87d8-edde08920f1d.png">

**Comment by muamichali** [comment]
Still not updated as of now.

**Comment by muamichali** [comment]
Still @ 3/28

**Comment by bnm91** [comment]
Washington State DOH is reporting an issue that prevents data from being updated.  

![image](https://user-images.githubusercontent.com/19519681/78088708-cd404600-7379-11ea-977b-a2a161f2387c.png)

**Comment by careeningspace** [comment]
We are now regularly updating WA data to match. If you right-click on a chart, it will let you see the data in a tabular format. This is not great, but slightly better than mousing over the charts.

Please see Issue #233 for the most recent update.

Thanks!
