### ISSUE TITLE
AR - including pos and neg antigen numbers in a table with slides

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#815]
**State or US**: [State name, or "US" if this is an issue with country-wide data]
AR

**Describe the problem**
AR has a table they have provided two days in a row with pos and neg antigen results. We should backfill and start collecting this data during pub shift (when available).

**Link to data source**
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1599248272194300?thread_ts=1599248268.194200&cid=CUQ4MMTPD

https://covid-tracking.slack.com/files/U01489QMX99/F01A503QPRQ/total_cases_by_case_status_09042020.pdf?origin_team=TUPV6BFR9&origin_channel=Vall_threads

**Comment by the-daniel-lin** [comment]
https://github.com/COVID19Tracking/issues/issues/816
