### ISSUE TITLE
[WI] Missed 9/6 hospitalization update

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#817]
**State or US**: Wisconsin

**Describe the problem**
On 9/6, data obtained from the Hospital Capabilities page was not updated.

https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1599511709068500

**Link to data source**
https://www.dhs.wisconsin.gov/covid-19/hosp-data.htm

<img width="372" alt="Screen Shot 2020-09-07 at 5 13 28 PM" src="https://user-images.githubusercontent.com/66738237/92416854-73fcef80-f12d-11ea-8394-8120112eb73c.png">

**Comment by muamichali** [comment]
Pending on 9/6 is being updated from 118 to 99. 
Source: https://covidtracking.com/screenshots/WI/WI-tertiary-20200906-183605.png

The other values were already updated by issue #865
