### ISSUE TITLE
[MP] Fix 9/7 Timestamp

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#818]
**State:** MP
**Dates impacted:** 9/7
**Issue described:** The week of 9/1 the MP dashboard was broken for a few days. As a result we got data (including a timestamp) from queries. The 9/1 0:00 source note from the queries turned out to be more of a site updated time vs a data "as of" timestamp. However we decided to carry over the 9/1 timestamp until the dashboard is updated, on 9/7 the timestamp was accidentally changed and should be patched to 9/1 0:00
**Sources:** https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1599594076151900

**Comment by jaclyde** [comment]
Before: 
<img width="366" alt="Screen Shot 2020-09-08 at 4 22 53 PM" src="https://user-images.githubusercontent.com/66583275/92536880-9fe0a980-f1ef-11ea-8d7c-ad225737f74f.png">

After:
<img width="363" alt="Screen Shot 2020-09-08 at 4 23 06 PM" src="https://user-images.githubusercontent.com/66583275/92536936-b71f9700-f1ef-11ea-8625-e58a11b24829.png">
