### ISSUE TITLE
Alaska data are missing when pulling data using API

### ISSUE THREAD

**Issue by vnminin** [COVID19Tracking/issues#82]
When I use the following R code:

`covid_us_data = read.csv("https://covidtracking.com/api/states/daily.csv", stringsAsFactors = FALSE)`

`covid_as_data = dplyr::filter(covid_us_data, state=="AS")`

`covid_as_data` has no data.

**Comment by hammer** [comment]
Ah, that's because `AS` is [American Samoa](https://en.wikipedia.org/wiki/American_Samoa), and we have had a hard time finding data for it!

`AK` is Alaska and should have data 🤞.

**Comment by vnminin** [comment]
Oops. My bad
