### ISSUE TITLE
[IL] Explicit Probables Backfill 6/8-7/27

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#824]
**State or US**: IL

**Describe the problem**
CTP didn't have a column for probables until 7/28 and we started a confirmed cases column on 4/29. 
IL didn't start separating out confirmed and probables until 6/8. 

**Action plan**
Calculate probables as positive - positive(PCR) from 6/9 to 7/28.

**Comment by jesseandersonumd** [comment]
BEFORE:
![Screen Shot 2020-09-11 at 11 00 46 AM](https://user-images.githubusercontent.com/57415941/92941208-1531c180-f41e-11ea-8fbc-63eba8e2623e.png)

**Comment by jesseandersonumd** [comment]
AFTER:
![Screen Shot 2020-09-11 at 11 02 04 AM](https://user-images.githubusercontent.com/57415941/92941372-47dbba00-f41e-11ea-83f1-3db0df46e241.png)

**Comment by the-daniel-lin** [comment]
DC'd by DZL 9/24 13:00
