### ISSUE TITLE
[MS] Backfill Cur. Hosp, Cur. icu from 8/24-9/10. Delete cur. vent from 8/30 - 9/10

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#825]
**State**: MS
**Dates impacted**: 8/24 - 9/10 
**Issue described**: On 8/24 MS switched current hospitalization and icu sources and stoped reporting cur. vent. They resumed reporting this on 9/15. We need to backfill current hospitalizations, cur. icu, and cur. vent for 8/24 - 9/14 from the ["Hospitalizations and ICU Use (Statewide)"](https://msdh.ms.gov/msdhsite/_static/14,21994,420,873.html) graph 
**Sources:** https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1600201831431600 
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1599857074458900, https://msdh.ms.gov/msdhsite/_static/14,21994,420,873.html

**Comment by muamichali** [comment]
![image](https://user-images.githubusercontent.com/1749380/113779343-9377ed00-96fb-11eb-8a86-7fb8b73d6605.png)

**Comment by muamichali** [comment]
The changes have been applied to the data. This is a spreadsheet with the numbers from the screenshot above. 
These are the changes that were made:
Rows edited: 13
MS 2020-09-14
    hospitalizedCurrently: 667 (was 513)
    inIcuCurrently: 178 (was 171)
    onVentilatorCurrently: 88 (was None)
MS 2020-09-13
    hospitalizedCurrently: 648 (was 542)
    inIcuCurrently: 178 (was 179)
    onVentilatorCurrently: 92 (was None)
MS 2020-09-12
    hospitalizedCurrently: 696 (was 542)
    inIcuCurrently: 177 (was 179)
    onVentilatorCurrently: 102 (was None)
MS 2020-09-11
    hospitalizedCurrently: 694 (was 545)
    inIcuCurrently: 177 (was 182)
    onVentilatorCurrently: 100 (was None)
MS 2020-09-10
    hospitalizedCurrently: 682 (was 668)
MS 2020-09-09
    hospitalizedCurrently: 698 (was 683)
MS 2020-09-08
    hospitalizedCurrently: 674 (was 758)
    inIcuCurrently: 184 (was 186)
    onVentilatorCurrently: 97 (was 111)
MS 2020-09-07
    hospitalizedCurrently: 694 (was 758)
    inIcuCurrently: 191 (was 186)
    onVentilatorCurrently: 113 (was 111)
MS 2020-09-06
    hospitalizedCurrently: 689 (was 758)
    inIcuCurrently: 187 (was 186)
MS 2020-09-05
    inIcuCurrently: 178 (was 186)
MS 2020-08-31
    hospitalizedCurrently: 825 (was 802)
    inIcuCurrently: 214 (was 207)
    onVentilatorCurrently: 126 (was 121)
MS 2020-08-30
    hospitalizedCurrently: 788 (was 819)
    onVentilatorCurrently: 113 (was 111)
MS 2020-08-28
    inIcuCurrently: 230 (was 203)
