### ISSUE TITLE
Forecast Expected Positive

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/issues#83]
Based on your code , we can forecast a hi/low range of expected positive values.

Now we need to tie it into the test logic.

We need to get the current value out of the row argument and use the history to forecast.  Right now, the logic uses the first value of the history as the current value.

**Comment by joshuaellinger** [comment]
Once you have it tied in, add it to the current checks.

**Comment by Erin-Boehmer** [comment]
Done - now expected positives forecast runs for worksheet and current (latest as determined by `lastUpdateEt` field) against the history_df (aka daily API pull, with any row matching `current.lastUpdateEt == history_df.date` removed). 

I also added a visual for fuzzy acceptance range in the plots

<img width="912" alt="Screen Shot 2020-03-30 at 3 38 25 PM" src="https://user-images.githubusercontent.com/3460589/77954615-e2937280-729c-11ea-818a-dfbf52542de1.png">
