### ISSUE TITLE
Kentucky data shows 100% positives every Sunday 

### ISSUE THREAD

**Issue by timkessler** [COVID19Tracking/issues#834]
In Kentucky, the negative column shows no increase on Sundays for the past few months.  Is this correct data?

**Comment by MattHilliard** [comment]
Hi @timkessler, thanks for asking about this. Our data is collected from the best available state government sources. Unfortunately, Kentucky only publishes a limited set of data on Sundays: positives, but no negatives or total tests. A few other states have similar limited weekend reporting and many states have strong day-of-week effects in their data, so 7 day averages like the ones on our web site graphs are usually the best way to get a sense for trends.
