### ISSUE TITLE
Invalid dates for South Dakota on August 6

### ISSUE THREAD

**Issue by hsbadr** [COVID19Tracking/issues#835]
Row COVID19Tracking/issues#391 (South Dakota on August 6) in _states_daily_4pm_et.csv_ (as of August 7, 2020 11:02 AM EDT) includes invalid entries for _lastUpdateEt_, _dateModified_, and _dateChecked_.

`
20200806,SD,9273,108301,,44,861,,,,,8145,B,8/5 13:)0,Invalid DateTime,Invalid DateTime,141,861,Invalid DateTime,147336,,,,,,46,105,1095,117574,117574,1200,117574,4,5,e9b4e75c9536df8f09e28d8386204e619aca0798,0,0,0,0,0,
`

**Comment by MattHilliard** [comment]
Took a quick look at this; the cells look right in both the API and the current states daily csv. I'm guessing it was a formatting issue that got addressed sometime between when the issue was opened and now. Please comment if this is still an issue anywhere!

**Comment by hsbadr** [comment]
Thanks @MattHilliard! Yes, this got addressed quickly. Just wanted to bring it to your attention to fix any related issues.
