### ISSUE TITLE
[UT]Back-fill PCR test numbers from the dashboard 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#842]
**State or US**: Utah

**Describe the problem**
Utah provides a time series of positive and negative PCR tests & people on their dashboard that can be manually captured and summed to get cumulative values.

The current number of total tests on the dashboard lumps PCR and antigen

**Link to data source**
https://coronavirus-dashboard.utah.gov/

**Comment by muamichali** [comment]
backfilled from file downloaded from Utah's website on 10/27, 10/28

[UT - Analysis PCR Tests 20201028.pdf](https://github.com/COVID19Tracking/issues/files/5455412/UT.-.Analysis.PCR.Tests.20201028.pdf)
[UT - Overview_Total Tests by Date_2020-10-27.csv.txt](https://github.com/COVID19Tracking/issues/files/5455413/UT.-.Overview_Total.Tests.by.Date_2020-10-27.csv.txt)

**Comment by space-buzzer** [comment]
Updated the `totalTestsPeopleViral` series from the download files to reflect only people tested for PCR testing, and not as reported on the dashboard, which includes all people tested in both PCR and antigen testing
