### ISSUE TITLE
[MI]Back-fill probable cases based on totals & confirmed from 6/12-7/27

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#843]
**State or US**: Michigan

**Describe the problem**
CTP did not capture explicit probable cases before 7/28. We can backfill the number of probable cases from 6/12 - 7/28 by subtracting confirmed cases from total. 

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.

**Comment by hmhoffman** [comment]
Done in #701, closing issue.
