### ISSUE TITLE
[TX] Removing negative serology/antibody calculation

### ISSUE THREAD

**Issue by jaclyde** [COVID19Tracking/issues#844]
State or Territory: Texas

Describe the problem: CTP started calculating negative serology tests on 5/23/2020 based on Texas's Total antibody tests - Positive antibody tests. Slack thread where this metric was added: https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1590265654141800

We are removing this metric.

**Comment by jaclyde** [comment]
BEFORE
<img width="382" alt="Screen Shot 2020-09-17 at 7 06 19 PM" src="https://user-images.githubusercontent.com/66583275/93547148-3c562a80-f919-11ea-8918-8434ad6322ac.png">

AFTER
<img width="348" alt="Screen Shot 2020-09-17 at 7 10 08 PM" src="https://user-images.githubusercontent.com/66583275/93547510-0b2a2a00-f91a-11ea-82d9-eeb0f065a6dc.png">

**Comment by karaschechtman** [comment]
clearing one additional day
![Screen Shot 2020-09-19 at 5 48 22 PM](https://user-images.githubusercontent.com/15933271/93689826-5b32f900-faa0-11ea-94a9-1bdb16c8347c.png)
![Screen Shot 2020-09-19 at 5 48 16 PM](https://user-images.githubusercontent.com/15933271/93689827-5bcb8f80-faa0-11ea-81de-8dd58ba7b78e.png)
