### ISSUE TITLE
[MS] Probables Backfill and Confirmed Cases Corrections

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#846]
**State or US**: MS

**Describe the problem**
As explained by this previous github issue [https://github.com/COVID19Tracking/issues/issues/712] we reported positive (PCR) cases from 4/30-6/01, though it wasn't clear whether the reported cases value represented confirmed cases exclusively. We will delete values in the positive PCR confirmed column prior to 6/1, after which both CTP and MS started separating confirmed and probable cases on their main state page according to screenshots. [https://covidtracking.com/screenshots/MS/MS-20200602-123808.png] We will also backfill probables using the formula positives - positive PCR confirmed from 6/02 - 7/28 (which is when CTP first started reporting probables) and cross-referencing with screenshots. 

We will also correct the value on 6/19 for positive cases PCR, which was 20641 when it should've been 20500 because we needed to carry over this value from 6/17 - MS stopped separating confirmed and probables between 6/17-6/21. We will also correct the value on 6/3 for positive cases PCR, which was 16211 according to screenshots [https://covidtracking.com/screenshots/MS/MS-20200603-124214.png] but reported as 15910. We will also correct the value on 6/14 for positive cases PCR, which was reported as 19216 when it should've been 19383 [https://covidtracking.com/screenshots/MS/MS-20200614-124313.png]. 

**Link to data source**
- https://covidtracking.com/screenshots/MS/MS-20200602-123808.png
- https://msdh.ms.gov/msdhsite/_static/14,0,420.html

**Comment by jesseandersonumd** [comment]
CORRECTING VALUE ON 6/19 - AFTER:
![Screen Shot 2020-09-18 at 10 12 09 AM](https://user-images.githubusercontent.com/57415941/93607527-6fd79a00-f997-11ea-92e2-38bf547892c8.png)

**Comment by jesseandersonumd** [comment]
CORRECTING CONFIRMED VALUES 4/30-6/1 - BEFORE:

![Screen Shot 2020-09-18 at 10 14 05 AM](https://user-images.githubusercontent.com/57415941/93607758-be853400-f997-11ea-9ba6-a88e17d52727.png)

**Comment by jesseandersonumd** [comment]
CORRECTING CONFIRMED VALUES 4/30-6/1 - AFTER:
![Screen Shot 2020-09-18 at 10 14 57 AM](https://user-images.githubusercontent.com/57415941/93607827-d78de500-f997-11ea-8c87-1a59eca613d9.png)

**Comment by jesseandersonumd** [comment]
MISTAKE CORRECTION 6/3 POSITIVE CASES PCR - BEFORE: 

![Screen Shot 2020-09-18 at 10 20 39 AM](https://user-images.githubusercontent.com/57415941/93608557-bf6a9580-f998-11ea-8de8-0abdf825f61f.png)

**Comment by jesseandersonumd** [comment]
MISTAKE CORRECTION 6/3 POSITIVE CASES PCR - AFTER:

![Screen Shot 2020-09-18 at 10 20 53 AM](https://user-images.githubusercontent.com/57415941/93608588-c85b6700-f998-11ea-8945-27c025cfeead.png)

**Comment by jesseandersonumd** [comment]
PROBABES (BEFORE):
![Screen Shot 2020-09-18 at 10 34 01 AM](https://user-images.githubusercontent.com/57415941/93610073-98ad5e80-f99a-11ea-937d-bdde79312baf.png)

**Comment by esquared** [comment]
MISTAKE CORRECTION 6/14 POSITIVE CASES PCR  AND PROBABLES- BEFORE:<img width="1101" alt="Screen Shot 2020-09-24 at 10 34 31 PM Before" src="https://user-images.githubusercontent.com/71461067/94223852-8cebfb80-feb6-11ea-8407-39a9233c8636.png">

**Comment by esquared** [comment]
MISTAKE CORRECTION 6/14 POSITIVE CASES PCR AND PROBABLES- BEFORE:
<img width="1109" alt="Screen Shot 2020-09-24 at 10 35 04 PM After" src="https://user-images.githubusercontent.com/71461067/94223982-ece2a200-feb6-11ea-97c2-795680b802ba.png">

**Comment by esquared** [comment]
Before and after values

[Probable Timeseries Backfill MS.xlsx](https://github.com/COVID19Tracking/issues/files/5313686/Probable.Timeseries.Backfill.MS.xlsx)
