### ISSUE TITLE
[VA] Probables Backfill

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#847]
**State or US**: VA

**Describe the problem**
CTP started reporting probables generally around 7/28 for many states. VA has been reporting probables since it started separating out confirmed and probable case counts on 4/21. We can backfill probables using positive - confirmed until 4/21 and cross-referencing with screenshots.

**Comment by jesseandersonumd** [comment]
BEFORE: 

![Screen Shot 2020-09-18 at 11 00 49 AM](https://user-images.githubusercontent.com/57415941/93613238-9947f400-f99e-11ea-84ac-55ddfb5b2ccc.png)

**Comment by jesseandersonumd** [comment]
AFTER: 

![Screen Shot 2020-09-18 at 11 01 03 AM](https://user-images.githubusercontent.com/57415941/93613268-a369f280-f99e-11ea-9495-478aa6c52fd6.png)

**Comment by the-daniel-lin** [comment]
DC'd by DZL 9/24 13:16
