### ISSUE TITLE
TX: Incorrect tests number for 3/29

### ISSUE THREAD

**Issue by johndhancock** [COVID19Tracking/issues#85]
For Texas, the number of Negative tests did not increase from 3/28 to 3/29, despite an increase in testing shown on the Texas dashboard, as seen on the screenshots on this page: https://covidtracking.com/data/state/texas/. 

One possible issue, there were more positive cases reported from 3/28 to 3/29 (500) than tests administered (25,260 on 3/28, 25,483 on 3/29, according to the state dashboard). Having been keeping an eye on the state dashboard pretty closely for a couple of weeks now, I could see how this could happen, as the state only updates the dashboard once per day, and often times individual counties will update after that or multiple times a day.

**Comment by johndhancock** [comment]
![TX-20200328-191515](https://user-images.githubusercontent.com/2925642/77959645-8b8d9d80-729c-11ea-8755-115de16b1c22.png)
![TX-20200329-191254](https://user-images.githubusercontent.com/2925642/77959654-90eae800-729c-11ea-8765-767e0d55cf5c.png)

**Comment by erfgottlieb** [comment]
Thanks for bringing our attention to this @johndhancock. By our publish time on 4/29 it looked like there was a lag in the state reporting for the number of tests administered, so we carried over the Negative numbers from the previous day.
