### ISSUE TITLE
County numbers roll up into state numbers

### ISSUE THREAD

**Issue by Erin-Boehmer** [COVID19Tracking/issues#86]
There are 3 county sites available:
CSBS, CDS, NYT

Use these 3 to create a current day validation check that sum(counties.positives) ~= state.positives and sum(counties.deaths) ~= state.deaths

Based on https://github.com/COVID19Tracking/associated-data/blob/master/county_data/County%20Data%20Comparison.ipynb

**Comment by Erin-Boehmer** [comment]
Done in [commit a0082f4df9eb9c324b9a9f262a94743299dca316](https://github.com/COVID19Tracking/quality-control/commit/a0082f4df9eb9c324b9a9f262a94743299dca316)

Uses CSBS, CDS, and NYT data to get a [min, max] range of values for positives, deaths, recovered. If the state #s don't fall within the summed county aggregate ranges, then an error is triggered (warning for recovered since that data is more sparse).

This test is intentionally imprecise because each sheet is updated at different times. If we can find a better way to make the range of possible values tighter, that would be better.

For now, this test still throws a lot of errors.

**Comment by joshuaellinger** [comment]
I added a --exp / --experimental flags for cases like this.

It looks like it doesn't generate too many errors now so I move it production by removing the flag
