### ISSUE TITLE
[NH] Issue thread for NH late updates beginning 9/27

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#872]
**State or US**: New Hampshire

**Describe the problem**
NH sometimes updates after our daily publication time, so we don't end up collecting their data the day of. Beginning 9/27, this issue thread will log all of the backfills due to NH late updates.

Backfilled dates in this issue: 9/27, 9/30, 10/4, 10/14, 10/20, 10/23, 11/11, 11/13, 11/24

Previous backfill dates include: , https://github.com/COVID19Tracking/issues/issues/807 (9/01), https://github.com/COVID19Tracking/issues/issues/821 (9/9), https://github.com/COVID19Tracking/issues/issues/855 (9/21)

**Link to data source**
https://www.nh.gov/covid19/

**Comment by the-daniel-lin** [comment]
BEFORE:
![Uploading image.png…]()

**Comment by the-daniel-lin** [comment]
AFTER:
![image](https://user-images.githubusercontent.com/67408226/94474081-f81d2280-0181-11eb-9f6c-494e5b42a7ad.png)

**Comment by the-daniel-lin** [comment]
BEFORE 9/30:
![image](https://user-images.githubusercontent.com/67408226/94825347-ea9ead00-03ba-11eb-863e-e7571360c125.png)

**Comment by the-daniel-lin** [comment]
AFTER 9/30:
![image](https://user-images.githubusercontent.com/67408226/94826147-de671f80-03bb-11eb-9d26-fb83f1aa82ef.png)

**Comment by the-daniel-lin** [comment]
BEFORE 10/4:
![image](https://user-images.githubusercontent.com/67408226/95122111-e2b97280-0704-11eb-8404-d991da36b444.png)

**Comment by the-daniel-lin** [comment]
AFTER 10/4:
![image](https://user-images.githubusercontent.com/67408226/95122752-d2ee5e00-0705-11eb-972d-8b985383b888.png)

On 10/4, NH removed the testing by individuals from their website. As a result, we've carried over the values for Total Antibody Tests (People), Total PCR Tests (People), and Negative.

**Comment by the-daniel-lin** [comment]
BEFFORE 10/5:
![image](https://user-images.githubusercontent.com/67408226/95359203-bc1f4700-087e-11eb-882c-8c85d74aa4bd.png)

**Comment by the-daniel-lin** [comment]
AFTER: 
![image](https://user-images.githubusercontent.com/67408226/95360727-a3179580-0880-11eb-80a3-6f8566da4fd4.png)
** UPDATE 10/5 **
Total Antibody Tests (People) and Total PCR Tests (People) values returned with the 10/5 update.
NH seems to have skipped the 10/5 update for the Interactive Dashboard 
(https://www.nh.gov/covid19/dashboard/overview.htm#dash) and the Summary Dashboard (https://www.nh.gov/covid19/dashboard/summary.htm) . As a result, We are carrying over Antibody Tests (People), Total Tests (PCR), and "Cumulative in ICU."

**Comment by hmhoffman** [comment]
BEFORE 10/14: 
<img width="1216" alt="Screen Shot 2020-10-15 at 9 33 48 AM" src="https://user-images.githubusercontent.com/68712382/96135480-8a832d00-0ec9-11eb-87f4-77a39c6d7dea.png">
<img width="1146" alt="Screen Shot 2020-10-15 at 9 34 58 AM" src="https://user-images.githubusercontent.com/68712382/96136070-b3a3bd80-0ec9-11eb-8608-f7b7c705fe16.png">

AFTER 10/14:
<img width="1184" alt="Screen Shot 2020-10-15 at 9 41 22 AM" src="https://user-images.githubusercontent.com/68712382/96137393-99b6aa80-0eca-11eb-9588-8c30fbb1a9a5.png">
<img width="735" alt="Screen Shot 2020-10-15 at 9 41 42 AM" src="https://user-images.githubusercontent.com/68712382/96137426-a3d8a900-0eca-11eb-88b2-48f4a518dbdb.png">

On 10/14 NH updated after we published. I patched that late update.

**Comment by hmhoffman** [comment]
BEFORE:
<img width="1274" alt="Screen Shot 2020-10-21 at 9 17 23 AM" src="https://user-images.githubusercontent.com/68712382/96724812-3cb16d80-137e-11eb-90eb-bc2f88b09031.png">
<img width="505" alt="Screen Shot 2020-10-21 at 9 17 47 AM" src="https://user-images.githubusercontent.com/68712382/96724871-4a66f300-137e-11eb-82c6-618c8b395038.png">

AFTER:
<img width="1189" alt="Screen Shot 2020-10-21 at 9 27 17 AM" src="https://user-images.githubusercontent.com/68712382/96726087-9e260c00-137f-11eb-92a7-0a9afbcab720.png">
<img width="616" alt="Screen Shot 2020-10-21 at 9 27 38 AM" src="https://user-images.githubusercontent.com/68712382/96726148-abdb9180-137f-11eb-873a-e35a2a76b5d0.png">
On 10/20 NH updated after we published, I patched that late update.

**Comment by hmhoffman** [comment]
BEFORE:
<img width="1321" alt="Screen Shot 2020-10-26 at 12 52 20 PM" src="https://user-images.githubusercontent.com/68712382/97202505-17f83400-178a-11eb-8f6a-55b88ea53eb1.png">
<img width="565" alt="Screen Shot 2020-10-26 at 12 52 46 PM" src="https://user-images.githubusercontent.com/68712382/97202549-27777d00-178a-11eb-8ef8-947181ce9788.png">


AFTER:
<img width="1307" alt="Screen Shot 2020-10-26 at 12 57 31 PM" src="https://user-images.githubusercontent.com/68712382/97203138-d1570980-178a-11eb-95f4-a7128ddf9f9e.png">
<img width="564" alt="Screen Shot 2020-10-26 at 12 57 48 PM" src="https://user-images.githubusercontent.com/68712382/97203171-db790800-178a-11eb-9d60-6a669bff0644.png">

On 10/23 NH updated after we published. I patched that late update

**Comment by hmhoffman** [comment]
BEFORE 11/11:

<img width="1015" alt="Screen Shot 2020-11-12 at 1 32 02 PM" src="https://user-images.githubusercontent.com/68712382/98981041-73952200-24eb-11eb-9944-c5d2707b63d5.png">
<img width="858" alt="Screen Shot 2020-11-12 at 1 32 13 PM" src="https://user-images.githubusercontent.com/68712382/98981057-7a239980-24eb-11eb-8fc6-7f4df33be1c2.png">

AFTER 11/11:
<img width="1010" alt="Screen Shot 2020-11-12 at 1 38 32 PM" src="https://user-images.githubusercontent.com/68712382/98981735-5ca2ff80-24ec-11eb-9a51-d274882aef53.png">
<img width="801" alt="Screen Shot 2020-11-12 at 1 38 48 PM" src="https://user-images.githubusercontent.com/68712382/98981767-662c6780-24ec-11eb-8349-f8d8ea7de9df.png">

All metrics were patched except for Total antibody tests (specimens), Total PCR tests (specimens), and cum. icu as the NH dashboard were experiencing technical difficulties.

**Comment by hmhoffman** [comment]
BEFORE 11/13:
<img width="1011" alt="Screen Shot 2020-11-14 at 4 35 38 PM" src="https://user-images.githubusercontent.com/68712382/99157509-6f0d6c80-2697-11eb-95fb-dc357ea0a96c.png">
<img width="795" alt="Screen Shot 2020-11-14 at 4 35 56 PM" src="https://user-images.githubusercontent.com/68712382/99157517-79c80180-2697-11eb-8804-1857ba82245a.png">

AFTER 11/13:
<img width="1013" alt="Screen Shot 2020-11-14 at 4 38 06 PM" src="https://user-images.githubusercontent.com/68712382/99157541-c7446e80-2697-11eb-9432-90ccbeae559b.png">
<img width="738" alt="Screen Shot 2020-11-14 at 4 38 20 PM" src="https://user-images.githubusercontent.com/68712382/99157543-cf041300-2697-11eb-919d-9977b38cf1cb.png">

All metrics were patched except for Total antibody tests (specimens), Total PCR tests (specimens), and cum. icu as the NH dashboard were experiencing technical difficulties.

**Comment by hmhoffman** [comment]
11/24:
Rows edited: 1
NH 2020-11-24
    positive: 18382 (was 18042)
    negative: 389286 (was 388185)
    hospitalizedCumulative: 832 (was 831)
    inIcuCumulative: 276 (was 277)
    recovered: 13558 (was 13226)
    death: 513 (was 512)
    totalTestsViral: 775598 (was 770791)
    positiveCasesViral: 18382 (was 18042)
    totalTestsPeopleViral: 407668 (was 406227)
    totalTestsAntibody: 33949 (was 33915)
    totalTestsPeopleAntibody: 32967 (was 32939)
    positiveTestsPeopleAntigen: 2962 (was 2830)
    lastUpdateTime: 2020-11-24 14:00:00+00:00 (was 2020-11-23 14:00:00+00:00)
    dateChecked: 2020-11-25 18:15:00+00:00 (was 2020-11-24 23:46:00+00:00)
    checker: RSG (was DZL)
    doubleChecker: MM (was SB)

**Comment by hmhoffman** [comment]
BEFORE:
<img width="1062" alt="Screen Shot 2020-11-25 at 8 51 57 PM" src="https://user-images.githubusercontent.com/68712382/100298808-1031d800-2f60-11eb-848c-ddeadaa437f8.png">
<img width="1057" alt="Screen Shot 2020-11-25 at 8 52 12 PM" src="https://user-images.githubusercontent.com/68712382/100298820-1922a980-2f60-11eb-8d81-d4b74c8e8074.png">
<img width="1190" alt="Screen Shot 2020-11-25 at 8 46 01 PM" src="https://user-images.githubusercontent.com/68712382/100298480-3b67f780-2f5f-11eb-8cd6-4e9f0b6db09b.png">
<img width="1062" alt="Screen Shot 2020-11-25 at 8 46 19 PM" src="https://user-images.githubusercontent.com/68712382/100298498-46228c80-2f5f-11eb-9763-ce5a2b782bd2.png">

AFTER:
<img width="1186" alt="Screen Shot 2020-11-25 at 8 51 32 PM" src="https://user-images.githubusercontent.com/68712382/100298791-00b28f00-2f60-11eb-91cb-aebb33237bfd.png">

**Comment by whobody** [comment]
![Screen Shot 2020-12-01 at 2 44 17 PM](https://user-images.githubusercontent.com/69436257/100800332-b4de6a80-33e3-11eb-87c6-7de6ac08f0c9.png)
