### ISSUE TITLE
[CT] Confirmed, Probable and Total Cases 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#877]
**State or US**: CT

**Describe the problem**
It seems that a previous backfill did not take weekend gaps into consideration #617 

**Link to data source**
Statewide XLS from CT's website as of 7/22

**Comment by space-buzzer** [comment]
We updated the following fileds:
Positive cases PCR -- between 2020-06-01 - 2020-07-21
Probable cases -- between 2020-06-01 - 2020-07-27 (on the 28th it was part of pubshift)
Positives (lumped) -- A single values for for 2020-06-01: there was a small difference between the collected value during pub-shift and PDF and the number from the dataset provided by CT. We used the dataset value
Negatives -- betwene 2020-06-01 - 2020-07-21 -- calculated value based on Total Tests PCR minus Positive cases PCR
Total Tests PCR -- 2020-07-21 -- all the way down to the beginning of times (in practice, it shifted the series by 1 day, but all the values are the same)

[CT - Confirmed + Probable GH-877 20200930.csv.txt](https://github.com/COVID19Tracking/issues/files/5319426/CT.-.Confirmed.%2B.Probable.GH-877.20200930.csv.txt)
