### ISSUE TITLE
[GU] Guam added reporting of total and positive antigen tests to situ report

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#882]
**State or US**: Guam

**Describe the problem**
On 10/1 Guam started reporting positive and total antigen tests on their situation report. 

**Link to data source**
https://drive.google.com/file/d/1n-vrUGzEzs7rjcxXBFEbIMmeUQykuyO9/view

**Comment by karaschechtman** [comment]
Added values from 10/1
PDF linked in issue is 10/2. We used 10/1 which we had archived:
[Guam COVID-19 Surveillance Sit Rep.pdf](https://github.com/COVID19Tracking/issues/files/5319260/Guam.COVID-19.Surveillance.Sit.Rep.pdf)

**After**
![Screen Shot 2020-10-02 at 12 43 29 PM](https://user-images.githubusercontent.com/15933271/94948176-e783e980-04ac-11eb-9dba-3e19f0f7d4d6.png)
