### ISSUE TITLE
[MO] 10/9 Typo in Positive Cases (confirmed + probable)

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#894]
**State:** MO

**Dates affected:** 10/9 

**Describe the issue:** On 10/9 we reported 139164 cases for MO, when we should have reported 139614

**Links:** https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1602362417156400

**Comment by MattHilliard** [comment]
For MO both `Positives` and `Positive Cases (PCR)` come from the same place on the dashboard, "Cases to date". On 10/9, data entry recorded 139,164 for `Positives` and 139,614 for `Positive Tests (PCR)`. So far, as reported, however from the screenshot I believe 139,164 is the correct value and accordingly will update `Positive Tests (PCR)` to match.

Relevant screenshot: https://covidtracking.com/screenshots/MO/MO-20201009-182247.png

Before:
![image](https://user-images.githubusercontent.com/404503/95686120-fe6fbd80-0bc9-11eb-892a-e9cf42c1a48d.png)

After:
![image](https://user-images.githubusercontent.com/404503/95686193-5c9ca080-0bca-11eb-957d-707a254be040.png)
