### ISSUE TITLE
[IN] backfill total tests pcr and positive tests pcr from state provided data

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#898]
**State or US**:  Indiana

**Describe the problem**
A clear and concise description of what the data problem is.

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.

**Comment by space-buzzer** [comment]
Link to dataset: https://hub.mph.in.gov/dataset/covid-19-county-wide-test-case-and-death-trends/resource/5ff3931f-aa68-4ee6-ac1d-d6c5d6cca50a

**Comment by space-buzzer** [comment]
Replaced the existing time series we collected, that started on 31-07-2020 with the time series from the posted dataset, that started on 26-02-2020. It also included filling positive PCR test results time series for the same period
