### ISSUE TITLE
[FL] Backfill total test encounters and cases from open hub data

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#914]
**State or US**:  Florida

**Describe the problem**
Florida has provided a total number of tests and cases going back to 1/28 on their open data hub. This backfills the data in order to provide a total tests metric that reflects repeat testing. 

**Link to data source**
https://open-fdoh.hub.arcgis.com/datasets/a91ca3832bd448a2a1b1bedad199ba2b/geoservice?page=25

**Comment by theomichel** [comment]
From the public note: On October 27, Florida started providing a full timeseries of total test encounters excluding tests from individuals after they test positive. This timeseries only reflects Florida residents, so **we have also revised our existing cases figures and unique individuals tested figure to reflect only residents. These changes resulted in a 1.28% decrease in Florida's cases and a 0.38% decrease in Florida's unique people tested.**

This change affects:
- Positive Cases (People, confirmed + probable) 
- Positive Cases (PCR) 
- Probable Cases 
- Total Test Encounters (PCR) 
- Total PCR Tests (People)

Attaching the analysis spreadsheet as well as the sheets we used as intermediate steps for the data. 

Analysis sheet:
[FL - Analysis 20201026.csv.txt](https://github.com/COVID19Tracking/issues/files/5448136/FL.-.Analysis.20201026.csv.txt)

Time series downloaded from florida covid data hub, this is referred to as "FL download 10-26-2020" in the analysis sheet:
[FL - FL download 10-26-2020.csv.txt](https://github.com/COVID19Tracking/issues/files/5448135/FL.-.FL.download.10-26-2020.csv.txt)

Time series built from florida's daily PDF summaries, over time, this is referred to as "PDF 10-26" in the analysis sheet:
[FL - PDF 10-26.csv.txt](https://github.com/COVID19Tracking/issues/files/5448137/FL.-.PDF.10-26.csv.txt)
