### ISSUE TITLE
[WI] Backfill Total Tests PCR for 3/3-10/19

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#917]
**State or US**: Wisconsin

**Describe the problem**
Wisconsin provides a time series of the tests it performed from 3/3 onwards on its website. This is backfilling the time series. 

**Link to data source**
https://bi.wisconsin.gov/t/DHS/views/PercentPositivebyTestPersonandaComparisonandTestCapacity/TestCapacityDashboard.csv

**Comment by theomichel** [comment]
Backfilled, attached analysis sheet and sheet containing wisconsin's data. (from the above data source link)

[WI - Analysis PCR Test Encounters 20201029.csv.txt](https://github.com/COVID19Tracking/issues/files/5461631/WI.-.Analysis.PCR.Test.Encounters.20201029.csv.txt)
[WI - Wisconsin Data 10-19.csv.txt](https://github.com/COVID19Tracking/issues/files/5461632/WI.-.Wisconsin.Data.10-19.csv.txt)
