### ISSUE TITLE
[DE] Backfill Test Encounters

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#918]
**State or US**: Delaware

**Describe the problem**
Filling the time series of test encounters and positive tests from public State provided data. 

**Link to data source**
https://myhealthycommunity.dhss.delaware.gov/locations/state/download_covid_19_data

**Comment by theomichel** [comment]
Backfilled total test encounters and positive tests (PCR).  Attached analysis sheet and data sheet that was downloaded from the data source on two separate days for comparison.

[DE - Analysis PCR 20201028.csv.txt](https://github.com/COVID19Tracking/issues/files/5461636/DE.-.Analysis.PCR.20201028.csv.txt)
[DE - DE data 10_19 and 10_28.csv.txt](https://github.com/COVID19Tracking/issues/files/5461637/DE.-.DE.data.10_19.and.10_28.csv.txt)
