### ISSUE TITLE
General: Grading Hospitalization Data

### ISSUE THREAD

**Issue by jawiv** [COVID19Tracking/issues#92]
It appears some states are not providing updated hospitalization data (or any future datapoints you may be planning to track like cumulative and current hospitalization, ICU, and Ventilator information).

It might be helpful to incorporate this into the grading metric to help encourage states to publish this important information.

Y'all are doing a great job and thank you!

**Comment by muamichali** [comment]
Thank you @jawiv !

We revamped our grading system and it now takes the hospitalization data into consideration. 

You can read more about it here: https://covidtracking.com/about-data#state-data-quality-grades
