### ISSUE TITLE
[NE] Backfill positive tests pcr, negative tests pcr and total tests pcr from dashboard data

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#920]
**State or US**:  Nebraska

**Describe the problem**
Nebraska is providing a full timeseries of negative, positive and total tests PCR on their dashboard via ArcGis queries. We are backfilling the total numbers from this data.

**Link to data source**
https://gis.ne.gov/enterprise/rest/services/Covid19MapV5/MapServer/11/query?where=1%3D1&outFields=%2A&orderByFields=LAB_REPORT_DATE+desc&resultRecordCount=1&f=json
![image](https://user-images.githubusercontent.com/1749380/97744326-632d8200-1abd-11eb-978c-c0ad8a56878e.png)

**Comment by theomichel** [comment]
We backfilled Nebraska total, positive, and negative tests. Here is the analysis sheet and sheet containing the raw data from the data source linked above.

[NE - Analysis PCR 20201030.csv.txt](https://github.com/COVID19Tracking/issues/files/5467163/NE.-.Analysis.PCR.20201030.csv.txt)
[NE - NE Raw.csv.txt](https://github.com/COVID19Tracking/issues/files/5467164/NE.-.NE.Raw.csv.txt)
