### ISSUE TITLE
[OR] Remove In ICU – Cumulative value for 4/9

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#927]
**State or US**: Oregon

**Describe the problem**
On 4/9 we recorded a cumulative in ICU value of 69 in Oregon. This seems to be a mistake

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.
![image](https://user-images.githubusercontent.com/1749380/98243565-1f62ce80-1f3c-11eb-8da5-223938cebb0d.png)

**Comment by space-buzzer** [comment]
Updated in batch 466
