### ISSUE TITLE
[VA] Remove one-time cumulative vent and icu numbers from reporting

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#930]
**State or US**: Virginia

**Describe the problem**
This is a number that was retrieved once from reporting and carried for one week 
https://www.facebook.com/GovernorVA/videos/218402129225741/
reporting an errant cumulative number for one week is skewing the national numbers.
We should either remove the numbers, or carry them forward.

**Link to data source**
![image](https://user-images.githubusercontent.com/1749380/98308322-bc9e2100-1f95-11eb-9da1-cfe9fb4a1531.png)

Additionally, VA has a 4 day gap in cumulative hospitalizations: 2020-04-14 - 2020-04-11

**Comment by muamichali** [comment]
https://github.com/COVID19Tracking/issues/issues/929

**Comment by space-buzzer** [comment]
This is updated: the values in cumulative ICU and cumulative on ventilator were deleted

**Comment by space-buzzer** [comment]
Similarly, fix a 4-day gap in in cumulative hospitalized between 2020-04-11 and 2020-04-14
