### ISSUE TITLE
[PR] Puerto Rico to redefine "probable" cases to mean antigen testing

### ISSUE THREAD

**Issue by sacundim** [COVID19Tracking/issues#936]
**State or US**: Puerto Rico

Puerto Rico's Department of Health announced today that it's going to revise its COVID-19 dashboard to adopt the case classification in the Council of State and Territorial Epidemiologists' [Coronavirus Disease 2019 (COVID-19) 2020 Interim Case Definition, Approved August 5, 2020](https://wwwn.cdc.gov/nndss/conditions/coronavirus-disease-2019-covid-19/case-definition/2020/08/05/), so that:

* Confirmed case: Positive PCR test
* Probable case: Positive antigen test
* Suspect case: Positive antibody test

Previous to this, the "probable case" category was (mis)used to cover cases that generally all they had was a positive antibody test. These cases will now be reclassified as "suspect," which means that the number of cases labeled as "probable" will soon drop from the current 33,615 to something in the neighborhood of 160 (my estimate using PRDoH testing API data).

Sources:

* [Journalist's Twitter thread with press release](https://twitter.com/angelicaserran0/status/1324824895784714240)
* Puerto Rico Department of Health press release (attached below)

![2020-11-06_reclassification](https://user-images.githubusercontent.com/4076056/98427006-2b3fb500-2050-11eb-82fc-21481f7d8b45.jpg)

**Comment by muamichali** [comment]
Thank you so much @sacundim for letting us know!
