### ISSUE TITLE
[CT] Update Total Tests (PCR) & Negatives value for 11/6-11/9

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#942]
**State or US**: Connecticut

**Describe the problem**
Starting on 11/5, Connecticut changed its reporting to lump antigen tests with PCR in the main testing number. We are backfilling our Positive Tests (PCR) and Negative (People or cases) numbers for 11/5-11/9 to use these values.

**Link to data source**
https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary11052020.pdf 
COVID-19 Tests Reported (molecular and antigen) 2455122

https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary11062020.pdf
COVID-19 Tests Reported (molecular and antigen) 2484685 

https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary11092020.pdf
COVID-19 Tests Reported (molecular and antigen) 2574371

**Comment by muamichali** [comment]
![image](https://user-images.githubusercontent.com/1749380/98699064-b963b600-2344-11eb-9299-c7d335610e22.png)

**Comment by hmhoffman** [comment]
We've cleared their negatives, and backfilled their total tests in[ #1109](https://github.com/COVID19Tracking/issues/issues/1109), so I think this is done.
