### ISSUE TITLE
[CT] Some total tests (PCR) values are duplicated in the peoplewise column they should be removed

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#946]
**State or US**:  Connecticut

**Describe the problem**
Some data is duplicated in the wrong column

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.
![image](https://user-images.githubusercontent.com/1749380/98840783-3bbbab00-2415-11eb-8c54-dbacda3739f4.png)

**Comment by jaclyde** [comment]
BEFORE:
<img width="410" alt="Screen Shot 2020-11-25 at 8 46 09 PM" src="https://user-images.githubusercontent.com/66583275/100309263-49b61380-2f5f-11eb-9d67-7c6cd825c89e.png">

AFTER:
<img width="421" alt="Screen Shot 2020-11-25 at 8 47 21 PM" src="https://user-images.githubusercontent.com/66583275/100309310-6fdbb380-2f5f-11eb-9757-f267e6a78fdf.png">
