### ISSUE TITLE
[KY] Backfill new Curr. Vent. metric for 11/12

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#948]
**State or US**: Kentucky

**Describe the problem**
On 11/12/20, Kentucky began to include a Currently on Ventilator number in their daily PDF report. We need to backfill the number for 11/12.

**Link to data source**
https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/KY/KY-tertiary-20201112-172508.pdf

**Comment by hmhoffman** [comment]
BEFORE:
<img width="184" alt="Screen Shot 2020-11-13 at 3 02 32 PM" src="https://user-images.githubusercontent.com/68712382/99115951-431fb780-25c1-11eb-870f-15af9c6ac7ad.png">

AFTER:
<img width="176" alt="Screen Shot 2020-11-13 at 3 03 53 PM" src="https://user-images.githubusercontent.com/68712382/99116092-74988300-25c1-11eb-8d1a-00e6fa348eb7.png">
