### ISSUE TITLE
CA: Screenshots cut off

### ISSUE THREAD

**Issue by toppy42** [COVID19Tracking/issues#96]
First off, thank you all for your hard work!

I was looking at California data and was searching for where the testing numbers came from.  I noticed two things:

1) The screenshots for California are cut off.  They only show the top part of the page without scrolling. This is the most recent screenshot (March 31st @ 6pm)
![image](https://user-images.githubusercontent.com/4970365/78087606-3bd7d080-7387-11ea-9ecd-65185fb3d574.png)

2) The linked "Best Current Data Source" website doesn't list the number of tests.  California has a different website that does have testing data: [https://covid19.ca.gov/](https://covid19.ca.gov/)

Thank you!
-Ethan

**Comment by joshuaellinger** [comment]
In case you missed it.

**Comment by julia326** [comment]
CA screenshots fixed
