### ISSUE TITLE
[GU] Remove Total PCR tests (people)

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#964]
State: GU

Dates affected: 5/13 - 11/20

Describe the issue: Prior to 11/20, we had been capturing Guam's Total PCR tests (people) as {Positive PCR tests (people) + Negative PCR tests (people)}. However due to new information discovered through outreach, we learned that the negative test value we had been using was actually Negative PCR tests (specimens). In order to ensure our data is as accurate as possible, we are removing Guam's Total PCR tests (people) from our time series.

**Comment by hmhoffman** [comment]
[Changes.txt](https://github.com/COVID19Tracking/issues/files/5578368/Changes.txt)

**Comment by karaschechtman** [comment]
An extra people entry snuck in, modified the source note
[Changes.txt](https://github.com/COVID19Tracking/issues/files/5579048/Changes.txt)
