### ISSUE TITLE
[NY] Backfill Total Test Encounters PCR and cases time series from NYS source

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#970]
**State or US**: New York

**Describe the problem**
Due to our early capture we do not have a full timeseries of total test encounters PCR. New York provides a full time series of tests and cases  by report date.

**Link to data source**
https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e/data

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - NY-REB-20201123.csv.txt](https://github.com/COVID19Tracking/issues/files/5585062/Multi-edit.tool-PRODUCTION.-.NY-REB-20201123.csv.txt)
[Multi-edit tool-PRODUCTION - NY-REB-20201123_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5585063/Multi-edit.tool-PRODUCTION.-.NY-REB-20201123_post.csv.txt)
