### ISSUE TITLE
[WY] Backfill time-series in specimens units 

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#975]
**State or US**: Wyoming

**Describe the problem**
There is a time-series of positive & negative tests on the state and county page that sums up to the tests number on the 

**Link to data source**
Provide links to original data sources that we can refer to, like a state COVID website.

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - WY-reb-20201126.csv.txt](https://github.com/COVID19Tracking/issues/files/5599770/Multi-edit.tool-PRODUCTION.-.WY-reb-20201126.csv.txt)
[Multi-edit tool-PRODUCTION - WY-reb-20201126_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5599771/Multi-edit.tool-PRODUCTION.-.WY-reb-20201126_post.csv.txt)

**Comment by space-buzzer** [comment]
The data taken from [County Dashboard](https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-state-and-county-dashboards/) page, the chart "Laboratory Results by Date"
