### ISSUE TITLE
CO: Data integrity problem on March 31, 2020

### ISSUE THREAD

**Issue by saewoonam** [COVID19Tracking/issues#98]
This is the data from the Colorado website
<img width="687" alt="Screen Shot 2020-03-31 at 7 35 28 PM" src="https://user-images.githubusercontent.com/2872116/78090436-56aa4500-7387-11ea-859c-57867702f926.png">

**Comment by schwartzadev** [comment]
Thanks for your contribution @saewoonam ! Can you please share more detail? What was the data integrity problem with the website?

**Comment by saewoonam** [comment]
At least when I checked last night, the data from the Colorado website did not match what was on your website.   It is still not corrected... The data listed in the 10:03PM screenshot is what should be used not the 4:02PM... But, it kind of depends how you want to define boundaries in days.   If it is really 4:00 PM EDT, then most of your CO data is wrong since the reporting from CO usually occurs around 4:00PM MDT... And, for the data prior to yesterday, you were using the 4PM MDT values...

**Comment by schmian** [comment]
investigating

**Comment by muamichali** [comment]
Hi @saewoonam 

With our current publish shift times we often catch Colorado's updates only two days later. We are considering changing the publish times to be able to cover states that update late. Until then, I have updated the lastUpdateEt for CO entries to reflect the time of the data. 

I know it's not a perfect solution, but I hope it can help somewhat. 

![Screenshot_2020-05-20 Coronavirus numbers by state (CovidTracking, DEV COPY)(1)](https://user-images.githubusercontent.com/1749380/82452453-45bfab00-9a7d-11ea-98c3-f0fb7ae8f86c.png)

![Screenshot_2020-05-20 Coronavirus numbers by state (CovidTracking, DEV COPY)](https://user-images.githubusercontent.com/1749380/82452454-45bfab00-9a7d-11ea-9819-782eac85684c.png)
