### ISSUE TITLE
[ND] Backfill Deaths (Confirmed and Probable), Deaths (Confirmed) to reflect all deaths rather than deaths due to COVID

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#988]
**State or US**:  North Dakota

**Describe the problem**
Over the past week, a gap has opened between the number of COVID-19 deaths North Dakota's health department reports and The COVID Tracking Project’s counts of deaths in the state. On November 30, North Dakota’s health department dashboard reported 927 cumulative COVID-19 deaths, but The COVID Tracking Project recorded 680. This is because we track deaths due to COVID, instead of deaths among cases in the state.

It’s clear that a reporting backlog is to blame for most of the widening discrepancy between figures: The share of COVID-19-positive individuals who died in North Dakota with death certificates still pending has doubled since the beginning of November.  To better reflect the reality of rising deaths in North Dakota, we are changing our method for counting deaths in the state to the other main paradigm for tracking deaths: counting deaths among cases.

**Link to data source**
https://covidtracking.com/data/state/north-dakota/screenshots

**Comment by muamichali** [comment]
[
[ND.xlsx](https://github.com/COVID19Tracking/issues/files/5624952/ND.xlsx)
](url)

**Comment by karaschechtman** [comment]
[Changes (1).txt](https://github.com/COVID19Tracking/issues/files/5625473/Changes.1.txt)
