### ISSUE TITLE
HI: Pending tests clarification

### ISSUE THREAD

**Issue by whodaguy** [COVID19Tracking/issues#99]
On the Hawaii Department of Health website sourced for covidtracking data, the category "Pending" does not refer to people in Hawaii who have been swabbed and are still awaiting test results. It means people who have tested positive but whose county of residence has not yet been confirmed.

Just FYI.

**Comment by goldfarb** [comment]
Thank you, we have made a note of that for future updates.

**Comment by goldfarb** [comment]
Inaccurate pending data had been input for 18 - 21 March, 27 March - 02 April.
![image](https://user-images.githubusercontent.com/3722037/78370074-284d8500-7594-11ea-8a4a-bc81fc9bd74c.png)

**Comment by goldfarb** [comment]
https://health.hawaii.gov/coronavirusdisease2019/ shows that **Pending** is pending county assignment, not pending test results.

![image](https://user-images.githubusercontent.com/3722037/78371526-17057800-7596-11ea-84a0-08308841f211.png)

![image](https://user-images.githubusercontent.com/3722037/78371544-1d93ef80-7596-11ea-8714-818ed680c3b8.png)

For 3/18 - 3/21, assuming the same terminology was used, updating the past pending values.

3/18
![image](https://user-images.githubusercontent.com/3722037/78371708-52a04200-7596-11ea-989e-15eedb5012b2.png)

![image](https://user-images.githubusercontent.com/3722037/78371755-6350b800-7596-11ea-86c7-afd88c893993.png)

3/19

![image](https://user-images.githubusercontent.com/3722037/78371851-85e2d100-7596-11ea-88e5-ad6212520776.png)

![image](https://user-images.githubusercontent.com/3722037/78371879-8ed3a280-7596-11ea-8cb4-6e660d6d356d.png)

3/20

![image](https://user-images.githubusercontent.com/3722037/78372043-c93d3f80-7596-11ea-988f-cc8749341522.png)

![image](https://user-images.githubusercontent.com/3722037/78372093-d78b5b80-7596-11ea-9b43-b01b8d77d5aa.png)

3/21

![image](https://user-images.githubusercontent.com/3722037/78372163-f0940c80-7596-11ea-9838-82e50d30d9b8.png)

![image](https://user-images.githubusercontent.com/3722037/78372188-f853b100-7596-11ea-92d2-23203cebac99.png)

**Comment by goldfarb** [comment]
For 3/27, snapshot of the historical data https://covidtracking.com/screenshots/HI/HI-20200327-160426.png

![image](https://user-images.githubusercontent.com/3722037/78372450-49fc3b80-7597-11ea-805c-eb6197ccb422.png)

updated to 

![image](https://user-images.githubusercontent.com/3722037/78372498-5e403880-7597-11ea-8586-55af38540be1.png)

**Comment by goldfarb** [comment]
For 3/28, https://covidtracking.com/screenshots/HI/HI-20200328-010559.png

![image](https://user-images.githubusercontent.com/3722037/78372619-7e6ff780-7597-11ea-835c-3a6e6de84505.png)

![image](https://user-images.githubusercontent.com/3722037/78372655-87f95f80-7597-11ea-9c4d-f3bde2431789.png)

**Comment by goldfarb** [comment]
For 3/29, https://covidtracking.com/screenshots/HI/HI-20200329-010349.png

![image](https://user-images.githubusercontent.com/3722037/78373048-0c4be280-7598-11ea-98b5-0e1a032f849a.png)

![image](https://user-images.githubusercontent.com/3722037/78373054-0fdf6980-7598-11ea-92f2-786e4802dbf5.png)

**Comment by goldfarb** [comment]
3/30 https://covidtracking.com/screenshots/HI/HI-20200330-180433.png

![image](https://user-images.githubusercontent.com/3722037/78373457-9eec8180-7598-11ea-9d00-08408c121730.png)

![image](https://user-images.githubusercontent.com/3722037/78373489-aad84380-7598-11ea-937c-80a0fdb4d8e4.png)
