### ISSUE TITLE
[VT] changes to VT's Positive (confirmed + probable) and Totals  

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#991]
**State or US**: VT

**Describe the problem**
Vermont is adding ~120 probables since September to its counts today, which previously were only confirmed.
https://www.healthvermont.gov/sites/default/files/documents/pdf/Covid-19-Daily-Update.pdf
They provide a cases timeseries where those probables are distributed over the full timeseries, so we are backfilling Positive so it doesn't appear as if cases rose by an additional 120 today.

As a bonus, we're also backfilling Total PCR Tests (People) with a by-result timeseries so that we can get more history — we only have it back to May but this will get us back to March.

**Link to data source**
https://geodata.vermont.gov/datasets/vt-covid-19-daily-counts-table

**Comment by karaschechtman** [comment]
![Columns C-D](https://user-images.githubusercontent.com/15933271/100915959-1a456080-34a3-11eb-9e3b-c45152a480f9.png)
![Columns I-J](https://user-images.githubusercontent.com/15933271/100915960-1a456080-34a3-11eb-92bb-445295961836.png)

**Comment by karaschechtman** [comment]
[Changes (2).txt](https://github.com/COVID19Tracking/issues/files/5631374/Changes.2.txt)

**Comment by space-buzzer** [comment]
We have a time series for probable cases.
Updating positives (lumped), confirmed & probables.
[Multi-edit tool-PRODUCTION - VT-reb-20201204.csv.txt](https://github.com/COVID19Tracking/issues/files/5644847/Multi-edit.tool-PRODUCTION.-.VT-reb-20201204.csv.txt)
[Multi-edit tool-PRODUCTION - VT-reb-20201204_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5644848/Multi-edit.tool-PRODUCTION.-.VT-reb-20201204_post.csv.txt)
